import { characterizationFindings, characterizationTasks } from "../data/chapter_02/characterization";
import { conflictChain } from "../data/chapter_02/conflicts";
import { developmentCards } from "../data/chapter_02/development";
import { ensembleFinalePool } from "../data/chapter_02/finale";
import { knowledgeStates } from "../data/chapter_02/knowledge_states";
import { relationships } from "../data/chapter_02/relationships";
import { GenericEvidenceReasoningEngine } from "../../../core/interactions/evidence_reasoning_engine";

const evidenceReasoning = new GenericEvidenceReasoningEngine(characterizationTasks.map((task) => ({ id: task.id, observationId: `${task.id}:observation`, evidenceId: `${task.id}:evidence`, interpretationId: `${task.id}:interpretation` })));

export type Chapter02Round=1|2|3|4|5|6|7;
export type Chapter02Competency="character_relationships"|"direct_characterization"|"indirect_characterization"|"motivation"|"conflict_analysis"|"character_development"|"knowledge_state_analysis"|"evidence_reasoning";
export interface Chapter02Event{competency:Chapter02Competency;success:boolean;round:Chapter02Round;}
export interface Chapter02Session{round:Chapter02Round;relationshipIndex:number;pendingRelationship:string|null;completedRelationships:string[];characterizationTask:number;reasoningStep:number;classified:Record<string,string>;conflictStages:string[];knowledgeAssignments:Record<string,string>;developmentStages:string[];finaleIndex:number;completed:boolean;failedAttempts:number;competencyEvents:Chapter02Event[];}
export function createChapter02Session(random:()=>number=Math.random):Chapter02Session{return{round:1,relationshipIndex:0,pendingRelationship:null,completedRelationships:[],characterizationTask:0,reasoningStep:0,classified:{},conflictStages:[],knowledgeAssignments:{},developmentStages:[],finaleIndex:Math.floor(random()*ensembleFinalePool.length),completed:false,failedAttempts:0,competencyEvents:[]};}
function record(session:Chapter02Session,competency:Chapter02Competency,success:boolean):Chapter02Session{return{...session,failedAttempts:session.failedAttempts+(success?0:1),competencyEvents:[...session.competencyEvents,{competency,success,round:session.round}]};}
function samePair(a:string,b:string,x:string,y:string){return(a===x&&b===y)||(a===y&&b===x);}
export function connectCharacters(session:Chapter02Session,a:string,b:string){const task=relationships[session.relationshipIndex];const valid=Boolean(task&&samePair(a,b,task.a,task.b));return{valid,session:record({...session,pendingRelationship:valid?task.id:null},"character_relationships",valid)};}
export function justifyRelationship(session:Chapter02Session,relationshipId:string){const valid=session.pendingRelationship===relationshipId;let next=record(session,"evidence_reasoning",valid);if(valid){const done=[...next.completedRelationships,relationshipId];next={...next,pendingRelationship:null,completedRelationships:done,relationshipIndex:next.relationshipIndex+1,round:done.length===relationships.length?2:1};}return{valid,session:next};}
export function selectReasoningStep(session:Chapter02Session,kind:"observation"|"evidence"|"interpretation",taskId:string){const task=characterizationTasks[session.characterizationTask];const expected=["observation","evidence","interpretation"][session.reasoningStep];const chainValid=kind!=="interpretation"||evidenceReasoning.evaluate({observationId:`${taskId}:observation`,evidenceId:`${taskId}:evidence`,interpretationId:`${taskId}:interpretation`}).valid;const valid=task?.id===taskId&&kind===expected&&chainValid;let next=record(session,"indirect_characterization",valid);if(valid){const step=next.reasoningStep+1;if(step===3){const index=next.characterizationTask+1;next={...next,reasoningStep:0,characterizationTask:index,round:index===characterizationTasks.length?3:2};}else next={...next,reasoningStep:step};}return{valid,session:next};}
export function classifyFinding(session:Chapter02Session,id:string,target:string){const finding=characterizationFindings.find((item)=>item.id===id);const valid=finding?.target===target;let next=record({...session,classified:valid?{...session.classified,[id]:target}:session.classified},target==="direct"?"direct_characterization":"indirect_characterization",valid);if(characterizationFindings.every((item)=>next.classified[item.id]===item.target))next={...next,round:4};return{valid,session:next};}
export function placeConflictStage(session:Chapter02Session,id:string){const expected=conflictChain[session.conflictStages.length];const valid=expected?.id===id;let next=record(session,"conflict_analysis",valid);if(valid){const stages=[...next.conflictStages,id];next={...next,conflictStages:stages,round:stages.length===conflictChain.length?5:4};}return{valid,session:next};}
export function placeKnowledge(session:Chapter02Session,id:string,target:string){const item=knowledgeStates.find((entry)=>entry.id===id);const valid=item?.target===target;let next=record({...session,knowledgeAssignments:valid?{...session.knowledgeAssignments,[id]:target}:session.knowledgeAssignments},"knowledge_state_analysis",valid);if(knowledgeStates.every((entry)=>next.knowledgeAssignments[entry.id]===entry.target))next={...next,round:6};return{valid,session:next};}
export function placeDevelopment(session:Chapter02Session,id:string){const expected=developmentCards[session.developmentStages.length];const valid=expected?.id===id;let next=record(session,"character_development",valid);if(valid){const stages=[...next.developmentStages,id];next={...next,developmentStages:stages,round:stages.length===developmentCards.length?7:6};}return{valid,session:next};}
export function completeEnsembleProbe(session:Chapter02Session,relationshipId:string){const expected=ensembleFinalePool[session.finaleIndex];const valid=relationshipId===expected;const next=record({...session,completed:valid},"evidence_reasoning",valid);return{valid,session:next};}
