import {comparisonTasks,finalTask,findingTasks,goalChange,goalTasks,languageTasks,miniAnalysis,neutralBoundary,neutralLanguage,neutralPhases,phaseBoundary,phaseOrder,practiceActs,speechTasks,stageEffectTask,transferTasks,turningPoints} from "../data/chapter_03_content";
export type Chapter03Round=1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16;
export type Chapter03Competency="speech_act"|"conversation_goal"|"dialogue_development"|"evidence_reasoning"|"language_effect"|"stage_signal"|"transfer_analysis";
export interface Chapter03Event{competency:Chapter03Competency;success:boolean;round:Chapter03Round}
export interface Chapter03Session{round:Chapter03Round;practiceActs:Record<string,string>;practiceGoals:Record<string,string>;neutralModel:string[];neutralPhaseOrder:string[];neutralBoundary:string|null;neutralLanguage:string|null;goalEvidence:Record<string,string>;goalChange:string|null;speechChains:string[];phaseOrder:string[];phaseBoundary:string|null;turningPoint:string|null;languageChains:string[];findingAssignments:Record<string,string>;stageEffect:string|null;miniAnalysis:string[];transferEvidence:Record<string,string>;comparisonAssignments:Record<string,string>;finalSteps:string[];completed:boolean;failedAttempts:number;competencyEvents:Chapter03Event[];seenGlossaryIntroductions:string[]}
export const initialChapter03Session:Chapter03Session={round:1,practiceActs:{},practiceGoals:{},neutralModel:[],neutralPhaseOrder:[],neutralBoundary:null,neutralLanguage:null,goalEvidence:{},goalChange:null,speechChains:[],phaseOrder:[],phaseBoundary:null,turningPoint:null,languageChains:[],findingAssignments:{},stageEffect:null,miniAnalysis:[],transferEvidence:{},comparisonAssignments:{},finalSteps:[],completed:false,failedAttempts:0,competencyEvents:[],seenGlossaryIntroductions:[]};
export const createChapter03Session=():Chapter03Session=>structuredClone(initialChapter03Session);
const record=(s:Chapter03Session,c:Chapter03Competency,ok:boolean):Chapter03Session=>({...s,failedAttempts:s.failedAttempts+(ok?0:1),competencyEvents:[...s.competencyEvents,{competency:c,success:ok,round:s.round}]});
const advance=(s:Chapter03Session):Chapter03Session=>({...s,round:Math.min(16,s.round+1) as Chapter03Round});
export function setNeutralModel(s:Chapter03Session,ids:string[]){const expected=["model_utterance","model_act","model_reaction","model_change"];const ok=expected.every((id,i)=>ids[i]===id);let n=record(s,"dialogue_development",ok);if(ok)n=advance({...n,neutralModel:ids});return{valid:ok,session:n}}
export function assignPracticeAct(s:Chapter03Session,id:string,value:string){const item=practiceActs.find(x=>x.id===id);const ok=item?.act===value;let n=record(s,"speech_act",ok);if(ok)n={...n,practiceActs:{...n.practiceActs,[id]:value}};if(ok&&Object.keys(n.practiceActs).length===practiceActs.length)n=advance(n);return{valid:ok,session:n}}
export function assignPracticeGoal(s:Chapter03Session,id:string,value:string){const item=practiceActs.find(x=>x.id===id);const ok=item?.goal===value&&Boolean(s.practiceActs[id]);let n=record(s,"conversation_goal",ok);if(ok)n={...n,practiceGoals:{...n.practiceGoals,[id]:value}};if(ok&&Object.keys(n.practiceGoals).length===practiceActs.length)n=advance(n);return{valid:ok,session:n}}
export function setNeutralPhases(s:Chapter03Session,ids:string[]){const expected=neutralPhases.map(x=>x.id);const ok=expected.every((id,i)=>ids[i]===id);let n=record(s,"dialogue_development",ok);if(ok)n=advance({...n,neutralPhaseOrder:ids});return{valid:ok,session:n}}
export function justifyNeutralBoundary(s:Chapter03Session,after:string,reason:string){const ok=after===neutralBoundary.after&&reason===neutralBoundary.reason;let n=record(s,"dialogue_development",ok);if(ok)n=advance({...n,neutralBoundary:after});return{valid:ok,session:n}}
export function solveNeutralLanguage(s:Chapter03Session,finding:string,effect:string,fn:string){const t=neutralLanguage[0];const ok=finding===t.finding&&effect===t.effect&&fn===t.function;let n=record(s,"language_effect",ok);if(ok)n=advance({...n,neutralLanguage:t.id});return{valid:ok,session:n}}
export function linkGoalEvidence(s:Chapter03Session,id:string,sourceId:string){const item=goalTasks.find(x=>x.id===id);const ok=item?.sourceId===sourceId;let n=record(s,"conversation_goal",ok);if(ok)n={...n,goalEvidence:{...n.goalEvidence,[id]:sourceId}};if(ok&&Object.keys(n.goalEvidence).length===goalTasks.length)n=advance(n);return{valid:ok,session:n}}
export function analyzeGoalChange(s:Chapter03Session,value:string,first:string,second:string){const ok=value===goalChange.answer&&first===goalChange.first&&second===goalChange.second;let n=record(s,"conversation_goal",ok);if(ok)n=advance({...n,goalChange:value});return{valid:ok,session:n}}
export function connectSpeechChain(s:Chapter03Session,id:string,act:string,reaction:string){const item=speechTasks.find(x=>x.id===id);const ok=item?.act===act&&item.reactionId===reaction;let n=record(s,"dialogue_development",ok);if(ok&&!n.speechChains.includes(id))n={...n,speechChains:[...n.speechChains,id]};if(ok&&n.speechChains.length===speechTasks.length)n=advance(n);return{valid:ok,session:n}}
export function setPhaseOrder(s:Chapter03Session,ids:string[]){const ok=phaseOrder.every((id,i)=>ids[i]===id);let n=record(s,"dialogue_development",ok);if(ok)n={...n,phaseOrder:ids};return{valid:ok,session:n}}
export function justifyPhaseBoundary(s:Chapter03Session,after:string,reason:string){const ok=after===phaseBoundary.after&&reason===phaseBoundary.reason;let n=record(s,"dialogue_development",ok);if(ok)n=advance({...n,phaseBoundary:after});return{valid:ok,session:n}}
export function chooseTurningPoint(s:Chapter03Session,id:string,sourceId:string,change?:string){const item=turningPoints.find(x=>x.id===id);const ok=item?.sourceId===sourceId&&(!change||item.change===change);let n=record(s,"stage_signal",ok);if(ok)n=advance({...n,turningPoint:id});return{valid:ok,session:n}}
export function solveLanguage(s:Chapter03Session,id:string,feature:string,effect:string){const item=languageTasks.find(x=>x.id===id);const ok=item?.feature===feature&&item.effect===effect;let n=record(s,"language_effect",ok);if(ok&&!n.languageChains.includes(id))n={...n,languageChains:[...n.languageChains,id]};if(ok&&n.languageChains.length===languageTasks.length)n=advance(n);return{valid:ok,session:n}}
export function classifyFinding(s:Chapter03Session,id:string,target:string){const item=findingTasks.find(x=>x.id===id);const ok=item?.target===target;let n=record(s,"stage_signal",ok);if(ok)n={...n,findingAssignments:{...n.findingAssignments,[id]:target}};return{valid:ok,session:n}}
export function analyzeStageEffect(s:Chapter03Session,sourceId:string,effect:string){const ok=sourceId===stageEffectTask.sourceId&&effect===stageEffectTask.effect;let n=record(s,"stage_signal",ok);if(ok)n=advance({...n,stageEffect:effect});return{valid:ok,session:n}}
export function solveMiniAnalysis(s:Chapter03Session,ids:string[]){const expected=miniAnalysis.map(x=>x.id);const ok=expected.every((id,i)=>ids[i]===id);let n=record(s,"evidence_reasoning",ok);if(ok)n=advance({...n,miniAnalysis:ids});return{valid:ok,session:n}}
export function solveTransfer(s:Chapter03Session,id:string,sourceId:string){const item=transferTasks.find(x=>x.id===id);const ok=item?.sourceId===sourceId;let n=record(s,"transfer_analysis",ok);if(ok)n={...n,transferEvidence:{...n.transferEvidence,[id]:sourceId}};if(ok&&Object.keys(n.transferEvidence).length===transferTasks.length)n=advance(n);return{valid:ok,session:n}}
export function compareDialogues(s:Chapter03Session,id:string,target:string){const item=comparisonTasks.find(x=>x.id===id);const ok=item?.target===target;let n=record(s,"dialogue_development",ok);if(ok)n={...n,comparisonAssignments:{...n.comparisonAssignments,[id]:target}};if(ok&&Object.keys(n.comparisonAssignments).length===comparisonTasks.length)n=advance(n);return{valid:ok,session:n}}
export function solveFinal(s:Chapter03Session,steps:string[]){const expected=[finalTask.goalSource,finalTask.actSource,finalTask.reactionSource];const ok=expected.every((id,i)=>steps[i]===id);let n=record(s,"evidence_reasoning",ok);if(ok)n={...n,finalSteps:steps,completed:true};return{valid:ok,session:n}}
