import { causalIntro, chain, chainLinks, conflictTypes, escalationCards, finalConnections, goals, introFacts, julietCards, knowledgeCards, situationCards } from "../data/chapter_04_content";
import type { StagingDecision } from "../data/staging";

export type Chapter04Competency="conflict_analysis"|"causal_reasoning"|"action_analysis"|"turning_point"|"evidence_reasoning"|"internal_conflict"|"transfer_analysis";
export interface Chapter04Event{competency:Chapter04Competency;success:boolean;round:number}
export interface Chapter04Session{round:number;introRelevant:string[];introGoals:Record<string,string>;conflictAssignments:Record<string,string>;causalIntroAssignments:Record<string,string>;situationAssignments:Record<string,string>;knowledgeAssignments:Record<string,string>;goalEvidence:Record<string,string>;incompatibilityReason?:string;chainOrder:string[];chainRelations:Record<string,string>;actionReaction:Record<string,string>;alternative?:string;escalationAssignments:Record<string,string>;turningPoint?:string;consequences:Record<string,string>;julietAssignments:Record<string,string>;monologueOrder:string[];decisionEvidence?:string;executionEvidence?:string;comparison?:string;finalAssignments:Record<string,string>;miniAnalysis:string[];stagingDecisions:Record<string,StagingDecision>;completed:boolean;failedAttempts:number;competencyEvents:Chapter04Event[]}
export const initialChapter04Session:Chapter04Session={round:1,introRelevant:[],introGoals:{},conflictAssignments:{},causalIntroAssignments:{},situationAssignments:{},knowledgeAssignments:{},goalEvidence:{},chainOrder:[],chainRelations:{},actionReaction:{},escalationAssignments:{},consequences:{},julietAssignments:{},monologueOrder:[],finalAssignments:{},miniAnalysis:[],stagingDecisions:{},completed:false,failedAttempts:0,competencyEvents:[]};
const rec=(s:Chapter04Session,c:Chapter04Competency,ok:boolean):Chapter04Session=>({...s,failedAttempts:s.failedAttempts+(ok?0:1),competencyEvents:[...s.competencyEvents,{competency:c,success:ok,round:s.round}]});
const result=(s:Chapter04Session,c:Chapter04Competency,ok:boolean,patch:Partial<Chapter04Session>={},advance=false)=>({valid:ok,session:{...rec(s,c,ok),...(ok?patch:{}),...(ok&&advance?{round:s.round+1}:{})}});
export function selectIntroFact(s:Chapter04Session,id:string){const item=introFacts.find(x=>x.id===id);return result(s,"conflict_analysis",Boolean(item?.relevant),item?.relevant?{introRelevant:[...new Set([...s.introRelevant,id])]}:{});}
export function saveIntroGoals(s:Chapter04Session,mara:string,father:string){return result(s,"conflict_analysis",mara==="party"&&father==="study",{introGoals:{mara,father}},true)}
export function assignConflictType(s:Chapter04Session,id:string,target:string){const item=conflictTypes.find(x=>x.id===id),ok=item?.answer===target;const assignments=ok?{...s.conflictAssignments,[id]:target}:s.conflictAssignments;return result(s,"conflict_analysis",ok,{conflictAssignments:assignments},Object.keys(assignments).length===conflictTypes.length)}
export function assignCausalIntro(s:Chapter04Session,id:string,target:string){const item=causalIntro.find(x=>x.id===id),ok=item?.answer===target;const assignments=ok?{...s.causalIntroAssignments,[id]:target}:s.causalIntroAssignments;return result(s,"causal_reasoning",ok,{causalIntroAssignments:assignments},Object.keys(assignments).length===causalIntro.length)}
export function assignSituation(s:Chapter04Session,id:string,target:string){const item=situationCards.find(x=>x.id===id),ok=item?.target===target;const assignments=ok?{...s.situationAssignments,[id]:target}:s.situationAssignments;return result(s,"conflict_analysis",ok,{situationAssignments:assignments},Object.keys(assignments).length===situationCards.length)}
export function assignKnowledge(s:Chapter04Session,id:string,target:string){const item=knowledgeCards.find(x=>x.id===id),ok=item?.target===target;const assignments=ok?{...s.knowledgeAssignments,[id]:target}:s.knowledgeAssignments;return result(s,"evidence_reasoning",ok,{knowledgeAssignments:assignments},Object.keys(assignments).length===knowledgeCards.length)}
export function linkGoal(s:Chapter04Session,id:string,evidence:string){const item=goals.find(x=>x.id===id),ok=item?.evidence===evidence;const assignments=ok?{...s.goalEvidence,[id]:evidence}:s.goalEvidence;return result(s,"evidence_reasoning",ok,{goalEvidence:assignments},Object.keys(assignments).length===goals.length)}
export function setIncompatibility(s:Chapter04Session,id:string){return result(s,"conflict_analysis",id==="cannot_both_succeed",{incompatibilityReason:id},true)}
export function placeChainEvent(s:Chapter04Session,id:string){const ok=chain[s.chainOrder.length]?.id===id;return result(s,"action_analysis",ok,{chainOrder:ok?[...s.chainOrder,id]:s.chainOrder})}
export function setChainRelation(s:Chapter04Session,from:string,to:string,type:string){const link=chainLinks.find(x=>x.from===from&&x.to===to),ok=link?.type===type;const relations=ok?{...s.chainRelations,[`${from}:${to}`]:type}:s.chainRelations;return result(s,"causal_reasoning",ok,{chainRelations:relations},Object.keys(relations).length===chainLinks.length&&s.chainOrder.length===chain.length)}
export function assignActionReaction(s:Chapter04Session,id:string,target:string){const expected=id==="paris_stops"?"action":id==="romeo_appeals"?"reaction":undefined,ok=expected===target;const assignments=ok?{...s.actionReaction,[id]:target}:s.actionReaction;return result(s,"action_analysis",ok,{actionReaction:assignments})}
export function chooseAlternative(s:Chapter04Session,id:string){return result(s,"action_analysis",id==="paris_allows_exit",{alternative:id},true)}
export function assignEscalation(s:Chapter04Session,id:string,target:string){const item=escalationCards.find(x=>x.id===id),ok=item?.level===target;const assignments=ok?{...s.escalationAssignments,[id]:target}:s.escalationAssignments;return result(s,"turning_point",ok,{escalationAssignments:assignments})}
export function chooseTurningPoint(s:Chapter04Session,id:string){return result(s,"turning_point",id==="fight",{turningPoint:id})}
export function assignConsequence(s:Chapter04Session,id:string,target:string){const expected=id==="fight"?"immediate":id==="paris_falls"?"farther":id==="peace"?"not_determinable":undefined,ok=expected===target;const assignments=ok?{...s.consequences,[id]:target}:s.consequences;return result(s,"causal_reasoning",ok,{consequences:assignments},Object.keys(assignments).length===3)}
export function assignJuliet(s:Chapter04Session,id:string,target:string){const item=julietCards.find(x=>x.id===id),ok=item?.kind===target;const assignments=ok?{...s.julietAssignments,[id]:target}:s.julietAssignments;return result(s,"internal_conflict",ok,{julietAssignments:assignments},Object.keys(assignments).length===julietCards.length)}
export function placeMonologueStep(s:Chapter04Session,id:string){const expected=["alone","marriage","poison","wake","decision","execution"][s.monologueOrder.length],ok=expected===id,order=ok?[...s.monologueOrder,id]:s.monologueOrder;return result(s,"internal_conflict",ok,{monologueOrder:order},order.length===6)}
export function distinguishDecision(s:Chapter04Session,decision:string,execution:string){const ok=decision==="c04_juliet_drinks"&&execution==="c04_juliet_execution";return result(s,"turning_point",ok,{decisionEvidence:decision,executionEvidence:execution},true)}
export function compareConflicts(s:Chapter04Session,id:string){return result(s,"transfer_analysis",id==="external_vs_internal",{comparison:id},true)}
export function assignFinalRelation(s:Chapter04Session,id:string,target:string){const item=finalConnections.find(x=>x.id===id),ok=item?.answer===target;const assignments=ok?{...s.finalAssignments,[id]:target}:s.finalAssignments;return result(s,"causal_reasoning",ok,{finalAssignments:assignments})}
export function toggleMiniAnalysis(s:Chapter04Session,id:string){const required=["situation","goal","conflict","action","reaction","turning","consequence","evidence"];return required.includes(id)?{...s,miniAnalysis:s.miniAnalysis.includes(id)?s.miniAnalysis.filter(x=>x!==id):[...s.miniAnalysis,id]}:s}
export function completeChapter04(s:Chapter04Session){const ok=Object.keys(s.finalAssignments).length===finalConnections.length&&["situation","goal","conflict","action","reaction","turning","consequence","evidence"].every(x=>s.miniAnalysis.includes(x));return result(s,"transfer_analysis",ok,{completed:ok})}
