import {causalIntro,chain,chainLinks,comparisonAspects,conflictTypes,dramaticCurve,finalConnections,finalCurve,finalEvidence,finalMeaningOptions,finalTransferOptions,generalEpistemicPractice,generalEvidenceTasks,generalGoalTasks,goals,historyPractice,internalPreparation,introFacts,julietAlternatives,julietCards,julietSequence,knowledgeCards,neutralActionChains,neutralTurningPoints,situationCards,tombActionChains,escalationCards} from "../data/chapter_04_content";
import type {StagingDecision} from "../data/staging";

export type Chapter04Competency="conflict_analysis"|"causal_reasoning"|"action_analysis"|"turning_point"|"evidence_reasoning"|"internal_conflict"|"transfer_analysis";
export interface Chapter04Event{competency:Chapter04Competency;success:boolean;round:number}
export interface Chapter04Session{round:number;introRelevant:string[];introGoals:Record<string,string>;generalGoals:string[];conflictAssignments:Record<string,string>;historyAssignments:Record<string,string>;causalIntroAssignments:Record<string,string>;generalEpistemicAssignments:Record<string,string>;generalEvidence:string[];curveIntroduced:boolean;curveOrder:string[];neutralActionChains:string[];neutralTurning?:string;situationAssignments:Record<string,string>;knowledgeAssignments:Record<string,string>;goalChoices:Record<string,number>;goalEvidence:Record<string,string>;goalAnalyses:string[];incompatibilityReason?:string;chainOrder:string[];chainRelations:Record<string,string>;actionReaction:Record<string,string>;tombActionChains:string[];alternative?:string;escalationAssignments:Record<string,string>;turningPoint?:string;turningReason?:string;consequences:Record<string,string>;internalPreparation:Record<string,string>;julietAssignments:Record<string,string>;monologueOrder:string[];decisionEvidence?:string;executionEvidence?:string;julietAlternatives:Record<string,string>;comparisonAssignments:Record<string,string>;comparison?:string;finalCurve:string[];finalAssignments:Record<string,string>;finalMeaning?:string;finalEvidence?:string;finalEvidenceAnalysis?:number;finalTransfer?:string;miniAnalysis:string[];stagingDecisions:Record<string,StagingDecision>;completed:boolean;failedAttempts:number;competencyEvents:Chapter04Event[];seenGlossaryIntroductions:string[]}
export const initialChapter04Session:Chapter04Session={round:1,introRelevant:[],introGoals:{},generalGoals:[],conflictAssignments:{},historyAssignments:{},causalIntroAssignments:{},generalEpistemicAssignments:{},generalEvidence:[],curveIntroduced:false,curveOrder:[],neutralActionChains:[],situationAssignments:{},knowledgeAssignments:{},goalChoices:{},goalEvidence:{},goalAnalyses:[],chainOrder:[],chainRelations:{},actionReaction:{},tombActionChains:[],escalationAssignments:{},consequences:{},internalPreparation:{},julietAssignments:{},monologueOrder:[],julietAlternatives:{},comparisonAssignments:{},finalCurve:[],finalAssignments:{},miniAnalysis:[],stagingDecisions:{},completed:false,failedAttempts:0,competencyEvents:[],seenGlossaryIntroductions:[]};
const rec=(s:Chapter04Session,c:Chapter04Competency,ok:boolean):Chapter04Session=>({...s,failedAttempts:s.failedAttempts+(ok?0:1),competencyEvents:[...s.competencyEvents,{competency:c,success:ok,round:s.round}]});
const result=(s:Chapter04Session,c:Chapter04Competency,ok:boolean,patch:Partial<Chapter04Session>={},advance=false)=>({valid:ok,session:{...rec(s,c,ok),...(ok?patch:{}),...(ok&&advance?{round:s.round+1}:{})}} as {valid:boolean;session:Chapter04Session});
export const advanceChapter04=(s:Chapter04Session,expected:number,patch:Partial<Chapter04Session>={})=>result(s,"action_analysis",s.round===expected,patch,true);
const assign=<T extends readonly {id:string}[]>(s:Chapter04Session,c:Chapter04Competency,items:T,id:string,target:string,expected:(item:T[number])=>string,done:Record<string,string>,key:keyof Chapter04Session,advance=true)=>{const item=items.find(x=>x.id===id),ok=Boolean(item)&&expected(item!)===target,next=ok?{...done,[id]:target}:done;return result(s,c,ok,{[key]:next},advance&&Object.keys(next).length===items.length)};
export function selectIntroFact(s:Chapter04Session,id:string){const item=introFacts.find(x=>x.id===id);return result(s,"conflict_analysis",Boolean(item?.relevant),item?.relevant?{introRelevant:[...new Set([...s.introRelevant,id])]}:{});}
export const saveIntroGoals=(s:Chapter04Session,mara:string,father:string)=>result(s,"conflict_analysis",mara==="party"&&father==="study",{introGoals:{mara,father}});
export function solveGeneralGoal(s:Chapter04Session,id:string,choice:number){const item=generalGoalTasks.find(x=>x.id===id),ok=item?.answer===choice,done=ok?[...new Set([...s.generalGoals,id])]:s.generalGoals;return result(s,"conflict_analysis",ok,{generalGoals:done},done.length===generalGoalTasks.length&&Object.keys(s.introGoals).length===2)}
export function assignConflictType(s:Chapter04Session,id:string,target:string){const item=conflictTypes.find(x=>x.id===id),ok=item?.answer===target,next=ok?{...s.conflictAssignments,[id]:target}:s.conflictAssignments;return result(s,"conflict_analysis",ok,{conflictAssignments:next},Object.keys(next).length===conflictTypes.length&&Object.keys(s.historyAssignments).length===historyPractice.length)}
export function assignHistory(s:Chapter04Session,id:string,target:string){const item=historyPractice.find(x=>x.id===id),ok=item?.target===target,next=ok?{...s.historyAssignments,[id]:target}:s.historyAssignments;return result(s,"conflict_analysis",ok,{historyAssignments:next},Object.keys(next).length===historyPractice.length&&Object.keys(s.conflictAssignments).length===conflictTypes.length)}
export const assignCausalIntro=(s:Chapter04Session,id:string,target:string)=>assign(s,"causal_reasoning",causalIntro,id,target,x=>x.answer,s.causalIntroAssignments,"causalIntroAssignments");
export const assignGeneralEpistemic=(s:Chapter04Session,id:string,target:string)=>assign(s,"evidence_reasoning",generalEpistemicPractice,id,target,x=>x.target,s.generalEpistemicAssignments,"generalEpistemicAssignments",false);
export function solveGeneralEvidence(s:Chapter04Session,id:string,evidence:number,analysis:number){const item=generalEvidenceTasks.find(x=>x.id===id),ok=item?.evidenceAnswer===evidence&&item.analysisAnswer===analysis,done=ok?[...new Set([...s.generalEvidence,id])]:s.generalEvidence;return result(s,"evidence_reasoning",ok,{generalEvidence:done})}
export const setCurveOrder=(s:Chapter04Session,ids:string[])=>result(s,"action_analysis",dramaticCurve.every((x,i)=>ids[i]===x.id),{curveOrder:ids});
export function solveNeutralActionChain(s:Chapter04Session,id:string,impulse:string,reaction:string,effect:string){const item=neutralActionChains.find(x=>x.id===id),ok=item?.impulse===impulse&&item.reaction===reaction&&item.effect===effect,done=ok?[...new Set([...s.neutralActionChains,id])]:s.neutralActionChains;return result(s,"action_analysis",ok,{neutralActionChains:done},done.length===neutralActionChains.length)}
export function chooseNeutralTurning(s:Chapter04Session,id:string,judgement:string){const item=neutralTurningPoints.find(x=>x.id===id);return result(s,"turning_point",item?.judgement===judgement,{neutralTurning:id},true)}
export const assignSituation=(s:Chapter04Session,id:string,target:string)=>assign(s,"conflict_analysis",situationCards,id,target,x=>x.target,s.situationAssignments,"situationAssignments");
export const assignKnowledge=(s:Chapter04Session,id:string,target:string)=>assign(s,"evidence_reasoning",knowledgeCards,id,target,x=>x.target,s.knowledgeAssignments,"knowledgeAssignments");
export function chooseGoal(s:Chapter04Session,id:string,choice:number){const item=goals.find(x=>x.id===id),ok=item?.goalAnswer===choice;return result(s,"conflict_analysis",ok,{goalChoices:{...s.goalChoices,[id]:choice}})}
export function linkGoal(s:Chapter04Session,id:string,evidence:string,analysis:string){const item=goals.find(x=>x.id===id),ok=s.goalChoices[id]===item?.goalAnswer&&item?.evidence===evidence&&item.analysis===analysis,e=ok?{...s.goalEvidence,[id]:evidence}:s.goalEvidence,a=ok?[...new Set([...s.goalAnalyses,id])]:s.goalAnalyses;return result(s,"evidence_reasoning",ok,{goalEvidence:e,goalAnalyses:a})}
export const setIncompatibility=(s:Chapter04Session,id:string)=>result(s,"conflict_analysis",id==="cannot_both_succeed"&&s.goalAnalyses.length===goals.length,{incompatibilityReason:id},true);
export function placeChainEvent(s:Chapter04Session,id:string){const ok=chain[s.chainOrder.length]?.id===id,order=ok?[...s.chainOrder,id]:s.chainOrder;return result(s,"action_analysis",ok,{chainOrder:order},order.length===chain.length)}
export const setChainRelation=(s:Chapter04Session,from:string,to:string,type:string)=>{const link=chainLinks.find(x=>x.from===from&&x.to===to),ok=link?.type===type,relations=ok?{...s.chainRelations,[`${from}:${to}`]:type}:s.chainRelations;return result(s,"causal_reasoning",ok,{chainRelations:relations},Object.keys(relations).length===chainLinks.length)};
export const assignActionReaction=(s:Chapter04Session,id:string,target:string)=>result(s,"action_analysis",(id==="paris_stops"?"action":id==="romeo_appeals"?"reaction":undefined)===target,{actionReaction:{...s.actionReaction,[id]:target}});
export function solveTombActionChain(s:Chapter04Session,id:string,impulse:string,reaction:string,effect:string){const item=tombActionChains.find(x=>x.id===id),ok=item?.impulse===impulse&&item.reaction===reaction&&item.effect===effect,done=ok?[...new Set([...s.tombActionChains,id])]:s.tombActionChains;return result(s,"action_analysis",ok,{tombActionChains:done},done.length===tombActionChains.length)}
export const chooseAlternative=(s:Chapter04Session,id:string)=>result(s,"action_analysis",id==="paris_allows_exit",{alternative:id},true);
export const assignEscalation=(s:Chapter04Session,id:string,target:string)=>assign(s,"turning_point",escalationCards,id,target,x=>x.level,s.escalationAssignments,"escalationAssignments",false);
export const chooseTurningPoint=(s:Chapter04Session,id:string)=>result(s,"turning_point",id==="fight",{turningPoint:id});
export const explainTurningPoint=(s:Chapter04Session,id:string)=>result(s,"turning_point",id==="form_irreversible"&&s.turningPoint==="fight",{turningReason:id});
export function assignConsequence(s:Chapter04Session,id:string,target:string){const expected=id==="fight"?"immediate":id==="paris_falls"?"farther":id==="peace"?"not_determinable":undefined,ok=expected===target,next=ok?{...s.consequences,[id]:target}:s.consequences;return result(s,"causal_reasoning",ok,{consequences:next},Object.keys(next).length===3)}
export const assignInternalPreparation=(s:Chapter04Session,id:string,target:string)=>assign(s,"internal_conflict",internalPreparation,id,target,x=>x.target,s.internalPreparation,"internalPreparation");
export const assignJuliet=(s:Chapter04Session,id:string,target:string)=>assign(s,"internal_conflict",julietCards,id,target,x=>x.kind,s.julietAssignments,"julietAssignments");
export function placeMonologueStep(s:Chapter04Session,id:string){const ok=julietSequence[s.monologueOrder.length]?.id===id,order=ok?[...s.monologueOrder,id]:s.monologueOrder;return result(s,"internal_conflict",ok,{monologueOrder:order},order.length===julietSequence.length)}
export const distinguishDecision=(s:Chapter04Session,decision:string,execution:string)=>result(s,"turning_point",decision==="c04_juliet_drinks"&&execution==="c04_juliet_execution",{decisionEvidence:decision,executionEvidence:execution},true);
export const assignJulietAlternative=(s:Chapter04Session,id:string,target:string)=>assign(s,"evidence_reasoning",julietAlternatives,id,target,x=>x.target,s.julietAlternatives,"julietAlternatives");
export const assignComparison=(s:Chapter04Session,id:string,target:string)=>assign(s,"transfer_analysis",comparisonAspects,id,target,x=>x.target,s.comparisonAssignments,"comparisonAssignments",false);
export const compareConflicts=(s:Chapter04Session,id:string)=>result(s,"transfer_analysis",["external_vs_internal","representation_difference"].includes(id)&&Object.keys(s.comparisonAssignments).length===comparisonAspects.length,{comparison:id},true);
export const setFinalCurve=(s:Chapter04Session,ids:string[])=>result(s,"action_analysis",finalCurve.every((x,i)=>ids[i]===x.id),{finalCurve:ids});
export const assignFinalRelation=(s:Chapter04Session,id:string,target:string)=>assign(s,"causal_reasoning",finalConnections,id,target,x=>x.answer,s.finalAssignments,"finalAssignments",false);
export const setFinalMeaning=(s:Chapter04Session,id:string)=>result(s,"transfer_analysis",Boolean(finalMeaningOptions.find(x=>x.id===id)?.valid),{finalMeaning:id});
export const setFinalEvidence=(s:Chapter04Session,id:string)=>result(s,"evidence_reasoning",id===finalEvidence.evidence,{finalEvidence:id});
export const setFinalEvidenceAnalysis=(s:Chapter04Session,index:number)=>result(s,"evidence_reasoning",index===finalEvidence.analysisAnswer,{finalEvidenceAnalysis:index});
export const setFinalTransfer=(s:Chapter04Session,id:string)=>result(s,"transfer_analysis",Boolean(finalTransferOptions.find(x=>x.id===id)?.valid),{finalTransfer:id});
export function toggleMiniAnalysis(s:Chapter04Session,id:string){return {...s,miniAnalysis:s.miniAnalysis.includes(id)?s.miniAnalysis.filter(x=>x!==id):[...s.miniAnalysis,id]}}
export function completeChapter04(s:Chapter04Session){const ok=s.finalCurve.length===finalCurve.length&&Object.keys(s.finalAssignments).length===finalConnections.length&&Boolean(s.finalMeaning)&&s.finalEvidence===finalEvidence.evidence&&s.finalEvidenceAnalysis===finalEvidence.analysisAnswer&&Boolean(s.finalTransfer);return result(s,"transfer_analysis",ok,{completed:ok})}
