import { characterizationCards, comparisonCards, ensembleLinks, highlightCandidateIds, highlightReasoning, highlightTasks, momentClaims, momentPractice, practiceClaims, relationshipPractice, relationshipTasks, relevancePractice, rolePractice, roleTasks, selfOtherPractice, selfOtherTasks, shakespeareCharacterizationCards, transferTasks, type AnalysisKind, type Certainty, type MomentKind, type RelevanceKind, type SelfOtherKind } from "../data/chapter_02_content";

export type Chapter02Round=1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17;
export type Chapter02Competency="direct_characterization"|"indirect_characterization"|"evidence_reasoning"|"motivation"|"character_relationships"|"character_development";
export interface Chapter02Event{competency:Chapter02Competency;success:boolean;round:Chapter02Round;}
export interface Chapter02Session{
 round:Chapter02Round;practiceAssignments:Record<string,Certainty>;characterizationAssignments:Record<string,"direct"|"indirect"|"unsupported">;
 momentPracticeAssignments:Record<string,MomentKind>;relevanceAssignments:Record<string,RelevanceKind>;rolePracticeAssignments:Record<string,AnalysisKind>;
 relationshipPracticeSteps:string[];selfOtherPracticeAssignments:Record<string,SelfOtherKind>;
 highlights:string[];highlightSelection:string[];highlightSelectionChecked:boolean;highlightJustification:string|null;momentAssignments:Record<string,"supported"|"uncertain"|"unsupported">;roleAssignments:Record<string,AnalysisKind>;
 relationshipSteps:string[];selfOtherAssignments:Record<string,"self"|"other"|"finding"|"unsupported">;transferSteps:string[];transferAnalyses:Record<string,number>;
 comparisonAssignments:Record<string,"early"|"late"|"conclusion"|"unsupported">;ensembleConnections:string[];completed:boolean;failedAttempts:number;competencyEvents:Chapter02Event[];
 seenGlossaryIntroductions:string[];
}
export const initialChapter02Session:Chapter02Session={round:1,practiceAssignments:{},characterizationAssignments:{},momentPracticeAssignments:{},relevanceAssignments:{},rolePracticeAssignments:{},relationshipPracticeSteps:[],selfOtherPracticeAssignments:{},highlights:[],highlightSelection:[],highlightSelectionChecked:false,highlightJustification:null,momentAssignments:{},roleAssignments:{},relationshipSteps:[],selfOtherAssignments:{},transferSteps:[],transferAnalyses:{},comparisonAssignments:{},ensembleConnections:[],completed:false,failedAttempts:0,competencyEvents:[],seenGlossaryIntroductions:[]};
export function createChapter02Session():Chapter02Session{return structuredClone(initialChapter02Session)}
function record(session:Chapter02Session,competency:Chapter02Competency,success:boolean):Chapter02Session{return{...session,failedAttempts:session.failedAttempts+(success?0:1),competencyEvents:[...session.competencyEvents,{competency,success,round:session.round}]}}
export function advanceChapter02(session:Chapter02Session){return{...session,round:Math.min(17,session.round+1) as Chapter02Round}}
type AssignmentKey="practiceAssignments"|"characterizationAssignments"|"momentPracticeAssignments"|"relevanceAssignments"|"rolePracticeAssignments"|"selfOtherPracticeAssignments"|"momentAssignments"|"roleAssignments"|"selfOtherAssignments"|"comparisonAssignments";
function assign<T extends string>(session:Chapter02Session,key:AssignmentKey,id:string,target:T,expected:T,competency:Chapter02Competency,next:boolean){const valid=target===expected;let result=record(session,competency,valid);if(valid)result={...result,[key]:{...(result[key] as Record<string,T>),[id]:target}};if(valid&&next)result=advanceChapter02(result);return{valid,session:result}}
export function classifyPractice(session:Chapter02Session,id:string,target:Certainty){const item=practiceClaims.find(x=>x.id===id)!;return assign(session,"practiceAssignments",id,target,item.target,"evidence_reasoning",Object.keys(session.practiceAssignments).length+1===practiceClaims.length)}
export function classifyCharacterization(session:Chapter02Session,id:string,target:"direct"|"indirect"|"unsupported"){const general=characterizationCards.some(x=>x.id===id);const items=general?characterizationCards:shakespeareCharacterizationCards;const item=items.find(x=>x.id===id)!;const completed=items.every(entry=>entry.id===id||session.characterizationAssignments[entry.id]);return assign(session,"characterizationAssignments",id,target,item.target,target==="direct"?"direct_characterization":"indirect_characterization",completed)}
export function classifyMomentPractice(session:Chapter02Session,id:string,target:MomentKind){const item=momentPractice.find(x=>x.id===id)!;return assign(session,"momentPracticeAssignments",id,target,item.target,"indirect_characterization",Object.keys(session.momentPracticeAssignments).length+1===momentPractice.length)}
export function classifyRelevance(session:Chapter02Session,id:string,target:RelevanceKind){const item=relevancePractice.find(x=>x.id===id)!;return assign(session,"relevanceAssignments",id,target,item.target,"evidence_reasoning",Object.keys(session.relevanceAssignments).length+1===relevancePractice.length)}
export function classifyRolePractice(session:Chapter02Session,id:string,target:AnalysisKind){const item=rolePractice.find(x=>x.id===id)!;return assign(session,"rolePracticeAssignments",id,target,item.target,"motivation",Object.keys(session.rolePracticeAssignments).length+1===rolePractice.length)}
export function connectPracticeRelationship(session:Chapter02Session,id:string,signal:string,analysis:number){const item=relationshipPractice.find(x=>x.id===id);const valid=item?.signal===signal&&item.answer===analysis;let next=record(session,"character_relationships",valid);if(valid&&item&&!next.relationshipPracticeSteps.includes(id)){const steps=[...next.relationshipPracticeSteps,id];next={...next,relationshipPracticeSteps:steps,round:steps.length===relationshipPractice.length?8:7}}return{valid,session:next}}
export function classifySelfOtherPractice(session:Chapter02Session,id:string,target:SelfOtherKind){const item=selfOtherPractice.find(x=>x.id===id)!;return assign(session,"selfOtherPracticeAssignments",id,target,item.target,"evidence_reasoning",Object.keys(session.selfOtherPracticeAssignments).length+1===selfOtherPractice.length)}
export function toggleTextSignal(session:Chapter02Session,id:string){if(!highlightCandidateIds.includes(id as typeof highlightCandidateIds[number])||session.highlightSelectionChecked)return session;const selected=session.highlightSelection.includes(id)?session.highlightSelection.filter(value=>value!==id):[...session.highlightSelection,id];return{...session,highlightSelection:selected}}
export function checkTextSignals(session:Chapter02Session){const required:string[]=highlightTasks.map(task=>task.sourceId);const allowed=new Set<string>(required);const valid=required.every(id=>session.highlightSelection.includes(id))&&session.highlightSelection.every(id=>allowed.has(id));let next=record(session,"evidence_reasoning",valid);if(valid)next={...next,highlights:[...session.highlightSelection],highlightSelectionChecked:true};return{valid,session:next}}
export function justifyTextSignals(session:Chapter02Session,id:string){const reasoning=highlightReasoning.find(item=>item.id===id);const valid=Boolean(session.highlightSelectionChecked&&reasoning?.valid);let next=record(session,"evidence_reasoning",valid);if(valid)next={...next,highlightJustification:id,round:11};return{valid,session:next}}
export function classifyMoment(session:Chapter02Session,id:string,target:"supported"|"uncertain"|"unsupported"){const item=momentClaims.find(x=>x.id===id)!;return assign(session,"momentAssignments",id,target,item.target,"indirect_characterization",Object.keys(session.momentAssignments).length+1===momentClaims.length)}
export function classifyRole(session:Chapter02Session,id:string,target:AnalysisKind){const item=roleTasks.find(x=>x.id===id)!;return assign(session,"roleAssignments",id,target,item.target,"motivation",Object.keys(session.roleAssignments).length+1===roleTasks.length)}
export function analyzeRelationship(session:Chapter02Session,id:string,sourceId:string,analysis:number){const task=relationshipTasks.find(x=>x.id===id);const valid=task?.sourceId===sourceId&&task.answer===analysis;let next=record(session,"character_relationships",valid);if(valid&&task&&!next.relationshipSteps.includes(id)){const steps=[...next.relationshipSteps,id];next={...next,relationshipSteps:steps,round:steps.length===relationshipTasks.length?14:13}}return{valid,session:next}}
export function classifySelfOther(session:Chapter02Session,id:string,target:"self"|"other"|"finding"|"unsupported"){const item=selfOtherTasks.find(x=>x.id===id)!;return assign(session,"selfOtherAssignments",id,target,item.target,"evidence_reasoning",Object.keys(session.selfOtherAssignments).length+1===selfOtherTasks.length)}
export function solveTransfer(session:Chapter02Session,id:string,sourceId:string,analysis:number){const task=transferTasks.find(x=>x.id===id);const valid=task?.sourceId===sourceId&&task.answer===analysis;let next=record(session,"evidence_reasoning",valid);if(valid&&task&&!next.transferSteps.includes(id)){const steps=[...next.transferSteps,id];next={...next,transferSteps:steps,transferAnalyses:{...next.transferAnalyses,[id]:analysis},round:steps.length===transferTasks.length?16:15}}return{valid,session:next}}
export function compareSituations(session:Chapter02Session,id:string,target:"early"|"late"|"conclusion"|"unsupported"){const item=comparisonCards.find(x=>x.id===id)!;return assign(session,"comparisonAssignments",id,target,item.target,"character_development",Object.keys(session.comparisonAssignments).length+1===comparisonCards.length)}
export function connectEnsemble(session:Chapter02Session,from:string,to:string,analysis:string,sourceId:string){const task=ensembleLinks.find(x=>x.from===from&&x.to===to);const valid=task?.label===analysis&&task.sourceId===sourceId;let next=record(session,"character_relationships",valid);if(valid&&task&&!next.ensembleConnections.includes(task.id)){const links=[...next.ensembleConnections,task.id];next={...next,ensembleConnections:links,completed:links.length===ensembleLinks.length}}return{valid,session:next}}
