import { argumentBlocks, classificationCards, generalChain, hypothesisOptions, interpretationStructure, julietFindings, julietHypothesis, julietReverseChain, transferArgument, transferChain, transferEvidence, transferHypotheses, transferRefined } from "../data/chapter_05_content";
export type Chapter05Competency="interpretation_reasoning"|"hypothesis_building"|"evidence_reasoning"|"relevance_reasoning"|"counterevidence"|"argumentation"|"transfer_analysis";
export interface Chapter05Event{competency:Chapter05Competency;success:boolean;round:number}
export interface Chapter05Session{round:number;classifications:Record<string,string>;generalChain:string[];generalHypothesis?:string;generalRevision?:"keep"|"refine"|"reject";julietRelevance:Record<string,string>;julietChain:string[];julietCountercheck?:string;julietHypothesis:string;julietRevision?:string;julietArgument:string[];errorAssignments:Record<string,string>;structureOrder:string[];transferSelected:string[];transferChain:string[];transferHypothesis?:string;transferCountercheck?:string;transferRevision?:string;transferArgument:string[];synthesis?:string;completed:boolean;failedAttempts:number;competencyEvents:Chapter05Event[];seenGlossaryIntroductions:string[]}
export const initialChapter05Session:Chapter05Session={round:1,classifications:{},generalChain:[],julietRelevance:{},julietChain:[],julietHypothesis:"Juliette ist in dieser Szene völlig machtlos.",julietArgument:[],errorAssignments:{},structureOrder:[],transferSelected:[],transferChain:[],transferArgument:[],completed:false,failedAttempts:0,competencyEvents:[],seenGlossaryIntroductions:[]};
function record(s:Chapter05Session,competency:Chapter05Competency,success:boolean,patch:Partial<Chapter05Session>={}){return{...s,...patch,failedAttempts:s.failedAttempts+(success?0:1),competencyEvents:[...s.competencyEvents,{competency,success,round:s.round}]}}
function ordered(s:Chapter05Session,id:string,items:readonly {id:string}[],field:"generalChain"|"julietChain"|"julietArgument"|"structureOrder"|"transferChain"|"transferArgument",competency:Chapter05Competency,next:number){const current=s[field],ok=items[current.length]?.id===id;return{valid:ok,session:record(s,competency,ok,ok?{[field]:[...current,id],round:current.length+1===items.length?next:s.round}:{})}}
export function classifyStatement(s:Chapter05Session,id:string,target:string){const item=classificationCards.find(x=>x.id===id),ok=item?.target===target,assignments=ok?{...s.classifications,[id]:target}:s.classifications;return{valid:ok,session:record(s,"interpretation_reasoning",ok,{classifications:assignments,round:Object.keys(assignments).length===classificationCards.length?2:s.round})}}
export const placeGeneralChain=(s:Chapter05Session,id:string)=>ordered(s,id,generalChain,"generalChain","evidence_reasoning",3);
export function chooseGeneralHypothesis(s:Chapter05Session,id:string){const item=hypothesisOptions.find(x=>x.id===id),ok=item?.quality==="supported";return{valid:ok,quality:item?.quality,session:record(s,"hypothesis_building",ok,ok?{generalHypothesis:item.text,round:4}:{})}}
export function reviseGeneralHypothesis(s:Chapter05Session,action:"keep"|"refine"|"reject"){const ok=action==="refine";return{valid:ok,session:record(s,"counterevidence",ok,ok?{generalRevision:action,round:5}:{})}}
export function assignJulietRelevance(s:Chapter05Session,id:string,level:string){const item=julietFindings.find(x=>x.id===id),ok=Boolean(item?.accepted.includes(level as never)),assignments=ok?{...s.julietRelevance,[id]:level}:s.julietRelevance;return{valid:ok,accepted:item?.accepted,session:record(s,"relevance_reasoning",ok,{julietRelevance:assignments,round:Object.keys(assignments).length===julietFindings.length?6:s.round})}}
export const placeJulietChain=(s:Chapter05Session,id:string)=>ordered(s,id,[...julietReverseChain].reverse(),"julietChain","evidence_reasoning",7);
export function countercheckJuliet(s:Chapter05Session,id:string){const ok=id==="juliet_has_agency";return{valid:ok,session:record(s,"counterevidence",ok,ok?{julietCountercheck:id,round:8}:{})}}
export function refineJuliet(s:Chapter05Session,text:string){const ok=text===julietHypothesis&&text!==s.julietHypothesis;return{valid:ok,session:record(s,"hypothesis_building",ok,ok?{julietHypothesis:text,julietRevision:text,round:9}:{})}}
export const placeJulietArgument=(s:Chapter05Session,id:string)=>ordered(s,id,argumentBlocks,"julietArgument","argumentation",10);
export function assignError(s:Chapter05Session,id:string,target:string,expected:string,total:number){const ok=target===expected,assignments=ok?{...s.errorAssignments,[id]:target}:s.errorAssignments;return{valid:ok,session:record(s,"interpretation_reasoning",ok,{errorAssignments:assignments,round:Object.keys(assignments).length===total?11:s.round})}}
export const placeStructure=(s:Chapter05Session,id:string)=>ordered(s,id,interpretationStructure.map((_,index)=>({id:`structure_${index}`})),"structureOrder","argumentation",12);
export function selectTransferEvidence(s:Chapter05Session,id:string){const item=transferEvidence.find(x=>x.id===id),ok=item?.relevance!=="little",selected=ok&&!s.transferSelected.includes(id)?[...s.transferSelected,id]:s.transferSelected;return{valid:ok,session:record(s,"relevance_reasoning",ok,{transferSelected:selected,round:selected.length>=4?13:s.round})}}
export const placeTransferChain=(s:Chapter05Session,id:string)=>ordered(s,id,transferChain,"transferChain","transfer_analysis",14);
export function chooseTransferHypothesis(s:Chapter05Session,id:string){const item=transferHypotheses.find(x=>x.id===id),ok=item?.quality==="supported";return{valid:ok,quality:item?.quality,session:record(s,"hypothesis_building",ok,ok?{transferHypothesis:item.text,round:15}:{})}}
export function countercheckTransfer(s:Chapter05Session,id:string){const ok=id==="apothecary_resists";return{valid:ok,session:record(s,"counterevidence",ok,ok?{transferCountercheck:id,round:16}:{})}}
export function refineTransfer(s:Chapter05Session,text:string){const ok=text===transferRefined&&text!==s.transferHypothesis;return{valid:ok,session:record(s,"hypothesis_building",ok,ok?{transferRevision:text,transferHypothesis:text,round:17}:{})}}
export const placeTransferArgument=(s:Chapter05Session,id:string)=>ordered(s,id,transferArgument,"transferArgument","argumentation",18);
export function synthesize(s:Chapter05Session,id:string){const ok=id==="synthesis_complete";return{valid:ok,session:record(s,"transfer_analysis",ok,ok?{synthesis:id,round:19}:{})}}
export function completeChapter05(s:Chapter05Session){const ok=s.synthesis==="synthesis_complete"&&s.transferArgument.length===transferArgument.length&&Boolean(s.transferRevision);return{valid:ok,session:record(s,"interpretation_reasoning",ok,{completed:ok})}}
