import { characterizationCards, comparisonCards, ensembleLinks, highlightCandidateIds, highlightReasoning, highlightTasks, momentClaims, practiceClaims, relationshipTasks, roleTasks, selfOtherTasks, shakespeareCharacterizationCards, transferTasks, type AnalysisKind, type Certainty } from "../data/chapter_02_content";

export type Chapter02Round=1|2|3|4|5|6|7|8|9|10|11;
export type Chapter02Competency="direct_characterization"|"indirect_characterization"|"evidence_reasoning"|"motivation"|"character_relationships"|"character_development";
export interface Chapter02Event{competency:Chapter02Competency;success:boolean;round:Chapter02Round;}
export interface Chapter02Session{
 round:Chapter02Round;practiceAssignments:Record<string,Certainty>;characterizationAssignments:Record<string,"direct"|"indirect"|"unsupported">;
 highlights:string[];highlightSelection:string[];highlightSelectionChecked:boolean;highlightJustification:string|null;momentAssignments:Record<string,"supported"|"uncertain"|"unsupported">;roleAssignments:Record<string,AnalysisKind>;
 relationshipSteps:string[];selfOtherAssignments:Record<string,"self"|"other">;transferSteps:string[];
 comparisonAssignments:Record<string,"early"|"late"|"conclusion">;ensembleConnections:string[];completed:boolean;failedAttempts:number;competencyEvents:Chapter02Event[];
 seenGlossaryIntroductions:string[];
}
export const initialChapter02Session:Chapter02Session={round:1,practiceAssignments:{},characterizationAssignments:{},highlights:[],highlightSelection:[],highlightSelectionChecked:false,highlightJustification:null,momentAssignments:{},roleAssignments:{},relationshipSteps:[],selfOtherAssignments:{},transferSteps:[],comparisonAssignments:{},ensembleConnections:[],completed:false,failedAttempts:0,competencyEvents:[],seenGlossaryIntroductions:[]};
export function createChapter02Session():Chapter02Session{return structuredClone(initialChapter02Session)}
function record(session:Chapter02Session,competency:Chapter02Competency,success:boolean):Chapter02Session{return{...session,failedAttempts:session.failedAttempts+(success?0:1),competencyEvents:[...session.competencyEvents,{competency,success,round:session.round}]}}
export function advanceChapter02(session:Chapter02Session){return{...session,round:Math.min(11,session.round+1) as Chapter02Round}}
function assign<T extends string>(session:Chapter02Session,key:"practiceAssignments"|"characterizationAssignments"|"momentAssignments"|"roleAssignments"|"selfOtherAssignments"|"comparisonAssignments",id:string,target:T,expected:T,competency:Chapter02Competency,next:boolean){const valid=target===expected;let result=record(session,competency,valid);if(valid)result={...result,[key]:{...(result[key] as Record<string,T>),[id]:target}};if(valid&&next)result=advanceChapter02(result);return{valid,session:result}}
export function classifyPractice(session:Chapter02Session,id:string,target:Certainty){const item=practiceClaims.find(x=>x.id===id)!;return assign(session,"practiceAssignments",id,target,item.target,"evidence_reasoning",Object.keys(session.practiceAssignments).length+1===practiceClaims.length)}
export function classifyCharacterization(session:Chapter02Session,id:string,target:"direct"|"indirect"|"unsupported"){const items=[...characterizationCards,...shakespeareCharacterizationCards];const item=items.find(x=>x.id===id)!;return assign(session,"characterizationAssignments",id,target,item.target,target==="direct"?"direct_characterization":"indirect_characterization",Object.keys(session.characterizationAssignments).length+1===items.length)}
export function toggleTextSignal(session:Chapter02Session,id:string){if(!highlightCandidateIds.includes(id as typeof highlightCandidateIds[number])||session.highlightSelectionChecked)return session;const selected=session.highlightSelection.includes(id)?session.highlightSelection.filter(value=>value!==id):[...session.highlightSelection,id];return{...session,highlightSelection:selected}}
export function checkTextSignals(session:Chapter02Session){const required:string[]=highlightTasks.map(task=>task.sourceId);const allowed=new Set<string>(required);const valid=required.every(id=>session.highlightSelection.includes(id))&&session.highlightSelection.every(id=>allowed.has(id));let next=record(session,"evidence_reasoning",valid);if(valid)next={...next,highlights:[...session.highlightSelection],highlightSelectionChecked:true};return{valid,session:next}}
export function justifyTextSignals(session:Chapter02Session,id:string){const reasoning=highlightReasoning.find(item=>item.id===id);const valid=Boolean(session.highlightSelectionChecked&&reasoning?.valid);let next=record(session,"evidence_reasoning",valid);if(valid)next={...next,highlightJustification:id,round:5};return{valid,session:next}}
export function classifyMoment(session:Chapter02Session,id:string,target:"supported"|"uncertain"|"unsupported"){const item=momentClaims.find(x=>x.id===id)!;return assign(session,"momentAssignments",id,target,item.target,"indirect_characterization",Object.keys(session.momentAssignments).length+1===momentClaims.length)}
export function classifyRole(session:Chapter02Session,id:string,target:AnalysisKind){const item=roleTasks.find(x=>x.id===id)!;return assign(session,"roleAssignments",id,target,item.target,"motivation",Object.keys(session.roleAssignments).length+1===roleTasks.length)}
export function analyzeRelationship(session:Chapter02Session,id:string,sourceId:string){const task=relationshipTasks.find(x=>x.id===id);const valid=task?.sourceId===sourceId;let next=record(session,"character_relationships",valid);if(valid&&task&&!next.relationshipSteps.includes(id)){const steps=[...next.relationshipSteps,id];next={...next,relationshipSteps:steps,round:steps.length===relationshipTasks.length?8:7}}return{valid,session:next}}
export function classifySelfOther(session:Chapter02Session,id:string,target:"self"|"other"){const item=selfOtherTasks.find(x=>x.id===id)!;return assign(session,"selfOtherAssignments",id,target,item.target,"evidence_reasoning",Object.keys(session.selfOtherAssignments).length+1===selfOtherTasks.length)}
export function solveTransfer(session:Chapter02Session,id:string,sourceId:string){const task=transferTasks.find(x=>x.id===id);const valid=task?.sourceId===sourceId;let next=record(session,"evidence_reasoning",valid);if(valid&&task&&!next.transferSteps.includes(id)){const steps=[...next.transferSteps,id];next={...next,transferSteps:steps,round:steps.length===transferTasks.length?10:9}}return{valid,session:next}}
export function compareSituations(session:Chapter02Session,id:string,target:"early"|"late"|"conclusion"){const item=comparisonCards.find(x=>x.id===id)!;return assign(session,"comparisonAssignments",id,target,item.target,"character_development",Object.keys(session.comparisonAssignments).length+1===comparisonCards.length)}
export function connectEnsemble(session:Chapter02Session,from:string,to:string,sourceId:string){const task=ensembleLinks.find(x=>x.from===from&&x.to===to);const valid=task?.sourceId===sourceId;let next=record(session,"character_relationships",valid);if(valid&&task&&!next.ensembleConnections.includes(task.id)){const links=[...next.ensembleConnections,task.id];next={...next,ensembleConnections:links,completed:links.length===ensembleLinks.length}}return{valid,session:next}}
