import { GenericEvidenceReasoningEngine } from "../../../core/interactions/evidence_reasoning_engine";
import { analysisResults } from "../data/chapter_05/evidence_selection";
import { interpretationLinks } from "../data/chapter_05/interpretation_links";
import { interpretationClaims } from "../data/chapter_05/unsupported_claims";
import { escalationStructure, oneSidedClaim } from "../data/chapter_05/countercheck";
import { argumentBlocks } from "../data/chapter_05/argument_chain";
import { refinedHypothesis } from "../data/chapter_05/hypothesis";
import type { StagingDecision } from "../data/staging";
export type Chapter05Round=1|2|3|4|5|6|7|8;
export type Chapter05Competency="relevance_selection"|"interpretation"|"evidence_reasoning"|"hypothesis_testing"|"claim_validation"|"argument_structure"|"critical_revision"|"staging_reasoning";
export interface StoredInterpretationLink{id:string;observation_id:string;evidence_id:string;explanation_id:string;hypothesis_relation:string}
export interface Chapter05Event{competency:Chapter05Competency;success:boolean;round:Chapter05Round}
export interface Chapter05Session{round:Chapter05Round;relevanceAssignments:Record<string,string>;pendingInterpretation:{observation_id:string;explanation_id:string;hypothesis_relation:string}|null;interpretationLinks:StoredInterpretationLink[];claimAssignments:Record<string,string>;escalationAssignments:Record<string,string>;countercheckPassed:boolean;hypothesisRefined:boolean;argumentOrder:string[];stagingReviewLoaded:boolean;stagingRevision:StagingDecision|null;revisionCount:number;completed:boolean;failedAttempts:number;competencyEvents:Chapter05Event[]}
export const initialChapter05Session:Chapter05Session={round:1,relevanceAssignments:{},pendingInterpretation:null,interpretationLinks:[],claimAssignments:{},escalationAssignments:{},countercheckPassed:false,hypothesisRefined:false,argumentOrder:[],stagingReviewLoaded:false,stagingRevision:null,revisionCount:0,completed:false,failedAttempts:0,competencyEvents:[]};
const reasoning=new GenericEvidenceReasoningEngine([],interpretationLinks.map(x=>({id:x.id,observationId:x.observation_id,evidenceId:x.evidence_reference,explanationId:x.explanation_id,hypothesisRelation:x.hypothesis_relation})));
function record(s:Chapter05Session,c:Chapter05Competency,ok:boolean){return{...s,failedAttempts:s.failedAttempts+(ok?0:1),competencyEvents:[...s.competencyEvents,{competency:c,success:ok,round:s.round}]}}
export function classifyRelevance(s:Chapter05Session,id:string,level:string){const item=analysisResults.find(x=>x.id===id),ok=item?.relevance===level;let n=record(s,"relevance_selection",ok);if(item&&ok)n={...n,relevanceAssignments:{...n.relevanceAssignments,[id]:level}};if(Object.keys(n.relevanceAssignments).length===analysisResults.length)n={...n,round:2};return{valid:ok,actual:item?.relevance,session:n}}
export function explainObservation(s:Chapter05Session,observationId:string,explanationId:string,relation:string){const link=interpretationLinks.find(x=>x.observation_id===observationId),ok=link?.explanation_id===explanationId&&link.hypothesis_relation===relation;const n=record({...s,pendingInterpretation:ok?{observation_id:observationId,explanation_id:explanationId,hypothesis_relation:relation}:s.pendingInterpretation,round:ok?3:2},"interpretation",ok);return{valid:ok,session:n}}
export function attachEvidence(s:Chapter05Session,evidenceId:string){const p=s.pendingInterpretation;if(!p)return{valid:false,session:record(s,"evidence_reasoning",false)};const result=reasoning.evaluateInterpretation({observationId:p.observation_id,evidenceId,explanationId:p.explanation_id,hypothesisRelation:p.hypothesis_relation as "supports"|"qualifies"|"contradicts"|"irrelevant"});const link=interpretationLinks.find(x=>x.observation_id===p.observation_id)!;const stored={id:link.id,observation_id:p.observation_id,evidence_id:evidenceId,explanation_id:p.explanation_id,hypothesis_relation:p.hypothesis_relation};const n=record({...s,interpretationLinks:result.valid?[...s.interpretationLinks,stored]:s.interpretationLinks,pendingInterpretation:null,round:result.valid?4:3},"evidence_reasoning",result.valid);return{valid:result.valid,session:n}}
export function classifyInterpretationClaim(s:Chapter05Session,id:string,status:string){const item=interpretationClaims.find(x=>x.id===id),ok=item?.status===status;let n=record(s,"claim_validation",ok);if(ok)n={...n,claimAssignments:{...n.claimAssignments,[id]:status}};if(Object.keys(n.claimAssignments).length===interpretationClaims.length)n={...n,round:5};return{valid:ok,session:n}}
export function assignEscalationLevel(s:Chapter05Session,id:string,level:string){const item=escalationStructure.find(x=>x.id===id),ok=item?.level===level;let n=record(s,"hypothesis_testing",ok);if(ok)n={...n,escalationAssignments:{...n.escalationAssignments,[id]:level}};if(Object.keys(n.escalationAssignments).length===escalationStructure.length)n={...n,round:6};return{valid:ok,session:n}}
export function countercheck(s:Chapter05Session,claim:string,refine:boolean){const ok=claim===oneSidedClaim;const n=record({...s,countercheckPassed:ok,hypothesisRefined:ok&&refine,round:ok?7:6},"critical_revision",ok);return{valid:ok,hypothesis:ok&&refine?refinedHypothesis:null,session:n}}
export function placeArgumentBlock(s:Chapter05Session,id:string){const ok=argumentBlocks[s.argumentOrder.length]?.id===id;let n=record(s,"argument_structure",ok);if(ok)n={...n,argumentOrder:[...n.argumentOrder,id]};if(n.argumentOrder.length===argumentBlocks.length)n={...n,round:8};return{valid:ok,session:n}}
export function loadStagingReview(s:Chapter05Session,decisions:Record<string,StagingDecision>){return{...s,stagingReviewLoaded:true,stagingRevision:s.stagingRevision??null,completed:false,round:8 as const,_loadedDecisionCount:Object.keys(decisions).length}}
export function reviseStagingOnce(s:Chapter05Session,decision:StagingDecision){if(s.revisionCount>=1)return{valid:false,session:record(s,"staging_reasoning",false)};const n=record({...s,stagingRevision:{...decision},revisionCount:1},"staging_reasoning",true);return{valid:true,session:n}}
export function completeChapter05(s:Chapter05Session){const ok=s.stagingReviewLoaded&&s.revisionCount===1;const n=record({...s,completed:ok},"interpretation",ok);return{valid:ok,session:n}}
