import { BasicStagingEngine } from "./staging_engine";
import type { FixedStageDirection, StagingDecision } from "../data/staging";
import { fixedStageDirections } from "../data/chapter_04/scene_source";
import { conversationGoals, dialoguePhases, escalationPoints, languageObservations, perspectives, speechActs } from "../data/chapter_04/analysis";
import { directorError, rehearsalMoments, stagingOptions } from "../data/chapter_04/staging_options";
export type Chapter04Round=1|2|3|4|5|6|7|8|9|10;
export type Chapter04Competency="dialogue_analysis"|"conversation_goals"|"speech_acts"|"conversation_development"|"conflict_analysis"|"language_analysis"|"nonverbal_analysis"|"staging_reasoning"|"evidence_reasoning"|"perspective_analysis";
export interface Chapter04Event{competency:Chapter04Competency;success:boolean;round:Chapter04Round}
export interface Chapter04Session{round:Chapter04Round;perspectiveAssignments:Record<string,string>;goalEvidence:Record<string,string>;speechAssignments:Record<string,string>;orderedPhases:string[];escalationSelections:string[];languageFindings:string[];stagingDecisions:Record<string,StagingDecision>;rehearsalPlayed:boolean;rehearsalMoment:number;counterprobeActive:boolean;correctionUsed:boolean;directorErrorResolved:boolean;revisedRehearsalPlayed:boolean;completed:boolean;failedAttempts:number;competencyEvents:Chapter04Event[]}
export const initialChapter04Session:Chapter04Session={round:1,perspectiveAssignments:{},goalEvidence:{},speechAssignments:{},orderedPhases:[],escalationSelections:[],languageFindings:[],stagingDecisions:{},rehearsalPlayed:false,rehearsalMoment:0,counterprobeActive:false,correctionUsed:false,directorErrorResolved:false,revisedRehearsalPlayed:false,completed:false,failedAttempts:0,competencyEvents:[]};
function record(s:Chapter04Session,c:Chapter04Competency,ok:boolean){return{...s,failedAttempts:s.failedAttempts+(ok?0:1),competencyEvents:[...s.competencyEvents,{competency:c,success:ok,round:s.round}]}}
export function assignPerspective(s:Chapter04Session,id:string,target:string){const item=perspectives.find(x=>x.id===id),ok=item?.target===target;let n=record(s,"perspective_analysis",ok);if(ok)n={...n,perspectiveAssignments:{...n.perspectiveAssignments,[id]:target}};if(Object.keys(n.perspectiveAssignments).length===2)n={...n,round:2};return{valid:ok,session:n}}
export function linkGoal(s:Chapter04Session,character:string,evidence:string){const goal=conversationGoals.find(x=>x.character_id===character),ok=Boolean(goal?.evidence.includes(evidence as never));let n=record(s,"conversation_goals",ok);if(ok)n={...n,goalEvidence:{...n.goalEvidence,[character]:evidence}};if(character==="paris"&&ok)n={...n,round:3};if(character==="romeo"&&ok)n={...n,round:4};return{valid:ok,session:n}}
export function assignSpeechAct(s:Chapter04Session,id:string,target:string){const item=speechActs.find(x=>x.id===id),ok=item?.target===target;let n=record(s,"speech_acts",ok);if(ok)n={...n,speechAssignments:{...n.speechAssignments,[id]:target}};if(Object.keys(n.speechAssignments).length===speechActs.length)n={...n,round:5};return{valid:ok,session:n}}
export function placeDialoguePhase(s:Chapter04Session,label:string){const ok=dialoguePhases[s.orderedPhases.length]===label;let n=record(s,"conversation_development",ok);if(ok)n={...n,orderedPhases:[...n.orderedPhases,label]};return{valid:ok,session:n}}
export function toggleEscalation(s:Chapter04Session,id:string){if(!escalationPoints.some(x=>x.id===id))return s;const selected=s.escalationSelections.includes(id)?s.escalationSelections.filter(x=>x!==id):[...s.escalationSelections,id];return{...s,escalationSelections:selected}}
export function finishDevelopment(s:Chapter04Session){const ok=s.orderedPhases.length===dialoguePhases.length&&s.escalationSelections.length>=2;const n=record({...s,round:ok?6:5},"conflict_analysis",ok);return{valid:ok,session:n}}
export function inspectLanguage(s:Chapter04Session,id:string){const ok=languageObservations.some(x=>x.id===id);let n=record(s,"language_analysis",ok);if(ok&&!n.languageFindings.includes(id))n={...n,languageFindings:[...n.languageFindings,id]};if(n.languageFindings.length===languageObservations.length)n={...n,round:7};return{valid:ok,session:n}}
const fixed:FixedStageDirection[]=fixedStageDirections.map(item=>({id:item.id,exactText:item.text,fixed:true,kind:"fixed_stage_direction",sourceReference:item.id}));
export function saveStaging(s:Chapter04Session,optionId:string,value:string,reasoningId:string){const option=stagingOptions.find(x=>x.id===optionId);if(!option)return{valid:false,quality:null,feedback:"Unbekannte Regieentscheidung.",session:record(s,"staging_reasoning",false)};const combination=option.combinations.find((item)=>item.value===value&&item.reasoningId===reasoningId);const decision:StagingDecision={id:option.id,dimension:option.type,characterId:option.character_id,value,evidenceIds:[option.source_reference],reasoningId,kind:"optional_staging_choice"};const engine=new BasicStagingEngine(fixed,stagingOptions);engine.restore(s.stagingDecisions);const result=engine.evaluate(decision);let n=record(s,"staging_reasoning",result.valid);if(result.valid)n={...n,stagingDecisions:engine.getDecisions()};if(Object.keys(n.stagingDecisions).length>=3&&s.round===7)n={...n,round:8};if(Object.keys(n.stagingDecisions).length===stagingOptions.length&&s.round===8)n={...n,round:9};return{valid:result.valid,quality:combination?.quality??null,feedback:combination?.feedback??"Regiewert und Begründung gehören nicht zusammen.",session:n}}
export function playRehearsal(s:Chapter04Session){return{...s,rehearsalPlayed:true,rehearsalMoment:0}}
export function advanceRehearsal(s:Chapter04Session){if(!s.rehearsalPlayed)return s;const next=s.rehearsalMoment+1;return next<rehearsalMoments.length?{...s,rehearsalMoment:next}:{...s,round:10 as const,counterprobeActive:true,rehearsalMoment:rehearsalMoments.length-1}}
export function resolveDirectorError(s:Chapter04Session,evidence:string){const ok=evidence===directorError.counterEvidence;const n=record({...s,directorErrorResolved:ok},"evidence_reasoning",ok);return{valid:ok,session:n}}
export function correctOneDecision(s:Chapter04Session,id:string,value:string,reasoningId:string){const current=s.stagingDecisions[id],option=stagingOptions.find((item)=>item.id===id);if(!current||!option||s.correctionUsed||!s.directorErrorResolved||current.value===value)return{valid:false,session:record(s,"staging_reasoning",false)};const decision:StagingDecision={...current,value,reasoningId};const engine=new BasicStagingEngine(fixed,stagingOptions);engine.restore(s.stagingDecisions);const result=engine.evaluate(decision);const n=record(result.valid?{...s,stagingDecisions:engine.getDecisions(),correctionUsed:true,counterprobeActive:false}:s,"staging_reasoning",result.valid);return{valid:result.valid,session:n}}
export function playCorrectedRehearsal(s:Chapter04Session){return s.correctionUsed?{...s,revisedRehearsalPlayed:true}:s}
export function completeChapter04(s:Chapter04Session){const ok=s.directorErrorResolved&&s.correctionUsed&&s.revisedRehearsalPlayed;const n=record({...s,completed:ok},"staging_reasoning",ok);return{valid:ok,session:n}}
