import { GenericCausalChainEngine, type CausalConnection } from "../../../core/interactions/causal_chain_engine";
import { audienceKnowledge } from "../data/chapter_03/audience_knowledge";
import { causalEvents } from "../data/chapter_03/causal_chain";
import { relationalRoles } from "../data/chapter_03/cause_effect";
import { archiveClues } from "../data/chapter_03/evidence";
import { evidenceClaims } from "../data/chapter_03/unsupported_claims";
import { chapter03Knowledge } from "../data/chapter_03/knowledge_states";
import { relevanceCards } from "../data/chapter_03/relevance";

export type Chapter03Round=1|2|3|4|5|6|7|8|9;
export type Chapter03Competency="situation_analysis"|"context_analysis"|"cause_effect"|"causal_reasoning"|"knowledge_state_analysis"|"evidence_reasoning"|"relevance_selection"|"unsupported_claim_detection";
export interface Chapter03Event{competency:Chapter03Competency;success:boolean;round:Chapter03Round;}
export interface Chapter03Session{round:Chapter03Round;messageAssignments:Record<string,string>;knowledgeAssignments:Record<string,string>;foundClues:string[];orderedEvents:string[];causalConnections:CausalConnection[];roleAssignments:Record<string,string>;missingInformationSelected:boolean;audienceAssignments:Record<string,string>;claimAssignments:Record<string,string>;relevanceSelections:string[];completed:boolean;failedAttempts:number;competencyEvents:Chapter03Event[];}
export const initialChapter03Session:Chapter03Session={round:1,messageAssignments:{},knowledgeAssignments:{},foundClues:[],orderedEvents:[],causalConnections:[],roleAssignments:{},missingInformationSelected:false,audienceAssignments:{},claimAssignments:{},relevanceSelections:[],completed:false,failedAttempts:0,competencyEvents:[]};
const causalEngine=new GenericCausalChainEngine(causalEvents);
function record(session:Chapter03Session,competency:Chapter03Competency,success:boolean){return{...session,failedAttempts:session.failedAttempts+(success?0:1),competencyEvents:[...session.competencyEvents,{competency,success,round:session.round}]};}
function assigned(next:Record<string,string>,items:readonly {id:string;target:string}[]){return items.every((item)=>next[item.id]===item.target);}
export function assignMessage(session:Chapter03Session,id:string,target:string){const expected=id==="message_balthasar"?"balthasar":"lorenzo";const valid=target===expected;let next=record(session,"situation_analysis",valid);if(valid)next={...next,messageAssignments:{...next.messageAssignments,[id]:target}};if(Object.keys(next.messageAssignments).length===2)next={...next,round:2};return{valid,session:next};}
export function assignKnowledge(session:Chapter03Session,id:string,target:string){const item=chapter03Knowledge.find((entry)=>entry.id===id);const valid=item?.target===target;let next=record(session,"knowledge_state_analysis",valid);if(valid)next={...next,knowledgeAssignments:{...next.knowledgeAssignments,[id]:target}};if(assigned(next.knowledgeAssignments,chapter03Knowledge))next={...next,round:3};return{valid,session:next};}
export function inspectClue(session:Chapter03Session,id:string){const valid=archiveClues.some((item)=>item.id===id);let next=record(record(session,"context_analysis",valid),"evidence_reasoning",valid);if(valid&&!next.foundClues.includes(id))next={...next,foundClues:[...next.foundClues,id]};if(next.foundClues.length===archiveClues.length)next={...next,round:4};return{valid,session:next};}
export function placeCausalEvent(session:Chapter03Session,id:string,index:number){const expected=causalEvents[index]?.id;const valid=id===expected&&!session.orderedEvents.includes(id);let next=record(session,"causal_reasoning",valid);if(valid){const ordered=[...next.orderedEvents];ordered[index]=id;next={...next,orderedEvents:ordered};}return{valid,session:next};}
export function connectCausalEvents(session:Chapter03Session,from:string,to:string){causalEngine.reset();causalEngine.restore(session.causalConnections);const result=causalEngine.evaluate({from,to});let next=record(session,"cause_effect",result.valid);if(result.valid)next={...next,causalConnections:causalEngine.getConnections()};if(causalEngine.isComplete())next={...next,round:5};return{valid:result.valid,session:next};}
export function assignRelationalRole(session:Chapter03Session,id:string,role:string){const item=relationalRoles.find((entry)=>entry.id===id);const valid=item?.role===role;let next=record(session,"cause_effect",valid);if(valid)next={...next,roleAssignments:{...next.roleAssignments,[id]:role}};if(relationalRoles.every((item)=>next.roleAssignments[item.id]===item.role))next={...next,round:6};return{valid,session:next};}
export function selectMissingInformation(session:Chapter03Session,id:string){const valid=id==="missing_plan";let next=record(session,"situation_analysis",valid);if(valid)next={...next,missingInformationSelected:true,round:7};return{valid,session:next};}
export function assignAudienceKnowledge(session:Chapter03Session,id:string,target:string){const item=audienceKnowledge.find((entry)=>entry.id===id);const valid=item?.target===target;let next=record(session,"knowledge_state_analysis",valid);if(valid)next={...next,audienceAssignments:{...next.audienceAssignments,[id]:target}};if(assigned(next.audienceAssignments,audienceKnowledge))next={...next,round:8};return{valid,session:next};}
export function classifyClaim(session:Chapter03Session,id:string,target:string){const item=evidenceClaims.find((entry)=>entry.id===id);const valid=Boolean(item&&(target==="supported")===item.supported);let next=record(session,"unsupported_claim_detection",valid);if(valid)next={...next,claimAssignments:{...next.claimAssignments,[id]:target}};if(evidenceClaims.every((item)=>next.claimAssignments[item.id]===(item.supported?"supported":"unsupported")))next={...next,round:9};return{valid,session:next};}
export function toggleRelevance(session:Chapter03Session,id:string){return{...session,relevanceSelections:session.relevanceSelections.includes(id)?session.relevanceSelections.filter((item)=>item!==id):[...session.relevanceSelections,id]};}
export function completeChapter03(session:Chapter03Session){const valid=relevanceCards.every((item)=>session.relevanceSelections.includes(item.id)===item.relevant);const next=record({...session,completed:valid},"relevance_selection",valid);return{valid,session:next};}
