import type { CompetencyLevel, GameState } from "../../../core/state/types";
export interface VisibleCompetencyDefinition{id:string;label:string;sources:readonly string[];feedback:Record<CompetencyLevel,string>}
const feedback=(noun:string):Record<CompetencyLevel,string>=>({developing:`Sie erschließen ${noun} zunehmend sicher. Binden Sie Beobachtungen noch konsequenter an Belege.`,progressing:`Ihre Arbeit mit ${noun} ist grundsätzlich stimmig und entwickelt sich weiter.`,secure:`Sie nutzen ${noun} sicher für Analyse und Deutung.`,advanced:noun==="Textbelege"?"Sie verbinden Textbelege und Schlussfolgerungen sehr sicher miteinander.":`Sie verbinden ${noun}, Textbelege und Schlussfolgerungen sehr sicher miteinander.`});
export const visibleCompetencies:readonly VisibleCompetencyDefinition[]=[
 {id:"text_access",label:"Dramatische Texte erschließen",sources:["text_structure","stage_direction","speaker_assignment","scene_orientation"],feedback:feedback("dramatische Textstrukturen")},
 {id:"character_analysis",label:"Figuren analysieren",sources:["character_relationships","direct_characterization","indirect_characterization","motivation","conflict_analysis","character_development"],feedback:feedback("Figurenbeziehungen und Handlungen")},
 {id:"situation_action",label:"Situation und Handlung verstehen",sources:["situation_analysis","context_analysis","cause_effect","causal_reasoning","knowledge_state_analysis"],feedback:feedback("Situations- und Handlungszusammenhänge")},
 {id:"dialogue",label:"Dialoge untersuchen",sources:["dialogue_analysis","conversation_goals","speech_acts","conversation_development","language_analysis"],feedback:feedback("Gesprächsverläufe und Sprachhandlungen")},
 {id:"evidence",label:"Textbelege nutzen",sources:["evidence_reasoning","claim_validation","unsupported_claim_detection","relevance_selection"],feedback:feedback("Textbelege")},
 {id:"interpretation",label:"Interpretieren",sources:["interpretation","hypothesis_testing","argument_structure","critical_revision"],feedback:feedback("Analyseergebnisse für Interpretationen")},
 {id:"staging",label:"Inszenierungen begründen",sources:["staging_reasoning","nonverbal_analysis","perspective_analysis"],feedback:feedback("textgebundene Inszenierungsentscheidungen")},
] as const;
function levelFor(value:number):CompetencyLevel{return value>=5?"advanced":value>=3.5?"secure":value>=2?"progressing":"developing"}
function normalizedMicroScore(value:number){return Math.min(5,Math.max(0,value))}
export function aggregateVisibleCompetencies(state:Pick<GameState,"competencies"|"decisions">){const revised=Boolean((state.decisions.chapter_05 as {revisionCount?:number}|undefined)?.revisionCount);return Object.fromEntries(visibleCompetencies.map(def=>{const values=def.sources.map(id=>state.competencies[id]?.value).filter((value):value is number=>typeof value==="number").map(normalizedMicroScore);let score=values.length?values.reduce((a,b)=>a+b,0)/values.length:0;if(def.id==="staging"&&revised)score=Math.min(5,score+.5);const level=levelFor(score);return[def.id,{label:def.label,level,feedback:def.feedback[level],score}]}));}
export function findDistinctStrength(results:ReturnType<typeof aggregateVisibleCompetencies>){const entries=Object.entries(results).sort((a,b)=>b[1].score-a[1].score);return entries.length>1&&entries[0][1].score>entries[1][1].score+.5?entries[0][0]:null}
export function findDevelopmentArea(results:ReturnType<typeof aggregateVisibleCompetencies>){const entries=Object.entries(results).sort((a,b)=>a[1].score-b[1].score);return entries.length&&entries[0][1].level!=="advanced"?entries[0][0]:null}
