import type { CompetencyLevel, GameState } from "../../../core/state/types";
export interface VisibleCompetencyDefinition{id:string;label:string;sources:readonly string[];feedback:Record<CompetencyLevel,string>}
const feedback=(noun:string):Record<CompetencyLevel,string>=>({developing:`Sie erschließen ${noun} zunehmend sicher. Binden Sie Beobachtungen noch konsequenter an Belege.`,progressing:`Ihre Arbeit mit ${noun} ist grundsätzlich stimmig und entwickelt sich weiter.`,secure:`Sie nutzen ${noun} sicher für Analyse und Deutung.`,advanced:noun==="Textbelege"?"Sie verbinden Textbelege und Schlussfolgerungen sehr sicher miteinander.":`Sie verbinden ${noun}, Textbelege und Schlussfolgerungen sehr sicher miteinander.`});
export const visibleCompetencies:readonly VisibleCompetencyDefinition[]=[
 {id:"situation",label:"Situationen erschließen",sources:["text_structure","stage_direction","speaker_assignment","scene_orientation","situation_analysis","context_analysis","knowledge_state_analysis"],feedback:feedback("Situationen und Textsignale")},
 {id:"characters",label:"Figuren und Beziehungen untersuchen",sources:["character_relationships","direct_characterization","indirect_characterization","motivation","character_development"],feedback:feedback("Figuren, Ziele und Beziehungen")},
 {id:"dialogue",label:"Dialog und Sprache analysieren",sources:["dialogue_analysis","conversation_goals","speech_acts","conversation_development","language_analysis","nonverbal_analysis"],feedback:feedback("Gesprächsverläufe und Sprache")},
 {id:"conflict",label:"Konflikt und Handlung verstehen",sources:["conflict_analysis","cause_effect","causal_reasoning","internal_conflict","turning_point","action_analysis"],feedback:feedback("Konflikte, Ursachen und Wendepunkte")},
 {id:"evidence",label:"Textbelege funktional nutzen",sources:["evidence_reasoning","claim_validation","unsupported_claim_detection","relevance_selection","relevance_reasoning"],feedback:feedback("Textbelege")},
 {id:"interpretation",label:"Deutungshypothesen prüfen",sources:["interpretation","hypothesis_testing","interpretation_reasoning","hypothesis_building","counterevidence","critical_revision"],feedback:feedback("Deutungshypothesen und Gegenbelege")},
 {id:"argumentation",label:"Interpretationsargumente aufbauen",sources:["argument_structure","argumentation","transfer_analysis"],feedback:feedback("Analyse, Begründung und Deutung")},
] as const;
function levelFor(value:number):CompetencyLevel{return value>=5?"advanced":value>=3.5?"secure":value>=2?"progressing":"developing"}
function normalizedMicroScore(value:number){return Math.min(5,Math.max(0,value))}
export function aggregateVisibleCompetencies(state:Pick<GameState,"competencies"|"decisions">){return Object.fromEntries(visibleCompetencies.map(def=>{const values=def.sources.map(id=>state.competencies[id]?.value).filter((value):value is number=>typeof value==="number").map(normalizedMicroScore);const observed=values.length>0;const score=observed?values.reduce((a,b)=>a+b,0)/values.length:0;const level=levelFor(score);return[def.id,{label:def.label,level,feedback:observed?def.feedback[level]:"In diesem Bereich liegen noch nicht ausreichend Beobachtungen vor.",score,observed}]}));}
export function findDistinctStrength(results:ReturnType<typeof aggregateVisibleCompetencies>){const entries=Object.entries(results).sort((a,b)=>b[1].score-a[1].score);return entries.length>1&&entries[0][1].score>entries[1][1].score+.5?entries[0][0]:null}
export function findDevelopmentArea(results:ReturnType<typeof aggregateVisibleCompetencies>){const entries=Object.entries(results).filter(([,value])=>value.observed).sort((a,b)=>a[1].score-b[1].score);return entries.length&&entries[0][1].level!=="advanced"?entries[0][0]:null}
