import { expect, test, type Page } from "@playwright/test";
import { finalCases } from "../../src/games/epik/data/final_case";

const item = finalCases[0];
const labels: Record<string, string> = { narrator:"Erzählinstanz", perspective:"Perspektive", perception:"Wahrnehmung / Nähe", thought:"Gedanken", speech:"Rede", reliability:"Zuverlässigkeit", time:"Zeit", character:"Figur", space:"Raum", conflict:"Handlung / Konflikt" };
async function openFinal(page: Page) { await page.goto("/epik?__epik_test=1"); await page.getByRole("button", { name:"Prüfmodus · Bereich wechseln" }).click(); await page.getByRole("button", { name:"Abschlussfall", exact:true }).click(); await expect(page.getByRole("heading", { name:"Der unbekannte Fall" })).toBeVisible(); }
async function orient(page: Page) { for (const answer of [item.situation,item.figures,item.change,item.openInformation]) await page.getByRole("button", { name:answer, exact:true }).click(); await page.getByRole("button", { name:"Orientierung prüfen" }).click(); await expect(page.locator(".epik-feedback")).toContainText("nicht vorweggenommen"); await page.getByRole("button", { name:"Spuren sichten" }).click(); }
async function findings(page: Page) { for (const finding of item.findings) { const field=page.locator("fieldset").filter({has:page.locator("legend",{hasText:finding.text})}); const label=finding.relevance==="central"?"Auffällige Spur":finding.relevance==="supporting"?"Nebenbeobachtung":"Nicht sicher belegt"; await field.getByRole("button",{name:label,exact:true}).click(); } await page.getByRole("button",{name:"Spuren auswerten"}).click(); await page.getByRole("button",{name:"Relevanz entscheiden"}).click(); }
async function relevance(page: Page) { let usedAlternative=false; for (const target of item.areaWeights) { const field=page.locator("fieldset").filter({has:page.locator("legend",{hasText:labels[target.area]})}); const chosen=!usedAlternative&&target.weight==="central"?"supporting":target.weight; if(chosen!==target.weight) usedAlternative=true; await field.getByRole("button",{name:chosen==="central"?"Zentral":chosen==="supporting"?"Ergänzend":"Kaum relevant",exact:true}).click(); } await expect(page.getByRole("button",{name:"Relevanz auswerten"})).toBeEnabled(); await page.getByRole("button",{name:"Relevanz auswerten"}).click(); await expect(page.locator(".epik-relevance-row small")).toHaveCount(item.areaWeights.length); await expect(page.locator(".epik-relevance-row small").filter({hasText:"Vertretbar"})).toHaveCount(1); await expect(page.locator(".epik-feedback")).toContainText("besonders ergiebig"); await expect(page.getByRole("button",{name:"Mit dieser Gewichtung Belege sichern"})).toBeEnabled(); await page.getByRole("button",{name:"Mit dieser Gewichtung Belege sichern"}).click(); }
async function evidence(page: Page) { for(const task of item.evidenceTasks) await page.getByRole("button",{name:task.answer,exact:true}).click(); await page.getByRole("button",{name:"Belegqualität prüfen"}).click(); await expect(page.getByText(/Direkt tragfähig/)).toHaveCount(item.evidenceTasks.length); await page.getByRole("button",{name:"Zusammenhänge herstellen"}).click(); }
async function connections(page: Page) { for(const [index,chain] of item.chains.entries()) { const field=page.locator("fieldset").filter({has:page.locator("legend",{hasText:`Welche Analyse erklärt Zusammenhang ${index+1}?`})}); await field.getByRole("button",{name:`${chain.analysis}: ${chain.effect}`,exact:true}).click(); } await page.getByRole("button",{name:`${item.chains[0].interpretation} ${item.chains[1].interpretation}`,exact:true}).click(); await page.getByRole("button",{name:"Verknüpfungen prüfen"}).click(); await page.getByRole("button",{name:"Deutung prüfen"}).click(); }
async function hypotheses(page: Page) { for(const hypothesis of item.hypotheses) { const field=page.locator("fieldset").filter({has:page.locator("legend",{hasText:hypothesis.text})}); await field.getByRole("button",{name:hypothesis.valid?"Textlich tragfähig":"Nicht ausreichend getragen",exact:true}).click(); } await page.getByRole("button",{name:"Deutungen auswerten"}).click(); await expect(page.locator("fieldset small")).toHaveCount(item.hypotheses.length); await page.getByRole("button",{name:"Interpretation zusammensetzen"}).click(); }
async function sortInterpretation(page: Page) { const desired=item.interpretationVariants[0]; for(let target=0;target<desired.length;target+=1){ const texts=await page.locator(".epik-sort li > span").allTextContents(); let current=texts.indexOf(desired[target]); while(current>target){ await page.locator(".epik-sort li").filter({hasText:desired[target]}).getByRole("button",{name:/nach oben/}).click(); current-=1; } } await page.getByRole("button",{name:"Reihenfolge prüfen"}).click(); await expect(page.locator(".epik-feedback")).toContainText("Sätze verbinden"); }

test("Relevanzbutton wertet alle Bereiche aus, akzeptiert Grenzfälle und führt weiter", async ({page})=>{ await openFinal(page); await orient(page); await findings(page); await relevance(page); await expect(page.getByRole("heading",{name:"Tragfähige Textbelege sichern"})).toBeVisible(); });

test("ein Fall führt vollständig bis zur eigenen Interpretation und Musteranalyse", async ({page})=>{ await page.setViewportSize({width:390,height:844}); await openFinal(page); await orient(page); await findings(page); await relevance(page); await evidence(page); await connections(page); await hypotheses(page); await sortInterpretation(page); await expect(page.getByText("Eine mögliche textnahe Interpretation")).toHaveCount(0); const own="Die Passage zeigt Ilyas vor einer offenen Verantwortungsentscheidung. Der Rückblick auf Helenas Beitrag relativiert die Titelfolie. Die Formulierung „Vor elf Monaten“ belegt diese Analepse. Zusammen mit dem Zögern am Vorhang kann sie den Konflikt zwischen Anerkennung und Verantwortung hervorheben. Ob Ilyas den Namen ändert, bleibt offen."; await page.getByRole("textbox").fill(own); for(const box of await page.getByRole("checkbox").all()) await box.check(); await page.getByRole("button",{name:"Eine mögliche Interpretation anzeigen"}).click(); await expect(page.getByRole("textbox")).toHaveValue(own); await expect(page.getByText("Eine mögliche textnahe Interpretation")).toBeVisible(); await expect(page.getByText(/Andere Deutungen können ebenfalls überzeugen/)).toBeVisible(); expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true); await page.getByRole("button",{name:"Fall abschließen"}).click(); await expect(page.getByRole("heading",{name:"Das können Sie jetzt"})).toBeVisible(); });

test("Review-Modus öffnet den Abschlussfall direkt und verändert keinen Fortschritt", async ({page})=>{ await page.addInitScript(()=>localStorage.setItem("epik.learningProgress.v1",JSON.stringify({version:1,completedChapters:[]}))); await openFinal(page); await expect(page.getByText("Abschlussfall · 1 von 7")).toBeVisible(); expect(await page.evaluate(()=>localStorage.getItem("epik.learningProgress.v1"))).toContain('"completedChapters":[]'); });

for(const viewport of [{width:1440,height:900},{width:1366,height:768},{width:768,height:1024},{width:390,height:844}]) test(`Abschlussfall bleibt bei ${viewport.width}×${viewport.height} bedienbar`,async({page})=>{await page.setViewportSize(viewport);await openFinal(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);await expect(page.locator(".epik-final-file")).toBeVisible();});
