import { expect, test, type Page } from "@playwright/test";

const key = "lernwerkstatt-games:state:v1";
function state(patch: Record<string, unknown> = {}) { return { version: 1, currentGame: "dramatik", currentChapter: "finale", completedChapters: ["chapter_01", "chapter_02", "chapter_03", "chapter_04", "chapter_05"], decisions: { chapter_05: { transferRevision: "Gespeicherte Deutung" } }, competencies: { evidence_reasoning: { value: 5, level: "advanced" }, interpretation_reasoning: { value: 4, level: "secure" } }, failedAttempts: {}, stagingDecisions: {}, selectedEvidence: [], progress: { finale_ready: true }, theatreState: "AFTER_CHAPTER_5", settings: { music: false, soundEffects: false, reducedMotion: false }, lastSavedAt: new Date().toISOString(), finaleStarted: false, finaleCompleted: false, gameCompleted: false, performanceState: "NOT_STARTED", currentPerformanceMoment: 0, finalStaging: {}, finalHypothesis: null, visibleCompetencyResults: {}, finaleVisitedAreas: [], finaleSynthesisCompleted: false, finaleBookOpened: false, finaleClosingSeen: false, ...patch }; }
async function seed(page: Page, value = state()) { await page.goto("/dramatik"); await page.evaluate(({ key, value }) => localStorage.setItem(key, JSON.stringify(value)), { key, value }); await page.reload(); await page.getByRole("button", { name: "Fortsetzen" }).click(); }
async function openAreas(page: Page) { await page.getByRole("button", { name: "Restauriertes Theater betreten" }).click(); for (const name of ["Regiebuch", "Ensemble", "Probenbühne", "Handlungsbuch", "Analysepult"]) { await page.getByRole("button", { name: new RegExp(`^${name}`) }).click(); await page.getByRole("button", { name: "Erinnerung schließen" }).click(); } }
async function solve(page: Page) { for (const [a, b] of [["Situation", "Figur und Ziel"], ["Figur und Ziel", "Konflikt und Handlung"], ["Sprache und Dialog", "Konflikt und Handlung"], ["Sprache und Dialog", "Deutung"], ["Konflikt und Handlung", "Deutung"]]) { await page.getByRole("button", { name: new RegExp(`^${a}`) }).click(); await page.getByRole("button", { name: new RegExp(`^${b}`) }).click(); } }

test("finale synthesizes five areas, permits correction and reaches the restored theatre", async ({ page }) => { await seed(page); await expect(page.getByRole("heading", { name: "Die letzte Probe" })).toBeVisible(); await expect(page.locator(".finale-new > .asset-backdrop")).toHaveAttribute("src", /Finale helle/); await openAreas(page); await expect(page.getByText("Drameninterpretation", { exact: true })).toBeVisible(); await page.getByRole("button", { name: "Eine letzte Verbindung herstellen" }).click(); await page.getByRole("button", { name: /^Situation/ }).click(); await page.getByRole("button", { name: /^Sprache und Dialog/ }).click(); await expect(page.getByRole("status")).toContainText("direkter analytischer Zusammenhang"); await solve(page); await page.getByRole("button", { name: "Mein Regiebuch öffnen" }).click(); await expect(page.getByRole("heading", { name: "Persönliche Lernübersicht" })).toBeVisible(); await expect(page.locator(".analysis-book")).not.toContainText("Bühnendistanz"); await expect(page.locator(".analysis-book")).not.toContainText("Sprechhaltung"); await page.getByRole("button", { name: "Regiebuch schließen" }).click(); await page.getByRole("button", { name: "Vorhang auf" }).click(); await expect(page.getByRole("heading", { name: "Das Theater ist restauriert." })).toBeVisible(); const saved = await page.evaluate((key) => JSON.parse(localStorage.getItem(key)!), key); expect(saved).toMatchObject({ finaleCompleted: true, gameCompleted: true, finaleClosingSeen: true }); });
test("new finale ignores legacy staging saves and reloads meaningful progress", async ({ page }) => { await seed(page, state({ stagingDecisions: { chapter_04: { legacy: "value" }, chapter_05_revision: { old: true } }, finaleStarted: true, finaleVisitedAreas: ["situation", "figures"] })); await expect(page.getByRole("button", { name: /^Regiebuch/ })).toHaveAttribute("aria-pressed", "true"); await page.reload(); await page.getByRole("button", { name: "Fortsetzen" }).click(); await expect(page.getByRole("button", { name: /^Ensemble/ })).toHaveAttribute("aria-pressed", "true"); await expect(page.locator("body")).not.toContainText("legacy"); });

for (const viewport of [{ width: 1920, height: 1080 }, { width: 1366, height: 768 }, { width: 1024, height: 768 }, { width: 768, height: 1024 }, { width: 390, height: 844 }]) test(`finale synthesis remains operable at ${viewport.width}x${viewport.height}`, async ({ page }) => { await page.setViewportSize(viewport); await seed(page, state({ finaleStarted: true, finaleVisitedAreas: ["situation", "figures", "dialogue", "conflict", "interpretation"] })); await expect(page.getByText("Drameninterpretation", { exact: true })).toBeVisible(); await page.getByRole("button", { name: "Eine letzte Verbindung herstellen" }).click(); await expect(page.getByRole("heading", { name: "Analyseergebnisse verbinden" })).toBeVisible(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true); await expect(page.getByRole("button", { name: /^Situation/ })).toBeInViewport(); });
test("book is keyboard-readable, print-safe and reports unobserved areas", async ({ page }) => { await seed(page, state({ finaleStarted: true, finaleVisitedAreas: ["situation", "figures", "dialogue", "conflict", "interpretation"], finaleSynthesisCompleted: true, finaleBookOpened: true, competencies: {} })); await expect(page.getByRole("heading", { name: "Werkzeuge für Analyse und Interpretation dramatischer Texte" })).toBeVisible(); await expect(page.getByText("Noch nicht ausreichend beobachtet").first()).toBeVisible(); await expect(page.locator("body")).not.toContainText("%"); await expect(page.getByRole("heading", { name: "Zentrale Lernformeln" })).toBeVisible(); await expect(page.getByRole("heading", { name: "So bauen Sie eine Drameninterpretation auf" })).toBeVisible(); await expect(page.getByRole("heading", { name: "Vor dem Abgeben" })).toBeVisible(); await page.emulateMedia({ media: "print" }); await expect(page.getByRole("navigation", { name: "Regiebuch-Aktionen" })).toBeHidden(); await expect(page.locator(".analysis-book")).not.toContainText("Bühnenposition"); });
test("completed finale replay does not change competence data", async ({ page }) => { await seed(page, state({ finaleCompleted: true, gameCompleted: true, finaleClosingSeen: true, performanceState: "PERFORMANCE_COMPLETE" })); const before = await page.evaluate((key) => JSON.parse(localStorage.getItem(key)!).competencies, key); await page.getByRole("button", { name: "Noch einmal spielen" }).click(); await page.getByRole("button", { name: "Restauriertes Theater betreten" }).click(); const after = await page.evaluate((key) => JSON.parse(localStorage.getItem(key)!).competencies, key); expect(after).toEqual(before); });
test("book and print expose the correct Wieland citation without internal paths",async({page})=>{await seed(page,state({finaleStarted:true,finaleVisitedAreas:["situation","figures","dialogue","conflict","interpretation"],finaleSynthesisCompleted:true,finaleBookOpened:true}));const citation=page.getByLabel("Quelleninformation");await expect(citation).toContainText("William Shakespeare");await expect(citation).toContainText("Romeo und Juliette");await expect(citation).toContainText("Christoph Martin Wieland");await expect(page.locator("body")).not.toContainText(/Schlegel|Wikisource|OEBPS\/chapter-/);await page.emulateMedia({media:"print"});await expect(citation).toBeVisible()});
