import { describe, expect, it } from "vitest";
import { chapter02Characters } from "../src/games/dramatik/data/chapter_02/characters";
import { characterizationFindings, characterizationTasks } from "../src/games/dramatik/data/chapter_02/characterization";
import { conflictChain } from "../src/games/dramatik/data/chapter_02/conflicts";
import { developmentCards } from "../src/games/dramatik/data/chapter_02/development";
import { knowledgeStates } from "../src/games/dramatik/data/chapter_02/knowledge_states";
import { relationships } from "../src/games/dramatik/data/chapter_02/relationships";
import { classifyFinding, connectCharacters, createChapter02Session, justifyRelationship, placeConflictStage, placeDevelopment, placeKnowledge, selectReasoningStep, type Chapter02Session } from "../src/games/dramatik/mechanics/chapter_02_engine";
import { isChapterUnlocked } from "../src/core/progress/progress";
import { loadGameState, saveGameState, STORAGE_KEY } from "../src/core/state/store";
import { initialGameState } from "../src/core/state/types";

describe("chapter 2 ensemble data and mechanics", () => {
  it("registers exactly the nine approved figures", () => expect(chapter02Characters.map(({ id }) => id)).toEqual(["romeo", "julia", "tybalt", "mercutio", "benvolio", "lorenzo", "amme", "capulet", "paris"]));
  it("loads all eight relationships from didactic data", () => { expect(relationships).toHaveLength(8); expect(relationships.every((item) => item.text_origin === "didactic_summary")).toBe(true); });
  it("allows a wrong connection to be corrected", () => { const start = createChapter02Session(() => 0); const wrong = connectCharacters(start, "romeo", "tybalt"); expect(wrong.valid).toBe(false); const right = connectCharacters(wrong.session, "romeo", "julia"); expect(right.valid).toBe(true); });
  it("rejects an unsuitable relationship basis and accepts the matching observation", () => { const connected = connectCharacters(createChapter02Session(() => 0), "romeo", "julia").session; const relation=relationships[0]; const wrong=justifyRelationship(connected,relation.evidenceOptions.find((item)=>!item.correct)!.id); expect(wrong.valid).toBe(false); expect(wrong.session.completedRelationships).toEqual([]); expect(wrong.session.pendingRelationship).toBe(relation.id); const justified=justifyRelationship(wrong.session,relation.evidenceOptions.find((item)=>item.correct)!.id); expect(justified.valid).toBe(true); expect(justified.session.completedRelationships).toEqual([relation.id]); });
  it("requires observation and evidence before an implicit interpretation", () => { const start = { ...createChapter02Session(() => 0), round: 2 as const }; const early = selectReasoningStep(start, "interpretation", characterizationTasks[0].id); expect(early.valid).toBe(false); const observation = selectReasoningStep(early.session, "observation", characterizationTasks[0].id); const evidence = selectReasoningStep(observation.session, "evidence", characterizationTasks[0].id); expect(evidence.valid).toBe(true); expect(evidence.session.reasoningStep).toBe(2); });
  it("keeps direct and indirect characterization separate", () => { const start = { ...createChapter02Session(() => 0), round: 3 as const }; const direct = characterizationFindings.find((item) => item.target === "direct")!; const indirect = characterizationFindings.find((item) => item.target === "indirect")!; expect(classifyFinding(start, direct.id, "indirect").valid).toBe(false); expect(classifyFinding(start, direct.id, "direct").valid).toBe(true); expect(classifyFinding(start, indirect.id, "indirect").valid).toBe(true); });
  it("uses approved didactic statements without editorial placeholders for conflict stages", () => expect(conflictChain.every((item) => ["didactic_summary","interpretation"].includes(item.text_origin) && item.source_verified === false && item.editorial_status === "approved_didactic" && !/placeholder|steht noch aus/i.test(item.text))).toBe(true));
  it("rejects a wrong conflict order and accepts the causal order", () => { let session:Chapter02Session={...createChapter02Session(()=>0),round:4}; const wrong=placeConflictStage(session,conflictChain[1].id); expect(wrong.valid).toBe(false); expect(wrong.session.conflictStages).toEqual([]); session=wrong.session; for(const item of conflictChain)session=placeConflictStage(session,item.id).session; expect(session.round).toBe(5); expect(session.conflictStages).toEqual(conflictChain.map((item)=>item.id)); });
  it("rejects a wrong development order and accepts the supported progression", () => { let session:Chapter02Session={...createChapter02Session(()=>0),round:6}; const wrong=placeDevelopment(session,developmentCards[1].id); expect(wrong.valid).toBe(false); expect(wrong.session.developmentStages).toEqual([]); session=wrong.session; for(const item of developmentCards)session=placeDevelopment(session,item.id).session; expect(session.round).toBe(7); expect(session.developmentStages).toEqual(developmentCards.map((item)=>item.id)); });
  it("never marks didactic interpretations as primary sources", () => expect(characterizationTasks.every((item) => item.text_origin === "interpretation" && item.source_verified === false)).toBe(true));
  it("separates Romeo's and the audience's knowledge", () => { expect(knowledgeStates.filter((item) => item.target === "romeo")).toHaveLength(2); expect(knowledgeStates.filter((item) => item.target === "audience")).toHaveLength(2); const placed = placeKnowledge({ ...createChapter02Session(() => 0), round: 5 }, knowledgeStates[0].id, knowledgeStates[0].target); expect(placed.valid).toBe(true); });
  it("unlocks chapter 3 only after chapter 2 completion", () => { expect(isChapterUnlocked("chapter_03", ["chapter_01"])).toBe(false); expect(isChapterUnlocked("chapter_03", ["chapter_01", "chapter_02"])).toBe(true); });
  it("persists a chapter-2 session across reload", () => { const memory = new Map<string,string>(); Object.defineProperty(globalThis, "localStorage", { configurable: true, value: { getItem:(key:string)=>memory.get(key)??null, setItem:(key:string,value:string)=>memory.set(key,value), removeItem:(key:string)=>memory.delete(key) } }); const relation=relationships[0]; const session = justifyRelationship(connectCharacters(createChapter02Session(() => 0), "romeo", "julia").session, relation.evidenceOptions.find((item)=>item.correct)!.id).session; saveGameState({ ...initialGameState, currentGame:"dramatik", currentChapter:"chapter_02", completedChapters:["chapter_01"], decisions:{chapter_02:session} }); expect((loadGameState().decisions.chapter_02 as typeof session).completedRelationships).toEqual(["rel_romeo_julia"]); localStorage.removeItem(STORAGE_KEY); });
});
