import { describe,expect,it } from "vitest";
import { characterizationCards, chapter02PrimarySources, comparisonCards, ensembleLinks, highlightTasks, momentClaims, practiceClaims, relationshipTasks, roleTasks, selfOtherTasks, transferTasks } from "../src/games/dramatik/data/chapter_02_content";
import { analyzeRelationship, classifyCharacterization, classifyMoment, classifyPractice, classifyRole, classifySelfOther, compareSituations, connectEnsemble, createChapter02Session, markTextSignal, solveTransfer, type Chapter02Session } from "../src/games/dramatik/mechanics/chapter_02_engine";
import { isChapterUnlocked } from "../src/core/progress/progress";
import { initialGameState } from "../src/core/state/types";
import { loadGameState,saveGameState } from "../src/core/state/store";

describe("chapter 2 · textgestützte Figurenanalyse",()=>{
 it("trennt Textbefund, plausible Erschließung und unbelegte Behauptung",()=>{let s:Chapter02Session={...createChapter02Session(),round:2};for(const item of practiceClaims)s=classifyPractice(s,item.id,item.target).session;expect(s.round).toBe(3);expect(s.practiceAssignments.leon_hate).toBe("unsupported")});
 it("weist eine unbelegte Charaktereigenschaft zurück und erlaubt Korrektur",()=>{const s={...createChapter02Session(),round:2 as const};const wrong=classifyPractice(s,"leon_hate","inference");expect(wrong.valid).toBe(false);expect(classifyPractice(wrong.session,"leon_hate","unsupported").valid).toBe(true)});
 it("erkennt direkte und indirekte Charakterisierung getrennt",()=>{let s:Chapter02Session={...createChapter02Session(),round:3};for(const item of characterizationCards)s=classifyCharacterization(s,item.id,item.target).session;expect(s.round).toBe(4);expect(Object.values(s.characterizationAssignments)).toContain("direct");expect(Object.values(s.characterizationAssignments)).toContain("indirect")});
 it("akzeptiert nur die tatsächlich vorgesehenen Textsignale",()=>{const s={...createChapter02Session(),round:4 as const};expect(markTextSignal(s,"c02_main_lady_paris").valid).toBe(false);expect(markTextSignal(s,highlightTasks[0].sourceId).valid).toBe(true)});
 it("behandelt situatives Verhalten nicht als dauerhafte Eigenschaft",()=>{const s={...createChapter02Session(),round:5 as const};const item=momentClaims.find(x=>x.id==="moment_obedient")!;expect(classifyMoment(s,item.id,"supported").valid).toBe(false);expect(classifyMoment(s,item.id,item.target).valid).toBe(true)});
 it("unterscheidet Ziel und Motiv und lässt Nicht-Feststellbarkeit zu",()=>{let s:Chapter02Session={...createChapter02Session(),round:6};for(const item of roleTasks)s=classifyRole(s,item.id,item.target).session;expect(s.roleAssignments.role_goal).toBe("goal");expect(s.roleAssignments.role_motive_unknown).toBe("unknown")});
 it("verlangt für Beziehungen einen passenden Textbezug und bildet Richtungen ab",()=>{const s={...createChapter02Session(),round:7 as const};const first=relationshipTasks[0];expect(analyzeRelationship(s,first.id,relationshipTasks[1].sourceId).valid).toBe(false);const correct=analyzeRelationship(s,first.id,first.sourceId);expect(correct.valid).toBe(true);expect(relationshipTasks[0].from).not.toBe(relationshipTasks[1].from)});
 it("verarbeitet Selbstbild und Fremdbild separat",()=>{let s:Chapter02Session={...createChapter02Session(),round:8};for(const item of selfOtherTasks)s=classifySelfOther(s,item.id,item.target).session;expect(s.selfOtherAssignments.self_juliette).toBe("self");expect(s.selfOtherAssignments.other_lady).toBe("other")});
 it("fordert im Transfer den konkreten Primärtextbeleg",()=>{const s={...createChapter02Session(),round:9 as const};const task=transferTasks[0];expect(solveTransfer(s,task.id,transferTasks[1].sourceId).valid).toBe(false);expect(solveTransfer(s,task.id,task.sourceId).valid).toBe(true)});
 it("weist die pauschale gehorsam-rebellisch-Schablone zurück",()=>{const s={...createChapter02Session(),round:10 as const};const conclusion=comparisonCards.find(x=>x.target==="conclusion")!;expect(compareSituations(s,conclusion.id,"late").valid).toBe(false);expect(compareSituations(s,conclusion.id,"conclusion").valid).toBe(true)});
 it("rekonstruiert die Ensemblewand interaktiv und textgestützt",()=>{let s:Chapter02Session={...createChapter02Session(),round:11};for(const link of ensembleLinks)s=connectEnsemble(s,link.from,link.to,link.sourceId).session;expect(s.completed).toBe(true);expect(s.ensembleConnections).toEqual(ensembleLinks.map(x=>x.id))});
 it("lädt ausschließlich den geschützten Wieland-Datensatz",()=>{expect(chapter02PrimarySources).toHaveLength(15);expect(chapter02PrimarySources.every(x=>x.translation==="Christoph Martin Wieland"&&x.source==="docs/sources/william-shakespeare-romeo-und-juliette.epub"&&x.text_origin==="primary_source"&&x.editable===false&&x.source_verified===true)).toBe(true)});
 it("persistiert einen sinnvollen Zwischenstand",()=>{const memory=new Map<string,string>();const storage={getItem:(k:string)=>memory.get(k)??null,setItem:(k:string,v:string)=>memory.set(k,v)};const session=classifyPractice({...createChapter02Session(),round:2},practiceClaims[0].id,practiceClaims[0].target).session;saveGameState({...initialGameState,currentGame:"dramatik",currentChapter:"chapter_02",completedChapters:["chapter_01"],decisions:{chapter_02:session}},storage);expect((loadGameState(storage).decisions.chapter_02 as Chapter02Session).practiceAssignments).toEqual(session.practiceAssignments)});
 it("schaltet Kapitel 3 weiterhin nur nach Kapitel 2 frei",()=>{expect(isChapterUnlocked("chapter_03",["chapter_01"])).toBe(false);expect(isChapterUnlocked("chapter_03",["chapter_01","chapter_02"])).toBe(true)});
});
