import {describe,expect,it} from "vitest";
import {isChapterUnlocked} from "../src/core/progress/progress";
import {initialGameState} from "../src/core/state/types";
import {loadGameState,saveGameState} from "../src/core/state/store";
import {chapter03PrimarySources,comparisonTasks,findingTasks,goalChange,goalTasks,languageTasks,practiceActs,speechTasks,transferTasks} from "../src/games/dramatik/data/chapter_03_content";
import {analyzeGoalChange,assignPracticeAct,assignPracticeGoal,chooseTurningPoint,classifyFinding,connectSpeechChain,createChapter03Session,linkGoalEvidence,setPhaseOrder,solveFinal,solveLanguage,solveTransfer} from "../src/games/dramatik/mechanics/chapter_03_engine";

describe("chapter 3 dialogue rehearsal",()=>{
 it("separates speech act from conversation goal",()=>{const s=createChapter03Session();const act=assignPracticeAct({...s,round:2},practiceActs[0].id,practiceActs[0].act);expect(act.valid).toBe(true);expect(act.session.practiceGoals).toEqual({});expect(assignPracticeGoal(act.session,practiceActs[0].id,practiceActs[0].goal).valid).toBe(true)});
 it("does not complete goal analysis with an act alone",()=>{const r=assignPracticeAct({...createChapter03Session(),round:2},practiceActs[0].id,practiceActs[0].act);expect(r.session.round).toBe(2)});
 it("requires matching evidence for section-specific goals",()=>{const s={...createChapter03Session(),round:4 as const};expect(linkGoalEvidence(s,goalTasks[0].id,goalTasks[1].sourceId).valid).toBe(false);const ok=linkGoalEvidence(s,goalTasks[0].id,goalTasks[0].sourceId);expect(ok.valid).toBe(true);expect(ok.session.goalEvidence[goalTasks[0].id]).toBe(goalTasks[0].sourceId)});
 it("allows a conversation goal to change with two references",()=>{const s={...createChapter03Session(),round:5 as const};expect(analyzeGoalChange(s,goalChange.answer,goalChange.first,goalChange.second).valid).toBe(true);expect(analyzeGoalChange(s,"bleibt_gleich",goalChange.first,goalChange.second).valid).toBe(false)});
 it("connects speech acts to reactions",()=>{const t=speechTasks[0],s={...createChapter03Session(),round:6 as const};expect(connectSpeechChain(s,t.id,t.act,t.reactionId).valid).toBe(true);expect(connectSpeechChain(s,t.id,t.act,t.sourceId).valid).toBe(false)});
 it("reconstructs conversation phases",()=>{const s={...createChapter03Session(),round:7 as const};expect(setPhaseOrder(s,["main_a","main_b","main_c","main_d"]).valid).toBe(true);expect(setPhaseOrder(s,["main_b","main_a","main_c","main_d"]).valid).toBe(false)});
 it("requires an evidenced turning point",()=>{const s={...createChapter03Session(),round:8 as const};expect(chooseTurningPoint(s,"turn_fight","c03_main_fight").valid).toBe(true);expect(chooseTurningPoint(s,"turn_fight","c03_main_tybalt_draws").valid).toBe(false)});
 it("processes fixed stage directions without treating staging as text",()=>{const s={...createChapter03Session(),round:10 as const};const text=findingTasks.find(x=>x.target==="text")!,staging=findingTasks.find(x=>x.target==="staging")!;expect(classifyFinding(s,text.id,"text").valid).toBe(true);expect(classifyFinding(s,staging.id,"text").valid).toBe(false);expect(classifyFinding(s,staging.id,"staging").valid).toBe(true)});
 it("requires feature, contextual effect, and function",()=>{const t=languageTasks[0],s={...createChapter03Session(),round:9 as const};expect(solveLanguage(s,t.id,t.feature,t.effect).valid).toBe(true);expect(solveLanguage(s,t.id,t.feature,"Fragen zeigen immer Unsicherheit.").valid).toBe(false)});
 it("accepts not safely determinable as a category without a mechanical style rule",()=>{expect(practiceActs.some(x=>x.goal.length>0)).toBe(true);expect(languageTasks.some(x=>/immer/.test(x.effect))).toBe(false)});
 it("requires evidence in the contrasting transfer",()=>{const t=transferTasks[0],s={...createChapter03Session(),round:11 as const};expect(solveTransfer(s,t.id,t.sourceId).valid).toBe(true);expect(solveTransfer(s,t.id,transferTasks[1].sourceId).valid).toBe(false);expect(comparisonTasks.map(x=>x.target)).toContain("transfer")});
 it("keeps mistakes correctable",()=>{const s={...createChapter03Session(),round:4 as const};const bad=linkGoalEvidence(s,goalTasks[0].id,goalTasks[1].sourceId);expect(linkGoalEvidence(bad.session,goalTasks[0].id,goalTasks[0].sourceId).valid).toBe(true)});
 it("completes only the full final evidence chain",()=>{const s={...createChapter03Session(),round:12 as const};expect(solveFinal(s,["c03_transfer_juliette_danger"]).valid).toBe(false);expect(solveFinal(s,["c03_transfer_juliette_danger","c03_transfer_romeo_love","c03_transfer_juliette_concern"]).session.completed).toBe(true)});
 it("contains only protected Wieland primary sources",()=>{expect(chapter03PrimarySources).toHaveLength(23);expect(chapter03PrimarySources.every(x=>x.source_verified&&x.editable===false&&x.translation==="Christoph Martin Wieland")).toBe(true);expect(new Set(chapter03PrimarySources.map(x=>x.source_location.split(",")[0]))).toEqual(new Set(["OEBPS/chapter-0014.xhtml","OEBPS/chapter-0009.xhtml"]))});
 it("persists a meaningful chapter state",()=>{const memory=new Map<string,string>();const storage={getItem:(k:string)=>memory.get(k)??null,setItem:(k:string,v:string)=>memory.set(k,v)};const session={...createChapter03Session(),round:6 as const,speechChains:["act_mercutio"]};saveGameState({...initialGameState,currentGame:"dramatik",currentChapter:"chapter_03",completedChapters:["chapter_01","chapter_02"],decisions:{chapter_03:session}},storage);expect((loadGameState(storage).decisions.chapter_03 as typeof session).speechChains).toEqual(["act_mercutio"])});
 it("keeps progression linear",()=>{expect(isChapterUnlocked("chapter_03",["chapter_01","chapter_02"])).toBe(true);expect(isChapterUnlocked("chapter_04",["chapter_01","chapter_02"])).toBe(false);expect(isChapterUnlocked("chapter_04",["chapter_01","chapter_02","chapter_03"])).toBe(true)});
});
