import { describe,expect,it } from "vitest";
import { isChapterUnlocked } from "../src/core/progress/progress";
import { BasicStagingEngine } from "../src/games/dramatik/mechanics/staging_engine";
import { fixedStageDirections,generalRehearsalSource } from "../src/games/dramatik/data/chapter_04/scene_source";
import { conversationGoals,escalationPoints,speechActs } from "../src/games/dramatik/data/chapter_04/analysis";
import { directorError,rehearsalMoments,stagingOptions } from "../src/games/dramatik/data/chapter_04/staging_options";
import { advanceRehearsal,completeChapter04,correctOneDecision,initialChapter04Session,playCorrectedRehearsal,playRehearsal,resolveDirectorError,saveStaging,type Chapter04Session } from "../src/games/dramatik/mechanics/chapter_04_engine";
import type { FixedStageDirection,StagingDecision } from "../src/games/dramatik/data/staging";
import { initialGameState } from "../src/core/state/types";
import { loadGameState,saveGameState } from "../src/core/state/store";

const choose=(session:Chapter04Session,id:string,value:string,reasoning:string)=>saveStaging(session,id,value,reasoning);
const completeChoices=()=>{let session:Chapter04Session={...initialChapter04Session,round:7};for(const option of stagingOptions){const combination=option.combinations.find(item=>item.quality!=="problematic")!;session=choose(session,option.id,combination.value,combination.reasoningId).session}return session};

describe("chapter 4 general rehearsal",()=>{
 it("unlocks chapter 4 only after chapter 3",()=>{expect(isChapterUnlocked("chapter_04",["chapter_01","chapter_02"])).toBe(false);expect(isChapterUnlocked("chapter_04",["chapter_01","chapter_02","chapter_03"])).toBe(true)});
 it("loads fixed stage directions as immutable primary source",()=>{expect(fixedStageDirections.map(x=>x.text)).toEqual(["(Tritt hervor.)","(Sie fechten.)"]);expect(fixedStageDirections.every(x=>x.editable===false&&x.source_verified===true)).toBe(true)});
 it("loads Paris and Romeo goals from didactic data",()=>{expect(conversationGoals.find(x=>x.character_id==="paris")?.goal).toBe("Romeo aufhalten und festnehmen.");expect(conversationGoals.find(x=>x.character_id==="romeo")?.goal).toContain("Konflikt zu vermeiden")});
 it("references protected evidence instead of duplicating excerpts",()=>{expect(conversationGoals.flatMap(x=>x.evidence).every(id=>generalRehearsalSource.some(source=>source.id===id))).toBe(true);expect(speechActs.every(item=>generalRehearsalSource.some(source=>source.id===item.source_reference))).toBe(true)});
 it("links the selected speech acts",()=>expect(speechActs.map(x=>x.target)).toEqual(["festnehmen / auffordern","warnen","zurückweisen"]));
 it("offers several plausible escalation points",()=>expect(escalationPoints.length).toBeGreaterThanOrEqual(3));
 it("never mutates primary text while evaluating staging",()=>{const fixed:FixedStageDirection[]=[{id:"fight",exactText:"(Sie fechten.)",fixed:true,kind:"fixed_stage_direction",sourceReference:"source"}];const engine=new BasicStagingEngine(fixed);const before=JSON.stringify(generalRehearsalSource);const decision:StagingDecision={id:"d",dimension:"distance",characterId:"both",value:"weit",evidenceIds:["source"],reasoningId:"reason",kind:"optional_staging_choice"};expect(engine.evaluate(decision).valid).toBe(true);expect(JSON.stringify(generalRehearsalSource)).toBe(before);expect(engine.getFixedDirections()[0].exactText).toBe("(Sie fechten.)")});
 it("stores exactly the actively selected value",()=>{const result=choose({...initialChapter04Session,round:7},"figure_distance","mittlere Distanz","distance_pressure");expect(result.valid).toBe(true);expect(result.session.stagingDecisions.figure_distance.value).toBe("mittlere Distanz");expect(result.session.stagingDecisions.figure_distance.reasoningId).toBe("distance_pressure")});
 it("offers at least two distinct values for every staging dimension",()=>expect(stagingOptions.every(option=>new Set(option.allowed_values).size>=2)).toBe(true));
 it("rejects a reasoning that does not belong to the selected value",()=>{const result=choose({...initialChapter04Session,round:7},"figure_distance","große Distanz","distance_attack");expect(result.valid).toBe(false);expect(result.session.stagingDecisions.figure_distance).toBeUndefined()});
 it("accepts more than one textually defensible interpretation",()=>{const start={...initialChapter04Session,round:7 as const};expect(choose(start,"figure_distance","große Distanz","distance_avoidance").valid).toBe(true);expect(choose(start,"figure_distance","mittlere Distanz","distance_pressure").valid).toBe(true)});
 it("moves through four rehearsal moments before the counterprobe",()=>{let session=playRehearsal(completeChoices());for(let index=0;index<rehearsalMoments.length;index+=1)session=advanceRehearsal(session);expect(session.round).toBe(10);expect(session.counterprobeActive).toBe(true)});
 it("requires counter-evidence before a revision",()=>{const session={...completeChoices(),round:10 as const,counterprobeActive:true};const rejected=correctOneDecision(session,"figure_distance","mittlere Distanz","distance_pressure");expect(rejected.valid).toBe(false);expect(rejected.session.correctionUsed).toBe(false);expect(resolveDirectorError(session,"Romeo greift sofort an.").valid).toBe(false);expect(resolveDirectorError(session,directorError.counterEvidence).valid).toBe(true)});
 it("counts a revision only when the value actually changes",()=>{const ready=resolveDirectorError({...completeChoices(),round:10 as const,counterprobeActive:true},directorError.counterEvidence).session;const current=ready.stagingDecisions.figure_distance;const same=correctOneDecision(ready,"figure_distance",current.value,current.reasoningId);expect(same.valid).toBe(false);expect(same.session.correctionUsed).toBe(false);const changed=correctOneDecision(ready,"figure_distance","mittlere Distanz","distance_pressure");expect(changed.valid).toBe(true);expect(changed.session.correctionUsed).toBe(true);expect(changed.session.stagingDecisions.figure_distance.value).toBe("mittlere Distanz")});
 it("cannot complete before the corrected rehearsal is viewed",()=>{const ready=resolveDirectorError({...completeChoices(),round:10 as const,counterprobeActive:true},directorError.counterEvidence).session;const changed=correctOneDecision(ready,"figure_distance","mittlere Distanz","distance_pressure").session;expect(completeChapter04(changed).valid).toBe(false);expect(completeChapter04(playCorrectedRehearsal(changed)).valid).toBe(true)});
 it("unlocks chapter 5 only after chapter 4",()=>{expect(isChapterUnlocked("chapter_05",["chapter_01","chapter_02","chapter_03"])).toBe(false);expect(isChapterUnlocked("chapter_05",["chapter_01","chapter_02","chapter_03","chapter_04"])).toBe(true)});
 it("persists the selected staging value and reasoning",()=>{const memory=new Map<string,string>();const storage={getItem:(k:string)=>memory.get(k)??null,setItem:(k:string,v:string)=>memory.set(k,v)};const session=choose({...initialChapter04Session,round:7},"figure_distance","mittlere Distanz","distance_pressure").session;saveGameState({...initialGameState,currentGame:"dramatik",currentChapter:"chapter_04",decisions:{chapter_04:session}},storage);const restored=loadGameState(storage).decisions.chapter_04 as typeof session;expect(restored.stagingDecisions.figure_distance).toMatchObject({value:"mittlere Distanz",reasoningId:"distance_pressure"})});
});
