import {describe,expect,it} from "vitest";
import {isChapterUnlocked} from "../src/core/progress/progress";
import {loadGameState,saveGameState} from "../src/core/state/store";
import {initialGameState} from "../src/core/state/types";
import {argumentBlocks, chapter05TransferSources, classificationCards, generalChain, julietFindings, julietHypothesis, julietReverseChain, transferArgument, transferChain, transferEvidence, transferHypotheses, transferRefined} from "../src/games/dramatik/data/chapter_05_content";
import {assignJulietRelevance, chooseTransferHypothesis, classifyStatement, completeChapter05, countercheckJuliet, countercheckTransfer, initialChapter05Session, placeGeneralChain, placeJulietArgument, placeJulietChain, placeTransferArgument, placeTransferChain, refineJuliet, refineTransfer, selectTransferEvidence, synthesize, type Chapter05Session} from "../src/games/dramatik/mechanics/chapter_05_engine";

describe("chapter 5 interpretation workshop",()=>{
 it("unlocks only after chapter 4",()=>{expect(isChapterUnlocked("chapter_05",["chapter_01","chapter_02","chapter_03"])).toBe(false);expect(isChapterUnlocked("chapter_05",["chapter_01","chapter_02","chapter_03","chapter_04"])).toBe(true)});
 it("separates observation, analysis, interpretation and unsupported claims",()=>expect(new Set(classificationCards.map(x=>x.target))).toEqual(new Set(["observation","analysis","interpretation","unsupported"])));
 it("requires every classification",()=>{let s=initialChapter05Session;for(const card of classificationCards)s=classifyStatement(s,card.id,card.target).session;expect(s.round).toBe(2);expect(classifyStatement(initialChapter05Session,"class_interpretation","observation").valid).toBe(false)});
 it("builds evidence, observation, analysis and meaning in order",()=>{let s={...initialChapter05Session,round:2};expect(placeGeneralChain(s,generalChain[1].id).valid).toBe(false);for(const item of generalChain)s=placeGeneralChain(s,item.id).session;expect(s.round).toBe(3)});
 it("loads the late Juliet evidence from chapter 2 without duplicating it",()=>expect(chapter05TransferSources.some(x=>x.id.startsWith("c02_"))).toBe(false));
 it("allows relative relevance where explicitly modelled",()=>{const flexible=julietFindings.find(x=>x.accepted.length>1)!;expect(assignJulietRelevance({...initialChapter05Session,round:5},flexible.id,flexible.accepted[1]!).valid).toBe(true)});
 it("rejects a wrong relevance without calling the fact false",()=>expect(assignJulietRelevance({...initialChapter05Session,round:5},"marriage_early","direct").valid).toBe(false));
 it("supports reverse evidence reasoning",()=>{let s={...initialChapter05Session,round:6};for(const item of [...julietReverseChain].reverse())s=placeJulietChain(s,item.id).session;expect(s.round).toBe(7)});
 it("uses counterevidence to challenge an absolute Juliet hypothesis",()=>{const s={...initialChapter05Session,round:7};expect(countercheckJuliet(s,"juliet_no_voice").valid).toBe(false);expect(countercheckJuliet(s,"juliet_has_agency").valid).toBe(true)});
 it("counts only a real hypothesis revision",()=>{const s={...initialChapter05Session,round:8};expect(refineJuliet(s,s.julietHypothesis).valid).toBe(false);const result=refineJuliet(s,julietHypothesis);expect(result.valid).toBe(true);expect(result.session.julietRevision).toBe(julietHypothesis)});
 it("requires claim, evidence, analysis and interpretation",()=>{let s={...initialChapter05Session,round:9};expect(placeJulietArgument(s,argumentBlocks[1].id).valid).toBe(false);for(const item of argumentBlocks)s=placeJulietArgument(s,item.id).session;expect(s.round).toBe(10)});
 it("uses exactly eight protected transfer fragments from the requested EPUB location",()=>{expect(chapter05TransferSources).toHaveLength(8);expect(chapter05TransferSources.every(x=>x.source==="docs/sources/william-shakespeare-romeo-und-juliette.epub"&&x.source_location.includes("OEBPS/chapter-0027.xhtml")&&x.translation==="Christoph Martin Wieland"&&x.source_verified&&x.editable===false)).toBe(true)});
 it("distinguishes relevant evidence from correct but low-relevance context",()=>{expect(selectTransferEvidence({...initialChapter05Session,round:12},"te_letter").valid).toBe(false);expect(selectTransferEvidence({...initialChapter05Session,round:12},"te_argument").valid).toBe(true)});
 it("builds the transfer meaning chain",()=>{let s={...initialChapter05Session,round:13};for(const item of transferChain)s=placeTransferChain(s,item.id).session;expect(s.round).toBe(14)});
 it("weights transfer hypotheses",()=>{const s={...initialChapter05Session,round:14};expect(chooseTransferHypothesis(s,transferHypotheses.find(x=>x.quality==="description")!.id).valid).toBe(false);expect(chooseTransferHypothesis(s,transferHypotheses.find(x=>x.quality==="supported")!.id).valid).toBe(true)});
 it("requires counterevidence before an actual transfer refinement",()=>{const s={...initialChapter05Session,round:15,transferHypothesis:transferHypotheses[0].text};expect(countercheckTransfer(s,"apothecary_eager").valid).toBe(false);const checked=countercheckTransfer(s,"apothecary_resists").session;expect(refineTransfer(checked,checked.transferHypothesis!).valid).toBe(false);expect(refineTransfer(checked,transferRefined).valid).toBe(true)});
 it("requires all semantic paragraph levels",()=>{let s={...initialChapter05Session,round:17};for(const item of transferArgument)s=placeTransferArgument(s,item.id).session;expect(s.round).toBe(18)});
 it("completes only after synthesis and unlocks the finale",()=>{let s:Chapter05Session={...initialChapter05Session,round:18,transferRevision:transferRefined,transferArgument:transferArgument.map(x=>x.id)};expect(completeChapter05(s).valid).toBe(false);s=synthesize(s,"synthesis_complete").session;expect(completeChapter05(s).valid).toBe(true);expect(isChapterUnlocked("finale",["chapter_01","chapter_02","chapter_03","chapter_04","chapter_05"])).toBe(true)});
 it("persists all interpretation and transfer fields",()=>{const memory=new Map<string,string>(),storage={getItem:(k:string)=>memory.get(k)??null,setItem:(k:string,v:string)=>memory.set(k,v)};const session:Chapter05Session={...initialChapter05Session,round:16,transferSelected:transferEvidence.slice(0,4).map(x=>x.id),transferCountercheck:"apothecary_resists"};saveGameState({...initialGameState,currentGame:"dramatik",currentChapter:"chapter_05",decisions:{chapter_05:session}},storage);expect(loadGameState(storage).decisions.chapter_05).toMatchObject({round:16,transferCountercheck:"apothecary_resists"})});
});
