import { describe,expect,it } from "vitest";
import { analysisErrorPractice, categoryPractice, certaintyClaims, certaintyPractice, chapter01PrimarySources, consolidationGroups, historyConditionPractice, signalChainPractice, situationEvidence, situationPracticeScenes, streetSituationCards, transferFields, transferSituationGroups } from "../src/games/dramatik/data/chapter_01_content";
import { advanceChapter01,assignTraining,checkAnalysisErrors,checkCategoryPractice,checkCertaintyPractice,checkChain,checkConsolidation,checkHistoryConditionPractice,classifyClaim,identifySignal,initialChapter01Session,linkSituationEvidence,placeSituation,selectChainPart,setTransferField,toggleTrainingSelection } from "../src/games/dramatik/mechanics/chapter_01_engine";
import type { Chapter01Session } from "../src/games/dramatik/mechanics/chapter_01_engine";
import { isChapterUnlocked } from "../src/core/progress/progress";
import { createNewGameState,loadGameState,saveGameState } from "../src/core/state/store";

function memoryStorage(){const data=new Map<string,string>();return{getItem:(key:string)=>data.get(key)??null,setItem:(key:string,value:string)=>void data.set(key,value)}}
function reachSignals(){return advanceChapter01(initialChapter01Session)}

describe("chapter 1 reconstructed director's book",()=>{
  it("identifies speaker, stage direction, and speech in sequence",()=>{let s=reachSignals();expect(identifySignal(s,"anna_speaker","speaker").valid).toBe(true);s=identifySignal(s,"anna_speaker","speaker").session;expect(identifySignal(s,"anna_direction_1","stage_direction").valid).toBe(true);s=identifySignal(s,"anna_direction_1","stage_direction").session;expect(identifySignal(s,"anna_speech_1","speech").session.round).toBe(3)});
  it("allows retry after a wrong signal",()=>{const wrong=identifySignal(reachSignals(),"anna_speech_1","speech");expect(wrong.valid).toBe(false);expect(wrong.session.signalStep).toBe(0);expect(identifySignal(wrong.session,"anna_speaker","speaker").valid).toBe(true)});
  it("distinguishes direct evidence, inference, and unsupported claims",()=>{let s:Chapter01Session={...initialChapter01Session,round:3};const fear=classifyClaim(s,"claim_fear","explicit");expect(fear.valid).toBe(false);expect(fear.session.certaintyAssignments.claim_fear).toBeUndefined();s=classifyClaim(fear.session,"claim_fear","inference").session;expect(s.certaintyAssignments.claim_fear).toBe("inference");expect(classifyClaim(s,"claim_person","unsupported").valid).toBe(true)});
  it("accepts information that is not ascertainable",()=>{const s={...initialChapter01Session,round:11 as const};expect(placeSituation(s,"street_time","unknown").valid).toBe(true);expect(placeSituation(s,"street_romeo","unknown").valid).toBe(true)});
  it("requires observation before situational inference",()=>{const s={...initialChapter01Session,round:12 as const};expect(linkSituationEvidence(s,situationEvidence.textId,"Sampson ist feige.",situationEvidence.situation).valid).toBe(false);expect(linkSituationEvidence(s,situationEvidence.textId,situationEvidence.observation,situationEvidence.situation).valid).toBe(true)});
  it("loads both excerpts only from the protected EPUB dataset",()=>{expect(chapter01PrimarySources).toHaveLength(10);expect(chapter01PrimarySources.every(item=>item.source.endsWith("william-shakespeare-romeo-und-juliette.epub")&&item.text_origin==="primary_source"&&item.editable===false&&item.source_verified)).toBe(true)});
  it("completes the transfer and unlocks chapter 2",()=>{let s:Chapter01Session={...initialChapter01Session,round:13};for(const field of transferFields)s=setTransferField(s,field.id,field.answer,field.evidenceId).session;expect(s.completed).toBe(true);expect(isChapterUnlocked("chapter_02",["chapter_01"])).toBe(true)});
  it("persists a meaningful mid-chapter state",()=>{const storage=memoryStorage();const session=classifyClaim({...initialChapter01Session,round:3 as const},certaintyClaims[0].id,certaintyClaims[0].target).session;saveGameState({...createNewGameState(),decisions:{chapter_01:session}},storage);expect((loadGameState(storage).decisions.chapter_01 as typeof session).certaintyAssignments.claim_door).toBe("explicit")});
  it("keeps all situation and transfer answers unambiguous",()=>{expect(new Set(streetSituationCards.map(item=>item.id)).size).toBe(streetSituationCards.length);expect(transferFields.filter(item=>item.answer==="Nicht eindeutig angegeben").map(item=>item.field)).toEqual(["place","time"])});
  it("trains situation analysis on independent didactic scenes before Shakespeare",()=>{expect(situationPracticeScenes).toHaveLength(6);expect(new Set(situationPracticeScenes.map(scene=>scene.lines.join("\n"))).size).toBe(6);expect(situationPracticeScenes.every(scene=>scene.lines.join(" ").includes("Romeo")===false&&scene.lines.join(" ").includes("Juliette")===false)).toBe(true)});
  it("focuses history and conditions with close, non-trivial alternatives",()=>{expect(historyConditionPractice.length).toBeGreaterThanOrEqual(8);expect(new Set(historyConditionPractice.map(item=>item.target))).toEqual(new Set(["history","current_condition","other","unknown"]));expect(historyConditionPractice.filter(item=>item.target==="history").length).toBeGreaterThanOrEqual(2);expect(historyConditionPractice.filter(item=>item.target==="current_condition").length).toBeGreaterThanOrEqual(2)});
  it("does not treat an inferred present effect as pure history",()=>{expect(historyConditionPractice.find(item=>item.text.startsWith("Die frühere Absage prägt"))?.target).toBe("other");expect(historyConditionPractice.find(item=>item.id==="hc_committee")).toMatchObject({text:"Noah und Aylin befinden sich kurz vor einem Gespräch mit einer Kommission.",target:"other"})});
  it("uses a new neutral consolidation scene with a complete delayed draft",()=>{const scene=situationPracticeScenes.find(item=>item.id==="committee_revision")!;expect(scene).toBeDefined();expect(scene.lines).toHaveLength(6);expect(scene.lines.join(" ")).not.toMatch(/SARA|LEON|Bahnsteig/);expect(scene.title).toBe("Eine Entscheidung");expect(consolidationGroups.flatMap(group=>group.options)).toHaveLength(16);expect(consolidationGroups.find(group=>group.field==="unknown")!.options.filter(item=>item.correct).length).toBeGreaterThanOrEqual(2);expect(consolidationGroups.find(group=>group.field==="history")!.options.some(item=>item.correct)).toBe(true);expect(consolidationGroups.find(group=>group.field==="conditions")!.options.some(item=>item.correct)).toBe(true)});
  it("assigns every consolidation statement to exactly one fachlich explicit category",()=>{const all=consolidationGroups.flatMap(group=>group.options.map(option=>({group:group.field,option})));expect(all).toHaveLength(16);expect(all.every(({group,option})=>option.targetField===group)).toBe(true);expect(all.every(({option})=>typeof option.targetField==="string")).toBe(true)});
  it("keeps present states out of consolidation history",()=>{const history=consolidationGroups.find(group=>group.field==="history")!.options;const conditions=consolidationGroups.find(group=>group.field==="conditions")!.options;expect(history.some(item=>item.text==="Der Antrag ist bereits unterschrieben.")).toBe(false);expect(history.find(item=>item.id==="con_history_signature")).toMatchObject({text:"Der Antrag wurde vor Beginn der Szene unterschrieben.",reasoningKind:"inference"});expect(conditions.find(item=>item.id==="con_condition_unchanged")).toMatchObject({correct:true,targetField:"conditions"});expect(conditions.find(item=>item.id==="con_condition_pressure")?.reasoningKind).toBe("inference")});
  it("keeps contextual feud facts out of the required Capulet and Paris core",()=>{const options=transferSituationGroups.flatMap(group=>group.options);expect(options.find(item=>item.id==="history_feud")).toMatchObject({correct:false,relevance:"context_only"});expect(options.find(item=>item.id==="condition_sanction")).toMatchObject({correct:false,relevance:"context_only"});expect(options.find(item=>item.id==="char_servant")?.correct).toBe(true)});
  it("covers distinct analysis error types",()=>{expect(new Set(analysisErrorPractice.map(item=>item.reason))).toEqual(new Set(["observation","inference","addition","overreach","certainty","irrelevant"]))});
  it("checks categories, certainty, history and analysis errors only as complete drafts",()=>{let s:Chapter01Session={...initialChapter01Session,round:4};for(const item of categoryPractice)s=assignTraining(s,item.id,item.target);expect(checkCategoryPractice(s).session.round).toBe(5);s={...s,round:5,trainingAssignments:{}};for(const item of certaintyPractice)s=assignTraining(s,item.id,item.target);expect(checkCertaintyPractice(s).session.round).toBe(6);s={...s,round:6,trainingAssignments:{}};for(const item of historyConditionPractice)s=assignTraining(s,item.id,item.target);expect(checkHistoryConditionPractice(s).session.round).toBe(7);s={...s,round:8,trainingAssignments:{}};for(const item of analysisErrorPractice)s=assignTraining(s,item.id,item.target);expect(checkAnalysisErrors(s).session.round).toBe(9)});
  it("requires every category in the independent consolidation before Shakespeare",()=>{let s:Chapter01Session={...initialChapter01Session,round:9};for(const group of consolidationGroups)for(const option of group.options.filter(item=>item.correct))s=toggleTrainingSelection(s,group.field,option.id);const result=checkConsolidation(s);expect(result.valid).toBe(true);expect(result.session.round).toBe(10)});
  it("does not reveal evidence chains through aligned option positions",()=>{expect(signalChainPractice.links.some(link=>link.signal===link.finding&&link.finding===link.inference)).toBe(false);const link=signalChainPractice.links[0];let s:Chapter01Session={...initialChapter01Session,round:7};s=selectChainPart(s,"signal",link.signal);s=selectChainPart(s,"finding",link.finding);s=selectChainPart(s,"inference",link.inference);expect(checkChain(s).valid).toBe(true)});
  it("uses varied deterministic answer positions",()=>{const certaintyPositions=certaintyPractice.map(item=>({explicit:1,inference:2,unsupported:3})[item.target]);expect(new Set(certaintyPositions).size).toBe(3);expect(certaintyPositions).not.toEqual([...certaintyPositions].sort());const situationPositions=categoryPractice.map(item=>({place:1,time:2,characters:3,history:4,conditions:5,unknown:6})[item.target]);expect(new Set(situationPositions).size).toBeGreaterThan(3);const consolidationPositions=consolidationGroups.flatMap(group=>group.options.map((item,index)=>item.correct?index+1:0).filter(Boolean));expect(new Set(consolidationPositions)).toEqual(new Set([1,2,3]));const transferPositions=transferSituationGroups.flatMap(group=>group.options.map((item,index)=>item.correct?index+1:0).filter(Boolean));expect(new Set(transferPositions)).toEqual(new Set([1,2,3,4,5]))});
});
