import { describe, expect, it } from "vitest";
import { chapter08PracticeTexts, chapter08Steps, conflictMisconceptions, evaluateConflictStatement, isConflictTransferComplete, problemCases, selectConflictText } from "../src/games/epik/data/chapter_08";
describe("Epik Bereich 8", () => {
  it("besitzt fünf Schritte und zehn unterschiedliche Texte", () => { expect(chapter08Steps).toHaveLength(5); expect(chapter08PracticeTexts).toHaveLength(10); expect(new Set(chapter08PracticeTexts.map((text) => text.id)).size).toBe(10); });
  it("deckt Konfliktmodell, Ebenen, Zuspitzung und offenen Ausgang ab", () => { const features = chapter08PracticeTexts.flatMap((text) => text.features); const levels = chapter08PracticeTexts.flatMap((text) => text.levels); expect(features).toEqual(expect.arrayContaining(["Gut", "Bedrohung", "Reaktion", "Zuspitzung", "Entscheidungssituation", "offener Ausgang"])); expect(levels).toEqual(expect.arrayContaining(["innerer Konflikt", "zwischenmenschlicher Konflikt", "institutioneller Konflikt", "äußerer Konflikt", "Wertekonflikt", "Pflichtenkonflikt", "mehrschichtiger Konflikt"])); });
  it("enthält drei Mini-Fallgruppen und rotiert ohne Wiederholung", () => { expect(problemCases).toHaveLength(3); const first = selectConflictText(0); expect(selectConflictText(0, [first.id]).id).not.toBe(first.id); });
  it("bewertet zentrale Fehlvorstellungen", () => { expect(conflictMisconceptions).toHaveLength(10); expect(evaluateConflictStatement("problem", false)).toBe(true); expect(evaluateConflictStatement("object", false)).toBe(true); expect(evaluateConflictStatement("argument", false)).toBe(true); expect(evaluateConflictStatement("types", false)).toBe(true); expect(evaluateConflictStatement("loud", false)).toBe(true); expect(evaluateConflictStatement("solution", false)).toBe(true); expect(evaluateConflictStatement("summary", false)).toBe(true); expect(evaluateConflictStatement("outer", true)).toBe(true); expect(evaluateConflictStatement("layers", true)).toBe(true); });
  it("erkennt den vollständigen Transfer", () => { const complete = { "motor-figure": 1, "motor-stake": 1, "motor-threat": 1, "motor-reaction": 1, "motor-situation": 1, "motor-decision": 1, "motor-consequence": 1, "motor-outcome": 1, axis: 1, "outer-form": 1, content: 1, turning: 1, analysis: 1 }; expect(isConflictTransferComplete(complete)).toBe(true); expect(isConflictTransferComplete({ axis: 1 })).toBe(false); });
});
