import { describe, expect, it } from "vitest";
import { chapter09PracticeTexts, chapter09Steps, evaluateInterpretationStatement, findingCases, interpretationChain, interpretationMisconceptions, isInterpretationTransferComplete, selectInterpretationText } from "../src/games/epik/data/chapter_09";
describe("Epik Bereich 9", () => {
  it("besitzt fünf Schritte und zehn unterschiedliche Mehrbereichstexte", () => { expect(chapter09Steps).toHaveLength(5); expect(chapter09PracticeTexts).toHaveLength(10); expect(new Set(chapter09PracticeTexts.map((text) => text.id)).size).toBe(10); expect(chapter09PracticeTexts.every((text) => text.foci.length >= 3)).toBe(true); });
  it("unterscheidet vier Aussageebenen und rotiert Texte", () => { expect(findingCases).toHaveLength(3); expect(findingCases.every((item) => item.observation && item.analysis && item.interpretation && item.overreach)).toBe(true); const first = selectInterpretationText(0); expect(selectInterpretationText(0, [first.id]).id).not.toBe(first.id); });
  it("enthält Belegqualität und die vollständige Analysekette", () => { expect(chapter09PracticeTexts.every((text) => text.strongEvidence !== text.weakEvidence)).toBe(true); expect(interpretationChain).toEqual(["Beobachtung", "Textbeleg", "Analyse", "Wirkung", "Deutung"]); expect(chapter09PracticeTexts.every((text) => text.blocks.length === 5)).toBe(true); });
  it("bewertet zentrale Fehlvorstellungen", () => { expect(interpretationMisconceptions).toHaveLength(7); expect(evaluateInterpretationStatement("quote", false)).toBe(true); expect(evaluateInterpretationStatement("term", false)).toBe(true); expect(evaluateInterpretationStatement("opinion", false)).toBe(true); expect(evaluateInterpretationStatement("multiple", true)).toBe(true); expect(evaluateInterpretationStatement("anything", false)).toBe(true); expect(evaluateInterpretationStatement("connect", true)).toBe(true); expect(evaluateInterpretationStatement("over", true)).toBe(true); });
  it("erkennt den vollständigen Transfer", () => { const complete = { finding: 1, areas: 1, evidence: 1, effect: 1, hypothesis: 1, blocks: 1, quality: 1, ownAnalysis: "Vier zusammenhängende Analysesätze.", "check-observation": true, "check-evidence": true, "check-term": true, "check-effect": true, "check-interpretation": true }; expect(isInterpretationTransferComplete(complete)).toBe(true); expect(isInterpretationTransferComplete({ finding: 1 })).toBe(false); });
});
