import { describe, expect, it } from "vitest";
import { initialGameState, type GameState } from "../src/core/state/types";
import { loadGameState, saveGameState } from "../src/core/state/store";
import { isChapterUnlocked } from "../src/core/progress/progress";
import { chapter05TransferSources } from "../src/games/dramatik/data/chapter_05_content";
import { analysisMethodGroups, examCheck, synthesisAreas, synthesisConnections, synthesisFindings, synthesisSourceReferences } from "../src/games/dramatik/data/finale/synthesis";
import { aggregateVisibleCompetencies, visibleCompetencies } from "../src/games/dramatik/mechanics/competency_aggregation";
import { createFinaleSnapshot, isFinaleAvailable } from "../src/games/dramatik/mechanics/finale_state";

const completed = ["chapter_01", "chapter_02", "chapter_03", "chapter_04", "chapter_05"];
const ready = (): GameState => ({ ...structuredClone(initialGameState), currentGame: "dramatik", currentChapter: "finale", completedChapters: completed, theatreState: "AFTER_CHAPTER_5", decisions: { chapter_05: { transferRevision: "Gespeicherte Deutung" } }, competencies: { evidence_reasoning: { value: 5, level: "secure" }, interpretation_reasoning: { value: 4, level: "secure" } } });

describe("new synthesis finale", () => {
  it("unlocks only after all five chapters, without staging data", () => { const state = ready(); expect(state.stagingDecisions).toEqual({}); expect(isFinaleAvailable(state)).toBe(true); expect(isChapterUnlocked("finale", completed.slice(0, -1))).toBe(false); expect(isFinaleAvailable({ completedChapters: completed.slice(0, -1), theatreState: "AFTER_CHAPTER_4" })).toBe(false); });
  it("registers five non-linear synthesis areas", () => { expect(synthesisAreas).toHaveLength(5); expect(new Set(synthesisAreas.map((area) => area.id)).size).toBe(5); expect(synthesisConnections.some((link) => link.a === "dialogue" && link.b === "interpretation")).toBe(true); });
  it("uses five validated findings and correctable direct links", () => { expect(synthesisFindings).toHaveLength(5); expect(synthesisConnections).toHaveLength(5); expect(synthesisConnections.every((link) => synthesisFindings.some((item) => item.id === link.a) && synthesisFindings.some((item) => item.id === link.b))).toBe(true); });
  it("references existing chapter-5 sources without duplicating primary text", () => { expect(synthesisSourceReferences.every((id) => chapter05TransferSources.some((source) => source.id === id))).toBe(true); expect(JSON.stringify({ synthesisFindings, synthesisConnections })).not.toContain("primary_source"); });
  it("creates no staging snapshot and mutates no competence data", () => { const state = ready(); const before = structuredClone(state.competencies); const snapshot = createFinaleSnapshot(state); expect(snapshot).not.toHaveProperty("finalStaging"); expect(state.competencies).toEqual(before); });
  it("aggregates deterministically without percentages", () => { const state = ready(); expect(aggregateVisibleCompetencies(state)).toEqual(aggregateVisibleCompetencies(state)); expect(JSON.stringify(aggregateVisibleCompetencies(state))).not.toContain("%"); });
  it("normalizes repetitions instead of rewarding raw volume", () => { const ordinary = ready(); const repeated = ready(); repeated.competencies.evidence_reasoning = { value: 500, level: "advanced" }; ordinary.competencies.evidence_reasoning = { value: 5, level: "advanced" }; expect(aggregateVisibleCompetencies(repeated).evidence).toEqual(aggregateVisibleCompetencies(ordinary).evidence); });
  it("marks missing measurement data as unobserved", () => { const empty = aggregateVisibleCompetencies({ competencies: {}, decisions: {} }); expect(Object.values(empty).every((result) => !result.observed && result.feedback.includes("nicht ausreichend"))).toBe(true); });
  it("uses understandable bundled labels", () => { expect(visibleCompetencies).toHaveLength(7); expect(visibleCompetencies.map((item) => item.label).join(" ")).not.toMatch(/speech_act|causal_reasoning|counterevidence|staging/); });
  it("contains transferable method and exam-check data", () => { expect(analysisMethodGroups).toHaveLength(5); expect(examCheck).toHaveLength(7); expect(examCheck.join(" ")).toContain("Textbeleg"); });
  it("persists the new cursor and safely defaults old staging saves", () => { const memory = new Map<string, string>(); const storage = { getItem: (key: string) => memory.get(key) ?? null, setItem: (key: string, value: string) => memory.set(key, value) }; saveGameState({ ...ready(), finaleStarted: true, finaleVisitedAreas: ["situation", "dialogue"], finaleSynthesisCompleted: true, finaleBookOpened: true }, storage); expect(loadGameState(storage)).toMatchObject({ finaleVisitedAreas: ["situation", "dialogue"], finaleSynthesisCompleted: true, finaleBookOpened: true }); const old = { ...ready(), stagingDecisions: { chapter_04: { legacy: true } } } as Partial<GameState>; delete old.finaleVisitedAreas; delete old.finaleSynthesisCompleted; memory.set("lernwerkstatt-games:state:v1", JSON.stringify(old)); expect(loadGameState(storage)).toMatchObject({ finaleVisitedAreas: [], finaleSynthesisCompleted: false }); });
  it("persists completion without performance moments", () => { const memory = new Map<string, string>(); const storage = { getItem: (key: string) => memory.get(key) ?? null, setItem: (key: string, value: string) => memory.set(key, value) }; saveGameState({ ...ready(), finaleCompleted: true, gameCompleted: true, finaleClosingSeen: true, performanceState: "PERFORMANCE_COMPLETE" }, storage); expect(loadGameState(storage)).toMatchObject({ finaleCompleted: true, gameCompleted: true, finaleClosingSeen: true }); });
  it("does not unlock from chapter completion with an inconsistent theatre state", () => expect(isFinaleAvailable({ completedChapters: completed, theatreState: "INITIAL" })).toBe(false));
  it("gives every restored area a concise method reminder", () => expect(synthesisAreas.every((area) => area.reminder.length > 80 && !area.reminder.includes("primary_source"))).toBe(true));
  it("contains only unique, non-reflexive synthesis links", () => { const keys = synthesisConnections.map((link) => [link.a, link.b].sort().join("--")); expect(new Set(keys).size).toBe(keys.length); expect(synthesisConnections.every((link) => link.a !== link.b)).toBe(true); });
  it("keeps the chapter-5 hypothesis as a snapshot without staging", () => expect(createFinaleSnapshot(ready())).toMatchObject({ finalHypothesis: "Gespeicherte Deutung" }));
  it("does not derive competence from failed-attempt counters", () => { const state = ready(); state.failedAttempts = { chapter_01: 99, chapter_05: 99 }; expect(aggregateVisibleCompetencies(state)).toEqual(aggregateVisibleCompetencies({ ...state, failedAttempts: {} })); });
  it("tolerates old performance flags without restoring old performance content", () => { const memory = new Map<string, string>(); const storage = { getItem: (key: string) => memory.get(key) ?? null, setItem: (key: string, value: string) => memory.set(key, value) }; memory.set("lernwerkstatt-games:state:v1", JSON.stringify({ ...ready(), performanceState: "PERFORMANCE_RUNNING", currentPerformanceMoment: 6, stagingDecisions: { chapter_04: { legacy: true } } })); expect(loadGameState(storage)).toMatchObject({ performanceState: "PERFORMANCE_RUNNING", finaleVisitedAreas: [] }); });
  it("keeps technical identifiers out of learner-facing synthesis copy", () => expect(JSON.stringify({ synthesisAreas, synthesisFindings }).toLowerCase()).not.toMatch(/finale_state|competency_aggregation|speech_act|primary_source|staging/));
});
