import { describe,expect,it } from "vitest";
import { humanReviewTaskIds,poolExercises } from "../src/games/lyrik/data/exercises/pools";
import { metricExamples,rejectedMeterIds } from "../src/games/lyrik/data/meter";
import { masterRoundTasks } from "../src/games/lyrik/data/exercises/masterRound";
import { optionsForLevel } from "../src/games/lyrik/engine";

const task=(reviewId:keyof typeof humanReviewTaskIds)=>poolExercises.find(item=>item.id===humanReviewTaskIds[reviewId])!;

describe("redaktioneller Human-Review-Patch",()=>{
 it("bildet in L3-15 alle drei vorhandenen Figuren transparent ab",()=>{const item=task("L3-15");expect(item.text).toBe("Wir lernen für morgen, wir streiten für morgen, wir wählen für morgen.");expect(item.sample).toContain("Anapher");expect(item.sample).toContain("Epipher");expect(item.sample).toContain("Parallelismus");expect(item.feedback).toContain("Anapher");expect(item.feedback).toContain("Epipher");expect(item.feedback).toContain("Parallelismus");});
 it("verwendet für L3-16 ausschließlich den akzeptierten Metrumdatensatz",()=>{const item=task("L3-16"),metric=metricExamples.find(entry=>`exercise-${entry.id}`===item.id);expect(metric?.verificationStatus).toBe("accepted");expect(metric?.hasDeviation).toBe(true);expect(metric?.id).toBe("meter-trochaeus-verse-e");expect(rejectedMeterIds).not.toContain(metric?.id);});
 it("hält die fünf Review-IDs stabil und produktiv",()=>{for(const [reviewId,id] of Object.entries(humanReviewTaskIds)){expect(reviewId).toMatch(/^L[123]-/);expect(poolExercises.some(item=>item.id===id)).toBe(true);}});
 it("entfernt Würde und ordnet Spätschicht-Belege präzise zu",()=>{const steps=poolExercises.filter(item=>item.transferCaseId==="transfer-01");expect(JSON.stringify(steps)).not.toContain("Würde");expect(steps[2].correct).toEqual(["„seit Mitternacht“ und „Morgen ohne Sirene“"]);expect(steps[1].feedback).toContain("Öl belegt Arbeitsnähe");});
 it("bezeichnet Update als inhaltlichen Kontrast und erklärt beide Enjambements",()=>{const steps=poolExercises.filter(item=>item.transferCaseId==="transfer-02");expect(steps[0].correct?.[0]).toContain("deutlichen inhaltlichen Kontrast");expect(steps[1].correct?.[0]).toContain("Das erste Enjambement");expect(steps[1].correct?.[0]).toContain("das zweite");expect(steps[1].correct?.[0]).toContain("nicht mehr");});
 it("ordnet alle 35 Review-IDs dem Präfix entsprechend ihrem Level zu",()=>{for(const [reviewId,id] of Object.entries(humanReviewTaskIds)){expect(poolExercises.find(item=>item.id===id)?.level).toBe(Number(reviewId[1]));}});
 it("führt L3-12 auf Level 3",()=>expect(task("L3-12").level).toBe(3));
 it("beseitigt Dubletten aus Text, Aufgabenstellung und Denkoperation",()=>{const signatures=Object.values(humanReviewTaskIds).map(id=>{const item=poolExercises.find(entry=>entry.id===id)!;return `${item.text}\u0000${item.prompt}\u0000${item.cognitiveOperation}`;});expect(new Set(signatures).size).toBe(signatures.length);});
 it("korrigiert die Domains der früheren Dubletten",()=>{expect(task("L3-17").domain).toBe("form");expect(task("L3-18").domain).toBe("speaker");expect(task("L3-19").domain).toBe("mood");});
 it("erklärt bei L2-8 Repetitio als Oberkategorie transparent",()=>{const item=task("L2-8");expect(item.prompt).toContain("Welche Stilmittel erkennst du");expect(item.feedback).toContain("Im weiteren Sinn");expect(item.feedback).toContain("Wiederholung");});
 it("enthält keine verbotenen Generatorformulierungen in produktiven Review-Aufgaben",()=>{const forbidden=["präzisiert, öffnet oder kontrastiert","language und mood","Krankenhausordnung","Todesszene","Leerstelle im Bett","dass die Figur ordnet"];const review=Object.values(humanReviewTaskIds).map(id=>poolExercises.find(item=>item.id===id));for(const phrase of forbidden)expect(JSON.stringify(review)).not.toContain(phrase);});
 it("vermeidet mechanisch identische Distraktor- und Feedbackschablonen",()=>{const review=Object.values(humanReviewTaskIds).map(id=>poolExercises.find(item=>item.id===id)!).filter(item=>item.options);const wrong=review.flatMap(item=>item.options!.filter(option=>!item.correct?.includes(option)));const repeated=Math.max(...[...new Set(wrong)].map(option=>wrong.filter(value=>value===option).length));expect(repeated).toBeLessThanOrEqual(2);const feedbacks=Object.values(humanReviewTaskIds).map(id=>poolExercises.find(item=>item.id===id)!.feedback);expect(Math.max(...[...new Set(feedbacks)].map(value=>feedbacks.filter(item=>item===value).length))).toBeLessThanOrEqual(2);});
 it("bevorzugt aufgabeneigene Review-Distraktoren vor allgemeinen Fallbacks",()=>{const item=task("L1-5");expect(optionsForLevel({...item,kind:"choice"},1,17).every(option=>item.options?.includes(option))).toBe(true);});
 it("redigiert Meisterrunde 8 bis 12 ohne vorausgesetzten Klinik- oder Todeskontext",()=>{const finalTasks=masterRoundTasks.slice(7);expect(JSON.stringify(finalTasks)).not.toMatch(/Krankenhaus|Todesszene|leere(?:s|n)? Bett|Leerstelle im Bett/);expect(finalTasks[0].correct?.[0]).toContain("Blumen täglich wechseln");expect(finalTasks[4].sample).toContain("nachgehende Uhr");});
});
