import { describe,expect,it } from "vitest";
import { poolExercises } from "../src/games/lyrik/data/exercises/pools";
import { styleDevices,styleExampleReviews } from "../src/games/lyrik/data/knowledge/styleDevices";
import { styleDeviceQualityReport } from "../src/games/lyrik/data/style-device-quality";

describe("Fail-closed-Stilmittelbestand",()=>{
 it("enthält 52 vollständige Karten",()=>{expect(styleDevices).toHaveLength(52);for(const card of styleDevices){expect(card.definition.trim()).not.toBe("");expect(card.recognition.trim()).not.toBe("");expect(card.analysisHint.trim()).not.toBe("");expect(card.functions).toHaveLength(3);expect(card.examples.length).toBeGreaterThan(0);}});
 it("verwendet nur akzeptierte, eindeutig referenzierte Beispiele",()=>{expect(styleExampleReviews.every(example=>example.verificationStatus==="accepted")).toBe(true);expect(new Set(styleExampleReviews.map(example=>example.id)).size).toBe(styleExampleReviews.length);const terms=new Set(styleDevices.map(card=>card.term));for(const example of styleExampleReviews){expect(terms.has(example.device)).toBe(true);for(const term of [...example.coexistingDevices,...example.distractors])expect(terms.has(term)).toBe(true);}});
 it("bilanziert Altbestand und kleine Erweiterung getrennt",()=>{expect(styleDeviceQualityReport.acceptedExamplesBeforeExpansion+styleDeviceQualityReport.legacyRejectedExamples).toBe(584);expect(styleDeviceQualityReport.newCandidates).toBe(52);expect(styleDeviceQualityReport.acceptedNewCandidates).toBe(48);expect(styleDeviceQualityReport.rejectedNewCandidates).toBe(4);expect(styleDeviceQualityReport.acceptedExamples).toBe(100);expect(styleDeviceQualityReport.ambiguousExamples).toBe(0);});
 it("hält Single Choice eindeutig und Multiple Choice lösbar",()=>{const tasks=poolExercises.filter(item=>item.id.startsWith("style-recognize-"));for(const task of tasks){if(task.mechanic==="multi")expect(task.correct!.length).toBeGreaterThan(1);else expect(task.correct).toHaveLength(1);expect(new Set(task.options).size).toBe(task.options!.length);for(const answer of task.correct!)expect(task.options).toContain(answer);}});
 it("verwendet keine nicht akzeptierten Stilbeispiele als Distraktorbasis",()=>{const acceptedTerms=new Set(styleExampleReviews.map(example=>example.device));for(const task of poolExercises.filter(item=>item.id.startsWith("style-")))for(const term of task.styleDistractors??[])expect(acceptedTerms.has(term)).toBe(true);});
 it("kennzeichnet Übungsbeispiele ohne fingierte Attribution",()=>{for(const example of styleExampleReviews){expect(example.sourceType).toBe("exerciseExample");expect(example).not.toHaveProperty("author");expect(example.text).not.toMatch(/—\s*(Goethe|Schiller|Rilke|Brecht)$/);}});
 it("enthält keine leeren Optionen oder Platzhalter",()=>{for(const task of poolExercises.filter(item=>item.id.startsWith("style-"))){expect(task.feedback.trim().length).toBeGreaterThan(30);expect(JSON.stringify(task).toLowerCase()).not.toMatch(/platzhalter|todo|tbd/);for(const option of task.options??[])expect(option.trim()).not.toBe("");}});
 it("verlangt vollständige Metadaten und eigenständige Texte",()=>{expect(new Set(styleExampleReviews.map(example=>example.text)).size).toBe(styleExampleReviews.length);for(const example of styleExampleReviews){expect(example.explanation.length).toBeGreaterThan(30);expect(example.functionProfile.length).toBeGreaterThan(10);expect(example.register.length).toBeGreaterThan(3);}for(const example of styleExampleReviews.filter(example=>["Repetitio","Geminatio","Epizeuxis","Anapher","Epipher","Anadiplose","Kyklos"].includes(example.device))){expect(example.repeatUnit).toBeTruthy();expect(example.repeatPosition).toBeTruthy();}});
 it("gibt Kernbegriffen mehrere, Spezialbegriffen bewusst wenige Lerngelegenheiten",()=>{for(const [device,data] of Object.entries(styleDeviceQualityReport.byDevice)){expect(data.accepted).toBe(styleDevices.find(card=>card.term===device&&styleDeviceQualityReport.byDevice[device])&&["Alliteration","Anapher","Antiklimax","Antithese","Apostrophe","Assonanz","Ellipse","Epipher","Euphemismus","Hyperbel","Inversion","Klimax","Litotes","Metapher","Neologismus","Onomatopoesie","Oxymoron","Paradoxon","Parallelismus","Personifikation","Repetitio","Rhetorische Frage","Symbol","Vergleich"].includes(device)?3:1);}});
});
