import {describe,expect,it} from "vitest";
import {canonicalPoems} from "../src/games/lyrik/data/texts/canonicalPoems";

describe("authentischer Nutzerkorpus",()=>{
 it("enthält exakt alle 47 Nutzerwerke mit Pflichtmetadaten",()=>{expect(canonicalPoems).toHaveLength(47);expect(new Set(canonicalPoems.map(p=>p.id)).size).toBe(47);expect(new Set(canonicalPoems.map(p=>`${p.author} – ${p.title}`)).size).toBe(47);for(const p of canonicalPoems){expect(p.sourceType).toBe("authentic");expect(p.textVerificationStatus).toBeTruthy();expect(p.stanzaVerification).toBeTruthy();expect(p.rightsStatus).toBeTruthy();expect(p.author).toBeTruthy();expect(p.title).toBeTruthy();expect(p.text.length).toBeGreaterThan(20);expect(p.verseCount).toBeGreaterThan(0);expect(p.stanzas.length).toBe(p.stanzaCount);}});
 it("hält Gibrans Übersetzungen im Rechte-Review",()=>{const g=canonicalPoems.filter(p=>p.author==="Khalil Gibran");expect(g).toHaveLength(2);expect(g.every(p=>p.rightsStatus==="translation-review-required"&&!p.approvedForProductiveUse&&!p.publicReleaseAllowed)).toBe(true);});
 it("enthält keine Navigations- oder Linkreste",()=>{for(const p of canonicalPoems){expect(p.text).not.toMatch(/https?:\/\/|www\.|\]\(|Zurück zur|Navigation|Quellenfooter/i);}});
 it("setzt Nutzerfassungen nicht pauschal mit Quellenverifikation gleich",()=>{expect(canonicalPoems.filter(p=>p.textVerificationStatus==="verified").map(p=>p.title)).toEqual(["Die schlesischen Weber","Mondnacht","Der Gott der Stadt","Die Stadt","Der Panther","Verfall"]);expect(canonicalPoems.filter(p=>p.textVerificationStatus==="needs-manual-review")).toHaveLength(39);});
 it("wendet die vier Freigabegates fail-closed an",()=>{for(const p of canonicalPoems){expect(typeof p.previewAllowed).toBe("boolean");expect(typeof p.contentTaskAllowed).toBe("boolean");expect(typeof p.formalTaskAllowed).toBe("boolean");expect(typeof p.publicReleaseAllowed).toBe("boolean");expect(p.sourceVerification.checkedAt).toBe("2026-09-12");if(p.publicReleaseAllowed)expect(p.textVerificationStatus).toBe("verified");if(p.formalTaskAllowed){expect(p.stanzaStructureStatus).toBe("verified");expect(p.rhymeStatus).toBe("verified");}}});
 it("dokumentiert Rilkes offene Geiger-Spieler-Variante",()=>{const p=canonicalPoems.find(p=>p.title==="Liebes-Lied")!;expect(p.sourceVerification.status).toBe("variant-unresolved");expect(p.variants.some(v=>v.userReading==="Geiger"&&v.verifiedReading==="Spieler")).toBe(true);expect(p.publicReleaseAllowed).toBe(false);});
 it("speichert pro Werk eine eindeutige Editionsentscheidung",()=>{for(const poem of canonicalPoems){const source=poem.sourceVerification as typeof poem.sourceVerification&{baseEdition:{title:string|null;sourceUrl:string|null;rationale:string};editionPolicy:string};expect(source.baseEdition).toBeTruthy();expect(source.editionPolicy).toMatch(/^(authorised-historical|first-authorised|user-requested-version|critical-edition|other-documented)$/);if(poem.textVerificationStatus==="verified"){expect(source.baseEdition.title).toBeTruthy();expect(source.baseEdition.sourceUrl).toBeTruthy();}}const welcome=canonicalPoems[13] as (typeof canonicalPoems)[number]&{versionLabel:string};expect((welcome.sourceVerification as typeof welcome.sourceVerification&{editionPolicy:string}).editionPolicy).toBe("user-requested-version");expect(welcome.versionLabel).toBe("spätere Fassung");});
 it("trennt Anzeigetitel von historischen Titelvarianten",()=>{const lorelei=canonicalPoems[33] as (typeof canonicalPoems)[number]&{canonicalDisplayTitle:string;knownTitleVariants:readonly string[]};expect(lorelei.canonicalDisplayTitle).toBe("Die Lorelei");expect(lorelei.knownTitleVariants).toContain("Lore-Ley");});
 it("trennt Nutzerfassung und kanonische Editionsfassung",()=>{for(const poem of canonicalPoems){const p=poem as typeof poem&{canonicalText:string|null;userStanzas:readonly string[];canonicalStanzas:readonly string[];collationStatus:string};expect(p.userText).toBeTruthy();expect(p.userStanzas.length).toBeGreaterThan(0);if(p.textVerificationStatus==="verified"){expect(p.collationStatus).toBe("collated");expect(p.canonicalText).toBe(p.text);expect(p.canonicalStanzas.join("\n\n")).toBe(p.canonicalText);}else expect(p.publicReleaseAllowed).toBe(false);}});
 it("bewahrt historische Basislesarten ohne automatische Modernisierung",()=>{const weber=canonicalPoems[34] as (typeof canonicalPoems)[number]&{canonicalText:string};expect(weber.userText).toContain("Wo nun gedeihen");expect(weber.canonicalText).toContain("Wo nur gedeihen");expect(weber.canonicalText).toContain("Thräne");const heym=canonicalPoems[40] as (typeof canonicalPoems)[number]&{canonicalText:string};expect(heym.canonicalText).toContain("schwält");expect(heym.canonicalText).toContain("frißt");});
});
