"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import type {GlossaryEntry} from "../../games/dramatik/data/glossary";

export function GlossaryHelp({entries,introTitle,introText,introEntryIds,seen,onSeen}:{entries:readonly GlossaryEntry[];introTitle:string;introText?:string;introEntryIds?:readonly string[];seen:boolean;onSeen:()=>void}){
 const[open,setOpen]=useState(!seen);const[active,setActive]=useState<GlossaryEntry|null>(null);const dialogRef=useRef<HTMLDivElement>(null);const returnRef=useRef<HTMLElement|null>(null);
 const show=(entry?:GlossaryEntry)=>{returnRef.current=document.activeElement instanceof HTMLElement?document.activeElement:null;setActive(entry??null);setOpen(true)};
 const close=useCallback(()=>{setOpen(false);onSeen();queueMicrotask(()=>returnRef.current?.focus())},[onSeen]);
 const contextualIntro=introText??(introTitle.includes("Figuren")?"Folgende Begriffe sind für die Figurenanalyse relevant.":introTitle.includes("Dialog")?"Folgende Begriffe sind für die Dialoganalyse relevant.":introTitle.includes("Konflikt")?"Folgende Begriffe sind für die Konflikt- und Handlungsanalyse relevant.":introTitle.includes("Interpretation")?"Folgende Begriffe sind für die Interpretation relevant.":introTitle.includes("Situation")?"Folgende Begriffe sind für die Situationsanalyse relevant.":"Folgende Begriffe sind für die anschließende Analyse relevant.");
 useEffect(()=>{if(!open)return;const root=dialogRef.current;root?.scrollTo({top:0,behavior:"auto"});root?.querySelector<HTMLElement>("button")?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape"&&seen){event.preventDefault();close()}if(event.key!=="Tab"||!root)return;const focusable=[...root.querySelectorAll<HTMLElement>('button,[href],[tabindex]:not([tabindex="-1"])')];if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key)},[close,open,seen]);
 const introEntries=introEntryIds?entries.filter(entry=>introEntryIds.includes(entry.id)):entries;
 return <><div className="glossary-tools" aria-label="Begriffshilfen">{entries.map(entry=><button key={entry.id} type="button" onClick={()=>show(entry)} aria-label={`Begriff ${entry.term} erklären`}>ⓘ {entry.term}</button>)}</div>{open&&<div className="glossary-backdrop"><div ref={dialogRef} className="glossary-dialog" role="dialog" aria-modal="true" aria-labelledby="glossary-title"><p className="eyebrow">Begriffshilfe</p><h2 id="glossary-title">{active?.term??introTitle}</h2>{active?<p>{active.definition}</p>:<><p>{contextualIntro}</p><dl>{introEntries.map(entry=><div key={entry.id}><dt>{entry.term}</dt><dd>{entry.definition}</dd></div>)}</dl></>}<button type="button" onClick={close}>{seen?"Schließen":"Analyse beginnen"}</button></div></div>}</>;
}
