"use client";
import { useMemo, useState } from "react";
import { Button } from "@/src/features/literature-archive/components/Button";
import { Card } from "@/src/features/literature-archive/components/Card";
import { PracticeText } from "./PracticeText";
import { ChapterCompletionActions } from "./ChapterCompletionActions";
import { useShuffledOptions, useRunSeed } from "./choice-options";
import { chapterChoiceFeedback } from "./data/formative_feedback";
import { chapter03Glossary, chapter03Steps, evaluatePerceptionStatement, isPerceptionTransferComplete, perceptionComparisons, perceptionMisconceptions, selectPerceptionText, type PerceptionText, type ViewMode } from "./data/chapter_03";

function TextCard({ text }: { text: PerceptionText }) { return <PracticeText title={text.title} text={text.text}/>; }
function Choice({ label, options, answer, value, onSelect }: { label: string; options: readonly string[]; answer: string; value?: string; onSelect: (value: string) => void }) { const orderedOptions = useShuffledOptions(options, label); return <fieldset className="epik-choice"><legend>{label}</legend>{orderedOptions.map((option) => <button type="button" key={option} className={value === option ? "is-selected" : ""} onClick={() => onSelect(option)}>{option}</button>)}{value && <small role="status">{chapterChoiceFeedback(label, value, answer)}</small>}</fieldset>; }
const comparisonStatements = [
  { id: "a-outside", text: "Text A beschränkt sich auf äußerlich Beobachtbares.", correct: true },
  { id: "b-subjective", text: "Text B enthält eine figurenbezogene Wahrnehmung und Bewertung.", correct: true },
  { id: "c-inside", text: "Text C gibt einen inneren Vorgang der Figur wieder.", correct: true },
  { id: "b-inside", text: "Text B ist wegen jeder Bewertung automatisch vollständige Innensicht.", correct: false },
  { id: "c-outside", text: "Text C bleibt vollständig bei äußerlich sichtbaren Vorgängen.", correct: false },
  { id: "same-info", text: "Alle drei Fassungen vermitteln exakt denselben Informationsstand.", correct: false },
  { id: "more-near", text: "Text B erzeugt mehr Figurennähe als Text A.", correct: true },
  { id: "grammar", text: "Die Er-/Sie-Form entscheidet allein darüber, ob Innensicht vorliegt.", correct: false },
] as const;

export function Chapter03Path({ initialStep = 0 }: { initialStep?: number }) {
  const [step, setStep] = useState(initialStep); const [offset, setOffset] = useRunSeed(); const [answers, setAnswers] = useState<Record<string, string | boolean>>({}); const [feedback, setFeedback] = useState<string>(); const [completed, setCompleted] = useState(false);
  const texts = useMemo(() => { const picked: PerceptionText[] = []; for (let index = 0; index < 5; index += 1) picked.push(selectPerceptionText(offset + index, picked.map((item) => item.id))); return picked; }, [offset]);
  const text = texts[step]; const comparison = perceptionComparisons[offset % perceptionComparisons.length]; const set = (id: string, value: string | boolean) => setAnswers((old) => ({ ...old, [id]: value }));
  const mainMode: ViewMode = text.modes.length > 1 ? "Kombination" : text.modes[0];
  function next(message: string) { setFeedback(message); setAnswers({}); if (step === 4) setCompleted(true); else setStep((value) => value + 1); }
  function repeat() { setOffset((value) => value + 3); setStep(0); setAnswers({}); setFeedback(undefined); setCompleted(false); }
  if (completed) return <section className="epik-path"><Card className="epik-completion"><p className="learning-card__label">Bereich 3 abgeschlossen</p><h2>Erzählte Wirklichkeit und Figurenwahrnehmung sind nicht dasselbe.</h2><p>Prüfen Sie: Was ist beobachtbar? Was erfahren wir aus der Innenwelt? Wessen Wahrnehmung bestimmt die Szene? Wie nah kommen wir der Figur? Wie sicher ist ihre Wahrnehmung – und welche Wirkung entsteht?</p><ChapterCompletionActions chapter={3} onRepeat={repeat}/></Card></section>;
  return <section className="epik-path" aria-labelledby="chapter03-step-title"><div className="epik-path-progress">{chapter03Steps.map((title, index) => <span key={title} className={index === step ? "is-current" : index < step ? "is-done" : ""}>{index + 1}</span>)}</div><p className="learning-card__label">Nähe, Distanz & Wahrnehmung · Schritt {step + 1} von 5</p><h2 id="chapter03-step-title">{chapter03Steps[step]}</h2>{feedback && <p role="status" className="epik-feedback is-correct">{feedback}</p>}
    {step === 0 && <><h3>{comparison.title}</h3><div className="epik-version-grid">{comparison.versions.map((version, index) => <Card key={version}><p className="learning-card__label">Fassung {String.fromCharCode(65 + index)}</p><p>{version}</p></Card>)}</div><Card className="epik-task"><fieldset className="epik-choice"><legend>Welche Aussagen treffen auf die drei Fassungen zu? Wählen Sie alle zutreffenden Aussagen.</legend>{comparisonStatements.map((item) => <label key={item.id}><input type="checkbox" checked={answers[item.id] === true} onChange={(event) => set(item.id, event.target.checked)}/>{item.text}</label>)}</fieldset><Button disabled={!comparisonStatements.every((item) => Boolean(answers[item.id]) === item.correct)} onClick={() => next("Text A bleibt bei Außensicht, Text B bindet Wahrnehmung an die Figur und Text C öffnet einen inneren Vorgang. Dadurch wächst die Figurennähe schrittweise.")}>Auswahl prüfen</Button></Card></>}
    {step === 1 && <div className="epik-layout"><TextCard text={text}/><Card className="epik-task"><Choice label="Was ist äußerlich beobachtbar?" options={[text.observable, text.internal, text.uncertain]} answer={text.observable} value={answers.observable as string} onSelect={(value) => set("observable", value)}/><Choice label="Welchen inneren Vorgang macht die Darstellung zugänglich?" options={[text.internal, text.observable, text.uncertain]} answer={text.internal} value={answers.internal as string} onSelect={(value) => set("internal", value)}/><Choice label="Welche Information bleibt unbekannt?" options={[text.uncertain, text.observable, text.internal]} answer={text.uncertain} value={answers.uncertain as string} onSelect={(value) => set("uncertain", value)}/><Choice label="Welche Schlussfolgerung wäre deshalb nicht belegt?" options={[`Dass ${text.uncertain.toLowerCase()} sicher feststeht.`, `Dass ${text.observable.toLowerCase()} beobachtbar ist.`, `Dass ${text.internal.toLowerCase()} subjektiv vermittelt wird.`]} answer={`Dass ${text.uncertain.toLowerCase()} sicher feststeht.`} value={answers.overreach as string} onSelect={(value) => set("overreach", value)}/><Button disabled={answers.observable !== text.observable || answers.internal !== text.internal || answers.uncertain !== text.uncertain || answers.overreach !== `Dass ${text.uncertain.toLowerCase()} sicher feststeht.`} onClick={() => next("Außenbeobachtung, innerer Zugang, offene Information und unbelegte Folgerung sind getrennt.")}>Kamera und Kopf trennen</Button></Card></div>}
    {step === 2 && <><div className="epik-version-grid"><Card><p className="learning-card__label">Milo A</p><p>Milo saß auf der Bank und zog seine Schuhe aus. Auf dem Gang rief jemand seinen Namen. Er reagierte nicht.</p></Card><Card><p className="learning-card__label">Milo B</p><p>Milo saß auf der Bank. Nicht aufsehen. Nur noch die Schuhe ausziehen und hier verschwinden. Als jemand seinen Namen rief, spannte sich sein Rücken an.</p></Card></div><Card className="epik-task"><Choice label="Welche Milo-Fassung erzeugt mehr Nähe?" options={["Text A", "Text B"]} answer="Text B" value={answers.near as string} onSelect={(value) => set("near", value)}/><Choice label="Welche Textmerkmale erzeugen in Milo B die größere Nähe?" options={["Gedanken und körperliche Reaktion machen Milos Erleben zugänglich.", "Allein die Er-/Sie-Form schafft die größere Nähe."]} answer="Gedanken und körperliche Reaktion machen Milos Erleben zugänglich." value={answers.reason as string} onSelect={(value) => set("reason", value)}/><Button disabled={answers.near !== "Text B" || !String(answers.reason).startsWith("Gedanken und körperliche")} onClick={() => next("Figurennähe entsteht durch Zugang zu Gedanken, Gefühlen, Empfindungen und subjektiven Bewertungen – nicht allein durch die grammatische Form.")}>Nähewirkung sichern</Button></Card></>}
    {step === 3 && <div className="epik-layout"><TextCard text={text}/><Card className="epik-task"><p><strong>Prüfung der Wahrnehmung:</strong> {text.reliability}</p><Choice label="Welche Schlussfolgerung ist angemessen?" options={[text.reliability, "Die Figur lügt eindeutig."]} answer={text.reliability} value={answers.reliability as string} onSelect={(value) => set("reliability", value)}/><h3>Erzählerkommentar</h3><p>Kai legte das Formular auf den Tisch und ging. <em>Eine besonders mutige Entscheidung war das gewiss nicht.</em></p><Choice label="Was bewirkt der Zusatz?" options={["Er bewertet die Handlung und lenkt die Leserwahrnehmung.", "Er gibt Kais Gedanken objektiv wieder."]} answer="Er bewertet die Handlung und lenkt die Leserwahrnehmung." value={answers.comment as string} onSelect={(value) => set("comment", value)}/><h3>Fehlerdetektiv</h3>{perceptionMisconceptions.map((item) => { const answerId = `misconception-${item.id}`; return <div key={item.id}><p>{item.text}</p><Button variant="secondary" onClick={() => set(answerId, true)}>Trifft zu</Button><Button variant="secondary" onClick={() => set(answerId, false)}>Trifft nicht zu</Button>{typeof answers[answerId] === "boolean" && <small>{evaluatePerceptionStatement(item.id, answers[answerId] as boolean) ? "Differenziert eingeordnet." : "Zu pauschal: Darstellungs- und Erzählebene müssen getrennt werden."}</small>}</div>;})}<Button disabled={answers.reliability !== text.reliability || !String(answers.comment).startsWith("Er bewertet") || !perceptionMisconceptions.every((item) => { const answerId = `misconception-${item.id}`; return typeof answers[answerId] === "boolean" && evaluatePerceptionStatement(item.id, answers[answerId] as boolean); })} onClick={() => next("Figurenwahrnehmung kann glaubwürdig und dennoch unsicher sein. Widersprüche und Kommentare lenken die Prüfung, beweisen aber nicht automatisch eine Lüge.")}>Wahrnehmung prüfen</Button></Card></div>}
    {step === 4 && <div className="epik-layout"><TextCard text={text}/><Card className="epik-task"><Choice label="Was ist äußerlich beobachtbar?" options={[text.observable, text.internal]} answer={text.observable} value={answers.observable as string} onSelect={(value) => set("observable", value)}/><Choice label="Was ist innerlich oder subjektiv zugänglich?" options={[text.internal, text.observable]} answer={text.internal} value={answers.internal as string} onSelect={(value) => set("internal", value)}/><Choice label="Welche Darstellungsweise prägt die Stelle?" options={["Außensicht", "subjektive Figurensicht", "Innensicht", "Kombination"]} answer={mainMode} value={answers.mode as string} onSelect={(value) => set("mode", value)}/><Choice label="Wie nah sind wir der Figur?" options={["eher distanziert", "mittlere Nähe", "starke Figurennähe"]} answer={text.proximity} value={answers.proximity as string} onSelect={(value) => set("proximity", value)}/><label>Begründung mit Textmerkmal<button type="button" className={answers.reason ? "is-selected" : ""} onClick={() => set("reason", text.internal)}>{text.internal}</button></label><Choice label="Was bleibt unsicher?" options={[text.uncertain, text.observable]} answer={text.uncertain} value={answers.certainty as string} onSelect={(value) => set("certainty", value)}/><Choice label="Welche Wirkung entsteht?" options={[text.effect, "Der Text schafft vollständige Gewissheit."]} answer={text.effect} value={answers.effect as string} onSelect={(value) => set("effect", value)}/><Choice label="Welche Analyse ist am überzeugendsten?" options={[`Der Text enthält ${mainMode}.`, `${mainMode}: ${text.internal}`, `${mainMode} bindet den Leser an die Figur: ${text.internal} ${text.effect}`]} answer={`${mainMode} bindet den Leser an die Figur: ${text.internal} ${text.effect}`} value={answers.analysis as string} onSelect={(value) => set("analysis", value)}/><Button disabled={!isPerceptionTransferComplete(answers) || answers.observable !== text.observable || answers.internal !== text.internal || answers.mode !== mainMode || answers.proximity !== text.proximity || answers.certainty !== text.uncertain || answers.effect !== text.effect} onClick={() => next("Beobachtung, Wahrnehmungsart, Nähe und Wirkung wurden textnah verbunden.")}>Bereich abschließen</Button></Card></div>}
    <section className="epik-chapter-glossary" aria-label="Glossar zu Bereich 3">{chapter03Glossary.map((entry) => <details key={entry.term}><summary>{entry.term}</summary><p>{entry.short}</p><small>{entry.hint}</small></details>)}</section>
  </section>;
}


