"use client";
import { useMemo, useState } from "react";
import { Button } from "@/src/features/literature-archive/components/Button";
import { Card } from "@/src/features/literature-archive/components/Card";
import { PracticeText } from "./PracticeText";
import { ChapterCompletionActions } from "./ChapterCompletionActions";
import { useShuffledOptions, useRunSeed } from "./choice-options";
import { chapterChoiceFeedback } from "./data/formative_feedback";
import { chapter09Glossary, chapter09Steps, evaluateInterpretationStatement, findingCases, interpretationChain, interpretationMisconceptions, isInterpretationTransferComplete, selectInterpretationText, type InterpretationText } from "./data/chapter_09";
function TextCard({ text }: { text: InterpretationText }) { return <PracticeText title={text.title} text={text.text}/>; }
function Choice({ label, options, answers, value, onSelect }: { label: string; options: readonly string[]; answers: readonly string[]; value?: string; onSelect: (value: string) => void }) { const orderedOptions = useShuffledOptions(options, label); const [firstAnswer] = answers; return <fieldset className="epik-choice"><legend>{label}</legend>{orderedOptions.map((option) => <button type="button" key={option} className={value === option ? "is-selected" : ""} onClick={() => onSelect(option)}>{option}</button>)}{value && <small role="status">{answers.includes(value) ? chapterChoiceFeedback(label, value, value) : chapterChoiceFeedback(label, value, firstAnswer)}</small>}</fieldset>; }
export function Chapter09Path({ initialStep = 0 }: { initialStep?: number }) {
  const [step, setStep] = useState(initialStep); const [offset, setOffset] = useRunSeed(); const [answers, setAnswers] = useState<Record<string, string | boolean>>({}); const [feedback, setFeedback] = useState<string>(); const [completed, setCompleted] = useState(false);
  const texts = useMemo(() => { const picked: InterpretationText[] = []; for (let index = 0; index < 5; index += 1) picked.push(selectInterpretationText(offset + index, picked.map((item) => item.id))); return picked; }, [offset]);
  const text = texts[step]; const finding = findingCases[offset % findingCases.length]; const set = (id: string, value: string | boolean) => setAnswers((old) => ({ ...old, [id]: value }));
  function next(message: string) { setFeedback(message); setAnswers({}); if (step === 4) setCompleted(true); else setStep((value) => value + 1); }
  function repeat() { setOffset((value) => value + 3); setStep(0); setAnswers({}); setFeedback(undefined); setCompleted(false); }
  if (completed) return <section className="epik-path"><Card className="epik-completion"><p className="learning-card__label">Bereich 9 abgeschlossen</p><h2>Interpretation beginnt nicht mit einer Idee – sondern mit dem Text.</h2><p>Beobachten → Belegen → Analysieren → Wirkung erklären → Deuten → Vernetzen.</p><p>Eine gute Interpretation ist keine Sammlung möglichst vieler Beobachtungen, sondern eine begründete Auswahl und Verknüpfung bedeutsamer Textbefunde.</p><ChapterCompletionActions chapter={9} onRepeat={repeat}/></Card></section>;
  return <section className="epik-path" aria-labelledby="chapter09-step-title"><div className="epik-path-progress">{chapter09Steps.map((title, index) => <span key={title} className={index === step ? "is-current" : index < step ? "is-done" : ""}>{index + 1}</span>)}</div><p className="learning-card__label">Analyse → Interpretation · Schritt {step + 1} von 5</p><h2 id="chapter09-step-title">{chapter09Steps[step]}</h2>{feedback && <p role="status" className="epik-feedback is-correct">{feedback}</p>}
    {step === 0 && <div className="epik-layout"><PracticeText title={finding.title} text={finding.text}/><Card className="epik-task"><Choice label="Textbeobachtung" options={[finding.observation, finding.analysis, finding.interpretation, finding.overreach]} answers={[finding.observation]} value={answers.observation as string} onSelect={(value) => set("observation", value)}/><Choice label="Analyse" options={[finding.analysis, finding.observation, finding.overreach]} answers={[finding.analysis]} value={answers.analysis as string} onSelect={(value) => set("analysis", value)}/><Choice label="Deutung" options={[finding.interpretation, finding.analysis, finding.overreach]} answers={[finding.interpretation]} value={answers.interpretation as string} onSelect={(value) => set("interpretation", value)}/><Choice label="Überinterpretation" options={[finding.overreach, finding.interpretation]} answers={[finding.overreach]} value={answers.overreach as string} onSelect={(value) => set("overreach", value)}/><Button disabled={answers.observation !== finding.observation || answers.analysis !== finding.analysis || answers.interpretation !== finding.interpretation || answers.overreach !== finding.overreach} onClick={() => next("Je weiter eine Aussage vom konkreten Text entfernt ist, desto stärker muss sie begründet werden.")}>Aussageebenen sichern</Button></Card></div>}
    {step === 1 && <div className="epik-layout"><TextCard text={text}/><Card className="epik-task"><p><strong>Analysebehauptung:</strong> {text.interpretation}</p><Choice label="Stärkster Beleg" options={[text.strongEvidence, text.weakEvidence, "Die Überschrift des Textes"]} answers={[text.strongEvidence]} value={answers.strong as string} onSelect={(value) => set("strong", value)}/><Choice label="Schwacher oder nur begrenzt relevanter Beleg" options={[text.weakEvidence, text.strongEvidence]} answers={[text.weakEvidence]} value={answers.weak as string} onSelect={(value) => set("weak", value)}/><Choice label="Warum ist der starke Beleg geeignet?" options={["Er trägt direkt den entscheidenden Zusammenhang und lässt sich erklären.", "Jedes Zitat ist automatisch aussagekräftig."]} answers={["Er trägt direkt den entscheidenden Zusammenhang und lässt sich erklären."]} value={answers.reason as string} onSelect={(value) => set("reason", value)}/><Button disabled={answers.strong !== text.strongEvidence || answers.weak !== text.weakEvidence || !String(answers.reason).startsWith("Er trägt direkt")} onClick={() => next("Ein guter Beleg passt direkt zur Behauptung, trägt den entscheidenden Zusammenhang und muss anschließend erklärt werden.")}>Belegqualität sichern</Button></Card></div>}
    {step === 2 && <div className="epik-layout"><TextCard text={text}/><Card className="epik-task"><div className="epik-chain" aria-label="Analysekette">{interpretationChain.map((item) => <span key={item}>{item}</span>)}</div><Choice label="Beobachtung" options={[text.observation, text.overreach]} answers={[text.observation]} value={answers.observation as string} onSelect={(value) => set("observation", value)}/><Choice label="Textbeleg" options={[text.strongEvidence, text.weakEvidence]} answers={[text.strongEvidence]} value={answers.evidence as string} onSelect={(value) => set("evidence", value)}/><Choice label="Analyse" options={[text.analysis, text.general]} answers={[text.analysis]} value={answers.analysis as string} onSelect={(value) => set("analysis", value)}/><Choice label="Wirkung" options={[text.effect, "Der Fachbegriff genügt."]} answers={[text.effect]} value={answers.effect as string} onSelect={(value) => set("effect", value)}/><Choice label="Deutung" options={[text.interpretation, text.overreach]} answers={[text.interpretation]} value={answers.interpretation as string} onSelect={(value) => set("interpretation", value)}/><Button disabled={answers.observation !== text.observation || answers.evidence !== text.strongEvidence || answers.analysis !== text.analysis || answers.effect !== text.effect || answers.interpretation !== text.interpretation} onClick={() => next("Beobachtung, Beleg, Analyse, Wirkung und Deutung bilden eine nachvollziehbare Kette.")}>Analysekette abschließen</Button></Card></div>}
    {step === 3 && <div className="epik-layout"><TextCard text={text}/><Card className="epik-task"><Choice label="Welche Hypothese trägt der Text?" options={[text.general, text.interpretation, text.overreach]} answers={[text.interpretation]} value={answers.hypothesis as string} onSelect={(value) => set("hypothesis", value)}/><Choice label="Welche zwei Befunde stützen sie besonders?" options={[`${text.observation} + ${text.analysis}`, `${text.weakEvidence} + Überschrift`]} answers={[`${text.observation} + ${text.analysis}`]} value={answers.findings as string} onSelect={(value) => set("findings", value)}/><h3>Fehlerdetektiv</h3>{interpretationMisconceptions.map((item) => <div key={item.id}><p>{item.text}</p><Button variant="secondary" onClick={() => set(item.id, true)}>Trifft zu</Button><Button variant="secondary" onClick={() => set(item.id, false)}>Trifft nicht zu</Button><small>{typeof answers[item.id] === "boolean" ? evaluateInterpretationStatement(item.id, answers[item.id] as boolean) ? "Interpretationsqualität korrekt eingeschätzt." : "Plausibilität braucht Textbelege; nicht jede denkbare Deutung ist gleich gut." : ""}</small></div>)}<Button disabled={answers.hypothesis !== text.interpretation || answers.findings !== `${text.observation} + ${text.analysis}` || !interpretationMisconceptions.every((item) => typeof answers[item.id] === "boolean" && evaluateInterpretationStatement(item.id, answers[item.id] as boolean))} onClick={() => next("Eine Deutungshypothese ist eine am Text zu prüfende Annahme. Mehrere Deutungen können plausibel sein, aber nicht beliebig.")}>Hypothese prüfen</Button></Card></div>}
    {step === 4 && <div className="epik-layout"><TextCard text={text}/><Card className="epik-task"><Choice label="Ergiebigster Befund" options={[text.observation, text.weakEvidence, text.overreach]} answers={[text.observation]} value={answers.finding as string} onSelect={(value) => set("finding", value)}/><Choice label="Verknüpfte Analysebereiche" options={[text.foci.join(" · "), "nur ein Fachbegriff"]} answers={[text.foci.join(" · ")]} value={answers.areas as string} onSelect={(value) => set("areas", value)}/><Choice label="Stärkster Beleg" options={[text.strongEvidence, text.weakEvidence]} answers={[text.strongEvidence]} value={answers.evidence as string} onSelect={(value) => set("evidence", value)}/><Choice label="Plausibelste Wirkung" options={[text.effect, "keine Wirkung erforderlich"]} answers={[text.effect]} value={answers.effect as string} onSelect={(value) => set("effect", value)}/><Choice label="Tragfähige Deutungshypothese" options={[text.general, text.interpretation, text.overreach]} answers={[text.interpretation]} value={answers.hypothesis as string} onSelect={(value) => set("hypothesis", value)}/><Choice label="Sinnvolle Reihenfolge der fünf Satzbausteine" options={[text.blocks.join(" → "), [...text.blocks].reverse().join(" → ")]} answers={[text.blocks.join(" → ")]} value={answers.blocks as string} onSelect={(value) => set("blocks", value)}/><Choice label="Qualität einer Gesamtinterpretation" options={["Fachbegriffe ohne Zusammenhang", "Plausible Idee ohne ausreichenden Beleg", `${text.interpretation} ${text.analysis} Beleg: ${text.strongEvidence} Wirkung: ${text.effect}`]} answers={[`${text.interpretation} ${text.analysis} Beleg: ${text.strongEvidence} Wirkung: ${text.effect}`]} value={answers.quality as string} onSelect={(value) => set("quality", value)}/><Button disabled={!isInterpretationTransferComplete(answers) || answers.finding !== text.observation || answers.areas !== text.foci.join(" · ") || answers.evidence !== text.strongEvidence || answers.effect !== text.effect || answers.hypothesis !== text.interpretation || answers.blocks !== text.blocks.join(" → ")} onClick={() => next("Relevante Befunde wurden ausgewählt, belegt, funktional verknüpft und zu einer textnahen Deutung geführt.")}>Bereich abschließen</Button></Card></div>}
    <section className="epik-chapter-glossary" aria-label="Glossar zu Bereich 9">{chapter09Glossary.map((entry) => <details key={entry.term}><summary>{entry.term}</summary><p>{entry.short}</p><small>Verknüpft: {entry.relatedTerms.join(" · ")}</small></details>)}</section>
    {step === 4 && <Card className="epik-task epik-writing-task"><label><strong>Eigene Analyse (3–5 Sätze)</strong><textarea rows={6} value={(answers.ownAnalysis as string) ?? ""} onChange={(event) => set("ownAnalysis", event.target.value)} placeholder="Befund, Beleg, Fachbegriff, Wirkung und Deutung verbinden."/></label><fieldset className="epik-self-check"><legend>Selbstcheck</legend>{[["check-observation", "Beobachtung genannt"], ["check-evidence", "Textbeleg verwendet"], ["check-term", "Fachbegriff passend eingesetzt"], ["check-effect", "Wirkung erklärt"], ["check-interpretation", "Deutung vorsichtig formuliert"]].map(([id, label]) => <label key={id}><input type="checkbox" checked={Boolean(answers[id])} onChange={(event) => set(id, event.target.checked)}/>{label}</label>)}</fieldset><Button variant="secondary" onClick={() => set("showExample", !answers.showExample)}>Eine mögliche Beispielanalyse anzeigen</Button>{answers.showExample && <p className="epik-example-analysis">{text.blocks.join(" ")}</p>}</Card>}
  </section>;
}


