"use client";

import { useMemo, useState } from "react";
import { Button } from "@/src/features/literature-archive/components/Button";
import { Card } from "@/src/features/literature-archive/components/Card";
import { createRunSeed, shuffleChoiceOptions, useRunSeed, useShuffledOptions } from "./choice-options";
import { categoryLearningExercises, evaluateFreeText, learningCategoryIds, selectCategoryTrainingRound, selectLearningFinalTest, type LearningCategoryId, type LearningExercise } from "./data/learning_exercises";
import { learningCategories } from "./data/learning_content";
import { familyFeedback } from "./data/formative_feedback";

const exerciseTypeLabels: Record<LearningExercise["type"], string> = { freeText: "Begriff eintragen", singleChoice: "Auswahl", multipleChoice: "Mehrfachauswahl", matching: "Zuordnung", sorting: "Reihenfolge", comparison: "Textvergleich", evidence: "Belegwahl", errorDetective: "Fehlerdetektiv" };
type ExerciseResult = { correct: boolean; answer: string };

function familyGuidance(exercise: LearningExercise): string { const guidance = familyFeedback[exercise.familyId]; return guidance ? `${guidance.focus} ${guidance.distinction}` : `Leitfrage: ${exercise.analysisQuestion} ${exercise.hint}`; }
function selectedAnswerSummary(exercise: LearningExercise, selected: readonly string[], text: string, mapping: Readonly<Record<string, string>>, order: readonly string[]): string { if (exercise.type === "freeText") return text; if (exercise.type === "matching") return Object.entries(mapping).map(([term, target]) => `${term} → ${target}`).join("; "); if (exercise.type === "sorting") return order.join(" → "); return selected.join("; "); }
function incorrectChoiceFeedback(exercise: LearningExercise, selected: readonly string[]): string { const wrong = selected.filter((item) => !exercise.correctIds.includes(item)); const missing = exercise.correctIds.filter((item) => !selected.includes(item)); const wrongReasons = wrong.map((item) => exercise.choices.find(({ text }) => text === item)?.distractorReason).filter(Boolean); if (exercise.type === "multipleChoice") return `↺ Falsch gewählt: ${wrong.join(" · ") || "keine"}. Noch nicht gewählt: ${missing.join(" · ") || "keine"}. ${wrongReasons.join(" ") || familyGuidance(exercise)}`; if (exercise.type === "evidence") return `↺ Der gewählte Beleg ist ${wrongReasons[0] ?? "für diese Behauptung nicht direkt tragfähig"} Entscheidend ist: ${exercise.solution}`; if (exercise.type === "errorDetective") return `↺ Die Fehlannahme lautet: ${exercise.solution}. ${exercise.explanation}`; if (exercise.type === "comparison") return `↺ Beim Vergleich ist entscheidend, welches Textsignal sich zwischen A und B verändert. ${wrongReasons[0] ?? familyGuidance(exercise)}`; return `↺ ${wrongReasons[0] ?? familyGuidance(exercise)}`; }

function ExerciseInteraction({ exercise, seed, deferFeedback, onDone }: { exercise: LearningExercise; seed: number; deferFeedback?: boolean; onDone: (result: ExerciseResult) => void }) {
  const [selected, setSelected] = useState<string[]>([]); const [text, setText] = useState(""); const [attempts, setAttempts] = useState(0); const [feedback, setFeedback] = useState<string>(); const [result, setResult] = useState<boolean>(); const [activeTerm, setActiveTerm] = useState<string>(); const [mapping, setMapping] = useState<Record<string, string>>({});
  const [order, setOrder] = useState(() => shuffleChoiceOptions(exercise.correctOrder ?? exercise.options, seed, exercise.id));
  const options = useShuffledOptions(exercise.options, exercise.id);
  const finish = (correct: boolean, detail?: string) => { setResult(correct); setFeedback(deferFeedback ? "✓ Antwort gespeichert. Die fachliche Auflösung folgt nach Aufgabe 30." : correct ? `✓ Richtig. ${exercise.explanation} ${familyGuidance(exercise)}` : detail ?? `↺ ${familyGuidance(exercise)}`); };
  const check = () => { if (exercise.type === "freeText") { const correct = evaluateFreeText(exercise, text); if (deferFeedback) return finish(correct); if (!correct && attempts === 0) { setAttempts(1); setFeedback(`↺ Erster Hinweis: ${familyGuidance(exercise)}`); return; } return finish(correct, `↺ Beispielantwort: ${exercise.acceptedAnswers?.[0]}. ${exercise.explanation} Selbstcheck: Enthält Ihre Antwort den passenden Fachbegriff und beantwortet sie die Leitfrage?`); } if (exercise.type === "matching") { const wrong = Object.entries(exercise.mapping ?? {}).filter(([term, target]) => mapping[term] !== target); const details = wrong.map(([term, target]) => `${term}: „${mapping[term]}“ passt nicht; entscheidend ist „${target}“.`).join(" "); return finish(wrong.length === 0, wrong.length ? `↺ ${details} ${familyGuidance(exercise)}` : undefined); } if (exercise.type === "sorting") { const target = exercise.correctOrder ?? []; const firstWrong = order.findIndex((item, index) => item !== target[index]); const correct = firstWrong < 0; return finish(correct, `↺ Der erste unstimmige Übergang liegt bei Position ${firstWrong + 1}. Analyse oder Wirkung darf erst nach Beobachtung und Textbeleg folgen. Zielreihenfolge: ${target.join(" → ")}`); } const correct = exercise.correctIds.length === selected.length && exercise.correctIds.every((id) => selected.includes(id)); finish(correct, incorrectChoiceFeedback(exercise, selected)); };
  return <>{exercise.requiresText !== false && <><p className="learning-card__label">Beispieltext</p><blockquote>{exercise.exampleText}</blockquote></>}<h3>{exercise.prompt}</h3>
    {exercise.type === "freeText" ? <label className="epik-free-text">Fachbegriff<input value={text} onChange={(event) => setText(event.target.value)} autoComplete="off"/></label> : exercise.type === "matching" ? <div className="epik-matching"><p>Wählen Sie links einen Begriff und rechts die passende Erklärung.</p><div className="epik-matching-terms">{exercise.terms.map((term) => <button type="button" key={term} aria-pressed={activeTerm === term} className={activeTerm === term ? "is-selected" : ""} onClick={() => setActiveTerm(term)}>{term}</button>)}</div><div className="epik-matching-targets">{exercise.options.map((target) => <button type="button" key={target} onClick={() => { if (activeTerm) { setMapping((old) => ({ ...old, [activeTerm]: target })); setActiveTerm(undefined); } }}>{target}</button>)}</div><ul className="epik-matching-pairs">{Object.entries(mapping).map(([term, target]) => <li key={term}><strong>{term}</strong><span>→</span>{target}</li>)}</ul></div> : exercise.type === "sorting" ? <ol className="epik-sort">{order.map((item, index) => <li key={item}><span>{item}</span><button type="button" aria-label={`${item} nach oben`} disabled={index === 0} onClick={() => setOrder((old) => { const next = [...old]; [next[index - 1], next[index]] = [next[index], next[index - 1]]; return next; })}>Nach oben</button><button type="button" aria-label={`${item} nach unten`} disabled={index === order.length - 1} onClick={() => setOrder((old) => { const next = [...old]; [next[index], next[index + 1]] = [next[index + 1], next[index]]; return next; })}>Nach unten</button></li>)}</ol> : <fieldset className="epik-choice"><legend>{exercise.type === "multipleChoice" ? "Mehrere Antworten sind richtig. Wählen Sie alle zutreffenden Aussagen aus." : "Wählen Sie die passendste Antwort."}</legend>{options.map((option) => <button type="button" key={option} className={selected.includes(option) ? "is-selected" : ""} onClick={() => setSelected((old) => exercise.type === "multipleChoice" ? old.includes(option) ? old.filter((item) => item !== option) : [...old, option] : [option])}>{option}</button>)}</fieldset>}
    {feedback && <p className="epik-feedback" role="status" aria-live="polite">{feedback}</p>}{typeof result === "boolean" ? <Button onClick={() => onDone({ correct: result, answer: selectedAnswerSummary(exercise, selected, text, mapping, order) })}>Weiter</Button> : <Button disabled={exercise.type === "freeText" ? !text.trim() : exercise.type === "matching" ? Object.keys(mapping).length < exercise.terms.length : exercise.type === "sorting" ? false : selected.length === 0} onClick={check}>{deferFeedback ? "Antwort speichern" : exercise.type === "multipleChoice" ? "Auswahl prüfen" : attempts ? "Zweiten Versuch prüfen" : "Antwort prüfen"}</Button>}</>;
}

export function CategoryTraining({ category, onOpenCards }: { category: LearningCategoryId; onOpenCards: () => void }) {
  const [seed, setSeed] = useRunSeed(); const [used, setUsed] = useState<string[]>([]); const [roundOverride, setRoundOverride] = useState<LearningExercise[]>(); const generatedRound = useMemo(() => selectCategoryTrainingRound(category, seed), [category, seed]); const round = roundOverride ?? generatedRound; const [index, setIndex] = useState(0); const [uncertain, setUncertain] = useState<string[]>([]); const [secure, setSecure] = useState<string[]>([]); const exercise = round[index];
  const newRound = () => { const nextSeed = createRunSeed(); const excluded = [...used, ...round.map(({ id }) => id)]; setUsed(excluded); setSeed(nextSeed); setRoundOverride(selectCategoryTrainingRound(category, nextSeed, excluded)); setIndex(0); };
  const repeatUncertain = () => { const nextSeed = createRunSeed(); const base = selectCategoryTrainingRound(category, nextSeed); const related = categoryLearningExercises.filter((item) => item.category === category && item.terms.some((term) => uncertain.includes(term))); setSeed(nextSeed); setRoundOverride([...related, ...base].filter((item, itemIndex, items) => items.findIndex(({ id }) => id === item.id) === itemIndex).slice(0, 6)); setIndex(0); };
  if (index >= 6) return <Card className="epik-task"><h3>Trainingsrunde abgeschlossen</h3><p><strong>Schon sicher:</strong> {secure.join(" · ") || "Noch keine Begriffe"}</p><p><strong>Noch einmal ansehen:</strong> {uncertain.join(" · ") || "Keine"}</p>{uncertain.length > 0 && <Button onClick={repeatUncertain}>Unsichere Begriffe wiederholen</Button>}<Button onClick={newRound}>Mit anderen Aufgaben weiterüben</Button><Button variant="secondary" onClick={onOpenCards}>Passende Lernkarten öffnen</Button></Card>;
  return <Card className="epik-task epik-card-test"><p className="learning-card__label">Übung {index + 1} von 6 · {exerciseTypeLabels[exercise.type]}</p><ExerciseInteraction key={exercise.id} exercise={exercise} seed={seed} onDone={({ correct }) => { const terms = exercise.terms; if (correct) setSecure((old) => [...new Set([...old, ...terms])]); else setUncertain((old) => [...new Set([...old, ...terms])]); setIndex((value) => value + 1); }}/></Card>;
}

export function LearningFinalTest({ onOpenCards }: { onOpenCards: (categoryIndex: number) => void }) {
  const [seed, setSeed] = useRunSeed(); const [exerciseOverride, setExerciseOverride] = useState<LearningExercise[]>(); const generatedExercises = useMemo(() => selectLearningFinalTest(seed), [seed]); const exercises = exerciseOverride ?? generatedExercises; const [index, setIndex] = useState(0); const [results, setResults] = useState<Record<string, ExerciseResult>>({}); const exercise = exercises[index];
  if (index >= 30) { const categoryResults = learningCategoryIds.map((category, categoryIndex) => { const relevant = exercises.filter((item) => item.category === category); const correct = relevant.filter((item) => results[item.id]?.correct).length; return { category, title: learningCategories[categoryIndex].title, status: correct === 2 ? "SICHER" : correct === 1 ? "TEILWEISE SICHER" : "NOCH ÜBEN" }; }); const particularlySecure = categoryResults.filter(({ status }) => status === "SICHER").map(({ title }) => title); const repeat = categoryResults.filter(({ status }) => status !== "SICHER").map(({ title }) => title); const incorrect = exercises.filter((item) => !results[item.id]?.correct); return <Card className="epik-task"><h3>Abschlusstest ausgewertet</h3><p><strong>Besonders sicher:</strong> {particularlySecure.join(" · ") || "Noch kein Analysebereich"}</p><p><strong>Das sollten Sie noch einmal wiederholen:</strong> {repeat.join(" · ") || "Nichts"}</p>{categoryResults.map(({ category, title, status }, categoryIndex) => <div key={category}><strong>{title}: {status}</strong> {status !== "SICHER" && <Button variant="secondary" onClick={() => onOpenCards(categoryIndex)}>Passende Lernkarten öffnen</Button>}</div>)}{incorrect.length > 0 && <section className="epik-test-review" aria-labelledby="test-review-title"><h3 id="test-review-title">Fachliche Auflösung</h3>{incorrect.map((item) => <details key={item.id}><summary>{item.analysisQuestion}</summary><p><strong>Ihre Antwort:</strong> {results[item.id]?.answer || "Keine Antwort"}</p><p><strong>Richtige Antwort:</strong> {item.solution}</p><p>{item.explanation} {familyGuidance(item)}</p></details>)}</section>}<Button onClick={() => { const next = createRunSeed(); setSeed(next); setExerciseOverride(selectLearningFinalTest(next)); setIndex(0); setResults({}); }}>Neuen Abschlusstest starten</Button></Card>; }
  const areaTitle = exercise.category === "integration" ? "Vernetzung ausdrücklich gekennzeichneter Befunde" : learningCategories.find(({ id }) => id === exercise.category)?.title;
  return <Card className="epik-task epik-card-test"><p className="learning-card__label">Abschlusstest · Aufgabe {index + 1} von 30</p><p className="epik-test-area"><strong>Bereich:</strong> {areaTitle}</p><ExerciseInteraction key={exercise.id} exercise={exercise} seed={seed} deferFeedback onDone={(result) => { setResults((old) => ({ ...old, [exercise.id]: result })); setIndex((value) => value + 1); }}/><p className="epik-help">Während des Tests wird nur gespeichert; die fachliche Auflösung folgt nach Aufgabe 30.</p></Card>;
}

