import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { expect,it } from "vitest";
import { masterRoundTasks } from "../src/games/lyrik/data/exercises/masterRound";
import { humanReviewTaskIds,poolExercises } from "../src/games/lyrik/data/exercises/pools";
import { metricExamples } from "../src/games/lyrik/data/meter";
import { microTexts } from "../src/games/lyrik/data/texts/microTexts";

const samples={
 1:Object.entries(humanReviewTaskIds).filter(([id])=>id.startsWith("L1-")).map(([,id])=>id),
 2:Object.entries(humanReviewTaskIds).filter(([id])=>id.startsWith("L2-")).map(([,id])=>id),
 3:Object.entries(humanReviewTaskIds).filter(([id])=>id.startsWith("L3-")).map(([,id])=>id),
} as const;
const taskById=(id:string)=>{const task=poolExercises.find(item=>item.id===id);if(!task)throw new Error(`Review-Aufgabe fehlt: ${id}`);return task;};
const full=(value:string)=>value.replaceAll("\n","<br>");
function taskSection(label:string,id:string){const task=taskById(id),open=task.mechanic==="free";const options=open?"entfällt – offene Analyse":task.options!.map((option,index)=>`${index+1}. ${option}${task.correct?.includes(option)?" **[richtig]**":""}`).join("<br>");const criteria=open?task.criteria!.map(item=>`- [ ] ${item}`).join("\n"):"entfällt";return `### ${label} · Produkt-ID \`${task.id}\`\n\n- **Vollständiger Text:** ${full(task.text)}\n- **Aufgabenstellung:** ${task.prompt}\n- **Antworttyp:** ${open?"offene Analyse mit Selbstkontrolle":task.mechanic}\n- **Alle Antwortoptionen:** ${options}\n- **Richtige Lösung:** ${open?"keine automatisch einzig richtige Lösung":task.correct!.join("; ")}\n- **Mögliche Alternativlösungen:** ${open?"Weitere textnahe Lösungen sind möglich, wenn alle Kriterien erfüllt und Abweichungen begründet werden.":"Keine weitere Option ist nach der präzisierten Aufgabenstellung gleichwertig richtig."}\n- **Feedback bei richtiger Antwort:** ${task.feedback}\n- **Feedback bei typischer Falschantwort:** Die gewählte Aussage trägt die Behauptung nicht vollständig. ${task.feedback}\n- **Cognitive Operation:** \`${task.cognitiveOperation}\`\n- **Domain:** \`${task.domain}\`\n- **Level:** ${task.level}\n- **Didaktische Begründung:** Die Aufgabe verlangt ${task.cognitiveOperation} am konkreten Text und begrenzt unbelegte Schlussfolgerungen.\n- **Kriteriencheck:**\n${criteria}\n- **Musteranalyse:** ${task.sample??"entfällt – geschlossene Aufgabe"}\n- **Hinweis:** ${open?"Die Musteranalyse ist ein Modell, keine Auswendiglösung.":"Distraktoren und Lösung werden vollständig offengelegt."}\n\n`;}
function fullTextCatalog(ids:readonly string[]){return [...new Set(ids.map(id=>taskById(id).text))].map((text,index)=>`**Text ${index+1}**\n\n${full(text)}`).join("\n\n");}
const l3Metric=metricExamples.find(item=>item.id==="meter-trochaeus-verse-e")!;
const transferIds=["transfer-01","transfer-02","transfer-03"];
const transferTasks=transferIds.flatMap(caseId=>poolExercises.filter(item=>item.transferCaseId===caseId).sort((a,b)=>(a.sequenceIndex??0)-(b.sequenceIndex??0)));
const allSampleIds=[...samples[1],...samples[2],...samples[3]];
let markdown=`# Didaktik-Review der Lyrikwerkstatt\n\nStand: 8. September 2026. Die Aufgaben-IDs der bestehenden Stichprobe bleiben erhalten; zusätzlich steht jeweils die stabile Produkt-ID dabei. Lösungen offener Aufgaben sind mögliche Muster, keine einzig richtige Interpretation.\n\n## Finaler Human-Review-Patch\n\n- textspezifische Distraktoren und Feedbacks in der 35er-Stichprobe\n- L1-4-Feedback korrigiert; L1-5 speaker-spezifisch ausgerichtet\n- L2-5 „Pfandbon“ textnäher; L2-6-Vernetzung konkretisiert\n- L2-8-Repetitio-Konvention transparent geklärt\n- L3-4 „Flussbericht“ konkretisiert; L3-12 auf Level 3 korrigiert\n- L3-13/14 grammatisch korrigiert\n- L3-17/18/19 als eigenständige Form-, Sprecher- und Stimmungsaufgaben redigiert\n- L3-20-Belegwahl auf Gruß und adressierte Puppe konzentriert\n- Transferfall 3 vollständig textbezogen redigiert\n- Meisterrunde 8–12 ohne vorausgesetzten Krankenhaus- oder Todeskontext redigiert\n- Transferfall 1 unverändert beibehalten; Transferfall 2 nur auf „äußere Verbesserung zu konkretem Verlust“ präzisiert\n\n## Volltexte der 35 Einzelaufgaben\n\n${fullTextCatalog(allSampleIds)}\n\n`;
for(const level of [1,2,3] as const){markdown+=`## Level ${level}: ${samples[level].length} Aufgaben\n\n`;samples[level].forEach((id,index)=>markdown+=taskSection(`L${level}-${index+1}`,id));}
markdown+=`## L3-16: vollständige metrische Fachannotation\n\n- **Vers:** ${l3Metric.text}\n- **Silbentrennung:** ${l3Metric.syllables.join(" | ")}\n- **Betonungsmuster:** ${l3Metric.stresses.map(value=>value?"— (betont)":"◡ (unbetont)").join(" | ")}\n- **Grundmetrum:** Trochäus\n- **Hebigkeit:** ${l3Metric.feet}-hebig\n- **Abweichung:** ${l3Metric.deviationExplanation}\n- **Kadenz:** männlich / stumpf\n- **Verifikationsstatus:** ${l3Metric.verificationStatus}\n- **Aufgabe, Optionen, Lösung und Feedback:** vollständig im Eintrag L3-16 oben.\n\n## Drei vollständige Transferfälle\n\n`;
for(const caseId of transferIds){const tasks=transferTasks.filter(item=>item.transferCaseId===caseId);markdown+=`### ${tasks[0].title.split(" · ")[0]}\n\n**Vollständiger Text:** ${full(tasks[0].text)}\n\n`;tasks.forEach((task,index)=>markdown+=taskSection(`${caseId} · Schritt ${index+1}/${tasks.length}`,task.id));}
markdown+=`## Meisterrunde: vollständige Texte\n\n### A · Selbstporträt\n\n${full(microTexts.find(item=>item.id==="micro-10")!.text)}\n\n### B · Flussbericht\n\n${full(microTexts.find(item=>item.id==="micro-12")!.text)}\n\n### C · Station vier\n\n${full(microTexts.find(item=>item.id==="micro-16")!.text)}\n\n## Meisterrunde: zwölf Aufgaben\n\n`;
masterRoundTasks.forEach((task,index)=>{const open=task.kind==="free";const options=open?"entfällt – offene Analyse":task.options!.map((option,i)=>`${i+1}. ${option}${task.correct?.includes(option)?" **[richtig]**":""}`).join("<br>");markdown+=`### Meisterrunde ${index+1}/12 · ${task.cognitivePhase}\n\n- **Vollständiger Text:** ${full(task.text!)}\n- **Aufgabenstellung:** ${task.prompt}\n- **Antworttyp:** ${open?"offene Analyse":task.mechanic}\n- **Alle Antwortoptionen:** ${options}\n- **Richtige Lösung / Musteranalyse:** ${task.correct?.join("; ")??task.sample}\n- **Alternativlösungen:** ${open?"Weitere kriteriensichere, textnahe Lösungen sind möglich.":"keine gleichwertige Option"}\n- **Feedback richtig:** ${task.feedback}\n- **Feedback typische Falschantwort:** Eine bloße Benennung, Wortübereinstimmung oder unbelegte Deutung erfüllt die Operation nicht. ${task.feedback}\n- **Operation / Domain / Level:** \`${task.cognitiveOperation}\` / \`${task.domain}\` / ${task.level}\n- **Didaktische Begründung:** Teil der garantierten Progression ${task.cognitivePhase}.\n- **Kriteriencheck:** ${task.criteria?.join("; ")??"entfällt"}\n\n`;});
it("erzeugt die vollständige, referenzgeprüfte Human-Review-Datei",()=>{expect(allSampleIds).toHaveLength(35);expect(new Set(allSampleIds).size).toBe(35);expect(transferTasks).toHaveLength(15);expect(masterRoundTasks).toHaveLength(12);writeFileSync(resolve(process.cwd(),"docs/LYRIK_DIDAKTIK_REVIEW.md"),markdown,"utf8");});
