"use client";
import { useEffect, useState } from "react";
import { hydrateSession } from "../../../core/state/hydrateSession";
import type { GameState } from "../../../core/state/types";
import { PrimarySourceText } from "../../../shared/components/PrimarySourceText";
import { GlossaryHelp } from "../../../shared/components/GlossaryHelp";
import { SceneCharacters } from "../../../shared/components/SceneCharacters";
import { glossaryFor } from "../data/glossary";
import { argumentBlocks, chapter05SourceById, classificationCards, commonErrors, generalChain, hypothesisOptions, interpretationStructure, julietCountercheckOptions, julietFindings, julietHypothesis, julietReverseChain, modernScene, transferArgument, transferChain, transferContext, transferCountercheckOptions, transferEvidence, transferHypotheses, transferRefined } from "../data/chapter_05_content";
import { dramatikSourceLabel } from "../data/sources";
import { assignError, assignJulietRelevance, chooseGeneralHypothesis, chooseTransferHypothesis, classifyStatement, completeChapter05, countercheckJuliet, countercheckTransfer, initialChapter05Session, placeGeneralChain, placeJulietArgument, placeJulietChain, placeStructure, placeTransferArgument, placeTransferChain, refineJuliet, refineTransfer, reviseGeneralHypothesis, selectTransferEvidence, synthesize, type Chapter05Session } from "../mechanics/chapter_05_engine";

type Props={gameState:GameState;onSave:(s:Chapter05Session)=>void;onExit:()=>void;onComplete:(s:Chapter05Session)=>void};
export function Chapter05({gameState,onSave,onExit,onComplete}:Props){
 const[s,setS]=useState(()=>hydrateSession(gameState.decisions.chapter_05,initialChapter05Session,19));const[feedback,setFeedback]=useState("Analyse beschreibt nicht nur, was im Text steht, sondern erklärt dessen Funktion und Bedeutung.");
 useEffect(()=>{document.querySelector(".chapter05-desk")?.scrollIntoView({block:"start",behavior:"auto"})},[s.round]);
 const apply=(result:{valid:boolean;session:Chapter05Session},ok="Der Zusammenhang ist textnah begründet.",bad="Prüfen Sie, welche Denkbewegung hier noch fehlt.")=>{setS(result.session);onSave(result.session);setFeedback(result.valid?ok:bad)};
 const finish=()=>{const r=completeChapter05(s);apply(r,"Die Deutung steht. Das Theater ist bereit.","Schließen Sie zuerst Transfer und Synthese ab.");if(r.valid)onComplete(r.session)};
 return <main className="chapter-shell interpretation-chapter chapter05-workshop"><header className="chapter-header"><button onClick={onExit}>← Theater</button><div><p>Kapitel 5 · Interpretationswerkstatt</p><h1>Was bedeutet das?</h1><small>Analyseergebnisse zu einer Interpretation verbinden</small></div><span>Station {Math.min(s.round,18)} von 18</span></header>
 <section className="interpretation-model" aria-label="Modell des Interpretierens"><span>Textbefund</span><b>→</b><span>Analyse</span><b>→</b><span>Wirkung / Funktion</span><b>→</b><span>Bedeutung</span><b>→</b><span>Deutungshypothese</span><b>→</b><span>Argumentation</span></section>
 <GlossaryHelp entries={glossaryFor("chapter_05")} introTitle="Werkzeuge der Interpretation" seen={s.seenGlossaryIntroductions.includes("chapter_05")||Boolean(gameState.decisions.chapter_05)} onSeen={()=>{const n={...s,seenGlossaryIntroductions:[...new Set([...s.seenGlossaryIntroductions,"chapter_05"])]};setS(n);onSave(n)}}/>
 {s.round>=5&&s.round<=11&&<SceneCharacters sceneId="chapter_05.juliet"/>}{s.round>=12&&<SceneCharacters sceneId="chapter_05.apothecary"/>}
 <section className="chapter05-layout"><aside className="chapter05-brief"><h2>{roundTitles[s.round]??"Abschluss"}</h2><p>{roundInstructions[s.round]??"Die Argumentation ist vollständig."}</p>{s.round>=5&&s.round<=11&&<blockquote>{s.julietHypothesis}</blockquote>}{s.round>=12&&<p className="transfer-label">Die Deutungsprobe · Transfer</p>}</aside><section className="chapter05-desk">
 {s.round===1&&<><SourceCard label="Spieltext · kein Primärtext">{modernScene.map((line,i)=><p key={i}><strong>{line.speaker&&`${line.speaker}: `}</strong>{line.text}</p>)}</SourceCard><AssignBoard items={classificationCards} assigned={s.classifications} zones={[{id:"observation",label:"Textbeobachtung"},{id:"analysis",label:"Analyse"},{id:"interpretation",label:"Interpretation"},{id:"unsupported",label:"nicht ausreichend belegt"}]} onAssign={(id,z)=>apply(classifyStatement(s,id,z),"Die Aussage ist ihrer Funktion entsprechend eingeordnet.")}/></>}
 {s.round===2&&<OrderedBoard title="Bauen Sie die Bedeutungskette." items={generalChain} placed={s.generalChain} onPlace={id=>apply(placeGeneralChain(s,id))}/>}
 {s.round===3&&<ChoiceRound items={hypothesisOptions} onChoose={id=>{const r=chooseGeneralHypothesis(s,id);apply(r,"Diese Hypothese ist deutend und am Ausschnitt prüfbar.",r.quality==="description"?"Das beschreibt den Text, deutet ihn aber noch nicht.":"Diese Aussage reicht über den Ausschnitt hinaus.")}}/>}
 {s.round===4&&<ChoiceRound items={[{id:"keep",text:"Hypothese unverändert beibehalten"},{id:"refine",text:"Hypothese durch den widersprüchlichen zweiten Satz präzisieren"},{id:"reject",text:"Hypothese ohne Prüfung verwerfen"}]} onChoose={id=>apply(reviseGeneralHypothesis(s,id as "keep"|"refine"|"reject"),"Eine Hypothese ist vorläufig und wird am Text weiterentwickelt.")}/>}
 {s.round===5&&<><SourceCard label="Originaltext · Wieland · aus Kapitel 2 wiederverwendet"><p><PrimarySourceText record={chapter05SourceById("c02_transfer_juliette_refusal")}/></p><p><PrimarySourceText record={chapter05SourceById("c02_transfer_capulet_threat")}/></p></SourceCard><AssignBoard items={julietFindings} assigned={s.julietRelevance} zones={[{id:"direct",label:"stützt unmittelbar"},{id:"supplement",label:"ergänzt"},{id:"little",label:"kaum relevant"},{id:"contradicts",label:"widerspricht"}]} onAssign={(id,z)=>{const r=assignJulietRelevance(s,id,z);apply(r,r.accepted?.length&&r.accepted.length>1?"Diese Einordnung ist vertretbar; der Befund kann die Hypothese direkt oder ergänzend stützen.":"Die Relevanz ist auf diese Hypothese bezogen.","Die Aussage kann richtig sein und für diese Hypothese dennoch eine andere Relevanz besitzen.")}}/></>}
 {s.round===6&&<OrderedBoard title="Rekonstruieren Sie die Begründung rückwärts – vom Beleg zur Hypothese." items={[...julietReverseChain].reverse()} placed={s.julietChain} onPlace={id=>apply(placeJulietChain(s,id))}/>}
 {s.round===7&&<ChoiceRound
   items={julietCountercheckOptions}
   onChoose={id=>apply(countercheckJuliet(s,id),"Das Gegenbeispiel widerlegt nicht jede Begrenzung, aber die absolute Formulierung.")}
 />}
 {s.round===8&&<ChoiceRound items={[{id:julietHypothesis,text:julietHypothesis},{id:"unchanged",text:"Juliette ist in dieser Szene völlig machtlos."},{id:"opposite",text:"Juliette besitzt uneingeschränkte Entscheidungsmacht."}]} onChoose={id=>apply(refineJuliet(s,id),"Die Hypothese wurde durch Gegenbelege tatsächlich präzisiert.")}/>} 
 {s.round===9&&<OrderedBoard title="Bauen Sie einen argumentierenden Absatz." items={argumentBlocks} placed={s.julietArgument} onPlace={id=>apply(placeJulietArgument(s,id))}/>}
 {s.round===10&&<AssignBoard items={commonErrors} assigned={s.errorAssignments} zones={[{id:"evidence_without_analysis",label:"Beleg ohne Analyse"},{id:"unsupported_claim",label:"unbelegte Behauptung"},{id:"summary_only",label:"bloße Inhaltsangabe"}]} onAssign={(id,z)=>{const item=commonErrors.find(x=>x.id===id)!;apply(assignError(s,id,z,item.target,commonErrors.length),"Der typische Argumentationsfehler ist erkannt.")}}/>}
 {s.round===11&&<OrderedBoard title="Ordnen Sie die Gesamtstruktur einer Interpretation." items={interpretationStructure.map((text,i)=>({id:`structure_${i}`,text}))} placed={s.structureOrder} onPlace={id=>apply(placeStructure(s,id))}/>}
 {s.round===12&&<><p>{transferContext}</p><SourceCard label={`Originaltext · ${dramatikSourceLabel}`}><p><PrimarySourceText record={chapter05SourceById("c05_transfer_romeo_argument")}/></p><p><PrimarySourceText record={chapter05SourceById("c05_transfer_apothecary_decision")}/></p></SourceCard><div className="choice-grid">{transferEvidence.filter(x=>!s.transferSelected.includes(x.id)).map(x=><button key={x.id} onClick={()=>apply(selectTransferEvidence(s,x.id),"Dieser Befund ist für die Deutung ergiebig.","Der Befund ist textlich richtig, trägt zu dieser konkreten Deutung aber nur wenig bei.")}>{x.text}</button>)}</div></>}
 {s.round===13&&<OrderedBoard title="Verbinden Sie Beleg, Beobachtung, Wirkung und Bedeutung." items={transferChain} placed={s.transferChain} onPlace={id=>apply(placeTransferChain(s,id))}/>}
 {s.round===14&&<ChoiceRound items={transferHypotheses} onChoose={id=>{const r=chooseTransferHypothesis(s,id);apply(r,"Die Hypothese verbindet Handlung, Sprache und Bedeutung.",r.quality==="description"?"Das bleibt eine Inhaltsangabe.":"Der Text widerspricht dieser Vereinfachung.")}}/>}
 {s.round===15&&<ChoiceRound
   items={transferCountercheckOptions}
   onChoose={id=>apply(countercheckTransfer(s,id),"Der Gegenbeleg begrenzt eine vereinfachende Schuldzuweisung.")}
 />}
 {s.round===16&&<ChoiceRound items={[{id:transferRefined,text:transferRefined},{id:"same",text:s.transferHypothesis??"Hypothese unverändert lassen"}]} onChoose={id=>apply(refineTransfer(s,id),"Die Transferhypothese wurde durch den Gegencheck präzisiert.","Revision bedeutet eine tatsächliche, textgestützte Veränderung.")}/>}
 {s.round===17&&<OrderedBoard title="Bauen Sie den Transfer-Absatz." items={transferArgument} placed={s.transferArgument} onPlace={id=>apply(placeTransferArgument(s,id))}/>}
 {s.round===18&&<ChoiceRound items={[{id:"synthesis_complete",text:"Textbefund, Analyse, Wirkung und Bedeutung stützen eine prüfbare Hypothese; Gegenbelege bestimmen ihre Reichweite."},{id:"synthesis_list",text:"Eine Interpretation sammelt möglichst viele richtige Einzelbeobachtungen."}]} onChoose={id=>apply(synthesize(s,id),"Analyseergebnisse sind zu einer differenzierten Interpretation verbunden.")}/>}
 {s.round===19&&<button className="finish-interpretation" onClick={finish}>Kapitel abschließen</button>}
 <p className="interpretation-feedback" role="status">{feedback}</p></section></section></main>;
}
function SourceCard({label,children}:{label:string;children:React.ReactNode}){return <article className="chapter05-source"><small>{label}</small>{children}</article>}
function ChoiceRound({items,onChoose}:{items:readonly {id:string;text:string}[];onChoose:(id:string)=>void}){return <div className="choice-grid">{items.map(item=><button key={item.id} onClick={()=>onChoose(item.id)}>{item.text}</button>)}</div>}
function AssignBoard({items,assigned,zones,onAssign}:{items:readonly {id:string;text:string}[];assigned:Record<string,string>;zones:readonly {id:string;label:string}[];onAssign:(id:string,zone:string)=>void}){const[selected,setSelected]=useState<string|null>(null);return <div className="assign-board"><div className="choice-grid">{items.filter(x=>!assigned[x.id]).map(item=><button key={item.id} aria-pressed={selected===item.id} onClick={()=>setSelected(item.id)}>{item.text}</button>)}</div><fieldset><legend>Ziel für die ausgewählte Karte</legend>{zones.map(zone=><button type="button" key={zone.id} disabled={!selected} onClick={()=>{if(selected){onAssign(selected,zone.id);setSelected(null)}}}>{zone.label}</button>)}</fieldset></div>}
function OrderedBoard({title,items,placed,onPlace}:{title:string;items:readonly {id:string;text:string;kind?:string}[];placed:string[];onPlace:(id:string)=>void}){return <div className="ordered-board"><h3>{title}</h3><ol>{placed.map(id=><li key={id}>{items.find(x=>x.id===id)?.text}</li>)}</ol><div className="choice-grid">{items.filter(x=>!placed.includes(x.id)).reverse().map(item=><button key={item.id} onClick={()=>onPlace(item.id)}><small>{item.kind}</small>{item.text}</button>)}</div></div>}
const roundTitles=["","Textbefund, Analyse oder Deutung?","Vom Befund zur Bedeutung","Eine prüfbare Hypothese","Hypothesen bleiben vorläufig","Juliettes Handlungsspielraum","Begründung rückwärts","Der Gegencheck","Hypothese präzisieren","Argumentieren statt aufzählen","Typische Fehler","Aufbau einer Interpretation","Die Deutungsprobe","Transferkette","Transferhypothese","Gegenbeleg","Transferhypothese präzisieren","Argumentationsabsatz","Synthese"];
const roundInstructions=["","Ordnen Sie Aussagen nach ihrer tatsächlichen Funktion.","Ein Befund erhält erst durch Analyse und Bedeutungsbildung eine interpretative Funktion.","Wählen Sie eine deutende, am Ausschnitt überprüfbare Aussage.","Prüfen Sie, ob der weitere Text die Hypothese bestätigt, einschränkt oder widerlegt.","Welche bekannten Befunde helfen bei genau dieser Hypothese?","Die Rückbindung an den Text bleibt in beiden Denkrichtungen erhalten.","Welche Beobachtung widerspricht der absoluten Formulierung?","Verändern Sie die Hypothese wirklich – nicht nur sprachlich.","Ein Absatz benötigt Behauptung, Beleg, Analyse und Deutung.","Erkennen Sie Brüche in der Argumentation.","Eine Interpretation folgt einer nachvollziehbaren Gesamtbewegung.","Untersuchen Sie nun selbstständig Romeos Gespräch mit dem Apotheker.","Erklären Sie die Funktion des ausgewählten Belegs.","Welche Hypothese ist deutend, gewichtet und textnah?","Suchen Sie eine Beobachtung, die eine zu einfache Lesart begrenzt.","Formulieren Sie die Reichweite der Hypothese genauer.","Führen Sie die Transferanalyse zu einem Absatz zusammen.","Was unterscheidet Interpretation von einer Sammlung richtiger Beobachtungen?"];
