"use client";
import { useState } from "react";
import { hydrateSession } from "../../../core/state/hydrateSession";
import type { GameState } from "../../../core/state/types";
import { CausalChainBoard } from "../../../shared/components/CausalChainBoard";
import { audienceKnowledge, informationDistributionNote } from "../data/chapter_03/audience_knowledge";
import { causalEvents } from "../data/chapter_03/causal_chain";
import { missingInformation, relationalRoles } from "../data/chapter_03/cause_effect";
import { archiveClues } from "../data/chapter_03/evidence";
import { chapter03Finale } from "../data/chapter_03/finale";
import { chapter03Knowledge } from "../data/chapter_03/knowledge_states";
import { chapter03Messages } from "../data/chapter_03/messages";
import { relevanceCards } from "../data/chapter_03/relevance";
import { evidenceClaims, unsupportedFeedback } from "../data/chapter_03/unsupported_claims";
import { assignAudienceKnowledge, assignKnowledge, assignMessage, assignRelationalRole, classifyClaim, completeChapter03, connectCausalEvents, initialChapter03Session, inspectClue, placeCausalEvent, selectMissingInformation, toggleRelevance, type Chapter03Session } from "../mechanics/chapter_03_engine";

type Props={gameState:GameState;onSave:(session:Chapter03Session)=>void;onExit:()=>void;onComplete:(session:Chapter03Session)=>void};
export function Chapter03({gameState,onSave,onExit,onComplete}:Props){
 const stored=gameState.decisions.chapter_03;const[session,setSession]=useState<Chapter03Session>(()=>hydrateSession(stored,initialChapter03Session,9));const[feedback,setFeedback]=useState("Eine entscheidende Nachricht hat Romeo nie erreicht. Finden Sie heraus, warum.");
 const update=(next:Chapter03Session,message:string)=>{setSession(next);onSave(next);setFeedback(message)};
 const message=(id:string,target:string)=>{const r=assignMessage(session,id,target);update(r.session,r.valid?"Die beiden Nachrichtenwege werden sichtbar.":"Prüfen Sie, welche Nachricht Romeo tatsächlich erreicht.")};
 const knowledge=(id:string,target:string)=>{const r=assignKnowledge(session,id,target);update(r.session,r.valid?"Romeos Informationsstand ist klarer.":"Diese Information steht Romeo zu diesem Zeitpunkt nicht zur Verfügung.")};
 const clue=(id:string)=>{const r=inspectClue(session,id);update(r.session,r.valid?"Eine weitere Spur ist gesichert.":"Dieses Objekt gehört nicht zum Ermittlungsfall.")};
 const place=(id:string,index:number)=>{const r=placeCausalEvent(session,id,index);update(r.session,r.valid?"Das Ereignis ist an der passenden Stelle.":"Die Verbindung ist noch nicht schlüssig. Die Karte kann neu eingesetzt werden.")};
 const link=(from:string,to:string)=>{const r=connectCausalEvents(session,from,to);update(r.session,r.valid?"Ursache und Folge sind verbunden.":"Diese Kausalverbindung ist nicht durch die geprüften Sachinformationen gestützt.")};
 const role=(id:string,value:string)=>{const r=assignRelationalRole(session,id,value);update(r.session,r.valid?"Die Rolle stimmt für diese konkrete Beziehung.":"Kausalität ist relational: Betrachten Sie das benachbarte Ereignis.")};
 const missing=(id:string)=>{const r=selectMissingInformation(session,id);update(r.session,r.valid?missingInformation.feedback:"Diese Information hätte Romeos Wissensstand nicht in gleicher Weise verändert.")};
 const audience=(id:string,target:string)=>{const r=assignAudienceKnowledge(session,id,target);update(r.session,r.valid?(r.session.round===8?informationDistributionNote:"Der Wissensstand ist richtig zugeordnet."):"Prüfen Sie, ob Romeo oder nur das Publikum darüber verfügt.")};
 const claim=(id:string,target:string)=>{const r=classifyClaim(session,id,target);update(r.session,r.valid?"Beleg und Vermutung sind getrennt.":unsupportedFeedback)};
 const finish=()=>{const r=completeChapter03(session);update(r.session,r.valid?`${chapter03Finale.message} ${chapter03Finale.next}`:"Wählen Sie nur Informationen, die Romeos weiteres Handeln unmittelbar verständlich machen.");if(r.valid)onComplete(r.session)};
 return <main className="chapter-shell archive-chapter"><header className="chapter-header"><button onClick={onExit}>← Theater</button><div><p>Kapitel 3 · Theaterarchiv</p><h1>Der Brief, der nie ankam</h1></div><span>Ermittlung {session.round} von 9</span></header><section className="archive-layout"><aside className="archive-brief"><p className="task-label">Ermittlungsauftrag</p><h2>Rekonstruieren Sie, wie aus fehlenden Informationen eine Katastrophe entsteht.</h2><p>{instructions[session.round]}</p><div className="archive-progress" aria-label={`Ermittlung ${session.round} von 9`}>{[1,2,3,4,5,6,7,8,9].map((n)=><span className={n<=session.round?"active":""} key={n}>{n}</span>)}</div></aside><section className="archive-table">{session.round===1&&<SortPanel items={chapter03Messages.map((item)=>({id:item.id,text:`${item.label}: ${item.description}`}))} assigned={session.messageAssignments} zones={[{id:"balthasar",label:"Nachricht von Balthasar"},{id:"lorenzo",label:"Nachricht von Lorenzo"}]} onAssign={message}/>} {session.round===2&&<><div className="romeo-file"><span>R</span><strong>Romeos Wissensstand</strong></div><SortPanel items={chapter03Knowledge} assigned={session.knowledgeAssignments} zones={[{id:"romeo",label:"Romeo weiß"},{id:"not_romeo",label:"Romeo weiß nicht"}]} onAssign={knowledge}/></>} {session.round===3&&<ClueRound session={session} onInspect={clue}/>} {session.round===4&&<ChainRound session={session} onPlace={place} onLink={link}/>} {session.round===5&&<RoleRound session={session} onAssign={role}/>} {session.round===6&&<MissingRound onChoose={missing}/>} {session.round===7&&<><SortPanel items={audienceKnowledge} assigned={session.audienceAssignments} zones={[{id:"romeo",label:"Romeo weiß"},{id:"audience",label:"Das Publikum weiß"}]} onAssign={audience}/>{Object.keys(session.audienceAssignments).length===audienceKnowledge.length&&<p className="theory-note">{informationDistributionNote}</p>}</>} {session.round===8&&<SortPanel items={evidenceClaims.map((item)=>({id:item.id,text:item.text,badge:"label" in item?item.label:undefined}))} assigned={session.claimAssignments} zones={[{id:"supported",label:"Textlich gestützt"},{id:"unsupported",label:"Vermutung / nicht gestützt"}]} onAssign={claim}/>} {session.round===9&&<RelevanceRound session={session} onToggle={(id)=>update(toggleRelevance(session,id),"Auswahl vorgemerkt.")} onFinish={finish}/>}<p className="archive-feedback" role="status">{feedback}</p></section></section></main>;
}
function SortPanel({items,assigned,zones,onAssign}:{items:readonly {id:string;text:string;badge?:string}[];assigned:Record<string,string>;zones:readonly {id:string;label:string}[];onAssign:(id:string,target:string)=>void}){const[selected,setSelected]=useState<string|null>(null);return <div className="archive-sort"><div className="archive-cards">{items.filter((item)=>!assigned[item.id]).map((item)=><button key={item.id} aria-pressed={selected===item.id} onClick={()=>setSelected(item.id)}>{item.badge&&<small>{item.badge}</small>}{item.text}</button>)}</div><div className="archive-zones">{zones.map((zone)=><button key={zone.id} onClick={()=>selected&&(onAssign(selected,zone.id),setSelected(null))}><strong>{zone.label}</strong><span>{Object.values(assigned).filter((value)=>value===zone.id).length} Hinweise</span></button>)}</div></div>}
function ClueRound({session,onInspect}:{session:Chapter03Session;onInspect:(id:string)=>void}){return <div className="clue-grid">{archiveClues.map((item)=><button key={item.id} className={session.foundClues.includes(item.id)?"found":""} onClick={()=>onInspect(item.id)}><span aria-hidden="true">{item.symbol}</span><strong>{item.label}</strong><small>{session.foundClues.includes(item.id)?item.information:"Untersuchen"}</small></button>)}</div>}
function ChainRound({session,onPlace,onLink}:{session:Chapter03Session;onPlace:(id:string,index:number)=>void;onLink:(from:string,to:string)=>void}){const ordered=session.orderedEvents.length===causalEvents.length;return <div><CausalChainBoard cards={causalEvents} orderedIds={session.orderedEvents} onPlace={onPlace}/>{ordered&&<div className="causal-links"><h3>Verknüpfungen als Ursache und Folge sichern</h3>{causalEvents.slice(0,-1).map((item,index)=>{const done=session.causalConnections.some((link)=>link.from===item.id);return <button key={item.id} disabled={done} onClick={()=>onLink(item.id,causalEvents[index+1].id)}>{done?"Gesichert: ":"Verbinden: "}{item.label} → {causalEvents[index+1].label}</button>})}</div>}</div>}
function RoleRound({session,onAssign}:{session:Chapter03Session;onAssign:(id:string,role:string)=>void}){return <div className="role-round">{relationalRoles.map((item)=><article key={item.id}><p>{item.label}</p><div><button onClick={()=>onAssign(item.id,"cause")}>Ursache von</button><button onClick={()=>onAssign(item.id,"effect")}>Folge von</button></div>{session.roleAssignments[item.id]&&<small>Gesichert: {session.roleAssignments[item.id]}</small>}</article>)}</div>}
function MissingRound({onChoose}:{onChoose:(id:string)=>void}){return <div className="missing-round"><button onClick={()=>onChoose("missing_plan")}><strong>{missingInformation.text}</strong><small>geprüfte didaktische Zusammenfassung</small></button><button onClick={()=>onChoose("route_detail")}><strong>Der genaue Reiseweg der Nachricht</strong><small>Kontextinformation</small></button></div>}
function RelevanceRound({session,onToggle,onFinish}:{session:Chapter03Session;onToggle:(id:string)=>void;onFinish:()=>void}){return <div className="relevance-round"><div>{relevanceCards.map((item)=><button key={item.id} aria-pressed={session.relevanceSelections.includes(item.id)} onClick={()=>onToggle(item.id)}>{item.text}</button>)}</div><button className="archive-complete" onClick={onFinish}>Zusammenhang archivieren</button>{session.completed&&<div className="archive-result"><strong>{chapter03Finale.message}</strong><span>{chapter03Finale.next}</span></div>}</div>}
const instructions=["","Ordnen Sie die beiden Nachrichten ihren tatsächlichen Wegen zu.","Rekonstruieren Sie zuerst nur, welche entscheidende Information Romeo fehlt.","Untersuchen Sie die Archivobjekte und öffnen Sie die Spurensuche schrittweise.","Ordnen und verknüpfen Sie Information, Ursache, Ereignis und Folge.","Bestimmen Sie die Funktion eines Ereignisses jeweils in seiner konkreten Beziehung.","Welche Information hätte Romeos Wissensstand entscheidend verändert?","Trennen Sie Figurenwissen und Publikumswissen.","Unterscheiden Sie belegbare Sachinformation und Vermutung.","Welche Archivinformationen sind für Romeos weiteres Handeln relevant?"];
