"use client";
import { useState } from "react";
import type { GameState } from "../../../core/state/types";
import { AssetImage } from "../../../shared/components/AssetImage";
import { causalIntro, chain, chainLinks, conflictTypes, escalationCards, finalConnections, goals, introFacts, julietCards, knowledgeCards, situationCards, sourceById } from "../data/chapter_04_content";
import { assignActionReaction, assignCausalIntro, assignConflictType, assignConsequence, assignEscalation, assignFinalRelation, assignJuliet, assignKnowledge, assignSituation, chooseAlternative, chooseTurningPoint, compareConflicts, completeChapter04, distinguishDecision, initialChapter04Session, linkGoal, placeChainEvent, placeMonologueStep, saveIntroGoals, selectIntroFact, setChainRelation, setIncompatibility, toggleMiniAnalysis, type Chapter04Session } from "../mechanics/chapter_04_engine";

type Props={gameState:GameState;onSave:(s:Chapter04Session)=>void;onExit:()=>void;onComplete:(s:Chapter04Session)=>void};
const labels:Record<string,string>={situation:"Ausgangslage",prior:"Vorgeschichte",not_determinable:"Nicht feststellbar",romeo:"Romeo weiß / beabsichtigt",paris:"Paris weiß / deutet",external:"Äußerer Konflikt",internal:"Innerer Konflikt",temporal:"Nur zeitlich nacheinander",causal:"Kausal verbunden",action:"Handlung",reaction:"Reaktion",tension:"Anspannung",escalation:"Zuspitzung",turning:"Wendepunkt",immediate:"Unmittelbare Folge",farther:"Weitere Folge",supports_action:"Spricht für das Handeln",feared_possibility:"Befürchtete Möglichkeit",decision:"Entscheidung",execution:"Ausführung",only_later:"Nur später",causes:"Verursacht",contributes:"Trägt bei"};
const hydrate=(value:unknown):Chapter04Session=>{if(!value||typeof value!=="object")return structuredClone(initialChapter04Session);const stored=value as Partial<Chapter04Session>;return{...structuredClone(initialChapter04Session),...stored,round:stored.completed?15:Math.min(Math.max(stored.round??1,1),15)}};

export function Chapter04({gameState,onSave,onExit,onComplete}:Props){
 const[s,setS]=useState(()=>hydrate(gameState.decisions.chapter_04));const[feedback,setFeedback]=useState("Rekonstruieren Sie, wie aus Interessen und Handlungen ein Punkt ohne Rückkehr entsteht.");
 const update=(next:Chapter04Session,valid:boolean,ok="Die Verbindung ist fachlich tragfähig.",wrong="Prüfen Sie Ursache, Handlung und Textbeleg noch einmal.")=>{setS(next);onSave(next);setFeedback(valid?ok:wrong)};
 const apply=(r:{valid:boolean;session:Chapter04Session},ok?:string,wrong?:string)=>update(r.session,r.valid,ok,wrong);
 const next=(patch:Partial<Chapter04Session>={})=>update({...s,...patch,round:s.round+1},true,"Der nächste Untersuchungsschritt ist geöffnet.");
 const finish=()=>{const r=completeChapter04(s);apply(r,"Der Handlungszusammenhang ist rekonstruiert.","Der Abschluss braucht alle acht Analysebausteine.");if(r.valid)onComplete(r.session)};
 return <main className="chapter chapter-04-causality">
  <header className="chapter-top"><button onClick={onExit}>Zurück zum Theater</button><div><small>Kapitel 4</small><h1>Der Punkt ohne Rückkehr</h1><p>Konflikte, Handlungen und Wendepunkte analysieren</p></div><span className="round-mark">Station {s.round}/15</span></header>
  <section className={`causal-stage ${s.round>=10?"inner-conflict":"tomb-conflict"}`} aria-label={s.round>=10?"Juliettes innerer Konflikt":"Konflikt an der Gruft"}>
   <AssetImage id={s.round>=10?"bg_analysis":"bg_tomb_stage"} className="asset-backdrop" decorative/>
   {s.round>=4&&s.round<10&&<><AssetImage id="character_romeo_thoughtful" className="causal-character romeo"/><AssetImage id="character_paris_calm" className="causal-character paris"/></>}
   {s.round>=10&&<AssetImage id="character_julia_thoughtful" className="causal-character julia"/>}
   <article className="causal-board"><Round s={s} apply={apply} next={next} finish={finish}/></article>
  </section>
  <div className="feedback-bar" role="status" aria-live="polite"><span aria-hidden="true">◆</span>{feedback}</div>
 </main>;
}

type RoundProps={s:Chapter04Session;apply:(r:{valid:boolean;session:Chapter04Session},ok?:string,wrong?:string)=>void;next:(p?:Partial<Chapter04Session>)=>void;finish:()=>void};
function Round({s,apply,next,finish}:RoundProps){
 if(s.round===1)return <><Kicker>Konfliktwerkstatt</Kicker><h2>Welche Informationen erzeugen den Konflikt?</h2><p>Mara möchte zu einer Feier gehen. Ihr Vater erwartet, dass sie zu Hause lernt.</p><ChoiceGrid items={introFacts} selected={s.introRelevant} onPick={id=>apply(selectIntroFact(s,id),"Diese Information bestimmt ein Ziel.","Diese Information ist richtig, aber für den Konflikt nicht entscheidend.")}/>{s.introRelevant.length===2&&<fieldset><legend>Ziele zuordnen</legend><button onClick={()=>apply(saveIntroGoals(s,"party","study"))}>Mara: Feier · Vater: Lernen</button><button onClick={()=>apply(saveIntroGoals(s,"study","party"))}>Mara: Lernen · Vater: Feier</button></fieldset>}</>;
 if(s.round===2)return <Assign title="Äußerer oder innerer Konflikt?" items={conflictTypes} targets={["external","internal"]} done={s.conflictAssignments} onPick={(id,t)=>apply(assignConflictType(s,id,t))}/>;
 if(s.round===3)return <Assign title="Danach – oder deshalb?" intro="Nicht alles, was danach geschieht, geschieht deshalb." items={causalIntro} targets={["temporal","causal"]} done={s.causalIntroAssignments} onPick={(id,t)=>apply(assignCausalIntro(s,id,t),t==="temporal"?"Richtig: Die zeitliche Folge belegt keine Ursache.":undefined)}/>;
 if(s.round===4)return <><Kicker>Gruft der Capulets</Kicker><h2>Die Ausgangslage rekonstruieren</h2><p className="orientation">Juliette gilt als tot und ist in der Familiengruft bestattet. Paris besucht die Gruft. Romeo kehrt heimlich zurück. Paris kennt Romeos wirklichen Grund nicht.</p><Assign items={situationCards} targets={["situation","prior","not_determinable"]} done={s.situationAssignments} onPick={(id,t)=>apply(assignSituation(s,id,t))}/></>;
 if(s.round===5)return <><Kicker>Unterschiedliche Wissensstände</Kicker><Assign title="Was weiß oder deutet die Figur?" items={knowledgeCards} targets={["romeo","paris"]} done={s.knowledgeAssignments} onPick={(id,t)=>apply(assignKnowledge(s,id,t))}/><SourceDrawer ids={["c04_tomb_romeo_order","c04_tomb_paris_view","c04_tomb_romeo_leave"]}/></>;
 if(s.round===6)return <><Kicker>Ziele und Belege</Kicker><h2>Was wollen Romeo und Paris?</h2>{goals.map(g=><fieldset key={g.id}><legend>{g.character}: {g.label}</legend><SourceButton id={g.evidence} onClick={()=>apply(linkGoal(s,g.id,g.evidence))}/><SourceButton id={g.id==="paris_goal"?"c04_tomb_romeo_leave":"c04_tomb_paris_arrest"} onClick={()=>apply(linkGoal(s,g.id,g.id==="paris_goal"?"c04_tomb_romeo_leave":"c04_tomb_paris_arrest"))}/></fieldset>)}{Object.keys(s.goalEvidence).length===2&&<fieldset><legend>Warum entsteht daraus ein Konflikt?</legend><button onClick={()=>apply(setIncompatibility(s,"cannot_both_succeed"))}>Beide Ziele können in dieser Situation nicht zugleich verwirklicht werden.</button><button onClick={()=>apply(setIncompatibility(s,"same_goal"))}>Beide verfolgen dasselbe Ziel.</button></fieldset>}</>;
 if(s.round===7)return <><Kicker>Handlungskette</Kicker><h2>Ereignisse ordnen und Verbindungen begründen</h2><ol className="causal-chain">{s.chainOrder.map(id=><li key={id}>{chain.find(x=>x.id===id)?.label}</li>)}</ol><ChoiceGrid items={chain.filter(x=>!s.chainOrder.includes(x.id))} selected={[]} onPick={id=>apply(placeChainEvent(s,id),"Zeitlich passend eingeordnet.","Diese Karte passt an dieser Stelle noch nicht.")}/>{s.chainOrder.length===chain.length&&<div className="relation-checks">{chainLinks.map(link=><fieldset key={link.from}><legend>{chain.find(x=>x.id===link.from)?.label} → {chain.find(x=>x.id===link.to)?.label}</legend>{["causes","contributes","only_later","not_determinable"].map(t=><button key={t} disabled={Boolean(s.chainRelations[`${link.from}:${link.to}`])} onClick={()=>apply(setChainRelation(s,link.from,link.to,t))}>{labels[t]??"Nicht sicher feststellbar"}</button>)}</fieldset>)}</div>}</>;
 if(s.round===8)return <><Assign title="Handlung oder Reaktion?" items={chain.filter(x=>x.id==="paris_stops"||x.id==="romeo_appeals")} targets={["action","reaction"]} done={s.actionReaction} onPick={(id,t)=>apply(assignActionReaction(s,id,t))}/>{Object.keys(s.actionReaction).length===2&&<fieldset><legend>Welche Alternative wäre an dieser Stelle möglich gewesen?</legend><button onClick={()=>apply(chooseAlternative(s,"paris_allows_exit"),"Möglich, aber nicht tatsächlich geschehen.")}>Paris hätte Romeos Aufforderung folgen und ihn gehen lassen können.</button><button onClick={()=>apply(chooseAlternative(s,"paris_knows_all"))}>Paris kannte bereits alle Hintergründe.</button></fieldset>}</>;
 if(s.round===9)return <><Assign title="Anspannung, Zuspitzung und Wendepunkt" items={escalationCards} targets={["tension","escalation","turning"]} done={s.escalationAssignments} onPick={(id,t)=>apply(assignEscalation(s,id,t))}/>{Object.keys(s.escalationAssignments).length===3&&<fieldset><legend>Wo verändert sich die Handlungsrichtung entscheidend?</legend><SourceButton id="c04_tomb_fight" onClick={()=>apply(chooseTurningPoint(s,"fight"),"Der sprachliche Konflikt wird zur körperlichen Handlung.")}/><SourceButton id="c04_tomb_romeo_leave" onClick={()=>apply(chooseTurningPoint(s,"appeal"))}/></fieldset>}{s.turningPoint&&<Assign title="Folgen differenzieren" items={[{id:"fight",label:"Der Konflikt wird körperlich."},{id:"paris_falls",label:"Paris fällt im Kampf."},{id:"peace",label:"Ohne Kampf wäre sicher Frieden entstanden."}]} targets={["immediate","farther","not_determinable"]} done={s.consequences} onPick={(id,t)=>apply(assignConsequence(s,id,t))}/>}</>;
 if(s.round===10)return <><Kicker>Transfer: Die Entscheidung</Kicker><h2>Juliette allein vor der Phiole</h2><p className="orientation">Juliette soll Paris heiraten, will dies aber nicht. Lorenzos riskanter Plan sieht vor, durch eine Tinktur den Tod vorzutäuschen. Allein vor dem Trinken ringt sie mit Furcht und Entschluss.</p><SourceDrawer ids={["c04_juliet_alone","c04_juliet_no_marriage","c04_juliet_poison_fear","c04_juliet_tomb_fear"]}/><button className="primary-action" onClick={()=>next()}>Den inneren Konflikt untersuchen</button></>;
 if(s.round===11)return <Assign title="Tatsache, Befürchtung oder Entscheidung?" intro="Eine vorgestellte Folge ist noch kein tatsächliches Ereignis." items={julietCards} targets={["situation","supports_action","feared_possibility","decision","execution"]} done={s.julietAssignments} onPick={(id,t)=>apply(assignJuliet(s,id,t),t==="feared_possibility"?"Als Befürchtung erkannt – nicht als eingetretene Folge.":undefined)}/>;
 if(s.round===12)return <><Kicker>Monolog als Handlung</Kicker><h2>Wie entwickelt sich die Entscheidung?</h2><ol className="causal-chain">{s.monologueOrder.map(id=><li key={id}>{julietCards.find(x=>x.id===id)?.label}</li>)}</ol><ChoiceGrid items={julietCards.filter(x=>!s.monologueOrder.includes(x.id))} selected={[]} onPick={id=>apply(placeMonologueStep(s,id),"Der Monolog führt die Entscheidung weiter.","Prüfen Sie die Entwicklung von Situation über Furcht zur Entscheidung.")}/></>;
 if(s.round===13)return <><Kicker>Innerer Wendepunkt</Kicker><h2>Entscheidung und Ausführung trennen</h2><fieldset><legend>Entscheidung</legend><SourceButton id="c04_juliet_drinks" onClick={()=>apply(distinguishDecision(s,"c04_juliet_drinks","c04_juliet_execution"))}/><SourceButton id="c04_juliet_execution" onClick={()=>apply(distinguishDecision(s,"c04_juliet_execution","c04_juliet_drinks"))}/></fieldset><fieldset><legend>Ausführung</legend><SourceDrawer ids={["c04_juliet_execution"]}/></fieldset></>;
 if(s.round===14)return <><Kicker>Konflikte vergleichen</Kicker><h2>Was unterscheidet die beiden Verläufe?</h2><button onClick={()=>apply(compareConflicts(s,"external_vs_internal"))}>An der Gruft treffen unvereinbare Ziele verschiedener Figuren aufeinander; in Juliettes Monolog stehen Handlungswille und Befürchtungen innerhalb einer Figur gegeneinander.</button><button onClick={()=>apply(compareConflicts(s,"both_external"))}>Beide Konflikte entstehen nur zwischen zwei anwesenden Figuren.</button></>;
 return <><Kicker>Abschlussrekonstruktion</Kicker><h2>Nicht alles, was danach geschieht, geschieht deshalb.</h2><Assign title="Kausale Beziehungen prüfen" items={finalConnections} targets={["causes","contributes","only_later"]} done={s.finalAssignments} onPick={(id,t)=>apply(assignFinalRelation(s,id,t))}/>{Object.keys(s.finalAssignments).length===finalConnections.length&&<fieldset><legend>Mini-Analyse zusammensetzen</legend><div className="analysis-puzzle">{[["situation","Ausgangslage"],["goal","Ziel"],["conflict","Konflikt"],["action","Handlung"],["reaction","Reaktion"],["turning","Wendepunkt oder begründet keiner"],["consequence","Folge"],["evidence","Textbeleg"]].map(([id,label])=><button key={id} aria-pressed={s.miniAnalysis.includes(id)} onClick={()=>apply({valid:true,session:toggleMiniAnalysis(s,id)},"Baustein im Analysebuch gesichert.")}>{label}</button>)}</div><button className="primary-action" onClick={finish}>Handlungsbuch restaurieren</button></fieldset>}</>;
}

function Kicker({children}:{children:React.ReactNode}){return <p className="chapter-kicker">{children}</p>}
function ChoiceGrid({items,selected,onPick}:{items:readonly {id:string;label:string}[];selected:string[];onPick:(id:string)=>void}){return <div className="choice-grid">{items.map(x=><button key={x.id} disabled={selected.includes(x.id)} onClick={()=>onPick(x.id)}>{x.label}</button>)}</div>}
function Assign({title,intro,items,targets,done,onPick}:{title?:string;intro?:string;items:readonly {id:string;label:string}[];targets:string[];done:Record<string,string>;onPick:(id:string,target:string)=>void}){return <div className="assignment-board">{title&&<h2>{title}</h2>}{intro&&<p>{intro}</p>}{items.map(item=><fieldset key={item.id}><legend>{item.label}</legend>{targets.map(target=><button key={target} disabled={Boolean(done[item.id])} onClick={()=>onPick(item.id,target)}>{labels[target]??target.replaceAll("_"," ")}</button>)}</fieldset>)}</div>}
function SourceButton({id,onClick}:{id:string;onClick:()=>void}){const source=sourceById(id);return <button className="source-card" onClick={onClick}><small>Originaltext · Wieland-Ausgabe</small><span>{source?.text}</span></button>}
function SourceDrawer({ids}:{ids:string[]}){return <details className="source-drawer"><summary>Geschützte Textbelege öffnen</summary>{ids.map(id=>{const source=sourceById(id);return <blockquote key={id}><small>ORIGINALTEXT · {source?.source_location}</small>{source?.text}</blockquote>})}</details>}
