"use client";

import { useState } from "react";
import type { ReactNode } from "react";
import { hydrateSession } from "../../../core/state/hydrateSession";
import type { GameState } from "../../../core/state/types";
import { AssetImage } from "../../../shared/components/AssetImage";
import { certaintyClaims, practiceSegments, practiceTextA, primaryById, signalPrompts, situationEvidence, situationLabels, streetSituationCards, transferSituationGroups, type Certainty, type SituationField } from "../data/chapter_01_content";
import { PrimarySourceText } from "../../../shared/components/PrimarySourceText";
import { GlossaryHelp } from "../../../shared/components/GlossaryHelp";
import { SceneCharacters } from "../../../shared/components/SceneCharacters";
import { glossaryFor } from "../data/glossary";
import { advanceChapter01, checkStreetSituation, checkTransferAnalysis, classifyClaim, draftSituation, identifySignal, initialChapter01Session, linkSituationEvidence, toggleTransferStatement, type Chapter01Session } from "../mechanics/chapter_01_engine";

const certaintyLabels:Record<Certainty,string>={explicit:"Eindeutig belegt",inference:"Plausibel erschließbar",unsupported:"Nicht belegt"};

export function Chapter01({gameState,onSave,onExit,onComplete}:{gameState:GameState;onSave:(session:Chapter01Session)=>void;onExit:()=>void;onComplete:(session:Chapter01Session)=>void}) {
  const [session,setSession]=useState(()=>hydrateSession(gameState.decisions.chapter_01,initialChapter01Session,7));
  const [feedback,setFeedback]=useState("Das beschädigte Regiebuch wartet auf seine Rekonstruktion.");
  const update=(next:Chapter01Session)=>{setSession(next);onSave(next)};
  const finish=(next:Chapter01Session)=>{update(next);if(next.completed)onComplete(next)};
  return <main className={`chapter-shell chapter-one round-${session.round}`}>
    <header className="chapter-header"><button onClick={onExit}>← Theater</button><div><p>Kapitel 1 · Regiepult</p><h1>Das zerrissene Regiebuch</h1></div><span>Szene {session.round} von 7</span></header>
    <section className="chapter-one-scene">
      <AssetImage id="bg_analysis_room" className="chapter-one-background" decorative loading="eager"/>
      <aside className="lorenzo-guide"><AssetImage id="character_lorenzo_letter" className="lorenzo-image" fallback={<span className="lorenzo-fallback">Bruder Lorenzo</span>}/></aside>
      <section className="regiebuch-workspace" aria-label="Historisches Regiepult">
        {session.round===1&&<Opening onNext={()=>update(advanceChapter01(session))}/>}
        {session.round===2&&<SignalRound session={session} onChoose={(id,kind)=>{const result=identifySignal(session,id,kind);update(result.session);setFeedback(result.valid?signalPrompts[session.signalStep].feedback:"Prüfen Sie, ob die markierte Stelle gesprochen wird oder eine andere Funktion erfüllt.")}}/>}
        {session.round===3&&<><GlossaryHelp entries={glossaryFor("chapter_01").filter(entry=>["text_finding","inference","not_determinable"].includes(entry.id))} introTitle="Textbefund, Erschließung und Nicht-Belegtes" seen={session.seenGlossaryIntroductions.includes("chapter_01_evidence")} onSeen={()=>update({...session,seenGlossaryIntroductions:[...new Set([...session.seenGlossaryIntroductions,"chapter_01_evidence"])]})}/><CertaintyRound session={session} onPlace={(id,target)=>{const result=classifyClaim(session,id,target);update(result.session);setFeedback(result.valid?target==="inference"?"Diese Aussage ist begründbar, aber nicht unmittelbar genannt.":target==="unsupported"?"Eine mögliche Vorstellung darf nicht als Textaussage ausgegeben werden.":"Diese Aussage ist unmittelbar durch den Text abgesichert.":"Prüfen Sie, ob der Wortlaut die Aussage ausdrücklich trägt oder nur eine Deutung ermöglicht.")}}/></>}
        {session.round===4&&<ShakespeareOpening onNext={()=>update(advanceChapter01(session))}/>}
        {session.round===5&&<><GlossaryHelp entries={glossaryFor("chapter_01")} introTitle="Was gehört zu einer Situationsanalyse?" seen={session.seenGlossaryIntroductions.includes("chapter_01")} onSeen={()=>update({...session,seenGlossaryIntroductions:[...new Set([...session.seenGlossaryIntroductions,"chapter_01"])]})}/><SceneCharacters sceneId="chapter_01.street"/><SituationRound session={session} onPlace={(id,target)=>update(draftSituation(session,id,target))} onCheck={()=>{const result=checkStreetSituation(session);update(result.session);setFeedback(result.valid?"Die Situationsangaben sind als Gesamtbild tragfähig.":`Prüfen Sie die Zuordnung in diesen Bereichen erneut: ${result.problemFields.map(field=>situationLabels[field]).join(", ")}.`)}}/></>}
        {session.round===6&&<EvidenceRound onCheck={(textId,observation,situation)=>{const result=linkSituationEvidence(session,textId,observation,situation);update(result.session);setFeedback(result.valid?"Textstelle, Beobachtung und Situationsinformation sind schlüssig verbunden.":"Die Verbindung springt zu weit. Bleiben Sie zunächst bei der beobachtbaren Gesprächshandlung.")}}/>}
        {session.round===7&&<><SceneCharacters sceneId="chapter_01.capulet_paris"/><TransferRound session={session} onToggle={(field,id)=>update(toggleTransferStatement(session,field,id))} onCheck={()=>{const result=checkTransferAnalysis(session,transferSituationGroups);finish(result.session);const fields=Object.entries(result.fieldResults).filter(([,status])=>status!=="complete").map(([field])=>situationLabels[field as SituationField]);setFeedback(result.valid?"Das Regiebuch ist wieder lesbar.":`Ein Teil ist bereits tragfähig. Prüfen Sie noch: ${fields.join(", ")}.`)}}/></>}
        <p className="chapter-feedback" role="status" aria-live="polite">{feedback}</p>
      </section>
    </section>
  </main>;
}

function Lorenzo({children}:{children:ReactNode}){return <div className="lorenzo-speech"><strong>Bruder Lorenzo</strong><p>{children}</p></div>}
function Opening({onNext}:{onNext:()=>void}){return <div className="regiebuch-scene opening-scene"><Lorenzo>Da seid Ihr ja. Ein Regiebuch hält fest, wer spricht, wer erscheint, was auf der Bühne geschieht und unter welchen Bedingungen eine Szene beginnt. Doch dieses Exemplar ist beschädigt. Bevor wir Shakespeares Bühne wieder zum Leben erwecken, müsst Ihr lernen, ihre Spuren zu lesen.</Lorenzo><AssetImage id="object_script" className="regiebuch-object"/><button className="chapter-primary-action" onClick={onNext}>Regiebuch untersuchen</button></div>}

function PracticeManuscript({onChoose}:{onChoose?:(id:string,kind:"speaker"|"stage_direction"|"speech")=>void}){return <div className="practice-spread"><article><span className="source-badge practice">Übungstext · nicht von Shakespeare</span><h3>Text A · erzählender Text</h3><p>{practiceTextA}</p></article><article className="practice-manuscript"><span className="source-badge practice">Übungstext · nicht von Shakespeare</span><h3>Text B · dramatischer Text</h3>{practiceSegments.map(segment=>onChoose?<button key={segment.id} onClick={()=>onChoose(segment.id,segment.kind)}>{segment.text}</button>:<p key={segment.id}>{segment.text}</p>)}</article></div>}

function SignalRound({session,onChoose}:{session:Chapter01Session;onChoose:(id:string,kind:"speaker"|"stage_direction"|"speech")=>void}){const prompt=signalPrompts[session.signalStep];return <div className="regiebuch-scene"><div className="task-slip"><span>Textsignale lesen</span><h2>Wer erzählt hier eigentlich?</h2><p>Ein Drama vermittelt vieles durch das, was Figuren sagen und auf der Bühne tun.</p><strong>{prompt.prompt}</strong></div><PracticeManuscript onChoose={onChoose}/></div>}

function CertaintyRound({session,onPlace}:{session:Chapter01Session;onPlace:(id:string,target:Certainty)=>void}){const [selected,setSelected]=useState<string|null>(null);return <div className="regiebuch-scene"><div className="task-slip"><h2>Was wissen wir wirklich?</h2><p>Ordnen Sie jede Aussage danach ein, wie sicher sie sich aus Text B ableiten lässt.</p></div><PracticeManuscript/><div className="loose-pages">{certaintyClaims.filter(c=>!session.certaintyAssignments[c.id]).map(c=><button key={c.id} aria-pressed={selected===c.id} onClick={()=>setSelected(c.id)}>{c.text}</button>)}</div><div className="certainty-racks">{Object.entries(certaintyLabels).map(([id,label])=><button key={id} disabled={!selected} onClick={()=>selected&&onPlace(selected,id as Certainty)}>{label}<small>{Object.values(session.certaintyAssignments).filter(v=>v===id).length} eingeordnet</small></button>)}</div></div>}

function ShakespeareOpening({onNext}:{onNext:()=>void}){return <div className="regiebuch-scene"><Lorenzo>Genug geübt. Dieses Regiebuch gehört zu William Shakespeares „Romeo und Juliette“. Ihr müsst das Stück nicht kennen. Vor jeder Untersuchung erhaltet Ihr genau die Informationen, die Ihr benötigt. Alles Weitere müsst Ihr aus dem Text selbst erschließen.</Lorenzo><article className="context-leaf"><span>Orientierung: Verona</span><p>Die Handlung spielt überwiegend in Verona. Dort stehen sich zwei vornehme Familien seit langer Zeit feindlich gegenüber: die Montagues und die Capulets. Romeo ist der Sohn Montagues. Julietta ist die Tochter Capulets. Die Feindschaft zwischen beiden Häusern bildet einen wichtigen Hintergrund des Dramas.</p></article><div className="method-sequence" aria-label="Methodischer Ablauf"><strong>Textbeobachtung</strong><span>↓</span><strong>Erschließen</strong><span>↓</span><strong>Deuten</strong></div><button className="chapter-primary-action" onClick={onNext}>Shakespeare-Regiebuch öffnen</button></div>}

function PrimaryLeaf({ids}:{ids:string[]}){return <article className="primary-leaf"><span className="source-badge original">Originaltext · Wieland-Ausgabe</span>{ids.map(id=>{const source=primaryById(id);return <p key={id} className={`source-${source.fragment_type}`}><PrimarySourceText record={source}/></p>})}</article>}

function SituationRound({session,onPlace,onCheck}:{session:Chapter01Session;onPlace:(id:string,target:SituationField)=>void;onCheck:()=>void}){const [selected,setSelected]=useState<string|null>(null);return <div className="regiebuch-scene"><div className="task-slip"><h2>Eine Szene beginnt vor dem ersten Satz</h2><p>Zu Beginn des Dramas besteht die Feindschaft bereits. Auch Bedienstete beider Häuser tragen den Streit aus. Ordnen Sie zunächst alle Karten zu. Die Auswertung erfolgt erst bei der Gesamtprüfung.</p></div><PrimaryLeaf ids={["c01_street_location","c01_street_opening_direction"]}/><div className="loose-pages">{streetSituationCards.map(c=><button key={c.id} aria-pressed={selected===c.id} onClick={()=>setSelected(c.id)}>{c.text}<small>{session.situationDraft[c.id]?`Zugeteilt: ${situationLabels[session.situationDraft[c.id]]}`:"Noch nicht zugeteilt"}</small></button>)}</div><div className="situation-ledger">{Object.entries(situationLabels).map(([id,label])=><button key={id} disabled={!selected} onClick={()=>{if(selected){onPlace(selected,id as SituationField);setSelected(null)}}}><strong>{label}</strong><small>{Object.values(session.situationDraft).filter(v=>v===id).length} vorgemerkt</small></button>)}</div><button className="chapter-primary-action" disabled={Object.keys(session.situationDraft).length!==streetSituationCards.length} onClick={onCheck}>Auswahl prüfen</button></div>}

function EvidenceRound({onCheck}:{onCheck:(textId:string,observation:string,situation:string)=>void}){const [text,setText]=useState("");const [observation,setObservation]=useState("");const [situation,setSituation]=useState("");const observations=[situationEvidence.observation,"Sampson ist feige.","Sampson kennt den Ausgang des Streits."];const situations=[situationEvidence.situation,"Sampson wird den Streit gewinnen.","Romeo lenkt die Begegnung."];return <div className="regiebuch-scene"><div className="task-slip"><h2>Figurenrede ergänzt die Situation</h2><p>Verbinden Sie Textstelle, beobachtbare Handlung und eine Information über die Situation.</p></div><PrimaryLeaf ids={["c01_street_provocation_1","c01_street_provocation_2","c01_street_provocation_3"]}/><div className="evidence-chain"><fieldset><legend>1 · Textstelle</legend>{["c01_street_provocation_1","c01_street_provocation_2"].map(id=><button aria-pressed={text===id} key={id} onClick={()=>setText(id)}>{primaryById(id).text}</button>)}</fieldset><fieldset><legend>2 · Beobachtung</legend>{observations.map(v=><button aria-pressed={observation===v} key={v} onClick={()=>setObservation(v)}>{v}</button>)}</fieldset><fieldset><legend>3 · Information über die Situation</legend>{situations.map(v=><button aria-pressed={situation===v} key={v} onClick={()=>setSituation(v)}>{v}</button>)}</fieldset></div><button className="chapter-primary-action" disabled={!text||!observation||!situation} onClick={()=>onCheck(text,observation,situation)}>Verbindung in das Regiebuch eintragen</button></div>}

function TransferRound({session,onToggle,onCheck}:{session:Chapter01Session;onToggle:(field:SituationField,id:string)=>void;onCheck:()=>void}){return <div className={`regiebuch-scene transfer-scene ${session.completed?"restored":""}`}><div className="task-slip"><span>Die Probe</span><h2>Situation selbstständig rekonstruieren</h2><p>Paris ist ein junger Adeliger und mit dem Fürsten von Verona verwandt. Er interessiert sich für Capulets Tochter Julietta und wendet sich an ihren Vater.</p><strong>Markieren Sie alle Informationen, die zum Ausschnitt gehören. Die Zahl der passenden Aussagen bleibt offen.</strong></div><PrimaryLeaf ids={["c01_transfer_direction","c01_transfer_capulet_peace","c01_transfer_paris_request","c01_transfer_capulet_age","c01_transfer_paris_reply"]}/><div className="situation-multiselect">{transferSituationGroups.map(group=><fieldset key={group.field} className={session.transferConfirmed.includes(group.field)?"confirmed":""}><legend>{situationLabels[group.field]}</legend>{group.options.map(option=><label key={option.id} className={session.transferSelections[group.field]?.includes(option.id)?"selected":""}><input type="checkbox" checked={session.transferSelections[group.field]?.includes(option.id)??false} onChange={()=>onToggle(group.field,option.id)}/><span>{option.text}</span>{option.evidenceKind==="primary"&&session.transferSelections[group.field]?.includes(option.id)&&<small>Textbeleg im eingeblendeten Originaltext prüfen.</small>}</label>)}</fieldset>)}</div><button className="chapter-primary-action" onClick={onCheck}>Situationsanalyse prüfen</button>{session.completed&&<div className="restored-message"><strong>BEOBACHTEN · BELEGEN · ERSCHLIESSEN · DEUTEN</strong><p>Eine Szene beginnt nicht mit ihrem ersten Satz. Fehlende Informationen dürfen nicht erfunden werden.</p><Lorenzo>Das Regiebuch ist wieder lesbar. Doch Namen auf einer Seite sind noch keine Figuren. Wer sind diese Menschen, und was wollen sie voneinander?</Lorenzo></div>}</div>}
