"use client";
import { useState } from "react";
import { hydrateSession } from "../../../core/state/hydrateSession";
import type { GameState } from "../../../core/state/types";
import type { StagingDecision } from "../data/staging";
import { argumentBlocks } from "../data/chapter_05/argument_chain";
import { countercheckExplanation, escalationStructure, oneSidedClaim } from "../data/chapter_05/countercheck";
import { analysisResults, relevanceFeedback } from "../data/chapter_05/evidence_selection";
import { interpretationHypothesis, refinedHypothesis } from "../data/chapter_05/hypothesis";
import { interpretationLinks } from "../data/chapter_05/interpretation_links";
import { stagingReviewFeedback } from "../data/chapter_05/staging_review";
import { evidenceMaxim, interpretationClaims, overreachFeedback } from "../data/chapter_05/unsupported_claims";
import { generalRehearsalSource } from "../data/chapter_04/scene_source";
import { attachEvidence, classifyInterpretationClaim, classifyRelevance, completeChapter05, countercheck, explainObservation, initialChapter05Session, loadStagingReview, placeArgumentBlock, reviseStagingOnce, assignEscalationLevel, type Chapter05Session } from "../mechanics/chapter_05_engine";
type Props={gameState:GameState;onSave:(s:Chapter05Session)=>void;onExit:()=>void;onComplete:(s:Chapter05Session)=>void};
export function Chapter05({gameState,onSave,onExit,onComplete}:Props){const stored=gameState.decisions.chapter_05;const[s,setS]=useState<Chapter05Session>(()=>hydrateSession(stored,initialChapter05Session,8));const[feedback,setFeedback]=useState("Sie haben viel herausgefunden. Aber nicht jede richtige Beobachtung hilft Ihnen bei dieser Deutung.");const update=(n:Chapter05Session,m:string)=>{setS(n);onSave(n);setFeedback(m)};const staging=(gameState.stagingDecisions.chapter_04??{}) as Record<string,StagingDecision>;
 const relevance=(id:string,l:string)=>{const r=classifyRelevance(s,id,l);update(r.session,relevanceFeedback[r.actual!])};const explain=()=>{const l=interpretationLinks[0];const r=explainObservation(s,l.observation_id,l.explanation_id,l.hypothesis_relation);update(r.session,r.valid?l.feedback:"Beobachtung allein ist noch keine Interpretation.")};const evidence=(id:string)=>{const r=attachEvidence(s,id);update(r.session,r.valid?"Analyseergebnis, Primärtextbeleg, Erklärung und Hypothesenbezug sind verbunden.":"Dieser Primärtextdatensatz stützt die gewählte Beobachtung nicht.")};const claim=(id:string,t:string)=>{const r=classifyInterpretationClaim(s,id,t);update(r.session,r.valid?(r.session.round===5?evidenceMaxim.join(" "):t==="unsupported"?overreachFeedback:"Die Reichweite der Aussage ist textnah bestimmt."):overreachFeedback)};const level=(id:string,t:string)=>{const r=assignEscalationLevel(s,id,t);update(r.session,r.valid?"Die bekannte Analyseebene ist eingeordnet.":"Diese Erkenntnis gehört auf eine andere Ebene.")};const place=(id:string)=>{const r=placeArgumentBlock(s,id);update(r.session,r.valid?"Der Argumentationsgang wächst.":"Die Kette benötigt Hypothese, Analyse, Beleg, Erklärung und Rückbindung in dieser Funktion.")};const finish=()=>{const r=completeChapter05(s);update(r.session,r.valid?"Die Deutung steht. Das Theater ist bereit.":"Prüfen Sie Ihre Inszenierung und speichern Sie genau eine Revision.");if(r.valid)onComplete(r.session)};
 return <main className="chapter-shell interpretation-chapter"><header className="chapter-header"><button onClick={onExit}>← Theater</button><div><p>Kapitel 5 · restauriertes Regiepult</p><h1>Die Deutungsprobe</h1></div><span>Probe {s.round} von 8</span></header><section className="interpretation-stage" aria-label="Bühne im Hintergrund"><span>P</span><i>◆</i><span>R</span></section><section className="interpretation-layout"><aside className="hypothesis-card"><p className="task-label">Deutungshypothese</p><blockquote>{s.hypothesisRefined?refinedHypothesis:interpretationHypothesis.text}</blockquote><p>{instructions[s.round]}</p><div className="interpretation-progress">{[1,2,3,4,5,6,7,8].map(n=><span className={n<=s.round?"active":""} key={n}>{n}</span>)}</div></aside><section className="interpretation-desk">{s.round===1&&<RelevanceRound s={s} onAssign={relevance}/>} {s.round===2&&<MeaningRound onChoose={explain}/>} {s.round===3&&<EvidenceRound onChoose={evidence}/>} {s.round===4&&<Sort items={interpretationClaims} assigned={s.claimAssignments} zones={[{id:"supported",label:"textlich begründbar"},{id:"unsupported",label:"geht über den Text hinaus"},{id:"contradicts",label:"widerspricht dem Verlauf"}]} onAssign={claim}/>} {s.round===5&&<Sort items={escalationStructure} assigned={s.escalationAssignments} zones={[{id:"perception",label:"Wahrnehmung"},{id:"goal",label:"Gesprächsziel"},{id:"reaction",label:"Reaktion"},{id:"consequence",label:"Konsequenz"}]} onAssign={level}/>} {s.round===6&&<Countercheck onChoose={(refine)=>{const r=countercheck(s,oneSidedClaim,refine);update(r.session,r.valid?countercheckExplanation:"Die Aussage kontrolliert ihre Reichweite noch nicht.")}}/>} {s.round===7&&<ArgumentRound s={s} onPlace={place}/>} {s.round===8&&<StagingReview s={s} decisions={staging} onLoad={()=>update(loadStagingReview(s,staging),"Die Regieentscheidungen aus der Generalprobe sind geladen.")} onRevise={(d)=>{const r=reviseStagingOnce(s,d);update(r.session,r.valid?"Genau eine zentrale Regieentscheidung wurde reflektiert und revidiert.":"Eine weitere Revision ist in dieser Deutungsprobe nicht vorgesehen.")}} onFinish={finish}/>}<p className="interpretation-feedback" role="status">{feedback}</p></section></section></main>}
function RelevanceRound({s,onAssign}:{s:Chapter05Session;onAssign:(id:string,l:string)=>void}){const[selected,setSelected]=useState<string|null>(null);return <div className="relevance-board"><div>{analysisResults.filter(x=>!s.relevanceAssignments[x.id]).map(x=><button key={x.id} aria-pressed={selected===x.id} onClick={()=>setSelected(x.id)}>{x.text}</button>)}</div><div>{[{id:"high_relevance",label:"besonders relevant"},{id:"medium_relevance",label:"ergänzend"},{id:"low_relevance",label:"für diese Deutung kaum relevant"}].map(z=><button key={z.id} onClick={()=>selected&&(onAssign(selected,z.id),setSelected(null))}>{z.label}</button>)}</div></div>}
function MeaningRound({onChoose}:{onChoose:()=>void}){const l=interpretationLinks[0];return <div className="meaning-chain"><article><small>Beobachtung</small><strong>{analysisResults.find(x=>x.id===l.observation_id)?.text}</strong></article><button onClick={onChoose}><small>Erklärung ergänzen</small>{l.explanation}<span>Bezug: unterstützt die Deutungshypothese</span></button></div>}
function EvidenceRound({onChoose}:{onChoose:(id:string)=>void}){return <div className="evidence-drawer">{interpretationLinks.map(l=>{const source=generalRehearsalSource.find(x=>x.id===l.evidence_reference)!;return <button key={l.id} onClick={()=>onChoose(source.id)}><small>Originaltext · {source.speaker??"Regieanweisung"}</small><span>{source.text}</span></button>})}</div>}
function Sort({items,assigned,zones,onAssign}:{items:readonly {id:string;text:string}[];assigned:Record<string,string>;zones:readonly {id:string;label:string}[];onAssign:(id:string,t:string)=>void}){const[selected,setSelected]=useState<string|null>(null);return <div className="interpretation-sort"><div>{items.filter(x=>!assigned[x.id]).map(x=><button aria-pressed={selected===x.id} key={x.id} onClick={()=>setSelected(x.id)}>{x.text}</button>)}</div><div>{zones.map(z=><button key={z.id} onClick={()=>selected&&(onAssign(selected,z.id),setSelected(null))}>{z.label}</button>)}</div>{items===interpretationClaims&&Object.keys(assigned).length===items.length&&<p>{evidenceMaxim.join(" ")}</p>}</div>}
function Countercheck({onChoose}:{onChoose:(r:boolean)=>void}){return <div className="countercheck"><h3>Welche Aussage wäre zu einseitig?</h3><button onClick={()=>onChoose(true)}>{oneSidedClaim}<small>Hypothese anschließend präzisieren</small></button><button onClick={()=>onChoose(false)}>Beide Figuren tragen auf unterschiedliche Weise zur Eskalation bei.</button></div>}
function ArgumentRound({s,onPlace}:{s:Chapter05Session;onPlace:(id:string)=>void}){return <div className="argument-puzzle"><ol>{s.argumentOrder.map(id=><li key={id}>{argumentBlocks.find(x=>x.id===id)?.text}</li>)}</ol><div>{argumentBlocks.filter(x=>!s.argumentOrder.includes(x.id)).map(x=><button key={x.id} onClick={()=>onPlace(x.id)}><small>{x.type}</small>{x.text}</button>)}</div></div>}
function StagingReview({s,decisions,onLoad,onRevise,onFinish}:{s:Chapter05Session;decisions:Record<string,StagingDecision>;onLoad:()=>void;onRevise:(d:StagingDecision)=>void;onFinish:()=>void}){if(!s.stagingReviewLoaded)return <button className="load-staging" onClick={onLoad}>Regieentscheidungen aus Kapitel 4 auf das Regiepult legen</button>;const list=Object.values(decisions);const conflicts=list.some(d=>d.value.toLowerCase().includes("offensiv"));return <div className="staging-review"><p>{conflicts?stagingReviewFeedback:"Ihre gespeicherten Regieentscheidungen sind mit der präzisierten Deutung grundsätzlich vereinbar. Prüfen Sie dennoch eine zentrale Entscheidung bewusst."}</p>{list.map(d=><article key={d.id}><strong>{d.dimension}: {d.value}</strong><small>{d.reasoningId}</small>{s.revisionCount===0&&<button onClick={()=>onRevise({...d,value:d.dimension==="distance"?"größere Anfangsdistanz":d.value})}>Diese Entscheidung revidieren</button>}</article>)}<button className="finish-interpretation" onClick={onFinish}>Deutung und Inszenierung abschließen</button></div>}
const instructions=["","Welche bekannten Analyseergebnisse tragen zu dieser Deutung bei?","Was bedeutet die Beobachtung für die Deutungshypothese?","Welcher bestehende Primärtextdatensatz stützt den Interpretationslink?","Ist die Aussage textnah, zu weitgehend oder widersprüchlich?","Ordnen Sie die bekannten Ergebnisse in den Eskalationszusammenhang.","Kontrollieren und präzisieren Sie die Reichweite der Hypothese.","Bauen Sie den Argumentationsgang aus fünf funktionalen Ebenen.","Unterstützt Ihre Inszenierung Ihre Deutung?"];
