"use client";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { hydrateSession } from "../../../core/state/hydrateSession";
import type { GameState } from "../../../core/state/types";
import { AssetImage } from "../../../shared/components/AssetImage";
import { characterizationCards, chapter02PrimaryById, comparisonCards, ensembleLinks, highlightCandidateIds, highlightReasoning, mainSourceIds, momentClaims, momentPractice, momentPracticeLines, practiceClaims, practiceLines, relationshipPractice, relationshipPracticeLines, relationshipTasks, relevancePractice, relevancePracticeLines, rolePractice, rolePracticeLines, roleTasks, selfOtherPractice, selfOtherPracticeLines, selfOtherTasks, shakespeareCharacterizationCards, transferSourceIds, transferTasks, type AnalysisKind, type Certainty, type MomentKind, type RelevanceKind, type SelfOtherKind } from "../data/chapter_02_content";
import { PrimarySourceText } from "../../../shared/components/PrimarySourceText";
import { GlossaryHelp } from "../../../shared/components/GlossaryHelp";
import { SceneCharacters } from "../../../shared/components/SceneCharacters";
import { glossaryFor } from "../data/glossary";
import { advanceChapter02, analyzeRelationship, checkTextSignals, classifyCharacterization, classifyMoment, classifyMomentPractice, classifyPractice, classifyRelevance, classifyRole, classifyRolePractice, classifySelfOther, classifySelfOtherPractice, compareSituations, connectEnsemble, connectPracticeRelationship, createChapter02Session, justifyTextSignals, solveTransfer, toggleTextSignal, type Chapter02Session } from "../mechanics/chapter_02_engine";

const certaintyLabels:Record<Certainty,string>={explicit:"Eindeutig belegt",inference:"Plausibel erschließbar",unsupported:"Nicht belegt"};
const roundNames=["","Ensemblewand","Befund oder Deutung?","Direkt oder indirekt?","Moment oder Muster?","Relevante Textsignale","Ziel, Motiv und Interesse","Gerichtete Beziehungen","Selbst- und Fremdbild","Werkzeuge am Drama","Juliette im Text","Momentaufnahme","Ziel und Motiv","Beziehungen","Selbst- und Fremdbild","Die Figurenakte","Situationen vergleichen","Ensemble rekonstruieren"];

export function Chapter02({gameState,onSave,onExit,onComplete}:{gameState:GameState;onSave:(session:Chapter02Session)=>void;onExit:()=>void;onComplete:(session:Chapter02Session)=>void}){
 const[session,setSession]=useState(()=>hydrateSession(gameState.decisions.chapter_02,createChapter02Session(),17));
 const[feedback,setFeedback]=useState("");
 const dossierRef=useRef<HTMLElement>(null);
 useEffect(()=>{dossierRef.current?.scrollTo({top:0,behavior:"auto"});dossierRef.current?.scrollIntoView({block:"start",behavior:"auto"})},[session.round]);
 const update=(next:Chapter02Session)=>{setSession(next);onSave(next)};
 const result=(r:{valid:boolean;session:Chapter02Session},ok:string,bad:string)=>{update(r.session);setFeedback(r.valid?ok:bad);if(r.session.completed)onComplete(r.session)};
 return <main className="chapter-shell ensemble-chapter chapter-two">
  <header className="chapter-header"><button onClick={onExit}>← Theater</button><div><p>Kapitel 2 · Ensemblewand</p><h1>Das Ensemble</h1><small>Figuren und Beziehungen analysieren</small></div><span>Abschnitt {session.round} von 17</span></header>
  <section className="ensemble-stage"><AssetImage id="bg_portrait_room" className="chapter-two-background" decorative loading="eager"/><aside className="ensemble-lorenzo"><AssetImage id="character_lorenzo_letter" className="ensemble-lorenzo-image" fallback={<span>Bruder Lorenzo</span>}/></aside>
   <section className="ensemble-dossier" ref={dossierRef} tabIndex={-1}><div className="dossier-progress" aria-label={`Abschnitt ${session.round} von 17`}><strong>{roundNames[session.round]}</strong><span>{session.round}/17</span></div>
    {session.round>=2&&<GlossaryHelp entries={glossaryFor("chapter_02")} introTitle="Werkzeuge der Figurenanalyse" seen={session.seenGlossaryIntroductions.includes("chapter_02")||session.round>2} onSeen={()=>update({...session,seenGlossaryIntroductions:[...new Set([...session.seenGlossaryIntroductions,"chapter_02"])]})}/>}
    {(session.round===9||session.round===10)&&<SceneCharacters sceneId="chapter_02.main"/>}
    {session.round===1&&<Opening onNext={()=>update(advanceChapter02(session))}/>}
    {session.round===2&&<PracticeRound session={session} onAssign={(id,target)=>result(classifyPractice(session,id,target),"Die Einordnung unterscheidet Textbefund und vorsichtige Erschließung.","Prüfen Sie, ob der Text dies sagt, nur nahelegt oder gar nicht trägt.")}/>}
    {session.round===3&&<CharacterizationRound session={session} shakespeare={false} onAssign={(id,target)=>result(classifyCharacterization(session,id,target),"Die Informationsquelle ist richtig bestimmt.","Prüfen Sie, ob eine Einschätzung ausgesprochen, aus Verhalten erschlossen oder nicht getragen wird.")}/>}<></>
    {session.round===4&&<MomentPracticeRound session={session} onAssign={(id,target)=>result(classifyMomentPractice(session,id,target),"Die Reichweite der Aussage ist angemessen bestimmt.","Aus einer einzelnen Handlung folgt noch kein dauerhafter Charakterzug.")}/>}<></>
    {session.round===5&&<RelevancePracticeRound session={session} onAssign={(id,target)=>result(classifyRelevance(session,id,target),"Die Bedeutung des Signals für die konkrete Figurenfrage ist passend gewichtet.","Prüfen Sie, ob die Aussage die Figurenfrage trägt, nur ergänzt oder über den Text hinausgeht.")}/>}<></>
    {session.round===6&&<RolePracticeRound session={session} onAssign={(id,target)=>result(classifyRolePractice(session,id,target),"Die analytische Frage ist passend bestimmt.",target==="goal"?"Das Ziel beschreibt, WAS die Figur erreichen will.":"Das Motiv erklärt, WARUM sie dies erreichen möchte. Interesse und Ziel sind ebenfalls zu trennen.")}/>}<></>
    {session.round===7&&<RelationshipPracticeRound session={session} onCheck={(id,signal,analysis)=>result(connectPracticeRelationship(session,id,signal,analysis),"Richtung, Analyse und Textsignal sind verbunden.","Prüfen Sie Beziehungsrichtung, Reichweite der Aussage und Textsignal gemeinsam.")}/>}<></>
    {session.round===8&&<SelfOtherPracticeRound session={session} onAssign={(id,target)=>result(classifySelfOtherPractice(session,id,target),"Perspektive, Textbefund und Überdehnung bleiben getrennt.","Eine Selbst- oder Fremdeinschätzung ist noch keine objektive Wahrheit.")}/>}<></>
    {session.round===9&&<CharacterizationRound session={session} shakespeare onAssign={(id,target)=>result(classifyCharacterization(session,id,target),"Das Werkzeug ist am Dramentext richtig angewendet.","Prüfen Sie Aussage und vollständigen Textbeleg gemeinsam.")}/>}<></>
    {session.round===10&&<MainAnalysis session={session} onToggle={id=>update(toggleTextSignal(session,id))} onCheck={()=>result(checkTextSignals(session),"Die Gesamtauswahl enthält die tragfähigen Kernbelege. Begründen Sie nun deren Zusammenhang.","Prüfen Sie Relevanz und Vollständigkeit der markierten Stellen.")} onJustify={id=>result(justifyTextSignals(session,id),"Die Begründung verbindet Textbeleg, Situation und vorsichtige Charakterisierung.","Die Begründung muss erklären, was die Stellen in ihrer jeweiligen Situation zeigen.")}/>}<></>
    {session.round===11&&<MomentRound session={session} onAssign={(id,target)=>result(classifyMoment(session,id,target),"Die Reichweite der Aussage ist passend eingeschätzt.","Der Ausschnitt trägt diese Aussage nicht mit dieser Sicherheit.")}/>}<></>
    {session.round===12&&<RoleRound session={session} onAssign={(id,target)=>result(classifyRole(session,id,target),"Beobachtung und analytische Kategorie passen zusammen.",target==="goal"?"Das Ziel beschreibt, WAS Juliette erreichen will.":"Das Motiv erklärt, WARUM sie dies erreichen möchte.")}/>}<></>
    {session.round===13&&<RelationshipRound session={session} onCheck={(id,source,analysis)=>result(analyzeRelationship(session,id,source,analysis),"Analyse und Textsignal tragen genau diese Beziehungsrichtung.","Prüfen Sie, ob die Aussage die Richtung umkehrt oder aus einem Moment ein dauerhaftes Verhältnis macht.")}/>}<></>
    {session.round===14&&<SelfOtherRound session={session} onAssign={(id,target)=>result(classifySelfOther(session,id,target),"Selbstdarstellung und Behandlung durch andere bleiben getrennt.","Prüfen Sie, wessen Perspektive diese Aussage zeigt.")}/>}<></>
    {session.round===15&&<TransferRound session={session} onCheck={(id,source,analysis)=>result(solveTransfer(session,id,source,analysis),"Analyseentscheidung und Textbeleg bilden eine tragfähige Verbindung.","Wählen Sie zuerst eine textnahe Analyse und dann den passenden Beleg.")}/>}<></>
    {session.round===16&&<ComparisonRound session={session} onAssign={(id,target)=>result(compareSituations(session,id,target),"Die Aussage bleibt an Situation und Kontext gebunden.","Vermeiden Sie eine starre Entwicklungsschablone.")}/>}<></>
    {session.round===17&&<EnsembleRound session={session} onConnect={(from,to,analysis,source)=>result(connectEnsemble(session,from,to,analysis,source),"Die Verbindung ist textgestützt rekonstruiert.","Ausgangsfigur, Zielfigur, Beziehungsanalyse und Textbeleg passen noch nicht zusammen.")}/>}<></>
    {feedback&&<p className="ensemble-feedback" role="status" aria-live="polite">{feedback}</p>}
   </section>
  </section>
 </main>
}

function Lorenzo({children}:{children:ReactNode}){return <div className="ensemble-lorenzo-speech"><strong>Bruder Lorenzo</strong><p>{children}</p></div>}
function Opening({onNext}:{onNext:()=>void}){return <div className="ensemble-scene opening"><Lorenzo>Das Regiebuch ist wieder lesbar. Aber Namen auf einer Seite erzählen noch nicht, wer ein Mensch ist. Eine Figur verrät selten einfach, wer sie ist. Man muss beobachten, was sie sagt, was sie tut und wie andere auf sie reagieren. Sehen wir uns das Ensemble genauer an.</Lorenzo><div className="method-sequence"><strong>Text</strong><span>↓</span><strong>Beobachtung</strong><span>↓</span><strong>Erschließung</strong><span>↓</span><strong>Charakterisierung</strong></div><button className="chapter-primary-action" onClick={onNext}>Erste Figurenakte öffnen</button></div>}
function PracticeText(){return <article className="practice-dialogue"><span className="source-badge practice">Übungstext · nicht von Shakespeare</span>{practiceLines.map((line,index)=><p key={index}>{line.speaker&&<strong>{line.speaker}: </strong>}{line.text}</p>)}</article>}
function PracticeRound({session,onAssign}:{session:Chapter02Session;onAssign:(id:string,target:Certainty)=>void}){return <div className="ensemble-scene"><div className="task-slip"><h2>Was verrät eine Figur?</h2><p>Untersuchen Sie Leon. Entscheiden Sie, wie sicher sich jede Aussage aus dem Text ableiten lässt.</p></div><PracticeText/><CardAssignment items={practiceClaims} assignments={session.practiceAssignments} zones={Object.entries(certaintyLabels).map(([id,label])=>({id,label}))} onAssign={onAssign}/></div>}
function CharacterizationRound({session,onAssign,shakespeare}:{session:Chapter02Session;onAssign:(id:string,target:"direct"|"indirect"|"unsupported")=>void;shakespeare:boolean}){const items=shakespeare?shakespeareCharacterizationCards:characterizationCards;return <div className="ensemble-scene"><div className="dossier-folds"><article><h3>Direkte Charakterisierung</h3><p>Eine Eigenschaft oder Einschätzung wird im Text über eine Figur formuliert.</p></article><article><h3>Indirekte Charakterisierung</h3><p>Eine mögliche Eigenschaft wird aus Rede, Verhalten, Entscheidungen, Handlungen oder Reaktionen hergeleitet.</p></article></div>{shakespeare?<><Lorenzo>Die Figurenakte ist vorbereitet. Nun müsst Ihr dieselben Werkzeuge an einer echten Dramenszene einsetzen.</Lorenzo><PrimaryDossier ids={[...new Set(shakespeareCharacterizationCards.map(item=>item.sourceId))]}/></>:<p className="didactic-note">Eine Selbstaussage kann einer direkten Charakterisierung widersprechen, die das Verhalten nahelegt.</p>}<CardAssignment items={items} assignments={session.characterizationAssignments} zones={[{id:"direct",label:"Direkt"},{id:"indirect",label:"Indirekt"},{id:"unsupported",label:"Nicht ausreichend belegt"}]} onAssign={onAssign}/>{!shakespeare&&<Lorenzo>Eine einzelne Handlung kann viel verraten. Aber sie beweist noch keinen dauerhaften Charakterzug.</Lorenzo>}</div>}
function PrimaryDossier({ids,buttons,onMark,label="Originaltext",initialOpen=true}:{ids:readonly string[];buttons?:boolean;onMark?:(id:string)=>void;label?:string;initialOpen?:boolean}){const[open,setOpen]=useState(initialOpen);return <div className="chapter-two-source"><button type="button" className="chapter-two-source-toggle" aria-expanded={open} onClick={()=>setOpen(value=>!value)}>{open?`${label} schließen`:`${label} erneut anzeigen`}</button>{open&&<article className="ensemble-primary"><span className="source-badge original">{label} · Wieland-Ausgabe</span>{ids.map(id=>{const source=chapter02PrimaryById(id);return buttons?<button key={id} onClick={()=>onMark?.(id)}><PrimarySourceText record={source}/></button>:<p key={id}><PrimarySourceText record={source}/></p>})}</article>}</div>}
function PracticeDialogue({lines}:{lines:readonly {speaker:string;text:string}[]}){return <article className="practice-dialogue"><span className="source-badge practice">Übungstext · nicht von Shakespeare</span>{lines.map((line,index)=><p key={index}>{line.speaker&&<strong>{line.speaker}: </strong>}{line.text}</p>)}</article>}
function MomentPracticeRound({session,onAssign}:{session:Chapter02Session;onAssign:(id:string,target:MomentKind)=>void}){return <div className="ensemble-scene"><div className="task-slip"><h2>Moment, Muster oder Überdehnung?</h2><p>Bestimmen Sie, wie weit die jeweilige Aussage auf Grundlage der Beobachtungen trägt.</p></div><PracticeDialogue lines={momentPracticeLines}/><CardAssignment items={momentPractice} assignments={session.momentPracticeAssignments} zones={[{id:"snapshot",label:"Situationsbezogener Befund"},{id:"pattern",label:"Wiederkehrendes Verhalten"},{id:"cautious",label:"Vorsichtige Charakterisierung"},{id:"overreach",label:"Unzulässige Verallgemeinerung"}]} onAssign={onAssign}/></div>}
function RelevancePracticeRound({session,onAssign}:{session:Chapter02Session;onAssign:(id:string,target:RelevanceKind)=>void}){return <div className="ensemble-scene"><div className="task-slip"><h2>Welche Signale tragen die Figurenanalyse?</h2><p>Gewichten Sie jede Aussage ausschließlich für die Frage: Wie geht Ben mit Verantwortung und Unterstützung um?</p></div><div className="relevance-key"><p><strong>Besonders relevant:</strong> beantwortet die Figurenfrage unmittelbar.</p><p><strong>Ergänzend relevant:</strong> hilft, einen unmittelbaren Befund einzuordnen.</p><p><strong>Wenig relevant:</strong> ist richtig, trägt aber kaum zu dieser Frage bei.</p><p><strong>Nicht ausreichend belegt:</strong> geht über die Textgrundlage hinaus.</p></div><PracticeDialogue lines={relevancePracticeLines}/><CardAssignment items={relevancePractice} assignments={session.relevanceAssignments} zones={[{id:"high",label:"Besonders relevant"},{id:"supporting",label:"Ergänzend relevant"},{id:"low",label:"Für diese Frage wenig relevant"},{id:"unsupported",label:"Nicht ausreichend belegt"}]} onAssign={onAssign}/></div>}
function RolePracticeRound({session,onAssign}:{session:Chapter02Session;onAssign:(id:string,target:AnalysisKind)=>void}){return <div className="ensemble-scene"><div className="dossier-folds four"><article><h3>Ziel</h3><p>Was will die Figur erreichen?</p></article><article><h3>Motiv</h3><p>Warum will sie es erreichen?</p></article><article><h3>Interesse / Bedürfnis</h3><p>Was ist ihr wichtig oder was braucht sie?</p></article><article><h3>Nicht sicher feststellbar</h3><p>Der Ausschnitt trägt keine zuverlässige Aussage.</p></article></div><PracticeDialogue lines={rolePracticeLines}/><CardAssignment items={rolePractice} assignments={session.rolePracticeAssignments} zones={[{id:"goal",label:"Ziel"},{id:"motive",label:"Motiv"},{id:"interest",label:"Interesse / Bedürfnis"},{id:"unknown",label:"Nicht sicher feststellbar"}]} onAssign={onAssign}/></div>}
function RelationshipPracticeRound({session,onCheck}:{session:Chapter02Session;onCheck:(id:string,signal:string,analysis:number)=>void}){const active=relationshipPractice.find(task=>!session.relationshipPracticeSteps.includes(task.id));const signals=relationshipPractice.map(item=>item.signal);return <div className="ensemble-scene"><div className="task-slip"><h2>Beziehungen haben eine Richtung</h2><p>Wählen Sie zuerst die treffendste Analyse und danach das Textsignal für genau diese Richtung.</p></div><PracticeDialogue lines={relationshipPracticeLines}/><p className="assignment-progress">Beziehung {Math.min(session.relationshipPracticeSteps.length+1,4)} von 4</p>{active&&<AnalysisEvidenceChoice task={active} evidence={signals.map(text=>({id:text,text}))} onCheck={(signal,analysis)=>onCheck(active.id,signal,analysis)}/>}</div>}
function SelfOtherPracticeRound({session,onAssign}:{session:Chapter02Session;onAssign:(id:string,target:SelfOtherKind)=>void}){return <div className="ensemble-scene"><div className="task-slip"><h2>Selbstbild, Fremdbild oder Textbefund?</h2><p>Beide Bilder sind perspektivisch. Trennen Sie sie vom beobachtbaren Verhalten und von Überdehnungen.</p></div><PracticeDialogue lines={selfOtherPracticeLines}/><CardAssignment items={selfOtherPractice} assignments={session.selfOtherPracticeAssignments} zones={[{id:"self",label:"Selbstbild"},{id:"other",label:"Fremdbild"},{id:"finding",label:"Textbefund"},{id:"overreach",label:"Überdehnung"}]} onAssign={onAssign}/></div>}
function JuliettePortrait(){return <figure className="dossier-portrait" aria-label="Juliette"><AssetImage id="character_julia_thoughtful" decorative fallback={<span aria-hidden="true">J</span>}/><figcaption>Juliette</figcaption></figure>}
function MainContext(){return <article className="context-leaf"><span>Hinführung</span><p>Juliette ist die Tochter der Familie Capulet. Ihre Mutter möchte mit ihr über eine mögliche Heirat sprechen. Paris, ein junger Adeliger, interessiert sich für Juliette.</p><strong>Achten Sie darauf, was Juliette selbst sagt und wie sie auf die Erwartungen ihrer Umgebung reagiert.</strong></article>}
function MainAnalysis({session,onToggle,onCheck,onJustify}:{session:Chapter02Session;onToggle:(id:string)=>void;onCheck:()=>void;onJustify:(id:string)=>void}){return <div className="ensemble-scene"><div className="dossier-with-portrait"><JuliettePortrait/><MainContext/></div><div className="task-slip"><h2>Textsignale sammeln</h2><p>Welche Äußerungen sind für Juliettes Umgang mit familiären Heiratserwartungen besonders aussagekräftig? Vergleichen Sie die frühe Aussicht auf Paris mit der später angeordneten Heirat.</p></div><article className="ensemble-primary"><span className="source-badge original">Originaltext · Wieland-Ausgabe · zwei Situationen</span>{highlightCandidateIds.map(id=>{const source=chapter02PrimaryById(id);return <button key={id} aria-pressed={session.highlightSelection.includes(id)} disabled={session.highlightSelectionChecked} onClick={()=>onToggle(id)}><PrimarySourceText record={source}/></button>})}</article>{!session.highlightSelectionChecked?<button className="chapter-primary-action" disabled={!session.highlightSelection.length} onClick={onCheck}>Gesamtauswahl prüfen</button>:<div className="signal-reasoning"><h3>Was zeigt Ihre Auswahl?</h3>{highlightReasoning.map(reason=><button key={reason.id} onClick={()=>onJustify(reason.id)}>{reason.text}</button>)}</div>}</div>}
function MomentRound({session,onAssign}:{session:Chapter02Session;onAssign:(id:string,target:"supported"|"uncertain"|"unsupported")=>void}){return <div className="ensemble-scene"><MainContext/><PrimaryDossier ids={mainSourceIds}/><div className="task-slip"><h2>Eigenschaft oder Momentaufnahme?</h2><p>Wie weit trägt dieser eine Ausschnitt?</p></div><CardAssignment items={momentClaims} assignments={session.momentAssignments} zones={[{id:"supported",label:"Gut gestützt"},{id:"uncertain",label:"Möglich, aber unsicher"},{id:"unsupported",label:"Nicht gestützt"}]} onAssign={onAssign}/><blockquote>Figuren zeigen sich in Situationen. Ein einzelner Ausschnitt kann eine Charakterisierung stützen, aber selten eine ganze Persönlichkeit beweisen.</blockquote></div>}
function RoleRound({session,onAssign}:{session:Chapter02Session;onAssign:(id:string,target:AnalysisKind)=>void}){return <div className="ensemble-scene"><div className="dossier-folds four"><article><h3>Ziel</h3><p>Was möchte eine Figur in der konkreten Situation erreichen?</p></article><article><h3>Motiv</h3><p>Warum handelt eine Figur auf diese Weise? Ein Motiv beschreibt einen möglichen inneren Beweggrund.</p></article><article><h3>Interesse / Bedürfnis</h3><p>Was ist für eine Figur grundsätzlich wichtig oder was braucht sie in der Situation?</p></article><article><h3>Nicht sicher feststellbar</h3><p>Der Text liefert nicht genug Hinweise, um eine Aussage zuverlässig zu begründen.</p></article></div><p className="didactic-note">Ordnen Sie nach der Frage, die eine Aussage beantwortet – nicht nach einem einzelnen Signalwort.</p><PrimaryDossier ids={[...new Set(roleTasks.map(task=>task.sourceId))]}/><CardAssignment items={roleTasks.map(x=>({id:x.id,text:x.observation}))} assignments={session.roleAssignments} zones={[{id:"goal",label:"Ziel"},{id:"motive",label:"Motiv"},{id:"interest",label:"Interesse / Bedürfnis"},{id:"unknown",label:"Nicht sicher feststellbar"}]} onAssign={onAssign}/></div>}
function RelationshipRound({session,onCheck}:{session:Chapter02Session;onCheck:(id:string,source:string,analysis:number)=>void}){const ids=[...new Set(relationshipTasks.map(task=>task.sourceId))];const active=relationshipTasks.find(task=>!session.relationshipSteps.includes(task.id));return <div className="ensemble-scene"><div className="relationship-portraits"><Person id="character_julia_calm" name="Juliette"/><span aria-hidden="true">⇄</span><Person id="character_lady_capulet" name="Lady Capulet"/></div><p className="didactic-note">Eine Beziehung hat zwei Richtungen. Wählen Sie zuerst die textnahe Analyse und sichern Sie sie danach mit dem vollständigen Textsignal.</p><PrimaryDossier ids={ids}/><p className="assignment-progress">Beziehungsrichtung {Math.min(session.relationshipSteps.length+1,2)} von 2</p>{active&&<AnalysisEvidenceChoice task={active} evidence={ids.map(id=>({id,text:chapter02PrimaryById(id).text}))} onCheck={(source,analysis)=>onCheck(active.id,source,analysis)}/>}</div>}
function SelfOtherRound({session,onAssign}:{session:Chapter02Session;onAssign:(id:string,target:"self"|"other"|"finding"|"unsupported")=>void}){return <div className="ensemble-scene"><div className="task-slip"><h2>Selbstbild und Fremdbild</h2><p>Trennen Sie Juliettes Selbstdarstellung, fremde Perspektiven, beobachtbares Verhalten und Überdehnungen.</p></div><PrimaryDossier ids={mainSourceIds}/><CardAssignment items={selfOtherTasks} assignments={session.selfOtherAssignments} zones={[{id:"self",label:"Selbstbild"},{id:"other",label:"Fremdbild"},{id:"finding",label:"Beobachtbares Verhalten"},{id:"unsupported",label:"Nicht ausreichend gestützt"}]} onAssign={onAssign}/></div>}
function TransferRound({session,onCheck}:{session:Chapter02Session;onCheck:(id:string,source:string,analysis:number)=>void}){const active=transferTasks.find(task=>!session.transferSteps.includes(task.id));return <div className="ensemble-scene"><div className="task-slip"><span>Die Figurenakte</span><h2>Eine spätere Situation selbstständig analysieren</h2><p>Juliettes Familie plant nun eine Hochzeit mit Paris. Bestimmen Sie zuerst die tragfähige Analyse und prüfen Sie sie anschließend am Text.</p><strong>Text → Analyseentscheidung → Belegprüfung</strong></div><div className="chapter-two-transfer-layout"><PrimaryDossier ids={transferSourceIds}/><div className="chapter-two-transfer-task"><p className="assignment-progress">Analyse {Math.min(session.transferSteps.length+1,4)} von 4</p>{active&&<TransferChoice task={active} done={false} onCheck={(source,analysis)=>onCheck(active.id,source,analysis)}/>}</div></div></div>}
function ComparisonRound({session,onAssign}:{session:Chapter02Session;onAssign:(id:string,target:"early"|"late"|"conclusion"|"unsupported")=>void}){return <div className="ensemble-scene"><div className="task-slip"><h2>Zeigt sich Juliette in beiden Situationen gleich?</h2><p>Ordnen Sie Beobachtungen, vorsichtige Schlussfolgerungen und Überdehnungen. Beide Textgrundlagen können Sie jederzeit erneut öffnen.</p></div><div className="comparison-sources"><PrimaryDossier label="Frühere Szene" ids={mainSourceIds} initialOpen={false}/><PrimaryDossier label="Spätere Szene" ids={transferSourceIds} initialOpen={false}/></div><CardAssignment items={comparisonCards} assignments={session.comparisonAssignments} zones={[{id:"early",label:"Frühere Situation"},{id:"late",label:"Spätere Situation"},{id:"conclusion",label:"Vorsichtige Schlussfolgerung"},{id:"unsupported",label:"Nicht ausreichend belegt"}]} onAssign={onAssign}/></div>}
function EnsembleRound({session,onConnect}:{session:Chapter02Session;onConnect:(from:string,to:string,analysis:string,source:string)=>void}){const [from,setFrom]=useState("");const [to,setTo]=useState("");const [selecting,setSelecting]=useState<"from"|"to">("from");const [analysis,setAnalysis]=useState("");const [source,setSource]=useState("");const people=[{name:"Juliette",asset:"character_julia_calm"},{name:"Lady Capulet",asset:"character_lady_capulet"},{name:"Capulet",asset:"character_capulet"},{name:"Amme",asset:"character_amme"}];return <div className={`ensemble-scene ensemble-restoration ${session.completed?"restored":""}`}><h2>Ensemblewand rekonstruieren</h2><p>Wählen Sie Ausgangsfigur, Zielfigur und Beziehungsanalyse. Sichern Sie die Verbindung anschließend mit einem vollständigen Textbeleg.</p><div className="connection-role-tabs"><button className={selecting==="from"?"selected":""} onClick={()=>setSelecting("from")}>Ausgangsfigur: {from||"auswählen"}</button><button className={selecting==="to"?"selected":""} onClick={()=>setSelecting("to")}>Zielfigur: {to||"auswählen"}</button></div><div className="final-portraits selectable">{people.map(p=><button key={p.name} className={(selecting==="from"?from:to)===p.name?"selected":""} aria-label={`${p.name} als ${selecting==="from"?"Ausgangsfigur":"Zielfigur"} wählen`} onClick={()=>{if(selecting==="from"){setFrom(p.name);setSelecting("to")}else setTo(p.name)}}><Person id={p.asset} name={p.name}/></button>)}</div><TextCardPicker legend="Beziehungsanalyse auswählen" options={ensembleLinks.map(link=>({id:link.label,text:link.label}))} value={analysis} onChange={setAnalysis}/><TextCardPicker legend="Textbeleg auswählen" options={transferSourceIds.map(id=>({id,text:chapter02PrimaryById(id).text}))} value={source} onChange={setSource}/><button disabled={!from||!to||!analysis||!source} onClick={()=>onConnect(from,to,analysis,source)}>Verbindung eintragen</button><ol className="restored-connections">{ensembleLinks.map(link=><li className={session.ensembleConnections.includes(link.id)?"complete":""} key={link.id}><strong>{link.from} → {link.to}</strong><span>{session.ensembleConnections.includes(link.id)?link.label:"Verbindung noch unterbrochen"}</span></li>)}</ol>{session.completed&&<><div className="method-sequence"><strong>Text</strong><span>↓</span><strong>Beobachtung</strong><span>↓</span><strong>Erschließung</strong><span>↓</span><strong>Charakterisierung</strong></div><blockquote>Eine Figurenanalyse behauptet nicht. Sie belegt und deutet.</blockquote><Lorenzo>Die Figurenakte ist vollständig. Ihre Reise geht nun auf der großen Bühne weiter.</Lorenzo></>}</div>}
function Person({id,name}:{id:string;name:string}){return <figure className="ensemble-person" aria-label={name}><AssetImage id={id} decorative fallback={<span aria-hidden="true">{name.slice(0,1)}</span>}/><figcaption>{name}</figcaption></figure>}
function TextCardPicker({legend,options,value,onChange}:{legend:string;options:readonly {id:string;text:string}[];value:string;onChange:(id:string)=>void}){return <fieldset className="text-card-picker"><legend>{legend}</legend>{options.map(option=><label key={option.id} className={value===option.id?"selected":""}><input type="radio" name={legend} checked={value===option.id} onChange={()=>onChange(option.id)}/><span>{option.text}</span></label>)}</fieldset>}
function TransferChoice({task,done,onCheck}:{task:typeof transferTasks[number];done:boolean;onCheck:(source:string,analysis:number)=>void}){const[analysis,setAnalysis]=useState<number|null>(null);const[source,setSource]=useState("");return <article className={`evidence-entry ${done?"done":""}`}><h3>{task.category}</h3>{done?<strong>Analyse und Textbezug gesichert</strong>:<><fieldset className="analysis-option-cards"><legend>Analyse auswählen</legend>{task.options.map((text,index)=><label key={text}><input type="radio" name={`${task.id}-analysis`} checked={analysis===index} onChange={()=>setAnalysis(index)}/><span>{text}</span></label>)}</fieldset><TextCardPicker legend={`Textbeleg für ${task.category}`} options={transferSourceIds.map(id=>({id,text:chapter02PrimaryById(id).text}))} value={source} onChange={setSource}/><button disabled={analysis===null||!source} onClick={()=>onCheck(source,analysis!)}>Analyse und Beleg prüfen</button></>}</article>}
function AnalysisEvidenceChoice({task,evidence,onCheck}:{task:{id:string;from:string;to:string;options:readonly string[]};evidence:readonly {id:string;text:string}[];onCheck:(source:string,analysis:number)=>void}){const[analysis,setAnalysis]=useState<number|null>(null);const[source,setSource]=useState("");return <article className="evidence-entry"><h3>{task.from} → {task.to}</h3><fieldset className="analysis-option-cards"><legend>Beziehungsanalyse auswählen</legend>{task.options.map((text,index)=><label key={text}><input type="radio" name={`${task.id}-analysis`} checked={analysis===index} onChange={()=>setAnalysis(index)}/><span>{text}</span></label>)}</fieldset><TextCardPicker legend={`Textbeleg für ${task.from} → ${task.to}`} options={evidence} value={source} onChange={setSource}/><button disabled={analysis===null||!source} onClick={()=>onCheck(source,analysis!)}>Analyse und Beleg prüfen</button></article>}
function CardAssignment<T extends string>({items,assignments,zones,onAssign}:{items:readonly {id:string;text:string}[];assignments:Record<string,T>;zones:readonly {id:string;label:string}[];onAssign:(id:string,target:T)=>void}){const[selected,setSelected]=useState<string|null>(null);const remaining=items.filter(item=>!assignments[item.id]);const visible=remaining.slice(0,4);const completed=items.length-remaining.length;return <div className="card-assignment"><p className="assignment-progress" aria-live="polite">Übungsfortschritt: {completed} von {items.length} Fällen bearbeitet</p><div className="assignment-cards">{visible.map(item=><button key={item.id} aria-pressed={selected===item.id} onClick={()=>setSelected(item.id)}>{item.text}</button>)}</div><div className="assignment-zones">{zones.map(zone=><button key={zone.id} disabled={!selected} onClick={()=>{if(selected){onAssign(selected,zone.id as T);setSelected(null)}}}><strong>{zone.label}</strong><small>{Object.values(assignments).some(v=>v===zone.id)?"Bereits verwendet":"Zuordnen"}</small></button>)}</div></div>}
