"use client";

import { useState } from "react";
import { hydrateSession } from "../../../core/state/hydrateSession";
import type { GameState } from "../../../core/state/types";
import { DragDropBoard } from "../../../shared/components/DragDropBoard";
import { AssetImage } from "../../../shared/components/AssetImage";
import { chapter01Fragments, directionChecks, fragmentById, informationCards, round1Targets, type FragmentType } from "../data/chapter_01_content";
import { checkManuscriptElement, initialChapter01Session, placeInformationCard, placeRound1, placeStageDirection, type Chapter01Session } from "../mechanics/chapter_01_engine";

export function Chapter01({ gameState, onSave, onExit, onComplete }: { gameState: GameState; onSave: (session: Chapter01Session) => void; onExit: () => void; onComplete: (session: Chapter01Session) => void }) {
  const stored = gameState.decisions.chapter_01;
  const [session,setSession] = useState<Chapter01Session>(() => hydrateSession(stored, initialChapter01Session, 5));
  const [feedback,setFeedback] = useState("Wählen Sie ein Fragment und anschließend den passenden Zielbereich.");
  const update = (next: Chapter01Session) => { setSession(next); onSave(next); };
  const assignRound1 = (fragmentId:string,targetId:string) => { const result=placeRound1(session,fragmentId,targetId as FragmentType); update(result.session); const target=round1Targets.find((item)=>item.id===targetId); setFeedback(result.valid?"Der Manuskriptabschnitt ist restauriert.":target?.feedback??"Diese Zuordnung passt noch nicht."); };
  const stage = (fragmentId:string) => { const result=placeStageDirection(session,fragmentId); update(result.session); setFeedback(result.valid?(session.round===2?"Die Regieanweisung macht den Bühnenauftritt spielbar.":"Die Regieanweisung beendet den Bühnenauftritt."):"Die Szene funktioniert noch nicht. Welche Information bestimmt hier das Bühnengeschehen?"); };
  const info = (cardId:string,targetId:string) => { const result=placeInformationCard(session,cardId,targetId); update(result.session); setFeedback(result.valid?"Die Informationslage ist korrekt eingeordnet.":"Prüfen Sie, welche Information Romeo zu diesem Zeitpunkt tatsächlich besitzt."); };
  const check = (type:FragmentType) => { const result=checkManuscriptElement(session,type); update(result.session); setFeedback(result.valid?(result.session.completed?"Das Regiebuch ist wieder lesbar.":"Funktion korrekt im Manuskript nachgewiesen."):"Dieses Manuskriptelement erfüllt eine andere Funktion."); if(result.session.completed) onComplete(result.session); };
  return <main className="chapter-shell"><header className="chapter-header"><button onClick={onExit}>← Theater</button><div><p>Kapitel 1 · Regiepult</p><h1>Das zerrissene Regiebuch</h1></div><span>Runde {session.round} von 5</span></header><section className="chapter-stage"><aside className="chapter-brief"><p className="task-label">Arbeitsauftrag</p><h2>{roundTitle(session.round)}</h2><p>{roundInstruction(session.round)}</p><div className="round-dots" aria-label={`Runde ${session.round} von 5`}>{[1,2,3,4,5].map((round)=><span key={round} className={round<=session.round?"active":""}>{round}</span>)}</div></aside><section className="writing-desk">{session.round===1&&<DragDropBoard items={chapter01Fragments.filter((item)=>["fragment_a","fragment_b","fragment_c","fragment_d"].includes(item.id)).map((item)=>({id:item.id,text:item.text,textOrigin:"primary_source"}))} targets={round1Targets} assigned={session.assignments} onAssign={assignRound1} feedback={feedback}/>} {session.round===2&&<StageDirectionRound session={session} mode="entrance" onAssign={stage} feedback={feedback}/>} {session.round===3&&<StageDirectionRound session={session} mode="exit" onAssign={stage} feedback={feedback}/>} {session.round===4&&<InformationRound session={session} onAssign={info} feedback={feedback}/>} {session.round===5&&<RegieCheck session={session} onSelect={check} feedback={feedback}/>}</section></section></main>;
}

function StageDirectionRound({session,mode,onAssign,feedback}:{session:Chapter01Session;mode:"entrance"|"exit";onAssign:(id:string)=>void;feedback:string}) { const candidates=mode==="entrance"?["fragment_e"]:["fragment_e","fragment_h"]; return <div className="stage-round"><div className="mini-stage"><div className="figure-slot romeo-slot"><AssetImage id="character_romeo_calm" className="character-image" fallback={<span>R</span>}/><small>Romeo</small></div>{session.balthasarVisible&&<div className="figure-slot balthasar-slot"><AssetImage id="character_balthasar_calm" className="character-image" fallback={<span>B</span>}/><small>Balthasar</small></div>}</div><div className="manuscript-page"><span className="origin-label">Originaltext · 5. Aufzug, 1. Szene</span>{mode==="entrance"?<><p>{fragmentById("fragment_f")?.text}</p><p className="missing-line">Fehlende Regieanweisung</p></>:<><p>{fragmentById("fragment_g_speaker")?.text} {fragmentById("fragment_g_speech")?.text}</p><p className="missing-line">Fehlende Regieanweisung</p></>}</div><div className="stage-fragments">{candidates.map((id)=><button className="paper-fragment" key={id} onClick={()=>onAssign(id)}><span className="origin-label">Originaltext</span>{fragmentById(id)?.text}</button>)}</div><p className="chapter-feedback" role="status">{feedback}</p></div>; }

function InformationRound({session,onAssign,feedback}:{session:Chapter01Session;onAssign:(card:string,target:string)=>void;feedback:string}) { const [selected,setSelected]=useState<string|null>(null); return <div className="information-round"><div className="knowledge-figure"><span>R</span><strong>Romeo</strong></div><div className="summary-cards">{informationCards.filter((item)=>!session.informationAssignments[item.id]).map((card)=><button key={card.id} className={selected===card.id?"selected":""} onClick={()=>setSelected(card.id)} aria-pressed={selected===card.id}><small>Didaktische Zusammenfassung</small>{card.text}</button>)}</div><div className="knowledge-zones"><button onClick={()=>selected&&onAssign(selected,"knows")}><strong>Romeo weiß</strong><span>{Object.entries(session.informationAssignments).filter(([,target])=>target==="knows").length} Karten</span></button><button onClick={()=>selected&&onAssign(selected,"does_not_know")}><strong>Romeo weiß nicht</strong><span>{Object.entries(session.informationAssignments).filter(([,target])=>target==="does_not_know").length} Karten</span></button></div><p className="chapter-feedback" role="status">{feedback}</p></div>; }

function RegieCheck({session,onSelect,feedback}:{session:Chapter01Session;onSelect:(type:FragmentType)=>void;feedback:string}) { return <div className={`regie-check ${session.completed?"complete":""}`}><div className="check-prompt"><small>Funktionsaussage {Math.min(session.checkIndex+1,4)} von 4</small><strong>{session.completed?"Das Regiebuch ist wieder lesbar.":directionChecks[session.checkIndex].statement}</strong><p>Wählen Sie das passende Element direkt im Manuskript.</p></div><div className="restored-manuscript"><span className="origin-label">Originaltext · redaktionell geprüft</span>{chapter01Fragments.map((fragment)=><button key={fragment.id} className={`manuscript-element type-${fragment.fragment_type}`} onClick={()=>onSelect(fragment.fragment_type as FragmentType)} disabled={session.completed}>{fragment.text}</button>)}</div><p className="chapter-feedback" role="status">{feedback}</p></div>; }

function roundTitle(round:number){return ["","Textarten rekonstruieren","Eine Figur betritt die Bühne","Regieanweisung hat Folgen","Informationslage","Regiecheck"][round];}
function roundInstruction(round:number){return ["","Ordnen Sie die Originalfragmente ihren Funktionen im Manuskript zu.","Setzen Sie die fehlende Regieanweisung ein, damit die Szene spielbar wird.","Welche Regieanweisung steuert jetzt das Bühnengeschehen?","Ordnen Sie die didaktischen Karten danach, was Romeo weiß und nicht weiß.","Weisen Sie jede Funktionsaussage direkt an einem passenden Manuskriptelement nach."][round];}
