"use client";
import { useState, type ReactNode } from "react";
import { hydrateSession } from "../../../core/state/hydrateSession";
import type { GameState } from "../../../core/state/types";
import { AssetImage } from "../../../shared/components/AssetImage";
import { characterizationCards, chapter02PrimaryById, comparisonCards, ensembleLinks, highlightTasks, mainSourceIds, momentClaims, practiceClaims, practiceLines, relationshipTasks, roleTasks, selfOtherTasks, transferSourceIds, transferTasks, type AnalysisKind, type Certainty } from "../data/chapter_02_content";
import { advanceChapter02, analyzeRelationship, classifyCharacterization, classifyMoment, classifyPractice, classifyRole, classifySelfOther, compareSituations, connectEnsemble, createChapter02Session, markTextSignal, solveTransfer, type Chapter02Session } from "../mechanics/chapter_02_engine";

const certaintyLabels:Record<Certainty,string>={explicit:"Eindeutig belegt",inference:"Plausibel erschließbar",unsupported:"Nicht belegt"};
const roundNames=["","Ensemblewand","Befund oder Deutung?","Figurenakte","Juliette im Text","Momentaufnahme","Ziel und Motiv","Beziehungen","Selbst- und Fremdbild","Die Figurenakte","Situationen vergleichen","Ensemble rekonstruieren"];

export function Chapter02({gameState,onSave,onExit,onComplete}:{gameState:GameState;onSave:(session:Chapter02Session)=>void;onExit:()=>void;onComplete:(session:Chapter02Session)=>void}){
 const[session,setSession]=useState(()=>hydrateSession(gameState.decisions.chapter_02,createChapter02Session(),11));
 const[feedback,setFeedback]=useState("Eine Figur zeigt sich durch das, was sie sagt, tut und auslöst.");
 const update=(next:Chapter02Session)=>{setSession(next);onSave(next)};
 const result=(r:{valid:boolean;session:Chapter02Session},ok:string,bad:string)=>{update(r.session);setFeedback(r.valid?ok:bad);if(r.session.completed)onComplete(r.session)};
 return <main className="chapter-shell ensemble-chapter chapter-two">
  <header className="chapter-header"><button onClick={onExit}>← Theater</button><div><p>Kapitel 2 · Ensemblewand</p><h1>Das Ensemble</h1><small>Figuren und Beziehungen analysieren</small></div><span>Abschnitt {session.round} von 11</span></header>
  <section className="ensemble-stage"><AssetImage id="bg_portrait_room" className="chapter-two-background" decorative loading="eager"/><aside className="ensemble-lorenzo"><AssetImage id="character_lorenzo_letter" className="ensemble-lorenzo-image" fallback={<span>Bruder Lorenzo</span>}/></aside>
   <section className="ensemble-dossier"><div className="dossier-progress" aria-label={`Abschnitt ${session.round} von 11`}><strong>{roundNames[session.round]}</strong><span>{session.round}/11</span></div>
    {session.round===1&&<Opening onNext={()=>update(advanceChapter02(session))}/>} 
    {session.round===2&&<PracticeRound session={session} onAssign={(id,target)=>result(classifyPractice(session,id,target),"Die Einordnung unterscheidet Textbefund und vorsichtige Erschließung.","Prüfen Sie, ob der Text dies sagt, nur nahelegt oder gar nicht trägt.")}/>} 
    {session.round===3&&<CharacterizationRound session={session} onAssign={(id,target)=>result(classifyCharacterization(session,id,target),"Die Informationsquelle ist richtig bestimmt.","Wird die Einschätzung ausgesprochen oder erst aus Verhalten erschlossen?")}/>} 
    {session.round===4&&<MainAnalysis session={session} onMark={id=>result(markTextSignal(session,id),"Textsignal gesichert. Jetzt lässt sich daraus vorsichtig erschließen.","Diese Stelle beantwortet die Frage nicht unmittelbar oder wurde bereits markiert.")}/>} 
    {session.round===5&&<MomentRound session={session} onAssign={(id,target)=>result(classifyMoment(session,id,target),"Die Reichweite der Aussage ist passend eingeschätzt.","Der Ausschnitt trägt diese Aussage nicht mit dieser Sicherheit.")}/>} 
    {session.round===6&&<RoleRound session={session} onAssign={(id,target)=>result(classifyRole(session,id,target),target==="unknown"?"Hier ist Zurückhaltung fachlich richtig.":"Beobachtung und analytische Kategorie passen zusammen.","Ziel, Motiv und Interesse beantworten unterschiedliche Fragen.")}/>} 
    {session.round===7&&<RelationshipRound session={session} onCheck={(id,source)=>result(analyzeRelationship(session,id,source),"Textsignal, Beobachtung und gerichtete Beziehung sind verbunden.","Diese Beziehungsaussage braucht genau den Textbezug, der ihre Richtung trägt.")}/>} 
    {session.round===8&&<SelfOtherRound session={session} onAssign={(id,target)=>result(classifySelfOther(session,id,target),"Selbstdarstellung und Behandlung durch andere bleiben getrennt.","Prüfen Sie, wessen Perspektive diese Aussage zeigt.")}/>} 
    {session.round===9&&<TransferRound session={session} onCheck={(id,source)=>result(solveTransfer(session,id,source),"Die Figurenakte enthält nun Textsignal, Beobachtung und Schlussfolgerung.","Diese Schlussfolgerung braucht einen anderen Beleg aus dem Ausschnitt.")}/>} 
    {session.round===10&&<ComparisonRound session={session} onAssign={(id,target)=>result(compareSituations(session,id,target),"Die Aussage bleibt an Situation und Kontext gebunden.","Vermeiden Sie eine starre Entwicklungsschablone.")}/>} 
    {session.round===11&&<EnsembleRound session={session} onConnect={(from,to,source)=>result(connectEnsemble(session,from,to,source),"Die Verbindung ist textgestützt rekonstruiert.","Figurenpaar, Beziehungsrichtung und Textbeleg passen noch nicht zusammen.")}/>} 
    <p className="ensemble-feedback" role="status" aria-live="polite">{feedback}</p>
   </section>
  </section>
 </main>
}

function Lorenzo({children}:{children:ReactNode}){return <div className="ensemble-lorenzo-speech"><strong>Bruder Lorenzo</strong><p>{children}</p></div>}
function Opening({onNext}:{onNext:()=>void}){return <div className="ensemble-scene opening"><Lorenzo>Das Regiebuch ist wieder lesbar. Aber Namen auf einer Seite erzählen noch nicht, wer ein Mensch ist. Eine Figur verrät selten einfach, wer sie ist. Man muss beobachten, was sie sagt, was sie tut und wie andere auf sie reagieren. Sehen wir uns das Ensemble genauer an.</Lorenzo><div className="method-sequence"><strong>Text</strong><span>↓</span><strong>Beobachtung</strong><span>↓</span><strong>Erschließung</strong><span>↓</span><strong>Charakterisierung</strong></div><button className="chapter-primary-action" onClick={onNext}>Erste Figurenakte öffnen</button></div>}
function PracticeText(){return <article className="practice-dialogue"><span className="source-badge practice">Übungstext · nicht von Shakespeare</span>{practiceLines.map((line,index)=><p key={index}>{line.speaker&&<strong>{line.speaker}: </strong>}{line.text}</p>)}</article>}
function PracticeRound({session,onAssign}:{session:Chapter02Session;onAssign:(id:string,target:Certainty)=>void}){return <div className="ensemble-scene"><div className="task-slip"><h2>Was verrät eine Figur?</h2><p>Untersuchen Sie Leon. Entscheiden Sie, wie sicher sich jede Aussage aus dem Text ableiten lässt.</p></div><PracticeText/><CardAssignment items={practiceClaims} assignments={session.practiceAssignments} zones={Object.entries(certaintyLabels).map(([id,label])=>({id,label}))} onAssign={onAssign}/></div>}
function CharacterizationRound({session,onAssign}:{session:Chapter02Session;onAssign:(id:string,target:"direct"|"indirect")=>void}){return <div className="ensemble-scene"><div className="dossier-folds"><article><h3>Direkte Charakterisierung</h3><p>Eine Eigenschaft oder Einschätzung wird ausdrücklich über eine Figur formuliert.</p></article><article><h3>Indirekte Charakterisierung</h3><p>Eine mögliche Eigenschaft wird aus Rede, Verhalten, Entscheidungen, Handlungen oder Reaktionen erschlossen.</p></article></div><CardAssignment items={characterizationCards} assignments={session.characterizationAssignments} zones={[{id:"direct",label:"Direkt"},{id:"indirect",label:"Indirekt"}]} onAssign={onAssign}/><Lorenzo>Eine einzelne Handlung kann viel verraten. Aber sie beweist noch keinen dauerhaften Charakterzug. Figurenanalyse beginnt beim Text, nicht beim Etikett.</Lorenzo></div>}
function PrimaryDossier({ids,buttons,onMark}:{ids:readonly string[];buttons?:boolean;onMark?:(id:string)=>void}){return <article className="ensemble-primary"><span className="source-badge original">Originaltext · Wieland-Ausgabe</span>{ids.map(id=>buttons?<button key={id} onClick={()=>onMark?.(id)}>{chapter02PrimaryById(id).text}</button>:<p key={id}>{chapter02PrimaryById(id).text}</p>)}</article>}
function JuliettePortrait(){return <figure className="dossier-portrait" aria-label="Juliette"><AssetImage id="character_julia_thoughtful" decorative fallback={<span aria-hidden="true">J</span>}/><figcaption>Juliette</figcaption></figure>}
function MainContext(){return <article className="context-leaf"><span>Hinführung</span><p>Juliette ist die Tochter der Familie Capulet. Ihre Mutter möchte mit ihr über eine mögliche Heirat sprechen. Paris, ein junger Adeliger, interessiert sich für Juliette.</p><strong>Achten Sie darauf, was Juliette selbst sagt und wie sie auf die Erwartungen ihrer Umgebung reagiert.</strong></article>}
function MainAnalysis({session,onMark}:{session:Chapter02Session;onMark:(id:string)=>void}){return <div className="ensemble-scene"><div className="dossier-with-portrait"><JuliettePortrait/><MainContext/></div><div className="task-slip"><h2>Textsignale sammeln</h2><p>Markieren Sie Juliettes zwei Äußerungen, die ihre Haltung in dieser Situation erkennen lassen.</p></div><PrimaryDossier ids={mainSourceIds} buttons onMark={onMark}/><div className="signal-ledger">{highlightTasks.map(t=><article className={session.highlights.includes(t.sourceId)?"revealed":""} key={t.id}><strong>{session.highlights.includes(t.sourceId)?t.observation:"Textsignal noch offen"}</strong>{session.highlights.includes(t.sourceId)&&<p>{t.characterization}</p>}</article>)}</div></div>}
function MomentRound({session,onAssign}:{session:Chapter02Session;onAssign:(id:string,target:"supported"|"uncertain"|"unsupported")=>void}){return <div className="ensemble-scene"><MainContext/><PrimaryDossier ids={mainSourceIds}/><div className="task-slip"><h2>Eigenschaft oder Momentaufnahme?</h2><p>Wie weit trägt dieser eine Ausschnitt?</p></div><CardAssignment items={momentClaims} assignments={session.momentAssignments} zones={[{id:"supported",label:"Gut gestützt"},{id:"uncertain",label:"Möglich, aber unsicher"},{id:"unsupported",label:"Nicht gestützt"}]} onAssign={onAssign}/><blockquote>Figuren zeigen sich in Situationen. Ein einzelner Ausschnitt kann eine Charakterisierung stützen, aber selten eine ganze Persönlichkeit beweisen.</blockquote></div>}
function RoleRound({session,onAssign}:{session:Chapter02Session;onAssign:(id:string,target:AnalysisKind)=>void}){return <div className="ensemble-scene"><div className="dossier-folds four"><article><h3>Ziel</h3><p>Was möchte die Figur hier erreichen?</p></article><article><h3>Motiv</h3><p>Warum möchte sie das?</p></article><article><h3>Interesse / Bedürfnis</h3><p>Was ist ihr wichtig?</p></article><article><h3>Nicht sicher</h3><p>Was trägt der Ausschnitt nicht?</p></article></div><PrimaryDossier ids={["c02_main_juliette_honor","c02_main_juliette_answer"]}/><CardAssignment items={roleTasks.map(x=>({id:x.id,text:x.observation}))} assignments={session.roleAssignments} zones={[{id:"goal",label:"Ziel"},{id:"motive",label:"Motiv"},{id:"interest",label:"Interesse / Bedürfnis"},{id:"unknown",label:"Nicht sicher feststellbar"}]} onAssign={onAssign}/></div>}
function RelationshipRound({session,onCheck}:{session:Chapter02Session;onCheck:(id:string,source:string)=>void}){return <div className="ensemble-scene"><div className="relationship-portraits"><Person id="character_julia_calm" name="Juliette"/><span aria-hidden="true">⇄</span><Person id="character_lady_capulet" name="Lady Capulet"/></div><p>Eine Beziehung hat zwei Richtungen. Verankern Sie jede Aussage mit dem passenden Textsignal.</p>{relationshipTasks.map(task=><EvidenceSelect key={task.id} title={`${task.from} → ${task.to} · ${task.axis}`} description={`${task.observation} ${task.statement}`} done={session.relationshipSteps.includes(task.id)} options={mainSourceIds} onCheck={source=>onCheck(task.id,source)}/>)}</div>}
function SelfOtherRound({session,onAssign}:{session:Chapter02Session;onAssign:(id:string,target:"self"|"other")=>void}){return <div className="ensemble-scene"><div className="task-slip"><h2>Selbstbild und Fremdbild</h2><p>Wie zeigt sich Juliette selbst – und wie wird sie von ihrer Mutter behandelt?</p></div><PrimaryDossier ids={mainSourceIds}/><CardAssignment items={selfOtherTasks} assignments={session.selfOtherAssignments} zones={[{id:"self",label:"So zeigt sich die Figur"},{id:"other",label:"So erscheint sie anderen"}]} onAssign={onAssign}/></div>}
function TransferRound({session,onCheck}:{session:Chapter02Session;onCheck:(id:string,source:string)=>void}){return <div className="ensemble-scene"><div className="task-slip"><span>Die Figurenakte</span><h2>Eine spätere Situation selbstständig analysieren</h2><p>Seit dem ersten Gespräch ist Zeit vergangen. Juliettes Familie plant nun eine Hochzeit mit Paris. Juliette lehnt diese Verbindung ab. Der Ausschnitt zeigt ihre Reaktion auf die Erwartungen ihrer Familie.</p><strong>Nutzen Sie nur Aussagen, die sich am Text belegen oder nachvollziehbar erschließen lassen.</strong></div><PrimaryDossier ids={transferSourceIds}/><div className="transfer-dossiers">{transferTasks.map(task=><EvidenceSelect key={task.id} title={task.category} description={`${task.observation} → ${task.conclusion}`} done={session.transferSteps.includes(task.id)} options={transferSourceIds} onCheck={source=>onCheck(task.id,source)}/>)}</div></div>}
function ComparisonRound({session,onAssign}:{session:Chapter02Session;onAssign:(id:string,target:"early"|"late"|"conclusion")=>void}){return <div className="ensemble-scene"><div className="task-slip"><h2>Zeigt sich Juliette in beiden Situationen gleich?</h2><p>Ordnen Sie Beobachtungen und die fachlich vorsichtigste Schlussfolgerung.</p></div><CardAssignment items={comparisonCards} assignments={session.comparisonAssignments} zones={[{id:"early",label:"Frühere Situation"},{id:"late",label:"Spätere Situation"},{id:"conclusion",label:"Vorsichtige Schlussfolgerung"}]} onAssign={onAssign}/></div>}
function EnsembleRound({session,onConnect}:{session:Chapter02Session;onConnect:(from:string,to:string,source:string)=>void}){const [from,setFrom]=useState("");const [to,setTo]=useState("");const [source,setSource]=useState("");const people=[{name:"Juliette",asset:"character_julia_calm"},{name:"Lady Capulet",asset:"character_lady_capulet"},{name:"Capulet",asset:"character_capulet"},{name:"Amme",asset:"character_amme"}];return <div className={`ensemble-scene ensemble-restoration ${session.completed?"restored":""}`}><h2>Ensemblewand rekonstruieren</h2><p>Wählen Sie Figur, Ziel und einen Textbeleg. Die Verbindungslinien besitzen zusätzlich eine lesbare Textfassung.</p><div className="final-portraits">{people.map(p=><Person key={p.name} id={p.asset} name={p.name}/>)}</div><div className="connection-builder"><label>Ausgangsfigur<select value={from} onChange={e=>setFrom(e.target.value)}><option value="">Bitte wählen</option>{people.map(p=><option key={p.name}>{p.name}</option>)}</select></label><label>Ziel<select value={to} onChange={e=>setTo(e.target.value)}><option value="">Bitte wählen</option>{people.map(p=><option key={p.name}>{p.name}</option>)}</select></label><label>Beleg<select value={source} onChange={e=>setSource(e.target.value)}><option value="">Bitte wählen</option>{transferSourceIds.map(id=><option key={id} value={id}>{chapter02PrimaryById(id).text.slice(0,75)}…</option>)}</select></label><button disabled={!from||!to||!source} onClick={()=>onConnect(from,to,source)}>Verbindung eintragen</button></div><ol className="restored-connections">{ensembleLinks.map(link=><li className={session.ensembleConnections.includes(link.id)?"complete":""} key={link.id}><strong>{link.from} → {link.to}</strong><span>{session.ensembleConnections.includes(link.id)?link.label:"Verbindung noch unterbrochen"}</span></li>)}</ol>{session.completed&&<><div className="method-sequence"><strong>Text</strong><span>↓</span><strong>Beobachtung</strong><span>↓</span><strong>Erschließung</strong><span>↓</span><strong>Charakterisierung</strong></div><blockquote>Eine Figurenanalyse behauptet nicht. Sie belegt und deutet.</blockquote><Lorenzo>Nun kennen wir die Spieler besser. Aber Figuren stehen nicht einfach nebeneinander. Sie sprechen miteinander, weichen aus, greifen an, überzeugen, schweigen und verfolgen ihre eigenen Ziele. Hören wir genauer hin.</Lorenzo></>}</div>}
function Person({id,name}:{id:string;name:string}){return <figure className="ensemble-person" aria-label={name}><AssetImage id={id} decorative fallback={<span aria-hidden="true">{name.slice(0,1)}</span>}/><figcaption>{name}</figcaption></figure>}
function EvidenceSelect({title,description,done,options,onCheck}:{title:string;description:string;done:boolean;options:readonly string[];onCheck:(source:string)=>void}){const[source,setSource]=useState("");return <article className={`evidence-entry ${done?"done":""}`}><h3>{title}</h3><p>{description}</p>{done?<strong>Textbezug gesichert</strong>:<><label>Passender Originaltext<select value={source} onChange={e=>setSource(e.target.value)}><option value="">Bitte wählen</option>{options.map(id=><option key={id} value={id}>{chapter02PrimaryById(id).text.slice(0,90)}…</option>)}</select></label><button disabled={!source} onClick={()=>onCheck(source)}>Beleg prüfen</button></>}</article>}
function CardAssignment<T extends string>({items,assignments,zones,onAssign}:{items:readonly {id:string;text:string}[];assignments:Record<string,T>;zones:readonly {id:string;label:string}[];onAssign:(id:string,target:T)=>void}){const[selected,setSelected]=useState<string|null>(null);return <div className="card-assignment"><div className="assignment-cards">{items.filter(item=>!assignments[item.id]).map(item=><button key={item.id} aria-pressed={selected===item.id} onClick={()=>setSelected(item.id)}>{item.text}</button>)}</div><div className="assignment-zones">{zones.map(zone=><button key={zone.id} disabled={!selected} onClick={()=>selected&&onAssign(selected,zone.id as T)}><strong>{zone.label}</strong><small>{Object.values(assignments).filter(v=>v===zone.id).length} eingeordnet</small></button>)}</div></div>}
