"use client";
import {useEffect,useState,type ReactNode} from "react";
import {hydrateSession} from "../../../core/state/hydrateSession";
import type {GameState} from "../../../core/state/types";
import {AssetImage} from "../../../shared/components/AssetImage";
import {chapter03Source,comparisonTasks,findingTasks,goalChange,goalTasks,languageTasks,mainSections,practiceActs,practiceDialogue,speechTasks,transferSections,transferTasks,turningPoints} from "../data/chapter_03_content";
import { PrimarySourceText } from "../../../shared/components/PrimarySourceText";
import {GlossaryHelp} from "../../../shared/components/GlossaryHelp";
import {SceneCharacters} from "../../../shared/components/SceneCharacters";
import {glossaryFor} from "../data/glossary";
import {analyzeGoalChange,assignPracticeAct,assignPracticeGoal,chooseTurningPoint,classifyFinding,compareDialogues,connectSpeechChain,initialChapter03Session,linkGoalEvidence,setPhaseOrder,solveFinal,solveLanguage,solveTransfer,type Chapter03Session} from "../mechanics/chapter_03_engine";

type Props={gameState:GameState;onSave:(s:Chapter03Session)=>void;onExit:()=>void;onComplete:(s:Chapter03Session)=>void};
export function Chapter03({gameState,onSave,onExit,onComplete}:Props){
 const[session,setSession]=useState<Chapter03Session>(()=>hydrateSession(gameState.decisions.chapter_03,initialChapter03Session,12));
 const[feedback,setFeedback]=useState("Die Bühne ist bereit, doch die Gesprächslinien fehlen noch.");
 useEffect(()=>{document.querySelector(".dialogue-task")?.scrollIntoView({block:"start",behavior:"auto"})},[session.round]);
 const update=(n:Chapter03Session,ok:boolean)=>{setSession(n);onSave(n);setFeedback(ok?"Der Zusammenhang ist textnah rekonstruiert.":"Prüfen Sie Textstelle, Handlung und Gesprächsziel noch einmal. Sie können die Auswahl korrigieren.")};
 const act=(id:string,v:string)=>{const r=assignPracticeAct(session,id,v);update(r.session,r.valid)};
 const goal=(id:string,v:string)=>{const r=assignPracticeGoal(session,id,v);update(r.session,r.valid)};
 const finish=(steps:string[])=>{const r=solveFinal(session,steps);update(r.session,r.valid);if(r.valid)onComplete(r.session)};
 return <main className="chapter-shell chapter-three"><header className="chapter-header"><button onClick={onExit}>← Theater</button><div><p>Kapitel 3 · Probenbühne</p><h1>Die Stimmen auf der Bühne</h1><small>Dialoge und Gesprächsentwicklungen analysieren</small></div><span>Probe {session.round} von 12</span></header>
 <section className="dialogue-stage"><AssetImage id="bg_analysis_room" className="asset-backdrop" decorative/><SceneCharacters sceneId={session.round>=11?"chapter_03.garden":"chapter_03.conflict"}/><div className="dialogue-line" aria-hidden="true"><span>Gesprächsziel</span><b>→</b><span>Sprachhandlung</span><b>→</b><span>Reaktion</span><b>→</b><span>Entwicklung</span><b>→</b><span>Wirkung</span></div></section>
 {session.round>=2&&<GlossaryHelp entries={glossaryFor("chapter_03")} introTitle="Werkzeuge der Dialoganalyse" seen={session.seenGlossaryIntroductions.includes("chapter_03")||session.round>2} onSeen={()=>{const n={...session,seenGlossaryIntroductions:[...new Set([...session.seenGlossaryIntroductions,"chapter_03"])]};setSession(n);onSave(n)}}/>}
 <section className="dialogue-workbench"><aside className="lorenzo-guide"><AssetImage id="character_lorenzo_blessing" className="character-image" fallback={<span>L</span>}/><strong>Bruder Lorenzo</strong><p>{prompts[session.round]}</p></aside><section className="dialogue-task">{session.round===1&&<Intro onNext={()=>{const n={...session,round:2 as const};setSession(n);onSave(n)}}/>}{session.round===2&&<PracticeActs session={session} onAssign={act}/>} {session.round===3&&<PracticeGoals session={session} onAssign={goal}/>} {session.round===4&&<GoalRound session={session} onChoose={(id,source)=>{const r=linkGoalEvidence(session,id,source);update(r.session,r.valid)}}/>} {session.round===5&&<Choice title="Vergleichen Sie Romeos Ziel in zwei Abschnitten." options={[goalChange.answer,"bleibt_gleich","nicht_sicher_feststellbar"]} onChoose={v=>{const r=analyzeGoalChange(session,v,goalChange.first,goalChange.second);update(r.session,r.valid)}}><Source id={goalChange.first}/><Source id={goalChange.second}/></Choice>} {session.round===6&&<SpeechRound session={session} onSolve={(id,a,re)=>{const r=connectSpeechChain(session,id,a,re);update(r.session,r.valid)}}/>} {session.round===7&&<PhaseRound onSolve={ids=>{const r=setPhaseOrder(session,ids);update(r.session,r.valid)}}/>} {session.round===8&&<Choice title="Wo wird aus sprachlicher Zuspitzung ausdrücklich Bühnenhandlung?" options={turningPoints.map(x=>x.id)} onChoose={id=>{const item=turningPoints.find(x=>x.id===id)!;const r=chooseTurningPoint(session,id,item.sourceId);update(r.session,r.valid)}}>{turningPoints.map(x=><Source key={x.id} id={x.sourceId}/>)}</Choice>} {session.round===9&&<LanguageRound session={session} onSolve={(id,f,e)=>{const r=solveLanguage(session,id,f,e);update(r.session,r.valid)}}/>} {session.round===10&&<FindingRound session={session} onSolve={(id,t)=>{const r=classifyFinding(session,id,t);update(r.session,r.valid)}}/>} {session.round===11&&<TransferRound session={session} onSolve={(id,sid)=>{const r=solveTransfer(session,id,sid);update(r.session,r.valid)}}/>} {session.round===12&&<FinalRound session={session} onCompare={(id,t)=>{const r=compareDialogues(session,id,t);update(r.session,r.valid)}} onFinish={finish}/>}<p className="dialogue-feedback" role="status">{feedback}</p></section></section></main>;
}
function Source({id}:{id:string}){const s=chapter03Source(id);return <span className={`source-card ${s.fragment_type==="stage_direction"?"stage-direction":""}`}><small>{s.fragment_type==="stage_direction"?"ORIGINALE BÜHNENANGABE":"ORIGINALTEXT"}</small><PrimarySourceText record={s}/></span>}
function Intro({onNext}:{onNext:()=>void}){return <div><h2>Eine Bühne beginnt zu sprechen</h2><p>Zwischen Montague und Capulet besteht eine alte Feindschaft. Mercutio ist mit Romeo befreundet. Tybalt gehört zur Familie Capulet und sucht Romeo. Untersuchen Sie, wie sich das Gespräch Schritt für Schritt verändert.</p><button onClick={onNext}>Allgemeine Dialogprobe beginnen</button></div>}
function PracticeActs({session,onAssign}:{session:Chapter03Session;onAssign:(id:string,v:string)=>void}){return <div><h2>Was tun die Figuren mit ihren Äußerungen?</h2><div className="practice-dialogue">{practiceDialogue.map((l,i)=><p key={i}><strong>{l.speaker}:</strong> {l.text}</p>)}</div>{practiceActs.filter(x=>!session.practiceActs[x.id]).map(x=><Choice key={x.id} title={practiceDialogue[x.line].text} options={x.actOptions} onChoose={v=>onAssign(x.id,v)}/>)}</div>}
function PracticeGoals({session,onAssign}:{session:Chapter03Session;onAssign:(id:string,v:string)=>void}){return <div><h2>Sprachhandlung ist nicht Gesprächsziel</h2><p>Was eine Figur sprachlich tut, ist nicht dasselbe wie das, was sie damit im Gespräch erreichen möchte.</p>{practiceActs.filter(x=>!session.practiceGoals[x.id]).map(x=><Choice key={x.id} title={`${practiceDialogue[x.line].text} · ${x.act}`} options={x.goalOptions} onChoose={v=>onAssign(x.id,v)}/>)}</div>}
function GoalRound({session,onChoose}:{session:Chapter03Session;onChoose:(id:string,s:string)=>void}){const task=goalTasks.find(x=>!session.goalEvidence[x.id]);return <div><h2>Wer will in diesem Abschnitt was?</h2>{task&&<><p><strong>{task.goal}</strong></p>{mainSections.filter(s=>s.id===task.sectionId).flatMap(s=>s.sourceIds).map(id=><button className="source-button" key={id} onClick={()=>onChoose(task.id,id)}><Source id={id}/></button>)}</>}</div>}
function SpeechRound({session,onSolve}:{session:Chapter03Session;onSolve:(id:string,a:string,r:string)=>void}){const t=speechTasks.find(x=>!session.speechChains.includes(x.id));return <div><h2>Textstelle → Sprachhandlung → Reaktion</h2>{t&&<><Source id={t.sourceId}/><Choice title="Sprachhandlung und passende Reaktion verbinden" options={t.options.map(option=>`${option.act}|${option.reactionId}`)} labels={t.options.map(option=>option.label)} onChoose={v=>{const[a,r]=v.split("|");onSolve(t.id,a,r)}}/></>}</div>}
function PhaseRound({onSolve}:{onSolve:(ids:string[])=>void}){const[order,setOrder]=useState<string[]>([]);return <div><h2>Gesprächsphasen selbst bilden</h2><p>Wählen Sie die Abschnitte in der Reihenfolge, in der Ziel, Ton und Handlung wechseln.</p><div className="dialogue-options">{[...mainSections].reverse().map(s=><button key={s.id} disabled={order.includes(s.id)} onClick={()=>setOrder([...order,s.id])}>{s.label}<small>{s.summary}</small></button>)}</div><p>Gesprächsinitiative: {order.map(id=>mainSections.find(s=>s.id===id)?.label).join(" → ")||"noch offen"}</p><button onClick={()=>onSolve(order)}>Gesprächslinie prüfen</button></div>}
function LanguageRound({session,onSolve}:{session:Chapter03Session;onSolve:(id:string,f:string,e:string)=>void}){const t=languageTasks.find(x=>!session.languageChains.includes(x.id));return <div><h2>Sprachliche Auffälligkeit → Wirkung → Funktion</h2>{t&&<><Source id={t.sourceId}/><Choice title={t.function} options={[`${t.feature}|${t.effect}`,`${t.feature}|Fragen zeigen immer Unsicherheit.`,`Stilmittel benennen|${t.effect}`]} labels={[`${t.feature} → ${t.effect}`,`${t.feature} → starre Wirkungsregel`,`nur benennen, ohne Funktion`]} onChoose={v=>{const[f,e]=v.split("|");onSolve(t.id,f,e)}}/></>}</div>}
function FindingRound({session,onSolve}:{session:Chapter03Session;onSolve:(id:string,t:string)=>void}){const item=findingTasks.find(x=>!session.findingAssignments[x.id]);return <div><h2>Textbefund oder mögliche Inszenierung?</h2>{item&&<Choice title={item.text} options={["text","staging","unsupported"]} labels={["IM TEXT BELEGT","ALS INSZENIERUNG MÖGLICH","NICHT BELEGT"]} onChoose={v=>onSolve(item.id,v)}><Source id={item.sourceId}/></Choice>}</div>}
function TransferRound({session,onSolve}:{session:Chapter03Session;onSolve:(id:string,s:string)=>void}){const t=transferTasks.find(x=>!session.transferEvidence[x.id]);return <div><h2>Die Regieprobe</h2><p>Romeo befindet sich nachts im Garten der Capulets. Juliette weiß zunächst nicht, dass er sie hören kann. Rekonstruieren Sie die Entwicklung und belegen Sie jede Aussage.</p>{transferSections.map(s=><article className="transfer-section" key={s.id}><strong>{s.id.replace("transfer_","Abschnitt ").toUpperCase()}</strong>{s.sourceIds.map(id=><Source key={id} id={id}/>)}</article>)}{t&&<><p>{t.claim}</p><div className="dialogue-options">{transferSections.flatMap(s=>s.sourceIds).map(id=><button key={id} onClick={()=>onSolve(t.id,id)}><Source id={id}/></button>)}</div></>}</div>}
function FinalRound({session,onCompare,onFinish}:{session:Chapter03Session;onCompare:(id:string,t:string)=>void;onFinish:(ids:string[])=>void}){const[steps,setSteps]=useState<string[]>([]);const pending=comparisonTasks.find(x=>!session.comparisonAssignments[x.id]);return <div><h2>Restauriertes Dialogprotokoll</h2>{pending?<Choice title={pending.text} options={[pending.target,pending.target==="main"?"transfer":"main","nicht_sicher"]} labels={[pending.target==="main"?"KONFLIKTDIALOG":pending.target==="transfer"?"ANNÄHERUNGSDIALOG":"BEIDE DIALOGE","ANDERE ZUORDNUNG","NICHT SICHER FESTSTELLBAR"]} onChoose={v=>onCompare(pending.id,v)}/>:<><p>Mini-Analyse eines bisher nicht geführten Zusammenhangs: Gesprächsziel → Sprachhandlung → Reaktion → Wirkung → Beleg.</p>{["c03_transfer_juliette_danger","c03_transfer_romeo_love","c03_transfer_juliette_concern"].map(id=><button className="source-button" disabled={steps.includes(id)} key={id} onClick={()=>setSteps([...steps,id])}><Source id={id}/></button>)}<p>{steps.length} von 3 Belegen verbunden</p><button onClick={()=>onFinish(steps)}>Dialogprotokoll abschließen</button></>}</div>}
function Choice({title,options,labels,children,onChoose}:{title:string;options:readonly string[];labels?:readonly string[];children?:ReactNode;onChoose:(v:string)=>void}){const visible=(o:string,i:number)=>labels?.[i]??(o==="turn_draw"?"Tybalt zieht den Degen":o==="turn_fight"?"Mercutio und Tybalt beginnen zu fechten":o.replaceAll("_"," "));return <fieldset className="dialogue-choice"><legend>{title}</legend>{children}<div>{options.map((o,i)=><button key={o} onClick={()=>onChoose(o)}>{visible(o,i)}</button>)}</div></fieldset>}
const prompts=["","Die Figuren stehen bereit. Rekonstruieren Sie nun ihre Gesprächsrichtungen.","Benennen Sie zuerst, was mit den Worten getan wird.","Fragen Sie danach: Was soll damit im Gespräch erreicht werden?","Gesprächsziele gelten für einen Abschnitt, nicht für eine Figur für immer.","Ein Ziel kann sich verändern. Zwei Textstellen sichern den Vergleich.","Eine Sprachhandlung wirkt erst durch die Reaktion des Gegenübers.","Ordnen Sie die Abschnitte zu einer Gesprächslinie.","Markieren Sie einen textgestützten Übergang von Wort zu Handlung.","Ein sprachliches Mittel ist erst mit Wirkung und Funktion analysiert.","Mögliche Inszenierung ist kein Originalbefund.","Übertragen Sie die Werkzeuge auf einen Dialog der Annäherung.","Vergleichen und sichern Sie eine eigenständige Mini-Analyse."];
