"use client";
import {useEffect,useState,type ReactNode} from "react";
import {hydrateSession} from "../../../core/state/hydrateSession";
import type {GameState} from "../../../core/state/types";
import {AssetImage} from "../../../shared/components/AssetImage";
import {PrimarySourceText} from "../../../shared/components/PrimarySourceText";
import {GlossaryHelp} from "../../../shared/components/GlossaryHelp";
import {SceneCharacters} from "../../../shared/components/SceneCharacters";
import {glossaryFor} from "../data/glossary";
import {chapter03Source,comparisonTasks,findingTasks,goalChange,goalTasks,languageTasks,mainSections,miniAnalysis,neutralBoundary,neutralLanguage,neutralPhases,practiceActs,practiceConversationModel,practiceDialogue,speechTasks,stageEffectTask,transferSections,transferTasks,turningPoints} from "../data/chapter_03_content";
import {analyzeGoalChange,analyzeStageEffect,assignPracticeAct,assignPracticeGoal,chooseTurningPoint,classifyFinding,compareDialogues,connectSpeechChain,initialChapter03Session,justifyNeutralBoundary,justifyPhaseBoundary,linkGoalEvidence,setNeutralModel,setNeutralPhases,setPhaseOrder,solveFinal,solveLanguage,solveMiniAnalysis,solveNeutralLanguage,solveTransfer,type Chapter03Session} from "../mechanics/chapter_03_engine";

type Props={gameState:GameState;onSave:(s:Chapter03Session)=>void;onExit:()=>void;onComplete:(s:Chapter03Session)=>void};
export function Chapter03({gameState,onSave,onExit,onComplete}:Props){
 const[session,setSession]=useState<Chapter03Session>(()=>hydrateSession(gameState.decisions.chapter_03,initialChapter03Session,16));
 const[feedback,setFeedback]=useState("Entscheidend ist der Zusammenhang, nicht ein einzelner Fachbegriff.");
 useEffect(()=>{document.querySelector(".dialogue-task")?.scrollIntoView({block:"start",behavior:"auto"})},[session.round]);
 const save=(n:Chapter03Session)=>{setSession(n);onSave(n)};
 const update=(r:{valid:boolean;session:Chapter03Session},good="Der Zusammenhang ist tragfähig begründet.",bad="Ein Teil der Kette trägt noch nicht. Prüfen Sie Äußerung, Reaktion und Veränderung.")=>{save(r.session);setFeedback(r.valid?good:bad)};
 const finish=(steps:string[])=>{const r=solveFinal(session,steps);update(r,"Die Stimmen sind geordnet.");if(r.valid)onComplete(r.session)};
 return <main className="chapter-shell chapter-three"><header className="chapter-header chapter-three-header"><button onClick={onExit}>← Theater</button><div><p>Kapitel 3 · Probenbühne</p><h1>Die Stimmen auf der Bühne</h1><small>Dialoge als Handlung und Entwicklung analysieren</small></div><span>Probe {session.round} von 16</span></header>
 {session.round===1?<Opening onNext={()=>save({...session,round:2})}/>:<><div className="dialogue-tools"><GlossaryHelp entries={glossaryFor("chapter_03")} introTitle="Werkzeuge der Dialoganalyse" seen={session.seenGlossaryIntroductions.includes("chapter_03")} onSeen={()=>save({...session,seenGlossaryIntroductions:[...new Set([...session.seenGlossaryIntroductions,"chapter_03"])]})}/></div><section className="dialogue-workbench"><aside className="dialogue-guide"><strong>Regiehinweis</strong><p>{prompts[session.round]}</p></aside><section className="dialogue-task">
 {session.round===2&&<OrderTask title="Dialog ist Handlung" intro="Bauen Sie das Grundmodell aus dem neutralen Dialog auf." items={practiceConversationModel} onSolve={ids=>update(setNeutralModel(session,ids))}/>}
 {session.round===3&&<PracticeActs session={session} onAssign={(id,v)=>update(assignPracticeAct(session,id,v),"Die Sprachhandlung beschreibt, was mit den Worten getan wird.","Benennen Sie die unmittelbare sprachliche Handlung, nicht das Fernziel.")}/>}
 {session.round===4&&<PracticeGoals session={session} onAssign={(id,v)=>update(assignPracticeGoal(session,id,v),"Das Gesprächsziel beschreibt, was die Figur erreichen möchte.","Fragen Sie nach der beabsichtigten Veränderung, nicht nach der Sprachhandlung.")}/>}
 {session.round===5&&<OrderTask title="Gespräch als Verlauf" intro="Ordnen Sie funktionale Gesprächsphasen. Nicht jede Äußerung bildet eine eigene Phase." items={[...neutralPhases].reverse()} onSolve={ids=>update(setNeutralPhases(session,ids))}/>}
 {session.round===6&&<BoundaryTask onSolve={(a,r)=>update(justifyNeutralBoundary(session,a,r),"Die Phasengrenze ist durch den Strategiewechsel begründet.","Eine Phasengrenze braucht eine Veränderung von Ziel, Ton, Initiative, Beziehung oder Handlung.")}/>}
 {session.round===7&&<NeutralLanguage onSolve={(f,e,fn)=>update(solveNeutralLanguage(session,f,e,fn))}/>}
 {session.round===8&&<MainGoals session={session} onChoose={(id,source)=>update(linkGoalEvidence(session,id,source),"Gesprächsziel und vollständiger Textbeleg passen zusammen.")}/>}
 {session.round===9&&<GoalChangeRound onSolve={(v,a,b)=>update(analyzeGoalChange(session,v,a,b),"Die Veränderung ist durch beide Textstellen abgesichert.","Bestimmen Sie beide Ziele getrennt und vergleichen Sie erst danach.")}/>}
 {session.round===10&&<SpeechRound session={session} onSolve={(id,a,re)=>update(connectSpeechChain(session,id,a,re))}/>}
 {session.round===11&&<MainPhaseRound session={session} onOrder={ids=>update(setPhaseOrder(session,ids),"Die Chronologie stimmt. Begründen Sie nun eine Phasengrenze.")} onBoundary={(a,r)=>update(justifyPhaseBoundary(session,a,r))}/>}
 {session.round===12&&<TurningPointRound onSolve={(id,s,c)=>update(chooseTurningPoint(session,id,s,c),"Der Kandidat ist durch eine Veränderung des Verlaufs begründet.","Dramatik allein genügt nicht: Benennen Sie, was davor gilt und danach anders ist.")}/>}
 {session.round===13&&<LanguageRound session={session} onSolve={(id,f,e)=>update(solveLanguage(session,id,f,e))}/>}
 {session.round===14&&<StageRound session={session} onClassify={(id,t)=>update(classifyFinding(session,id,t))} onEffect={(s,e)=>update(analyzeStageEffect(session,s,e))}/>}
 {session.round===15&&<OrderTask title="Mini-Dialoganalyse" intro="Bauen Sie: Behauptung → Textbeleg → Analyse → Wirkung/Funktion." items={[miniAnalysis[2],miniAnalysis[0],miniAnalysis[3],miniAnalysis[1]]} onSolve={ids=>update(solveMiniAnalysis(session,ids),"Die Analyse verbindet Behauptung, Beleg, Analyse und Funktion.")}/>}
 {session.round===16&&<TransferFinal session={session} onTransfer={(id,s)=>update(solveTransfer(session,id,s))} onCompare={(id,t)=>update(compareDialogues(session,id,t))} onFinish={finish}/>}
 <p className="dialogue-feedback" role="status">{feedback}</p></section></section></>}
 </main>;
}

function Opening({onNext}:{onNext:()=>void}){return <section className="dialogue-opening"><AssetImage id="bg_analysis_room" className="asset-backdrop" decorative/><SceneCharacters sceneId="chapter_03.conflict"/><div className="dialogue-opening-card"><p>Eine Äußerung ist auf der Bühne zugleich Handlung.</p><h2>Wie verändern Ziele, Worte und Reaktionen ein Gespräch?</h2><div className="dialogue-line"><span>Gesprächsziel</span><b>→</b><span>Äußerung</span><b>→</b><span>Sprachhandlung</span><b>→</b><span>Reaktion</span><b>→</b><span>Veränderung</span></div><button onClick={onNext}>Allgemeine Dialogprobe beginnen</button></div></section>}
function Source({id}:{id:string}){const s=chapter03Source(id);return <span className={`source-card ${s.fragment_type==="stage_direction"?"stage-direction":""}`}><small>{s.fragment_type==="stage_direction"?"ORIGINALE BÜHNENANGABE":"ORIGINALTEXT"}</small><PrimarySourceText record={s}/></span>}
function Choice({title,options,children,onChoose}:{title:string;options:readonly {value:string;label:string}[];children?:ReactNode;onChoose:(v:string)=>void}){return <fieldset className="dialogue-choice"><legend>{title}</legend>{children}<div>{options.map(o=><button key={o.value} onClick={()=>onChoose(o.value)}>{o.label}</button>)}</div></fieldset>}
function OrderTask({title,intro,items,onSolve}:{title:string;intro:string;items:readonly {id:string;label?:string;value?:string;text?:string}[];onSolve:(ids:string[])=>void}){const[order,setOrder]=useState<string[]>([]);return <div><h2>{title}</h2><p>{intro}</p><div className="dialogue-options">{items.map(item=><button key={item.id} disabled={order.includes(item.id)} onClick={()=>setOrder([...order,item.id])}><strong>{item.label??item.text}</strong><small>{item.value??item.text}</small></button>)}</div><ol className="chosen-chain">{order.map(id=><li key={id}>{items.find(x=>x.id===id)?.label??items.find(x=>x.id===id)?.text}</li>)}</ol><button className="primary-action" onClick={()=>onSolve(order)}>Gesprächsmodell prüfen</button></div>}
function PracticeActs({session,onAssign}:{session:Chapter03Session;onAssign:(id:string,v:string)=>void}){return <div><h2>Was tut die Figur mit den Worten?</h2><div className="practice-dialogue">{practiceDialogue.map((l,i)=><p key={i}><strong>{l.speaker}:</strong> {l.text}</p>)}</div>{practiceActs.filter(x=>!session.practiceActs[x.id]).map(x=><Choice key={x.id} title={practiceDialogue[x.line].text} options={x.actOptions.map(v=>({value:v,label:v}))} onChoose={v=>onAssign(x.id,v)}/>)}</div>}
function PracticeGoals({session,onAssign}:{session:Chapter03Session;onAssign:(id:string,v:string)=>void}){return <div><h2>Sprachhandlung ist nicht Gesprächsziel</h2><p>Die Sprachhandlung steht fest. Wählen Sie nun, was die Figur damit erreichen möchte.</p>{practiceActs.filter(x=>!session.practiceGoals[x.id]).map(x=><Choice key={x.id} title={`${practiceDialogue[x.line].text} · Sprachhandlung: ${x.act}`} options={x.goalOptions.map(v=>({value:v,label:v}))} onChoose={v=>onAssign(x.id,v)}/>)}</div>}
function BoundaryTask({onSolve}:{onSolve:(a:string,r:string)=>void}){const[after,setAfter]=useState("");return <div><h2>Eine Phasengrenze begründen</h2><Choice title="Nach welchem Schritt verändert sich die Strategie?" options={neutralPhases.slice(0,-1).map(x=>({value:x.id,label:`nach: ${x.label}`}))} onChoose={setAfter}/>{after&&<Choice title="Welche Veränderung begründet die Grenze?" options={[neutralBoundary.reason,...neutralBoundary.distractors].map(v=>({value:v,label:v}))} onChoose={r=>onSolve(after,r)}/>}</div>}
function NeutralLanguage({onSolve}:{onSolve:(f:string,e:string,fn:string)=>void}){const t=neutralLanguage[0];const[f,setF]=useState("");const[e,setE]=useState("");return <div><h2>Benennen reicht nicht</h2><div className="practice-dialogue"><p><strong>MARA:</strong> Dann sieh mich wenigstens an.</p></div><Choice title="1. Sprachlicher Befund" options={[t.finding,"Es liegt ein Stilmittel vor.","Mara ist wütend."].map(v=>({value:v,label:v}))} onChoose={setF}/>{f&&<Choice title="2. Wirkung im konkreten Gespräch" options={[t.effect,"Imperative wirken immer aggressiv.","Die Äußerung beendet das Gespräch."].map(v=>({value:v,label:v}))} onChoose={setE}/>} {e&&<Choice title="3. Funktion für den Verlauf" options={[t.function,"Die Formulierung beschreibt Maras Charakter dauerhaft.","Die Funktion ist nicht vom Kontext abhängig."].map(v=>({value:v,label:v}))} onChoose={fn=>onSolve(f,e,fn)}/>}</div>}
function MainSourcePanel(){return <details className="dialogue-source-panel" open><summary>Geschützten Szenenausschnitt anzeigen</summary><p className="scene-context"><strong>Hinführung:</strong> Montague und Capulet sind verfeindete Familien. Mercutio ist mit Romeo befreundet. Tybalt gehört zur Familie Capulet und sucht Romeo. Die Begegnung findet öffentlich statt.</p>{mainSections.flatMap(x=>x.sourceIds).map(id=><Source key={id} id={id}/>)}</details>}
function MainGoals({session,onChoose}:{session:Chapter03Session;onChoose:(id:string,s:string)=>void}){const task=goalTasks.find(x=>!session.goalEvidence[x.id]);return <div className="text-analysis-layout"><MainSourcePanel/><div className="analysis-panel"><h2>Gesprächsziele am Text</h2>{task&&<><p>Welcher vollständige Textbeleg stützt dieses erschlossene Ziel?</p><strong>{task.goal}</strong><div className="dialogue-options">{mainSections.filter(s=>s.id===task.sectionId).flatMap(s=>s.sourceIds).map(id=><button className="source-button" key={id} onClick={()=>onChoose(task.id,id)}><Source id={id}/></button>)}</div></>}</div></div>}
function GoalChangeRound({onSolve}:{onSolve:(v:string,a:string,b:string)=>void}){const[a,setA]=useState("");const[b,setB]=useState("");return <div className="text-analysis-layout"><MainSourcePanel/><div className="analysis-panel"><h2>Romeos Ziel verändert sich</h2><Choice title="Ziel in Textstelle 1" options={[{value:"beruhigen",label:"Tybalt beruhigen und den Konflikt vermeiden"},{value:"kämpfen",label:"Tybalt zum Kampf bewegen"},{value:"unklar",label:"nicht ausreichend belegt"}]} onChoose={setA}><Source id={goalChange.first}/></Choice>{a&&<Choice title="Ziel in Textstelle 2" options={[{value:"trennen",label:"in den Kampf eingreifen und die Degen trennen"},{value:"fliehen",label:"die Szene verlassen"},{value:"unklar",label:"nicht ausreichend belegt"}]} onChoose={setB}><Source id={goalChange.second}/></Choice>}{b&&<Choice title="Wie ist die Veränderung zu beschreiben?" options={[{value:goalChange.answer,label:"verändert sich"},{value:"bleibt_gleich",label:"bleibt gleich"},{value:"nicht_sicher_feststellbar",label:"nicht sicher feststellbar"}]} onChoose={v=>onSolve(v,a==="beruhigen"?goalChange.first:"",b==="trennen"?goalChange.second:"")}/>}</div></div>}
function SpeechRound({session,onSolve}:{session:Chapter03Session;onSolve:(id:string,a:string,r:string)=>void}){const t=speechTasks.find(x=>!session.speechChains.includes(x.id));return <div className="text-analysis-layout"><MainSourcePanel/><div className="analysis-panel"><h2>Sprachhandlung → Reaktion → Veränderung</h2>{t&&<><Source id={t.sourceId}/><Choice title="Welche Kette ist am Ausschnitt tragfähig?" options={[...t.options.map(o=>({value:`${o.act}|${o.reactionId}`,label:o.label})),{value:"unbelegt|unbelegt",label:"Reaktion im Ausschnitt nicht ausreichend belegt"}]} onChoose={v=>{const[a,r]=v.split("|");onSolve(t.id,a,r)}}/><p><strong>Veränderung:</strong> {t.effect}</p></>}</div></div>}
function MainPhaseRound({session,onOrder,onBoundary}:{session:Chapter03Session;onOrder:(ids:string[])=>void;onBoundary:(a:string,r:string)=>void}){const[order,setOrder]=useState<string[]>(session.phaseOrder);const[after,setAfter]=useState("");return <div><h2>Gesprächslinie und Phasengrenze</h2>{session.phaseOrder.length===0?<><div className="phase-cards">{[...mainSections].reverse().map(s=><button key={s.id} disabled={order.includes(s.id)} onClick={()=>setOrder([...order,s.id])}><strong>{s.label}</strong><small>{s.summary}</small></button>)}</div><button className="primary-action" onClick={()=>onOrder(order)}>Chronologie prüfen</button></>:<><ol className="phase-line">{mainSections.map(s=><li key={s.id}><strong>{s.label}</strong><span>{s.summary}</span></li>)}</ol><Choice title="Phasengrenze wählen" options={mainSections.slice(0,-1).map(x=>({value:x.id,label:`nach ${x.label}`}))} onChoose={setAfter}/>{after&&<Choice title="Grenze begründen" options={["Mercutio übernimmt nach Romeos Beschwichtigungsversuch die Initiative und fordert Tybalt zum Kampf heraus.","Eine neue Figur spricht; deshalb beginnt immer eine neue Phase.","Der Abschnitt ist länger als der vorherige."].map(v=>({value:v,label:v}))} onChoose={r=>onBoundary(after,r)}/>}</>}</div>}
function TurningPointRound({onSolve}:{onSolve:(id:string,s:string,c:string)=>void}){const[selected,setSelected]=useState("");const item=turningPoints.find(x=>x.id===selected);return <div className="text-analysis-layout"><MainSourcePanel/><div className="analysis-panel"><h2>Wendepunkt prüfen</h2><p>Mehrere Kandidaten sind begründbar. Prüfen Sie Davor und Danach.</p><Choice title="Kandidat wählen" options={turningPoints.map(x=>({value:x.id,label:chapter03Source(x.sourceId).text}))} onChoose={setSelected}/>{item&&<><p><strong>Davor:</strong> {item.before}</p><p><strong>Danach:</strong> {item.after}</p><Choice title="Welche Veränderung trägt die Entscheidung?" options={[item.change,"Die Stelle ist besonders dramatisch.","An dieser Stelle spricht eine andere Figur."].map(v=>({value:v,label:v}))} onChoose={c=>onSolve(item.id,item.sourceId,c)}/></>}</div></div>}
function LanguageRound({session,onSolve}:{session:Chapter03Session;onSolve:(id:string,f:string,e:string)=>void}){const t=languageTasks.find(x=>!session.languageChains.includes(x.id));const[f,setF]=useState("");return <div className="text-analysis-layout"><MainSourcePanel/><div className="analysis-panel"><h2>Sprache → Wirkung → Funktion</h2>{t&&<><Source id={t.sourceId}/><Choice title="Sprachlicher Befund" options={[t.feature,"Die Figur spricht auffällig.","Die Figur ist aggressiv."].map(v=>({value:v,label:v}))} onChoose={setF}/>{f&&<Choice title={`Funktion: ${t.function}`} options={[t.effect,"Diese Form wirkt in jedem Dialog gleich.","Die Benennung allein erklärt bereits die Funktion."].map(v=>({value:v,label:v}))} onChoose={e=>onSolve(t.id,f,e)}/>}</>}</div></div>}
function StageRound({session,onClassify,onEffect}:{session:Chapter03Session;onClassify:(id:string,t:string)=>void;onEffect:(s:string,e:string)=>void}){const pending=findingTasks.find(x=>!session.findingAssignments[x.id]);return <div className="text-analysis-layout"><MainSourcePanel/><div className="analysis-panel"><h2>Bühnenhandlung und Inszenierung trennen</h2>{pending?<Choice title={pending.text} options={[{value:"text",label:"TEXTLICH VORGEGEBEN"},{value:"staging",label:"MÖGLICHE INSZENIERUNG"},{value:"unsupported",label:"NICHT AUSREICHEND BELEGT"}]} onChoose={t=>onClassify(pending.id,t)}><Source id={pending.sourceId}/></Choice>:<Choice title="Wie verändert die vorgegebene Bühnenhandlung den Verlauf?" options={[stageEffectTask.effect,stageEffectTask.wrong,"Sie verändert ausschließlich die Beleuchtung."].map(v=>({value:v,label:v}))} onChoose={e=>onEffect(stageEffectTask.sourceId,e)}><Source id={stageEffectTask.sourceId}/></Choice>}</div></div>}
function TransferFinal({session,onTransfer,onCompare,onFinish}:{session:Chapter03Session;onTransfer:(id:string,s:string)=>void;onCompare:(id:string,t:string)=>void;onFinish:(ids:string[])=>void}){const transfer=transferTasks.find(x=>!session.transferEvidence[x.id]);const compare=comparisonTasks.find(x=>!session.comparisonAssignments[x.id]);const[steps,setSteps]=useState<string[]>(session.finalSteps);return <div><h2>Transfer: vorsichtige Annäherung</h2><p>Romeo befindet sich nachts im Garten der Capulets. Juliette weiß zunächst nicht, dass er sie hören kann.</p><details className="dialogue-source-panel" open><summary>Gartenszene anzeigen</summary>{transferSections.map(s=><section key={s.id}><h3>{s.id.replace("transfer_","Abschnitt ").toUpperCase()}</h3>{s.sourceIds.map(id=><Source key={id} id={id}/>)}</section>)}</details>{transfer?<><p><strong>{transfer.claim}</strong></p><div className="dialogue-options">{transferSections.flatMap(s=>s.sourceIds).map(id=><button key={id} onClick={()=>onTransfer(transfer.id,id)}><Source id={id}/></button>)}</div></>:compare?<Choice title={compare.text} options={[{value:"main",label:"KONFLIKTDIALOG"},{value:"transfer",label:"ANNÄHERUNGSDIALOG"},{value:"both",label:"BEIDE DIALOGE"},{value:"nicht_sicher",label:"NICHT SICHER"}]} onChoose={t=>onCompare(compare.id,t)}/>:<><h3>Abschließende Synthese</h3>{["c03_transfer_juliette_danger","c03_transfer_romeo_love","c03_transfer_juliette_concern"].map(id=><button className="source-button" disabled={steps.includes(id)} key={id} onClick={()=>setSteps([...steps,id])}><Source id={id}/></button>)}<button className="primary-action" onClick={()=>onFinish(steps)}>Dialoganalyse abschließen</button></>}</div>}
const prompts=["","Beginnen Sie werkunabhängig: Dialog entsteht durch aufeinander bezogene Handlungen.","Ordnen Sie erst die unmittelbare Sprachhandlung ein.","Fragen Sie danach nach dem übergeordneten Gesprächsziel.","Ein Verlauf besteht aus funktionalen Phasen.","Begründen Sie eine Grenze durch eine relevante Veränderung.","Verbinden Sie Befund, konkrete Wirkung und Funktion.","Übertragen Sie die Werkzeuge auf den geschützten Shakespeare-Text.","Gesprächsziele brauchen vollständige Textbelege.","Vergleichen Sie Romeos Ziele in zwei Textstellen.","Eine Sprachhandlung erhält ihre Bedeutung durch die Reaktion.","Rekonstruieren und begründen Sie den Verlauf.","Prüfen Sie Wendepunkte über Davor und Danach.","Benennung ist noch keine Sprachanalyse.","Trennen Sie Originalvorgabe und mögliche Inszenierung.","Bauen Sie eine vollständige Mini-Analyse.","Übertragen und vergleichen Sie die Werkzeuge in einem anderen Dialogtyp."];
