"use client";
import { useState } from "react";
import { hydrateSession } from "../../../core/state/hydrateSession";
import type { GameState } from "../../../core/state/types";
import { GenericFeedbackEngine } from "../../../core/feedback";
import { RelationshipGraph } from "../../../shared/components/RelationshipGraph";
import { chapter02Characters } from "../data/chapter_02/characters";
import { characterizationFindings, characterizationTasks } from "../data/chapter_02/characterization";
import { conflictChain } from "../data/chapter_02/conflicts";
import { developmentCards } from "../data/chapter_02/development";
import { ensembleFinalePool } from "../data/chapter_02/finale";
import { knowledgeStates } from "../data/chapter_02/knowledge_states";
import { relationships } from "../data/chapter_02/relationships";
import { classifyFinding, completeEnsembleProbe, connectCharacters, createChapter02Session, justifyRelationship, placeConflictStage, placeDevelopment, placeKnowledge, selectReasoningStep, type Chapter02Session } from "../mechanics/chapter_02_engine";

const chapter02Feedback = new GenericFeedbackEngine({ initial: "Eine Figur steht im Drama niemals für sich allein. Stellen Sie das Ensemble wieder zusammen.", connected: "Die Figuren sind verbunden. Ergänzen Sie jetzt die Begründungsgrundlage.", wrong_connection: "Diese Verbindung gehört an eine andere Stelle im Ensemble. Wählen Sie neu." });

export function Chapter02({gameState,onSave,onExit,onComplete}:{gameState:GameState;onSave:(session:Chapter02Session)=>void;onExit:()=>void;onComplete:(session:Chapter02Session)=>void}){
 const stored=gameState.decisions.chapter_02;const[session,setSession]=useState<Chapter02Session>(()=>hydrateSession(stored,createChapter02Session(),7));const[feedback,setFeedback]=useState(chapter02Feedback.getMessage("initial"));
 const update=(next:Chapter02Session)=>{setSession(next);onSave(next)};
 const connect=(a:string,b:string)=>{const result=connectCharacters(session,a,b);update(result.session);setFeedback(chapter02Feedback.getMessage(result.valid?"connected":"wrong_connection"))};
 const justify=()=>{const id=session.pendingRelationship;if(!id)return;const result=justifyRelationship(session,id);update(result.session);setFeedback(result.valid?"Beziehung und Begründungsgrundlage sind im Netz verankert.":"Die Verbindung benötigt noch eine passende Grundlage.")};
 const reason=(kind:"observation"|"evidence"|"interpretation")=>{const task=characterizationTasks[session.characterizationTask];const result=selectReasoningStep(session,kind,task.id);update(result.session);setFeedback(result.valid?"Der nächste Analyseschritt ist begründet.":task.feedback_wrong)};
 const classify=(id:string,target:string)=>{const result=classifyFinding(session,id,target);update(result.session);setFeedback(result.valid?(target==="indirect"?"Was lässt sich daraus begründet ableiten?":"Die Zuschreibung ist ausdrücklich formuliert."):"Prüfen Sie, ob die Aussage ausdrücklich genannt oder erst erschlossen wird.")};
 const conflict=(id:string)=>{const result=placeConflictStage(session,id);update(result.session);setFeedback(result.valid?"Der Konfliktknoten wird als Prozess sichtbar.":"Ordnen Sie zuerst den vorangehenden Schritt der Konfliktdynamik ein.")};
 const knowledge=(id:string,target:string)=>{const result=placeKnowledge(session,id,target);update(result.session);setFeedback(result.valid?"Der Wissensstand ist korrekt rekonstruiert.":"Figur und Publikum verfügen hier nicht über denselben Wissensstand.")};
 const development=(id:string)=>{const result=placeDevelopment(session,id);update(result.session);setFeedback(result.valid?"Die Entwicklungsstruktur ist ergänzt.":"Figurenentwicklung braucht die Abfolge: früher – Erfahrung – später.")};
 const finale=(id:string)=>{const result=completeEnsembleProbe(session,id);update(result.session);setFeedback(result.valid?"Das Ensemble ist wieder vollständig.":"Diese Beobachtung trägt die gezogene Beziehung nicht am stärksten.");if(result.session.completed)onComplete(result.session)};
 return <main className="chapter-shell ensemble-chapter"><header className="chapter-header"><button onClick={onExit}>← Theater</button><div><p>Kapitel 2 · Ensemblewand</p><h1>Das Ensemble erwacht</h1></div><span>Station {session.round} von 7</span></header><section className="ensemble-layout"><aside className="ensemble-brief"><p className="task-label">Leitfrage</p><h2>Was verraten Beziehungen, Sprache und Handlungen über dramatische Figuren?</h2><p>{instruction(session.round)}</p><div className="ensemble-progress" aria-label={`Station ${session.round} von 7`}>{[1,2,3,4,5,6,7].map((n)=><span key={n} className={n<=session.round?"active":""}>{n}</span>)}</div></aside><section className="ensemble-workspace">{session.round===1&&<RelationshipRound session={session} onConnect={connect} onJustify={justify}/>} {session.round===2&&<ReasoningRound session={session} onChoose={reason}/>} {session.round===3&&<SortRound items={characterizationFindings} assigned={session.classified} zones={[{id:"direct",label:"Direkte Charakterisierung"},{id:"indirect",label:"Indirekte Charakterisierung"}]} onAssign={classify}/>} {session.round===4&&<ConflictRound session={session} onChoose={conflict}/>} {session.round===5&&<SortRound items={knowledgeStates} assigned={session.knowledgeAssignments} zones={[{id:"romeo",label:"Romeo weiß"},{id:"audience",label:"Das Publikum weiß mehr"}]} onAssign={knowledge}/>} {session.round===6&&<DevelopmentRound session={session} onChoose={development}/>} {session.round===7&&<FinaleRound session={session} onChoose={finale}/>}<p className="ensemble-feedback" role="status">{feedback}</p></section></section></main>;
}

function RelationshipRound({session,onConnect,onJustify}:{session:Chapter02Session;onConnect:(a:string,b:string)=>void;onJustify:()=>void}){const active=relationships[session.relationshipIndex];const visible=session.completedRelationships.length>=4?chapter02Characters:chapter02Characters.slice(0,6);return <div><div className="task-ribbon"><span>Beziehungsfaden {Math.min(session.relationshipIndex+1,8)} von 8</span><strong>{active?.label??"Beziehungsnetz vollständig"}</strong></div><RelationshipGraph characters={visible} connections={relationships.map((item)=>({...item,completed:session.completedRelationships.includes(item.id)}))} onConnect={onConnect}/>{session.pendingRelationship&&<button className="evidence-placeholder" onClick={onJustify}><small>Beleg / Handlungsgrundlage</small>Redaktioneller Primärtextbeleg steht noch aus.<span>Als Platzhalter bestätigen</span></button>}</div>}
function ReasoningRound({session,onChoose}:{session:Chapter02Session;onChoose:(kind:"observation"|"evidence"|"interpretation")=>void}){const task=characterizationTasks[session.characterizationTask];const steps=[{kind:"observation" as const,label:"Beobachtung",text:task.observation},{kind:"evidence" as const,label:"Handlungsgrundlage",text:task.evidence},{kind:"interpretation" as const,label:"Mögliche Deutung",text:task.interpretation}];return <div><div className="task-ribbon"><span>{task.character_id}</span><strong>Beobachtung → Beleg → Schlussfolgerung</strong></div><div className="reasoning-chain">{steps.map((step,index)=><button key={step.kind} disabled={index>session.reasoningStep} className={index<session.reasoningStep?"complete":""} onClick={()=>onChoose(step.kind)}><small>{step.label}</small>{step.text}</button>)}</div></div>}
function SortRound({items,assigned,zones,onAssign}:{items:readonly {id:string;text:string}[];assigned:Record<string,string>;zones:readonly {id:string;label:string}[];onAssign:(id:string,target:string)=>void}){const[selected,setSelected]=useState<string|null>(null);return <div className="ensemble-sort"><div className="ensemble-cards">{items.filter((item)=>!assigned[item.id]).map((item)=><button key={item.id} aria-pressed={selected===item.id} onClick={()=>setSelected(item.id)}>{item.text}</button>)}</div><div className="ensemble-zones">{zones.map((zone)=><button key={zone.id} onClick={()=>selected&&onAssign(selected,zone.id)}><strong>{zone.label}</strong><span>{Object.values(assigned).filter((value)=>value===zone.id).length} Befunde</span></button>)}</div></div>}
function ConflictRound({session,onChoose}:{session:Chapter02Session;onChoose:(id:string)=>void}){return <div><div className="conflict-figures">{["Romeo","Tybalt","Mercutio","Benvolio"].map((name)=><span key={name}>{name.slice(0,1)}<small>{name}</small></span>)}</div><div className="conflict-chain">{conflictChain.map((item,index)=><button key={item.id} disabled={index>session.conflictStages.length} className={session.conflictStages.includes(item.id)?"complete":""} onClick={()=>onChoose(item.id)}><small>{item.stage}</small>{item.text}</button>)}</div></div>}
function DevelopmentRound({session,onChoose}:{session:Chapter02Session;onChoose:(id:string)=>void}){return <div><div className="task-ribbon"><span>Technischer Prototyp · Romeo</span><strong>Figur früher → Ereignis / Erfahrung → Figur später</strong></div><div className="development-chain">{developmentCards.map((item,index)=><button key={item.id} disabled={index>session.developmentStages.length} className={session.developmentStages.includes(item.id)?"complete":""} onClick={()=>onChoose(item.id)}><small>Entwicklungsplatzhalter</small>{item.text}</button>)}</div></div>}
function FinaleRound({session,onChoose}:{session:Chapter02Session;onChoose:(id:string)=>void}){const chosen=ensembleFinalePool[session.finaleIndex];const relation=relationships.find((item)=>item.id===chosen)!;const options=[relation,...relationships.filter((item)=>item.id!==chosen).slice(0,2)];return <div className="ensemble-finale"><p className="task-label">Ensembleprobe</p><h2>{relation.a} ↔ {relation.b}</h2><p>Wählen Sie die aussagekräftigste bekannte Beobachtungsgrundlage.</p>{options.map((item)=><button key={item.id} onClick={()=>onChoose(item.id)}><span>{item.symbol}</span><strong>{item.label}</strong><small>Beobachtung → Bedeutung → Beziehung</small></button>)}{session.completed&&<h3>Das Ensemble ist wieder vollständig.</h3>}</div>}
function instruction(round:number){return["","Verbinden Sie die Figuren und ergänzen Sie anschließend die Begründungsgrundlage.","Bauen Sie die Analyse von der Beobachtung bis zur möglichen Deutung auf.","Trennen Sie ausdrückliche Zuschreibung und begründete Ableitung.","Rekonstruieren Sie den Konflikt als mehrstufigen Prozess – nicht als Schuldfrage.","Ordnen Sie zuerst die verteilten Wissensstände. Figuren und Publikum verfügen nicht immer über denselben Wissensstand.","Bauen Sie die Struktur einer begründeten Figurenentwicklung auf.","Schließen Sie die Ensembleprobe mit einer bekannten Beziehung ab."][round]}
