"use client";
import { useEffect, useState, type CSSProperties } from "react";
import { getAsset } from "../../../core/assets/manifest";
import { hydrateSession } from "../../../core/state/hydrateSession";
import type { GameState } from "../../../core/state/types";
import { PrimarySourceText } from "../../../shared/components/PrimarySourceText";
import { SceneCharacters } from "../../../shared/components/SceneCharacters";
import { GlossaryHelp } from "../../../shared/components/GlossaryHelp";
import type { GlossaryEntry } from "../data/glossary";
import { additionalHelp, argumentBlocks, chapter05SourceById, classificationCards, commonErrors, errorRepairs, generalChain, generalCountercheckOptions, hypothesisOptions, interpretationStructure, julietCountercheckOptions, julietEvidenceMarkers, julietFindings, julietRefinementParts, julietReverseChain, microArgumentStructure, modernScene, processHelp, synthesisSteps, transferArgument, transferChain, transferContext, transferCountercheckOptions, transferEvidence, transferEvidenceMarkers, transferHypotheses, transferRefinementParts } from "../data/chapter_05_content";
import { assignError, assignJulietRelevance, buildJulietRefinement, buildTransferRefinement, chooseGeneralHypothesis, chooseTransferHypothesis, classifyStatement, completeChapter05, countercheckJuliet, countercheckTransfer, initialChapter05Session, placeGeneralChain, placeJulietArgument, placeJulietChain, placeStructure, placeTransferArgument, placeTransferChain, repairError, reviseGeneralHypothesis, selectTransferEvidence, synthesize, type Chapter05Session } from "../mechanics/chapter_05_engine";

type Props={gameState:GameState;onSave:(s:Chapter05Session)=>void;onExit:()=>void;onComplete:(s:Chapter05Session)=>void};
export function Chapter05({gameState,onSave,onExit,onComplete}:Props){
 const[s,setS]=useState(()=>hydrateSession(gameState.decisions.chapter_05,initialChapter05Session,19));const[feedback,setFeedback]=useState("Wählen Sie eine Karte und prüfen Sie deren Funktion im Interpretationsprozess.");const[feedbackTone,setFeedbackTone]=useState<"neutral"|"correct"|"incorrect">("neutral");
 useEffect(()=>{document.querySelector(".interpretation-model")?.scrollIntoView({block:"start",behavior:"auto"})},[s.round]);
 const apply=(result:{valid:boolean;session:Chapter05Session},ok="Der Zusammenhang ist textnah begründet.",bad="Prüfen Sie, welche Denkbewegung hier noch fehlt.")=>{setS(result.session);onSave(result.session);setFeedbackTone(result.valid?"correct":"incorrect");setFeedback(`${result.valid?"✓":"Noch nicht."} ${result.valid?ok:bad}`)};
 const finish=()=>{const r=completeChapter05(s);apply(r,"Die Deutung steht. Das Theater ist bereit.","Schließen Sie zuerst Transfer und Synthese ab.");if(r.valid)onComplete(r.session)};
 if(s.round===19&&s.completed)return null;
 if(s.round===19)return <main className="chapter-shell chapter05-final-state"><section className="chapter05-completion" aria-label="Kapitelabschluss"><h1>DIE DEUTUNG IST BEGRÜNDET.</h1><p>Sie können aus Textbefunden eine Deutung entwickeln, diese am Text überprüfen, Gegenbelege berücksichtigen und zu einer schlüssigen Argumentation verbinden.</p><button className="finish-interpretation" onClick={finish}>Zur großen Bühne</button></section></main>;
 const backgroundId=s.round>=5&&s.round<=9?"bg_portrait_room":"bg_analysis_room";const background=getAsset(backgroundId)?.path;
 return <main className={`chapter-shell interpretation-chapter chapter05-workshop chapter05-scene-${s.round>=12?"apothecary":s.round>=5?"juliet":"study"}`} style={{"--chapter05-background":`url("${background}")`} as CSSProperties}><header className="chapter-header"><button onClick={onExit}>← Theater</button><div><p>Kapitel 5 · Interpretationswerkstatt</p><h1>Was bedeutet das?</h1><small>Analyseergebnisse zu einer Interpretation verbinden</small></div><span>Station {Math.min(s.round,18)} von 18</span></header>
 <InterpretationTrace/>
 {s.round>=5&&s.round<=9&&<SceneCharacters sceneId="chapter_05.juliet"/>}{s.round>=12&&s.round<=17&&<SceneCharacters sceneId="chapter_05.apothecary"/>}
 <section className={`chapter05-layout chapter05-layout-round-${s.round}`}><aside className="chapter05-brief"><h2>{roundTitles[s.round]??"Abschluss"}</h2><p>{roundInstructions[s.round]??"Die Argumentation ist vollständig."}</p>{s.round>=5&&s.round<=9&&![7,8].includes(s.round)&&<blockquote>{s.julietHypothesis}</blockquote>}{s.round>=12&&s.round<=17&&<p className="transfer-label">Die Deutungsprobe · Transfer</p>}</aside><section className={`chapter05-desk chapter05-round-${s.round}`}>
 {s.round===1&&<><SourceCard label="Spieltext · kein Primärtext">{modernScene.map((line,i)=><p key={i}><strong>{line.speaker&&`${line.speaker}: `}</strong>{line.text}</p>)}</SourceCard><h3>Was können Sie hier zunächst sicher beobachten?</h3><AssignBoard items={classificationCards} assigned={s.classifications} zones={[{id:"observation",label:"Textbefund"},{id:"beyond",label:"geht über die Beobachtung hinaus"}]} onAssign={(id,z)=>apply(classifyStatement(s,id,z),z==="observation"?"Textbefund. Die Aussage beschreibt zunächst nur etwas unmittelbar Wahrnehmbares.":"Die Aussage erschließt bereits eine mögliche Absicht und ist deshalb noch kein reiner Textbefund.","Unterscheiden Sie zwischen unmittelbar Wahrnehmbarem und einer bereits erschlossenen Absicht.")}/></>}
 {s.round===2&&<OrderedBoard title="Bauen Sie die Bedeutungskette." items={generalChain} placed={s.generalChain} onPlace={id=>apply(placeGeneralChain(s,id))}/>}
 {s.round===3&&<><MeaningHypothesis/><ChoiceRound items={hypothesisOptions} onChoose={id=>{const r=chooseGeneralHypothesis(s,id);apply(r,"Diese Hypothese führt mehrere Befunde zu einer am Ausschnitt prüfbaren Deutung zusammen.",r.quality==="description"?"Das ist eine Inhaltsangabe; eine übergreifende, prüfbare Deutung fehlt.":r.quality==="general"?"Die Aussage ist zu allgemein und lässt sich an dieser Szene nicht gezielt prüfen.":"Die Aussage psychologisiert über den Text hinaus.")}}/></>}
 {s.round===4&&<><ReadingDirections/><ChoiceRound items={generalCountercheckOptions} onChoose={id=>{const item=generalCountercheckOptions.find(x=>x.id===id)!;apply(reviseGeneralHypothesis(s,item.action),"Die neue Beobachtung begrenzt die Reichweite. Die Hypothese wird textnah präzisiert.","Prüfen Sie, ob der Befund bestätigt, begrenzt, widerspricht oder noch nicht zur Entscheidung reicht.")}}/><p className="learning-note">Eine gute Interpretation hält nicht an einer Hypothese fest, wenn weitere Befunde ihre Reichweite begrenzen.</p></>}
 {s.round===5&&<><EvidenceSource markers={julietEvidenceMarkers}/><AssignBoard items={julietFindings} assigned={s.julietRelevance} zones={[{id:"direct",label:"stützt unmittelbar"},{id:"supplement",label:"ergänzt"},{id:"little",label:"kaum relevant"},{id:"contradicts",label:"widerspricht"}]} onAssign={(id,z)=>{const r=assignJulietRelevance(s,id,z);apply(r,r.accepted?.length&&r.accepted.length>1?"Diese Einordnung ist vertretbar: Der Befund trägt mittelbar oder unmittelbar zur Prüfung bei.":"Die Relevanz ist auf die konkrete Hypothese bezogen.","Der Befund kann sachlich richtig sein und für diese Hypothese dennoch eine andere Funktion besitzen.")}}/></>}
 {s.round===6&&<><ReadingDirections literary/><OrderedBoard title="Rekonstruieren Sie die Rückwärtsprüfung: Teilthese ← Bedeutung ← Analyse ← Textbeleg." items={[...julietReverseChain].reverse()} placed={s.julietChain} onPlace={id=>apply(placeJulietChain(s,id))}/></>}
 {s.round===7&&<><blockquote className="hypothesis-focus">{s.julietHypothesis}</blockquote><p className="hypothesis-question">Welcher Befund begrenzt diese Aussage?</p><ChoiceRound
   items={julietCountercheckOptions}
   onChoose={id=>apply(countercheckJuliet(s,id),"Das Gegenbeispiel widerlegt nicht jede Begrenzung, aber die absolute Formulierung.")}
 /></>}
 {s.round===8&&<><blockquote className="hypothesis-focus hypothesis-original">{s.julietHypothesis}</blockquote><SentenceBuilder title="Bauen Sie die präzisierte Hypothese aus drei Bausteinen." items={julietRefinementParts} placed={s.julietRefinementParts??[]} onPlace={id=>apply(buildJulietRefinement(s,id),"Der Baustein präzisiert die Reichweite, ohne Capulets Machtposition zu leugnen.")}/></>}
 {s.round===9&&<OrderedBoard title="Bauen Sie einen argumentierenden Absatz." items={argumentBlocks} placed={s.julietArgument} onPlace={id=>apply(placeJulietArgument(s,id))}/>}
 {s.round===10&&<><AssignBoard items={commonErrors} assigned={s.errorAssignments} zones={[{id:"summary_only",label:"bloße Inhaltsangabe"},{id:"evidence_without_analysis",label:"Beleg ohne Analyse"},{id:"overinterpretation",label:"Überinterpretation"},{id:"missing_link",label:"fehlende Rückbindung"},{id:"unsupported_claim",label:"unbelegte Behauptung"}]} onAssign={(id,z)=>{const item=commonErrors.find(x=>x.id===id)!;apply(assignError(s,id,z,item.target,commonErrors.length),"Der typische Argumentationsfehler ist erkannt. Jetzt muss er repariert werden.","Prüfen Sie, ob Beleg, Analyse oder Rückbindung fehlen beziehungsweise zu viel behauptet wird.")}}/><RepairBoard session={s} onRepair={(id,strategy)=>apply(repairError(s,id,strategy),"Die Reparatur ergänzt genau den fehlenden Interpretationsschritt.","Diese Strategie behebt den diagnostizierten Fehler noch nicht.")}/></>}
 {s.round===11&&<><StructureContrast/><OrderedBoard title="Makrostruktur: Ordnen Sie die Gesamtbewegung einer Interpretation." items={interpretationStructure.map((text,i)=>({id:`structure_${i}`,text}))} placed={s.structureOrder} onPlace={id=>apply(placeStructure(s,id))}/></>}
 {s.round===12&&<><p>{transferContext}</p><EvidenceSource markers={transferEvidenceMarkers} compact/><div className="choice-grid">{transferEvidence.filter(x=>!s.transferSelected.includes(x.id)).map(x=><button key={x.id} onClick={()=>apply(selectTransferEvidence(s,x.id),"Dieser Befund ist für die Deutung ergiebig.","Der Befund ist textlich richtig, trägt zu dieser konkreten Deutung aber nur wenig bei.")}>{x.text}</button>)}</div></>}
 {s.round===13&&<OrderedBoard title="Verbinden Sie Beleg, Beobachtung, Wirkung und Bedeutung." items={transferChain} placed={s.transferChain} onPlace={id=>apply(placeTransferChain(s,id))}/>}
 {s.round===14&&<ChoiceRound items={transferHypotheses} onChoose={id=>{const r=chooseTransferHypothesis(s,id);apply(r,"Die Hypothese verbindet Handlung, Sprache und Bedeutung.",r.quality==="description"?"Das bleibt eine Inhaltsangabe.":"Der Text widerspricht dieser Vereinfachung.")}}/>}
 {s.round===15&&<ChoiceRound
   items={transferCountercheckOptions}
   onChoose={id=>apply(countercheckTransfer(s,id),"Der Gegenbeleg begrenzt eine vereinfachende Schuldzuweisung.")}
 />}
 {s.round===16&&<SentenceBuilder title="Präzisieren Sie die Transferhypothese aus Bausteinen." items={transferRefinementParts} placed={s.transferRefinementParts??[]} onPlace={id=>apply(buildTransferRefinement(s,id),"Der Baustein verbindet ökonomischen Druck mit der verbleibenden Willensdimension.","Die Präzisierung muss den Gegenbefund aufnehmen.")}/>}
 {s.round===17&&<OrderedBoard title="Bauen Sie den Transfer-Absatz." items={transferArgument} placed={s.transferArgument} onPlace={id=>apply(placeTransferArgument(s,id))}/>}
 {s.round===18&&<RecursiveProcess placed={s.synthesisOrder??[]} onPlace={id=>apply(synthesize(s,id),"Der Prozessschritt ist sinnvoll angeschlossen.")}/>}
 {s.round<19&&<p className={`interpretation-feedback ${feedbackTone}`} role="status" aria-live="polite">{feedback}</p>}</section></section></main>;
}
function SourceCard({label,children}:{label:string;children:React.ReactNode}){return <article className="chapter05-source"><small>{label}</small>{children}</article>}
function ChoiceRound({items,onChoose}:{items:readonly {id:string;text:string}[];onChoose:(id:string)=>void}){return <div className="choice-grid">{items.map(item=><button key={item.id} onClick={()=>onChoose(item.id)}>{item.text}</button>)}</div>}
function AssignBoard({items,assigned,zones,onAssign}:{items:readonly {id:string;text:string}[];assigned:Record<string,string>;zones:readonly {id:string;label:string}[];onAssign:(id:string,zone:string)=>void}){const[selected,setSelected]=useState<string|null>(null);return <div className="assign-board"><div className="choice-grid">{items.filter(x=>!assigned[x.id]).map(item=><button key={item.id} aria-pressed={selected===item.id} onClick={()=>setSelected(item.id)}>{item.text}</button>)}</div><fieldset><legend>Ziel für die ausgewählte Karte</legend>{zones.map(zone=><button type="button" key={zone.id} disabled={!selected} onClick={()=>{if(selected){onAssign(selected,zone.id);setSelected(null)}}}>{zone.label}</button>)}</fieldset></div>}
function OrderedBoard({title,items,placed,onPlace}:{title:string;items:readonly {id:string;text:string;kind?:string}[];placed:string[];onPlace:(id:string)=>void}){return <div className={`ordered-board ${items.some(item=>item.kind)?"argument-path":"thought-chain"}`}><h3>{title}</h3><ol>{placed.map(id=>{const item=items.find(x=>x.id===id);return <li key={id}>{item?.kind&&<small>{kindLabels[item.kind]??item.kind}</small>}{item?.text}</li>})}</ol><div className="choice-grid">{items.filter(x=>!placed.includes(x.id)).reverse().map(item=><button key={item.id} onClick={()=>onPlace(item.id)}>{item.kind&&<small>{kindLabels[item.kind]??item.kind}</small>}{item.text}</button>)}</div></div>}
function InterpretationTrace(){const entries:GlossaryEntry[]=[...processHelp,...additionalHelp].map(item=>({id:`chapter05_${item.id}`,term:item.label,definition:item.definition,chapter:"chapter_05"}));return <section className="interpretation-trace" aria-label="Begriffshilfen zur Interpretation"><GlossaryHelp entries={entries} introTitle="Begriffshilfe Interpretation" seen onSeen={()=>{}}/></section>}
function ReadingDirections({literary=false}:{literary?:boolean}){return <section className="reading-directions" aria-label="Zwei Richtungen des Interpretierens"><article><h3>Vorwärts {literary?"argumentieren":"lesen"}</h3><p>Text{literary?"beleg":""} → Befund → Analyse → Bedeutung → {literary?"Teilthese":"Hypothese"}</p></article><article><h3>Rückwärts prüfen</h3><p>{literary?"Teilthese":"Hypothese"} → Welche Befunde tragen sie? → Gibt es Gegenbefunde? → Muss sie präzisiert werden?</p></article><strong>Interpretieren bedeutet, sich zwischen beiden Richtungen zu bewegen.</strong></section>}
function MeaningHypothesis(){return <section className="meaning-hypothesis" aria-label="Bedeutung und Deutungshypothese unterscheiden"><article><h3>Bedeutung</h3><p>Erkenntnis aus einem einzelnen analysierten Zusammenhang.</p></article><strong aria-hidden="true">Mehrere Befunde + Analyseergebnisse<br/>↓ zusammenführen</strong><article><h3>Deutungshypothese</h3><p>Übergreifende, vorläufige Aussage über die Szene, die durch mehrere Befunde geprüft wird.</p></article></section>}
function EvidenceSource({markers,compact=false}:{markers:readonly {id:string;label:string;sourceId:string}[];compact?:boolean}){const[open,setOpen]=useState(true);const jump=(id:string)=>document.getElementById(`evidence-${id}`)?.scrollIntoView({block:"center",behavior:"smooth"});if(compact)return <section className="evidence-source-layout compact-source"><SourceCard label="Originaltext · Wieland · geschützter Primärtext">{markers.map(marker=><p key={marker.id}><PrimarySourceText record={chapter05SourceById(marker.sourceId)}/></p>)}</SourceCard></section>;return <section className="evidence-source-layout"><nav className="evidence-markers" aria-label="Belegmarker">{markers.map(marker=><button key={marker.id} type="button" onClick={()=>{setOpen(true);queueMicrotask(()=>jump(marker.id))}}><strong>{marker.id}</strong> {marker.label}</button>)}</nav><button className="source-toggle" type="button" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?"Primärtext einklappen":"Primärtext ausklappen"}</button>{open&&<SourceCard label="Originaltext · Wieland · geschützter Primärtext">{markers.map(marker=><p id={`evidence-${marker.id}`} tabIndex={-1} key={marker.id} className="marked-source"><span>{marker.id}</span><PrimarySourceText record={chapter05SourceById(marker.sourceId)}/></p>)}</SourceCard>}</section>}
function SentenceBuilder({title,items,placed,onPlace}:{title:string;items:readonly {id:string;text:string}[];placed:string[];onPlace:(id:string)=>void}){return <section className="sentence-builder"><h3>{title}</h3><p className="built-sentence">{placed.map(id=>items.find(item=>item.id===id)?.text).join(" ")||"Die Formulierung entsteht aus Ihren Entscheidungen."}</p><div className="choice-grid">{items.filter(item=>!placed.includes(item.id)).reverse().map(item=><button key={item.id} onClick={()=>onPlace(item.id)}>{item.text}</button>)}</div></section>}
function RepairBoard({session,onRepair}:{session:Chapter05Session;onRepair:(id:string,strategy:string)=>void}){const diagnosed=commonErrors.filter(item=>session.errorAssignments[item.id]&&!session.errorRepairs?.[item.id]);if(!diagnosed.length)return null;const current=diagnosed[0];const correct=errorRepairs.find(item=>item.id===current.id)!;const distractors=[{id:"repeat_evidence",text:"Den vorhandenen Satz lediglich wiederholen."},{id:"make_absolute",text:"Die Aussage eindeutiger und absoluter formulieren."}];return <section className="repair-board"><h3>Wie lässt sich dieser Fehler beheben?</h3><p>{current.text}</p><ChoiceRound items={[{id:correct.target,text:correct.text},...distractors]} onChoose={strategy=>onRepair(current.id,strategy)}/></section>}
function StructureContrast(){return <><section className="structure-contrast"><article><h3>Makrostruktur</h3><p>Einleitung + Deutungshypothese → mehrere Analyseargumente → Befunde zusammenführen → Hypothese prüfen oder präzisieren → differenziertes Fazit</p></article><article><h3>Mikrostruktur</h3><p>{microArgumentStructure.join(" → ")}</p></article></section><p className="learning-note">Eine Interpretation besteht aus mehreren Mikroargumenten, die gemeinsam die Makrostruktur tragen.</p></>}
function RecursiveProcess({placed,onPlace}:{placed:string[];onPlace:(id:string)=>void}){return <section className="recursive-process"><h3>Rekonstruieren Sie das Schlussmodell.</h3><div className="process-column">{placed.map(id=><span key={id}>{synthesisSteps.find(item=>item.id===id)?.text}</span>)}</div>{placed.includes("s_test")&&<div className="process-branch"><p><strong>Befunde tragen die Hypothese</strong><br/>→ Argumentation</p><p><strong>Gegenbefund</strong><br/>↓ Hypothese präzisieren <span aria-hidden="true">↺</span><br/>erneut prüfen</p></div>}<div className="choice-grid">{synthesisSteps.filter(item=>!placed.includes(item.id)).reverse().map(item=><button key={item.id} onClick={()=>onPlace(item.id)}>{item.text}</button>)}</div>{placed.length===synthesisSteps.length&&<div className="conclusion-rule"><p>Eine tragfähige Interpretation entwickelt eine prüfbare Deutung aus Textbefunden, analysiert deren Funktion und Bedeutung und überprüft ihre Reichweite auch an Gegenbefunden.</p><strong>Interpretieren bedeutet deshalb, zwischen Text und Deutung vor- und zurückzugehen.</strong></div>}</section>}
const kindLabels:Record<string,string>={claim:"Behauptung / Teilthese",evidence:"Textbeleg",observation:"Textbeobachtung",analysis:"Analyse",effect:"Wirkung / Funktion",meaning:"Bedeutung",interpretation:"Rückbindung"};
const roundTitles=["","Beobachtung und Textbefund","Mara und Leon: Analyse, Wirkung und Bedeutung","Eine prüfbare Deutungshypothese","Vorwärts lesen – rückwärts prüfen","Juliette und Capulet: relevante Befunde","Juliette: Belege rückwärts prüfen","Juliette: Gegenbefund","Juliette: Hypothese präzisieren","Juliette: Argumentation bauen","Interpretationsfehler erkennen und reparieren","Mikro- und Makrostruktur","Romeo und der Apotheker: Primärtext und Belege","Transferanalyse","Transferhypothese","Transfer-Gegencheck","Transferhypothese präzisieren","Transferargument","Rekursiver Interpretationsprozess"];
const roundInstructions=["","Was können Sie zunächst sicher beobachten?","Erschließen Sie schrittweise, wie der zweite Satz die Wirkung und Bedeutung des ersten verändert.","Unterscheiden Sie Inhaltsangabe, Allgemeinplatz, Psychologisierung und prüfbare Hypothese.","Prüfen Sie die Reichweite der Hypothese an einem weiteren Befund.","Welche Befunde sind für die bewusst zu absolute Ausgangshypothese relevant?","Prüfen Sie eine Teilthese vom Ergebnis zurück bis zum Textbeleg.","Welcher Befund begrenzt die absolute Formulierung?","Bauen Sie eine differenzierte Hypothese aus textnahen Bausteinen.","Verbinden Sie Teilthese, Beleg, Analyse, Wirkung, Bedeutung und Rückbindung.","Diagnostizieren Sie den Fehler und wählen Sie anschließend eine passende Reparatur.","Trennen Sie den Gesamtaufbau von einem einzelnen Analyseargument.","Wählen Sie selbstständig ergiebige Befunde aus dem geschützten Primärtext.","Erschließen Sie Funktion und Bedeutung des zentralen Gegenbefunds.","Welche Hypothese ist deutend, gewichtet und textnah?","Was verändert der Gegenbefund an der Hypothese?","Präzisieren Sie ökonomischen Druck und verbleibende Willensdimension.","Führen Sie die Transferanalyse zu einem vollständigen Mikroargument zusammen.","Rekonstruieren Sie Interpretation als prüfenden und rekursiven Prozess."];
