"use client";
import { useState } from "react";
import { AssetImage } from "../../shared/components/AssetImage";
import { AppShell } from "./components/AppShell";
import { Button } from "./components/Button";
import { Card } from "./components/Card";
import { FeedbackBox } from "./components/FeedbackBox";
import { GlossaryTerm } from "./components/GlossaryTerm";
import { ProgressBar } from "./components/ProgressBar";
import { SectionHeader } from "./components/SectionHeader";
import { StatusBadge } from "./components/StatusBadge";
type Screen = "start" | "learning" | "complete";
const startDecorations = [{ asset: "archive_scroll", position: "bottom-left", width: "clamp(9rem, 22vw, 20rem)", opacity: .28, rotation: -8, visibility: "tablet-up" }] as const;
export function LiteratureArchive() { const [screen, setScreen] = useState<Screen>("start"); if (screen === "start") return <AppShell decorations={startDecorations}><section className="archive-view archive-view--start" aria-labelledby="archive-title"><p className="archive-kicker">Digitale Lernwerkstatt</p><h1 id="archive-title">Das Literatur-Archiv</h1><p className="archive-subtitle">Grundlagen der Arbeit mit Literatur</p><div className="ornament" aria-hidden="true" /><p className="archive-intro">Ordnen, entdecken und verstehen Sie zentrale Formen und Begriffe der Literatur.</p><Button onClick={() => setScreen("learning")}>Archiv öffnen <span aria-hidden="true">→</span></Button></section></AppShell>; if (screen === "learning") return <AppShell><section className="archive-view archive-view--learning" aria-labelledby="learning-title"><SectionHeader eyebrow="Grundlage 01" title="Literarische Mehrdeutigkeit" description="Lesen Sie den kurzen Impuls und erkunden Sie den markierten Fachbegriff." /><div className="learning-grid"><Card className="learning-card"><p className="learning-card__label">Lernimpuls</p><p className="learning-card__text" id="learning-title">Ein literarischer Text kann bewusst mehrere Deutungen ermöglichen. Diese <GlossaryTerm glossaryId="ambiguitaet" /> gehört zu seinen besonderen Eigenschaften.</p></Card><Card className="term-test-card"><p>Layoutprüfung</p><strong>produktionsorientiert</strong><small>Der lange Fachbegriff bleibt in jeder Ansicht vollständig lesbar.</small></Card></div><ProgressBar value={1} max={2} label="Fortschritt" /><FeedbackBox tone="neutral">Öffnen Sie den markierten Fachbegriff, um die Glossarfunktion kennenzulernen.</FeedbackBox><div className="archive-actions"><Button onClick={() => setScreen("complete")}>Weiter <span aria-hidden="true">→</span></Button></div></section></AppShell>; return <AppShell decorations={[{ asset: "archive_seal", position: "bottom-right", width: "clamp(8rem, 18vw, 14rem)", opacity: .22, rotation: 5, visibility: "tablet-up" }]}><section className="archive-view archive-view--complete" aria-labelledby="complete-title"><div className="completion-mark"><AssetImage id="archive_book_symbol" /><span aria-hidden="true">✓</span></div><p className="archive-kicker">Phase 1</p><h1 id="complete-title">Grundsystem bereit</h1><StatusBadge>Demo erfolgreich durchlaufen</StatusBadge><p className="completion-copy">Die technische und visuelle Basis des Literatur-Archivs ist eingerichtet.</p><Button variant="secondary" onClick={() => setScreen("start")}><span aria-hidden="true">←</span> Zurück zum Start</Button></section></AppShell>; }
